### ISSUE TITLE
OpenVPN support using ssh public keys of proven support volunteers

### ISSUE THREAD

**Issue by holta** [iiab/iiab#1006]
As discussed earlier today on community/team call @ http://minutes.iiab.io ssh public keys for ~4 proven support volunteers should be added to IIAB images when OpenVPN playbook is installed.

Will need to be documented very publicly @ http://wiki.laptop.org/go/IIAB/Security

@georgejhunt may take a crack at implementing this.

**Comment by georgejhunt** [comment]
IIAB-FACTORY is missing @jvonau's public key.

ref:https://github.com/iiab/iiab-factory/blob/master/box/keys/developers_authorized_keys

**Comment by holta** [comment]
@georgejhunt can you go ahead with 3 keys?  @jvonau's key can be added later as necessary.

**Comment by holta** [comment]
Resolved by PRs #1013, #1014

**Comment by holta** [comment]
Public-facing documentation at http://wiki.iiab.io/Security has been revised accordingly &mdash; please all review that, Thanks!
