### ISSUE TITLE
How many cities are searchable by new Vector-based OSM?

### ISSUE THREAD

**Issue by holta** [iiab/iiab#1034]
@georgejhunt and @tim-moody can prob answer this?

See cities1000.sqlite (25 MB) as documented near the top of https://github.com/iiab/iiab-factory/blob/master/content/vector-tiles/README.md

Refs: #877, #1033, PR iiab/iiab-factory#39

**Comment by holta** [comment]
Question: is there hope for 10,000-or-so searchable cities...and/or countries...and/or oceans/seas/lakes/rivers/mountains/deserts?

**Comment by georgejhunt** [comment]
see Experiments #13 in
https://github.com/iiab/iiab-factory/blob/master/content/vector-tiles/Design-Decisions.md

**Comment by holta** [comment]
@georgejhunt can you clarify exactly (or roughly) how many cities are searchable in cities1000.sqlite within the zipfiles at http://download.iiab.io/content/OSM/vector-tiles/ ?
