### ISSUE TITLE
Open Calibre-Web port 8083

### ISSUE THREAD

**Issue by arky** [iiab/iiab#1050]
Devops generally restrict access to ports running behind a reverse proxy for security reasons. Is there a specific use case need to open port 8083 to public?

>http://192.168.0.x:8083 does not work, as a result of iptables, even when services_externally_visible: true. This is fixable, but perhaps it's not a priority, as URL's like {http://192.168.0.x/books, http://10.8.0.x/books, http://127.0.0.1/books and http://box/books} all work.

https://github.com/iiab/iiab/blob/master/roles/calibre-web/README.rst

**Comment by holta** [comment]
Ambiguous whether port 8083 should be opened or not.  Am deferring the question to IIAB 6.7

**Comment by arky** [comment]
May I suggest perhaps there is no need to open port 8083 to the world. Apache2 httpd reverse proxy is supposed to obscure that information and provide the service on /calibre-web subpath.

**Comment by holta** [comment]
Sure.  IIAB implementers have greatly benefitted having access to http://box:3000 etc over the years (#852) when testing/provisioning from 192.168.0.x etc.

But perhaps it's not nearly as nec in this case.

**Comment by m-anish** [comment]
This behavior is inconsistent, with other services on the IIAB.

[For example, Kiwix is exposed thru iiab-gen-iptables](https://github.com/iiab/iiab/blob/master/roles/network/templates/gateway/iiab-gen-iptables#L58).

I suggest a proper discussion needs to happen and changes be made consistent across services.

**Comment by tim-moody** [comment]
pretty sure that in appliance mode all ports are open. on my applicance vm:

root@box:~# iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
ACCEPT     all  --  anywhere             anywhere
DROP       tcp  --  anywhere             anywhere             tcp dpt:sunrpc
DROP       udp  --  anywhere             anywhere             udp dpt:sunrpc
DROP       tcp  --  anywhere             anywhere             tcp dpt:mysql
DROP       udp  --  anywhere             anywhere             udp dpt:mysql
DROP       tcp  --  anywhere             anywhere             tcp dpt:postgresql
DROP       udp  --  anywhere             anywhere             udp dpt:postgresql
DROP       tcp  --  anywhere             anywhere             tcp dpt:5984
DROP       udp  --  anywhere             anywhere             udp dpt:5984
ACCEPT     all  --  anywhere             anywhere             state RELATED,ESTABLISHED
**ACCEPT     all  --  anywhere             anywhere             state NEW**
ACCEPT     udp  --  anywhere             anywhere             udp dpt:mdns
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:ssh state NEW
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:http state NEW
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:3000 state NEW
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:8008 state NEW
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:8009 state NEW
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:http-alt state NEW
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:ipp state NEW
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:8089 state NEW
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:9091 state NEW
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:51413 state NEW
DROP       all  --  anywhere             anywhere

or have I misunderstood this?

**Comment by m-anish** [comment]
Weirdly, I think the `iptables -L` output might be misleading, as it says so in the manpage...

```
The exact rules are
              suppressed until you use
               iptables -L -v

```

Here is the output of `iptables -L -v`

```
Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
 2328  311K ACCEPT     all  --  lo     any     anywhere             anywhere            
    0     0 DROP       tcp  --  any    any     anywhere             anywhere             tcp dpt:sunrpc
    0     0 DROP       udp  --  any    any     anywhere             anywhere             udp dpt:sunrpc
    0     0 DROP       tcp  --  any    any     anywhere             anywhere             tcp dpt:mysql
    0     0 DROP       udp  --  any    any     anywhere             anywhere             udp dpt:mysql
    0     0 DROP       tcp  --  any    any     anywhere             anywhere             tcp dpt:postgresql
    0     0 DROP       udp  --  any    any     anywhere             anywhere             udp dpt:postgresql
    0     0 DROP       tcp  --  any    any     anywhere             anywhere             tcp dpt:5984
    0     0 DROP       udp  --  any    any     anywhere             anywhere             udp dpt:5984
 2463 2012K ACCEPT     all  --  any    any     anywhere             anywhere             state RELATED,ESTABLISHED
    0     0 ACCEPT     all  --  none   any     anywhere             anywhere             state NEW
   20  3777 ACCEPT     udp  --  any    any     anywhere             anywhere             udp dpt:mdns
    1    60 ACCEPT     tcp  --  enp0s3 any     anywhere             anywhere             tcp dpt:ssh state NEW
    0     0 ACCEPT     tcp  --  enp0s3 any     anywhere             anywhere             tcp dpt:http state NEW
    0     0 ACCEPT     tcp  --  enp0s3 any     anywhere             anywhere             tcp dpt:3000 state NEW
    0     0 ACCEPT     tcp  --  enp0s3 any     anywhere             anywhere             tcp dpt:8008 state NEW
    0     0 ACCEPT     tcp  --  enp0s3 any     anywhere             anywhere             tcp dpt:8009 state NEW
    0     0 ACCEPT     tcp  --  enp0s3 any     anywhere             anywhere             tcp dpt:http-alt state NEW
    0     0 ACCEPT     tcp  --  enp0s3 any     anywhere             anywhere             tcp dpt:ipp state NEW
    0     0 ACCEPT     tcp  --  enp0s3 any     anywhere             anywhere             tcp dpt:8089 state NEW
    0     0 ACCEPT     tcp  --  enp0s3 any     anywhere             anywhere             tcp dpt:1880 state NEW
    0     0 ACCEPT     tcp  --  enp0s3 any     anywhere             anywhere             tcp dpt:1883 state NEW
    0     0 ACCEPT     tcp  --  enp0s3 any     anywhere             anywhere             tcp dpt:9091 state NEW
    0     0 ACCEPT     tcp  --  enp0s3 any     anywhere             anywhere             tcp dpt:51413 state NEW
    2    80 DROP       all  --  enp0s3 any     anywhere             anywhere            

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 ACCEPT     all  --  enp0s3 none    anywhere             anywhere             state RELATED,ESTABLISHED
    0     0 ACCEPT     all  --  none   enp0s3  anywhere             anywhere            
    0     0 DROP       all  --  enp0s3 none    anywhere             anywhere            

Chain OUTPUT (policy ACCEPT 4236 packets, 592K bytes)
 pkts bytes target     prot opt in     out     source               destination        
```

See that for the rule that allows all from anywhere -> anywhere the `in` column says none

Also, see the output of `iptables-save`
```
# Generated by iptables-save v1.6.1 on Sun Jan 27 07:52:12 2019
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [4573:631516]
-A INPUT -i lo -j ACCEPT
-A INPUT -p tcp -m tcp --dport 111 -j DROP
-A INPUT -p udp -m udp --dport 111 -j DROP
-A INPUT -p tcp -m tcp --dport 3306 -j DROP
-A INPUT -p udp -m udp --dport 3306 -j DROP
-A INPUT -p tcp -m tcp --dport 5432 -j DROP
-A INPUT -p udp -m udp --dport 5432 -j DROP
-A INPUT -p tcp -m tcp --dport 5984 -j DROP
-A INPUT -p udp -m udp --dport 5984 -j DROP
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -i none -m state --state NEW -j ACCEPT
-A INPUT -p udp -m udp --dport 5353 -j ACCEPT
-A INPUT -i enp0s3 -p tcp -m tcp --dport 22 -m state --state NEW -j ACCEPT
-A INPUT -i enp0s3 -p tcp -m tcp --dport 80 -m state --state NEW -j ACCEPT
-A INPUT -i enp0s3 -p tcp -m tcp --dport 3000 -m state --state NEW -j ACCEPT
-A INPUT -i enp0s3 -p tcp -m tcp --dport 8008 -m state --state NEW -j ACCEPT
-A INPUT -i enp0s3 -p tcp -m tcp --dport 8009 -m state --state NEW -j ACCEPT
-A INPUT -i enp0s3 -p tcp -m tcp --dport 8080 -m state --state NEW -j ACCEPT
-A INPUT -i enp0s3 -p tcp -m tcp --dport 631 -m state --state NEW -j ACCEPT
-A INPUT -i enp0s3 -p tcp -m tcp --dport 8089 -m state --state NEW -j ACCEPT
-A INPUT -i enp0s3 -p tcp -m tcp --dport 1880 -m state --state NEW -j ACCEPT
-A INPUT -i enp0s3 -p tcp -m tcp --dport 1883 -m state --state NEW -j ACCEPT
-A INPUT -i enp0s3 -p tcp -m tcp --dport 9091 -m state --state NEW -j ACCEPT
-A INPUT -i enp0s3 -p tcp -m tcp --dport 51413 -m state --state NEW -j ACCEPT
-A INPUT -i enp0s3 -j DROP
-A FORWARD -i enp0s3 -o none -m state --state RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i none -o enp0s3 -j ACCEPT
-A FORWARD -i enp0s3 -o none -j DROP
COMMIT
# Completed on Sun Jan 27 07:52:12 2019
# Generated by iptables-save v1.6.1 on Sun Jan 27 07:52:12 2019
*nat
:PREROUTING ACCEPT [4:769]
:INPUT ACCEPT [2:133]
:OUTPUT ACCEPT [140:10050]
:POSTROUTING ACCEPT [140:10050]
COMMIT
# Completed on Sun Jan 27 07:52:12 2019

```

and see that the rule which you listed as 
`ACCEPT all -- anywhere anywhere state NEW`
is actually
`-A INPUT -i none -m state --state NEW -j ACCEPT`

All this goes with the caveat that I may be missing something too... :)

**Comment by jvonau** [comment]
The 'none' above should not exist while in gateway mode, that should be 'br0', while Appliance or LanController use a much shorter rules set noted last below.
> grep iiab_network_mode_applied /etc/iiab/iiab.ini

iiab_network_mode_applied = Gateway


> iptables -v -L

Chain INPUT (policy ACCEPT 21 packets, 2320 bytes)
 pkts bytes target     prot opt in     out     source               destination         
3856K  522M ACCEPT     all  --  lo     any     anywhere             anywhere            
    0     0 DROP       tcp  --  any    any     anywhere             anywhere             tcp dpt:sunrpc
    0     0 DROP       udp  --  any    any     anywhere             anywhere             udp dpt:sunrpc
    0     0 DROP       tcp  --  any    any     anywhere             anywhere             tcp dpt:mysql
    0     0 DROP       udp  --  any    any     anywhere             anywhere             udp dpt:mysql
    0     0 DROP       tcp  --  any    any     anywhere             anywhere             tcp dpt:postgresql
    0     0 DROP       udp  --  any    any     anywhere             anywhere             udp dpt:postgresql
    0     0 DROP       tcp  --  any    any     anywhere             anywhere             tcp dpt:5984
    0     0 DROP       udp  --  any    any     anywhere             anywhere             udp dpt:5984
 305K  154M ACCEPT     all  --  any    any     anywhere             anywhere             state RELATED,ESTABLISHED
  255 19864 ACCEPT     all  --  br0    any     anywhere             anywhere             state NEW
12790 2067K ACCEPT     udp  --  any    any     anywhere             anywhere             udp dpt:mdns
    0     0 ACCEPT     tcp  --  eno1   any     anywhere             anywhere             tcp dpt:ssh state NEW
   11   572 ACCEPT     tcp  --  eno1   any     anywhere             anywhere             tcp dpt:http state NEW
    0     0 ACCEPT     tcp  --  eno1   any     anywhere             anywhere             tcp dpt:3000 state NEW
    0     0 ACCEPT     tcp  --  eno1   any     anywhere             anywhere             tcp dpt:8008 state NEW
    0     0 ACCEPT     tcp  --  eno1   any     anywhere             anywhere             tcp dpt:8009 state NEW
    0     0 ACCEPT     tcp  --  eno1   any     anywhere             anywhere             tcp dpt:http-alt state NEW
    0     0 ACCEPT     tcp  --  eno1   any     anywhere             anywhere             tcp dpt:ipp state NEW
    0     0 ACCEPT     tcp  --  eno1   any     anywhere             anywhere             tcp dpt:8089 state NEW
    1    52 ACCEPT     tcp  --  eno1   any     anywhere             anywhere             tcp dpt:1880 state NEW
    0     0 ACCEPT     tcp  --  eno1   any     anywhere             anywhere             tcp dpt:1883 state NEW
    0     0 ACCEPT     tcp  --  eno1   any     anywhere             anywhere             tcp dpt:9091 state NEW
    0     0 ACCEPT     tcp  --  eno1   any     anywhere             anywhere             tcp dpt:51413 state NEW
23581  982K DROP       all  --  eno1   any     anywhere             anywhere            

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 ACCEPT     all  --  eno1   br0     anywhere             anywhere             state RELATED,ESTABLISHED
    0     0 ACCEPT     all  --  br0    eno1    anywhere             anywhere            
    0     0 DROP       all  --  eno1   br0     anywhere             anywhere  

Chain OUTPUT (policy ACCEPT 4152K packets, 552M bytes)
 pkts bytes target     prot opt in     out     source               destination         

> grep iiab_network_mode_applied /etc/iiab/iiab.ini

iiab_network_mode_applied = Appliance
> iptables -v -L

Chain INPUT (policy ACCEPT 444K packets, 194M bytes)
 pkts bytes target     prot opt in     out     source               destination         
5311K  834M ACCEPT     all  --  lo     any     anywhere             anywhere            
    0     0 DROP       tcp  --  any    any     anywhere             anywhere             tcp dpt:sunrpc
    0     0 DROP       udp  --  any    any     anywhere             anywhere             udp dpt:sunrpc
    0     0 DROP       tcp  --  any    any     anywhere             anywhere             tcp dpt:mysql
    0     0 DROP       udp  --  any    any     anywhere             anywhere             udp dpt:mysql
    0     0 DROP       tcp  --  any    any     anywhere             anywhere             tcp dpt:postgresql
    0     0 DROP       udp  --  any    any     anywhere             anywhere             udp dpt:postgresql
    0     0 DROP       tcp  --  any    any     anywhere             anywhere             tcp dpt:5984
    0     0 DROP       udp  --  any    any     anywhere             anywhere             udp dpt:5984

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 5741K packets, 877M bytes)
 pkts bytes target     prot opt in     out     source               destination

**Comment by m-anish** [comment]
FWIW, the issue primarily relates to Appliance mode IMHO. 

The iptables I posted were also in appliance mode.

**Comment by jvonau** [comment]
and the commit that broke the logic https://github.com/iiab/iiab/commit/eaf81d0d6be5cce027883247e489d43ae6bf197d

**Comment by holta** [comment]
> and the commit that broke the logic [eaf81d0](https://github.com/iiab/iiab/commit/eaf81d0d6be5cce027883247e489d43ae6bf197d)

I'll fix this in the coming ~24h &mdash; thanks @jvonau who explained this to me during our http://minutes.iiab.io community/team call earlier today.
