### ISSUE TITLE
[CI] Don't hardcode roles paths in test.yml

### ISSUE THREAD

**Issue by arky** [iiab/iiab#1068]
Correct the roles path, don't hardcode the role path in test.yml. Right now we do  hardcode all the roles manually with  ls -l roles/ | cut -d " " -f 10

https://github.com/iiab/iiab/blob/master/tests/test.yml#L8-L61

Task list for #1055

**Comment by holta** [comment]
@arky thanks for making this happen!

(Please re-open if more is nec!)
