### ISSUE TITLE
Allow remote IIAB Deployments from local computer 

### ISSUE THREAD

**Issue by arky** [iiab/iiab#1070]
Allow IIAB deployments from remote machines (The Ansible Way).  IIAB is installed by running ansible commands on the deployments machine locally. The ideal way is to use ansible from local computer/laptop and ansible runs the IIAB deployments on the target machine.

Why you need this?
 * This is how ansible is designed to work. 
 * Helps you run deployments from your local computer over a network on headless systems like raspberry pi.
 * You can quickly modify/update large number of deployments which physically logging into the machine using SSH
* You can do CI/Unit Testing by creating vagrant virtual machines. 

Task List for #1055

**Comment by arky** [comment]
@jvonau Please do share the complete details about this 'os_ver' problem. Let's get this patched upstream quickly.

**Comment by jvonau** [comment]
I have been able to boot a rpi and run ansible against the rpi without having ansible installed on the target.

**Comment by jvonau** [comment]
close no interest.

**Comment by holta** [comment]
> close no interest.

Ok.

(This can be re-opened at any time if someone is motivated to work on this to fit worthy community needs!)
