### ISSUE TITLE
Clean up RedirectMatch rules (for Kolibri & others?)

### ISSUE THREAD

**Issue by arky** [iiab/iiab#1109]
Perhaps we need to investigate IIAB RedirectMatch rules as pointed out by Ivan in https://github.com/iiab/iiab/issues/913#issuecomment-410484137

> Scoping directives to <VirtualHost *:80> has some unholy interaction with the RedirectMatch ^/$ /home in sites-enabled/iiab-homepage.conf (/kolibri opens the python server on port 8009 but /kolibri/ was sending me to /home/) 
https://github.com/iiab/iiab/issues/913#issuecomment-410484137

https://github.com/iiab/iiab/blob/d1bbffb14f75794689a8b30c925b1f51b2894e76/roles/homepage/templates/iiab-homepage.conf#L9

Refer: https://github.com/iiab/iiab/issues/913

**Comment by holta** [comment]
Thanks @arky if you're able to research this in coming weeks &mdash; for the benefit of #923 and all playbooks?

**Comment by holta** [comment]
Can this build on the RedirectMatch used in PR #1060 "http://box/kiwix was failing" ?

**Comment by holta** [comment]
@arky can we close this now that your #913 -> PR #1412 are complete?

Or feel free to re-open as nec!
