### ISSUE TITLE
Nextcloud not accessible from VPN

### ISSUE THREAD

**Issue by tim-moody** [iiab/iiab#111]
/etc/apache2/sites-available/nextcloud.conf has

Require ip 127.0.0.1 172.18.96.1/255.255.224.0 192.168.0.0/255.255.255.0

to which must be added 10.8.0.0/255.255.255.0 (or we could ease the restriction)

(nextcloud config.php has '*' so it is already wide open)

**Comment by holta** [comment]
Does this apply only over VPN?

Or is "campus" use of Nextcloud also blocked on the WAN side of an IIAB 6.3 ?

**Comment by tim-moody** [comment]
campus works, vpn not

**Comment by jvonau** [comment]
What is the ip/netmask of the "campus" network that was tested? If the "campus" network is the same as what is defined in Require ip already it will work. However if the "campus" network falls outside of what is defined in Require ip then you can't login. ie 192.168.122.0/24 would fail. I suspect that Tim's network is already using 192.168.0.0/24

**Comment by tim-moody** [comment]
unless of course the required ip is softcoded to that of server.

**Comment by jvonau** [comment]
Perfect, in a dhcp environment where the portable server is jacked into different WANs on a regular bases what would be the procedure to refresh this "Require ip" setting?

**Comment by holta** [comment]
@tim-moody I still feel this is important, but will move it to our [IIAB 6.7 Milestone](https://github.com/iiab/iiab/milestone/4) if it's not likely to converge now in coming weeks ?

@jvonau: do you think this is plausibly solvable?  Or not realistic?

Somewhat related:
#551 "How to mitigate campuswide failures for Nextcloud, WordPress, Moodle, Elgg etc?"

**Comment by holta** [comment]
@jvonau suggests this restriction is likely in Nextcloud or Apache config files &mdash; sounds very solvable.

**Comment by holta** [comment]
Fixed by PR #967, Thanks @georgejhunt !
