### ISSUE TITLE
Upgrade path?

### ISSUE THREAD

**Issue by jvonau** [iiab/iiab#112]
How are future upgrades going to be handled? Lets say going from 6.3 -> 6.4
The acid test for a clean upgrade path is git checkout -b <new_release> and a git pull origin <new_release> 
Starting from a fresh clone:
git clone https://github.com/iiab/iiab -b 6.3-rc2 --depth 1
[root@box iiab]# cd iiab
[root@box iiab]# git branch
* 6.3-rc2
[root@box iiab]# git checkout -b 6.4
Switched to a new branch '6.4'

The end user should be able to switch from the current branch to any other release branch or master without issues.
Using master as an example
[root@box iiab]# git pull origin master
remote: Counting objects: 1366, done.
remote: Compressing objects: 100% (618/618), done.
remote: Total 1366 (delta 773), reused 1214 (delta 640), pack-reused 0
Receiving objects: 100% (1366/1366), 385.57 KiB | 0 bytes/s, done.
Resolving deltas: 100% (773/773), completed with 167 local objects.
From https://github.com/iiab/iiab
 * branch            master     -> FETCH_HEAD
Auto-merging vars/default_vars.yml
CONFLICT (add/add): Merge conflict in vars/default_vars.yml
Auto-merging runansible
CONFLICT (add/add): Merge conflict in runansible
Auto-merging roles/xovis/tasks/main.yml
CONFLICT (add/add): Merge conflict in roles/xovis/tasks/main.yml
Auto-merging roles/wordpress/tasks/install.yml
CONFLICT (add/add): Merge conflict in roles/wordpress/tasks/install.yml
Auto-merging roles/teamviewer/tasks/install.yml
CONFLICT (add/add): Merge conflict in roles/teamviewer/tasks/install.yml
Auto-merging roles/sugarizer/tasks/main.yml
CONFLICT (add/add): Merge conflict in roles/sugarizer/tasks/main.yml
Auto-merging roles/sugar-stats/tasks/statistics-consolidation.yml
CONFLICT (add/add): Merge conflict in roles/sugar-stats/tasks/statistics-consolidation.yml
Auto-merging roles/schooltool/tasks/main.yml
CONFLICT (add/add): Merge conflict in roles/schooltool/tasks/main.yml
Auto-merging roles/postgresql/tasks/main.yml
CONFLICT (add/add): Merge conflict in roles/postgresql/tasks/main.yml
Auto-merging roles/phpmyadmin/tasks/main.yml
CONFLICT (add/add): Merge conflict in roles/phpmyadmin/tasks/main.yml
Auto-merging roles/pathagar/tasks/main.yml
CONFLICT (add/add): Merge conflict in roles/pathagar/tasks/main.yml
Auto-merging roles/owncloud/tasks/main.yml
CONFLICT (add/add): Merge conflict in roles/owncloud/tasks/main.yml
Auto-merging roles/owncloud/tasks/F18.yml
CONFLICT (add/add): Merge conflict in roles/owncloud/tasks/F18.yml
Auto-merging roles/osm/tasks/main.yml
CONFLICT (add/add): Merge conflict in roles/osm/tasks/main.yml
Auto-merging roles/openvpn/tasks/main.yml
CONFLICT (add/add): Merge conflict in roles/openvpn/tasks/main.yml
Auto-merging roles/nextcloud/tasks/nextcloud_enabled.yml
CONFLICT (add/add): Merge conflict in roles/nextcloud/tasks/nextcloud_enabled.yml
Auto-merging roles/nextcloud/tasks/main.yml
CONFLICT (add/add): Merge conflict in roles/nextcloud/tasks/main.yml
Auto-merging roles/nextcloud/tasks/F18.yml
CONFLICT (add/add): Merge conflict in roles/nextcloud/tasks/F18.yml
Auto-merging roles/network/templates/squid/squid.sysconfig
CONFLICT (add/add): Merge conflict in roles/network/templates/squid/squid.sysconfig
Auto-merging roles/network/templates/named/named.j2
CONFLICT (add/add): Merge conflict in roles/network/templates/named/named.j2
Auto-merging roles/network/templates/named/named
CONFLICT (add/add): Merge conflict in roles/network/templates/named/named
Auto-merging roles/network/templates/dhcp/dhcpd-env.j2
CONFLICT (add/add): Merge conflict in roles/network/templates/dhcp/dhcpd-env.j2
Auto-merging roles/network/tasks/squid.yml
CONFLICT (add/add): Merge conflict in roles/network/tasks/squid.yml
Auto-merging roles/network/tasks/rpi_debian.yml
CONFLICT (add/add): Merge conflict in roles/network/tasks/rpi_debian.yml
Auto-merging roles/network/tasks/restart.yml
CONFLICT (add/add): Merge conflict in roles/network/tasks/restart.yml
Auto-merging roles/network/tasks/named.yml
CONFLICT (add/add): Merge conflict in roles/network/tasks/named.yml
Auto-merging roles/network/tasks/main.yml
CONFLICT (add/add): Merge conflict in roles/network/tasks/main.yml
Auto-merging roles/network/tasks/ifcfg_mods.yml
CONFLICT (add/add): Merge conflict in roles/network/tasks/ifcfg_mods.yml
Auto-merging roles/network/tasks/enable_services.yml
CONFLICT (add/add): Merge conflict in roles/network/tasks/enable_services.yml
Auto-merging roles/network/tasks/dhcpd.yml
CONFLICT (add/add): Merge conflict in roles/network/tasks/dhcpd.yml
Auto-merging roles/network/tasks/debian.yml
CONFLICT (add/add): Merge conflict in roles/network/tasks/debian.yml
Auto-merging roles/mysql/tasks/main.yml
CONFLICT (add/add): Merge conflict in roles/mysql/tasks/main.yml
Auto-merging roles/moodle/tasks/main.yml
CONFLICT (add/add): Merge conflict in roles/moodle/tasks/main.yml
Auto-merging roles/moodle-1.9/moodle/tasks/main.yml
CONFLICT (add/add): Merge conflict in roles/moodle-1.9/moodle/tasks/main.yml
Auto-merging roles/monit/templates/postgresql
CONFLICT (add/add): Merge conflict in roles/monit/templates/postgresql
Auto-merging roles/monit/tasks/main.yml
CONFLICT (add/add): Merge conflict in roles/monit/tasks/main.yml
Auto-merging roles/mongodb/tasks/main.yml
CONFLICT (add/add): Merge conflict in roles/mongodb/tasks/main.yml
Auto-merging roles/kiwix/templates/iiab-make-kiwix-lib.py
CONFLICT (add/add): Merge conflict in roles/kiwix/templates/iiab-make-kiwix-lib.py
Auto-merging roles/kiwix/templates/iiab-make-apache-config.py
CONFLICT (add/add): Merge conflict in roles/kiwix/templates/iiab-make-apache-config.py
Auto-merging roles/kiwix/tasks/main.yml
CONFLICT (add/add): Merge conflict in roles/kiwix/tasks/main.yml
Auto-merging roles/kiwix/tasks/kiwix_install.yml
CONFLICT (add/add): Merge conflict in roles/kiwix/tasks/kiwix_install.yml
Auto-merging roles/kalite/tasks/main.yml
CONFLICT (add/add): Merge conflict in roles/kalite/tasks/main.yml
Auto-merging roles/kalite/tasks/install.yml
CONFLICT (add/add): Merge conflict in roles/kalite/tasks/install.yml
Auto-merging roles/kalite/tasks/install-f18.yml
CONFLICT (add/add): Merge conflict in roles/kalite/tasks/install-f18.yml
Auto-merging roles/httpd/templates/php.ini.j2
CONFLICT (add/add): Merge conflict in roles/httpd/templates/php.ini.j2
Auto-merging roles/httpd/tasks/html.yml
CONFLICT (add/add): Merge conflict in roles/httpd/tasks/html.yml
Auto-merging roles/gateway/README.rst
CONFLICT (add/add): Merge conflict in roles/gateway/README.rst
Auto-merging roles/elgg/templates/settings.php.j2
CONFLICT (add/add): Merge conflict in roles/elgg/templates/settings.php.j2
Auto-merging roles/elgg/tasks/main.yml
CONFLICT (add/add): Merge conflict in roles/elgg/tasks/main.yml
Auto-merging roles/elgg/defaults/main.yml
CONFLICT (add/add): Merge conflict in roles/elgg/defaults/main.yml
Auto-merging roles/dokuwiki/tasks/install.yml
CONFLICT (add/add): Merge conflict in roles/dokuwiki/tasks/install.yml
Auto-merging roles/debian_schooltool/tasks/main.yml
CONFLICT (add/add): Merge conflict in roles/debian_schooltool/tasks/main.yml
Auto-merging roles/cups/tasks/main.yml
CONFLICT (add/add): Merge conflict in roles/cups/tasks/main.yml
Auto-merging roles/calibre/tasks/main.yml
CONFLICT (add/add): Merge conflict in roles/calibre/tasks/main.yml
Auto-merging roles/awstats/tasks/install.yml
CONFLICT (add/add): Merge conflict in roles/awstats/tasks/install.yml
Auto-merging roles/authserver/tasks/main.yml
CONFLICT (add/add): Merge conflict in roles/authserver/tasks/main.yml
Auto-merging roles/ajenti/tasks/main.yml
CONFLICT (add/add): Merge conflict in roles/ajenti/tasks/main.yml
Auto-merging roles/ajenti/tasks/ajenti-wondershaper.yml
CONFLICT (add/add): Merge conflict in roles/ajenti/tasks/ajenti-wondershaper.yml
Auto-merging roles/4-server-options/tasks/main.yml
CONFLICT (add/add): Merge conflict in roles/4-server-options/tasks/main.yml
Auto-merging roles/3-base-server/templates/profile_ssh_warn.sh
CONFLICT (add/add): Merge conflict in roles/3-base-server/templates/profile_ssh_warn.sh
Auto-merging roles/2-common/tasks/yum.yml
CONFLICT (add/add): Merge conflict in roles/2-common/tasks/yum.yml
Auto-merging roles/2-common/tasks/xo.yml
CONFLICT (add/add): Merge conflict in roles/2-common/tasks/xo.yml
Auto-merging roles/2-common/tasks/packages.yml
CONFLICT (add/add): Merge conflict in roles/2-common/tasks/packages.yml
Auto-merging roles/2-common/tasks/iiab_ini.yml
CONFLICT (add/add): Merge conflict in roles/2-common/tasks/iiab_ini.yml
Auto-merging roles/1-prep/templates/iiab.env.j2
CONFLICT (add/add): Merge conflict in roles/1-prep/templates/iiab.env.j2
Auto-merging roles/1-prep/tasks/prep.yml
CONFLICT (add/add): Merge conflict in roles/1-prep/tasks/prep.yml
Auto-merging roles/1-prep/tasks/main.yml
CONFLICT (add/add): Merge conflict in roles/1-prep/tasks/main.yml
Auto-merging roles/1-prep/tasks/iiab_ini.yml
CONFLICT (add/add): Merge conflict in roles/1-prep/tasks/iiab_ini.yml
Auto-merging roles/1-prep/tasks/detected_network.yml
CONFLICT (add/add): Merge conflict in roles/1-prep/tasks/detected_network.yml
Auto-merging roles/1-prep/tasks/computed_vars.yml
CONFLICT (add/add): Merge conflict in roles/1-prep/tasks/computed_vars.yml
Auto-merging roles/1-prep/defaults/main.yml
CONFLICT (add/add): Merge conflict in roles/1-prep/defaults/main.yml
Auto-merging iiab.yml
CONFLICT (add/add): Merge conflict in iiab.yml
Auto-merging iiab-network.yml
CONFLICT (add/add): Merge conflict in iiab-network.yml
Auto-merging iiab-from-console.yml
CONFLICT (add/add): Merge conflict in iiab-from-console.yml
Auto-merging iiab-base.yml
CONFLICT (add/add): Merge conflict in iiab-base.yml
Auto-merging ansible.cfg
CONFLICT (add/add): Merge conflict in ansible.cfg
Automatic merge failed; fix conflicts and then commit the result

**Comment by holta** [comment]
There is basically nearly-zero demand for upgrades, as the offline world (essentially!) always asks for new content + new features to be bundled onto 1 new SD card or similar.

*BUT* we should be open to an upgrade process if it hopefully becomes genuinely hassle-free at some point in future... as offline nations/regions acquire partial connectivity increasingly, and so become tempted by partial upgrades of content especially~

**Comment by jvonau** [comment]
"upgrade process if it hopefully becomes genuinely hassle-free"
The hassle-free part comes from using git correctly.
