### ISSUE TITLE
Unable to install ansible on lite 6-27-2018 [squid fails w/ raspbian.raspberrypi.org &/or mirrordirector.raspbian.org ?]

### ISSUE THREAD

**Issue by georgejhunt** [iiab/iiab#1162]
Fresh dd from image

1. apt-get update runs successfully
2. apt-get upgrade, and apt-get dist-upgrade fail
3. message when running ./scripts/ansible:

<snipped from running ./scripts/ansible by hand>
COMPLETE INSTALL INSTRUCTIONS:
https://github.com/iiab/iiab/wiki/IIAB-Installation#do-everything-from-scratch

VERIFY YOU'RE ONLINE BEFORE RUNNING THIS: /opt/iiab/iiab/scripts/ansible
Alternative: Run /opt/iiab/iiab/scripts/ansible-2.6.x ("slow food")

Ansible NOT found on this computer.
INTERNET-IN-A-BOX GENERALLY REQUIRES ANSIBLE VERSION: 2.6.4 or higher
scripts/ansible will now try to install the very latest Ansible...

apt update; install dirmngr; PPA to /etc/apt/sources.list.d/iiab-ansible.list

Get:1 http://raspbian.raspberrypi.org/raspbian stretch InRelease [15.0 kB]
Get:2 http://archive.raspberrypi.org/debian stretch InRelease [25.3 kB]        
Fetched 40.3 kB in 40s (991 B/s)                                               
Reading package lists... Done
Building dependency tree       
Reading state information... Done
39 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Suggested packages:
  dbus-user-session pinentry-gnome3 tor
The following NEW packages will be installed:
  dirmngr
0 upgraded, 1 newly installed, 0 to remove and 39 not upgraded.
Need to get 547 kB of archives.
After this operation, 963 kB of additional disk space will be used.
Err:1 http://raspbian.raspberrypi.org/raspbian stretch/main armhf dirmngr armhf 2.1.18-8~deb9u2
  503  Service Unavailable
E: Failed to fetch http://raspbian.raspberrypi.org/raspbian/pool/main/g/gnupg2/dirmngr_2.1.18-8~deb9u2_armhf.deb  503  Service Unavailable
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
root@raspberrypi:/opt/iiab/iiab/scripts# 

It may be an ISP issue. But I've rebooted the router, and all my ping tests succeed.
I don't know what the try next.
Do others have any difficullty?

**Comment by holta** [comment]
I just ran http://download.iiab.io/6.7/install.txt on a fresh Raspbian Lite 2018-06-27 and Ansible 2.6.4 installed successfully.

Is this still a problem for you @georgejhunt ?

**Comment by holta** [comment]
@georgejhunt if your ISP or Raspbian mirrors are giving you hell, consider pip installing Ansible instead?

FWIW even Ansible 2.7 RC3 is installable using `pip install ansible==2.7.0rc3` as mentioned at https://groups.google.com/forum/#!topic/ansible-devel/p96SnU6Z7Js (Ansible 2.7 is expected to be released in 12 days on Thursday 2018-10-04, just as [Detroit's OpenStreetMap conference](http://2018.stateofthemap.us) begins) according to https://docs.ansible.com/ansible/devel/roadmap/ROADMAP_2_7.html).  #1100

**Comment by georgejhunt** [comment]
I think ansible just happened to be the first error I encountered.
I'm living in mirrordirector hell. Can you tell me more about it?

**Comment by holta** [comment]
@georgejhunt should we re-open July ticket https://github.com/iiab/iiab/issues/953 relating to Raspbian mirror failings?
