### ISSUE TITLE
sqlite3 installation under 3-base-server (should this be mandatory?)

### ISSUE THREAD

**Issue by holta** [iiab/iiab#1191]
@georgejhunt indicates he may work on this in coming weeks.

Should this appear right next to SQLite presumably, around Line 17 of https://github.com/iiab/iiab/blob/master/roles/3-base-server/tasks/main.yml#L17 ?

For those implementers who do not need Captive Portal and Calibre, should this be mandatory?

Ref PRs: #1179 #1180 #1185 #1187

**Comment by holta** [comment]
@georgejhunt feel free to un-assign yourself (if you no longer want to work on this!)

**Comment by holta** [comment]
@georgejhunt & All, please see related ticket #1206

**Comment by tim-moody** [comment]
if it is part of base it is mandatory. otherwise it remains a dependency of several roles

**Comment by holta** [comment]
Is @georgejhunt's PR #809 "load php-sqlite on ubuntu" partially relevant, from May 2018?

**Comment by holta** [comment]
@jvonau & All: can we close this tkt?

(Or act on it, as nec?)

**Comment by jvonau** [comment]
Once #2070 with the addition of sqlite3 in 2-common's packages.yml lands this issue would be resolved.

**Comment by holta** [comment]
sqlite3 is not being installed by 2-common, as a result of PR #2070
