### ISSUE TITLE
sugarizer fails to untar on rpi

### ISSUE THREAD

**Issue by tim-moody** [iiab/iiab#12]
root@box:/tmp# tar xzf /opt/schoolserver/downloads/sugarizer-0.8.tar.gz
tar: Skipping to next header
tar: A lone zero block at 543329
tar: Exiting with failure status due to previous errors

**Comment by georgejhunt** [comment]
I'm wondering if there's a memory or disk free space issue.  I think this
has worked on rpi3 before.

If not, we can re-tar it on a machine that does not have the problem

**Comment by tim-moody** [comment]
I removed /opt/schoolserver/downloads/sugarizer-0.8.tar.gz and did runtags sugarizer with install true and enable false and it re downloaded and untarred OK

**Comment by tim-moody** [comment]
I then set enabled true an reran runtags and it succeeded.
