### ISSUE TITLE
iiab.io should redirect to internet-in-a-box.org

### ISSUE THREAD

**Issue by veeara282** [iiab/iiab#1203]
Currently, http://iiab.io doesn't go anywhere, like http://faq.iiab.io does. The most sensible URL for it to redirect to would be the Internet-in-a-Box homepage.

**Comment by tim-moody** [comment]
the dilemma is that this content is very out of date

**Comment by holta** [comment]
http://iiab.io was used for Internet-in-a-Box implementer community forums however this server (hosted in India) had very serious problems, so http://internet-in-a-box.org is an acceptable solution in the interim.

The change is complete, though DNS can take time to propagate of course.

**Comment by veeara282** [comment]
Okay, thank you!
