### ISSUE TITLE
dnsmasq service fails to start more than 50% of the time ("timeout was exceeded") on Ubuntu 16.04

### ISSUE THREAD

**Issue by holta** [iiab/iiab#1214]
Arising from #1184: `./iiab-network` continues to fail more than 50% of the time on Ubuntu 16.04, with error message:

> TASK [network : dhcp_server may be affected - starting - user choice] **********
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Unable to start service dnsmasq: Job for dnsmasq.service failed because a timeout was exceeded. See \"systemctl status dnsmasq.service\" and \"journalctl -xe\" for details.\n"}
        to retry, use: --limit @/opt/iiab/iiab/iiab-stages.retry

**Comment by jvonau** [comment]
I see this as 16.04 is not a primary target I would suggest not using dnsmasq with that distro until this could be further debugged. I'd be inclined to tag this as won't fix with a known bug warning to edit local_vars when using this distro. I suspect 16.04 has a less than ideal dnsmasq.service systemd unit file compared to the other distros.

**Comment by jvonau** [comment]
https://bugs.launchpad.net/ubuntu/+source/dnsmasq/+bug/1761096

**Comment by tim-moody** [comment]
agree with Jerry. Just use bind/dhcpd

**Comment by holta** [comment]
@m-anish please see above, and help us migrate Node-RED and Mosquitto/MQTT (#854) to Ubuntu 18.04 if possible prior to IIAB 6.7's release in December!
