### ISSUE TITLE
Create a README for 0-init & roles/network !

### ISSUE THREAD

**Issue by holta** [iiab/iiab#1237]
Thanks @jvonau & @tim-moody & @georgejhunt if you can send a sentence or two my way!

(Quite confusing to new folk wanting to learn what we've built!  Also what does fl.yml stand for again?)

FYI 0-init is the only stage among 10 that doesn't have a description here: https://github.com/iiab/iiab/tree/master/roles

FYI https://github.com/iiab/iiab/tree/master/roles/network desperately needs a README too (I can transcribe & write that up if @jvonau wants to delineate some of the core principles/design decision embedded herein by phone :-)

Refs: #1200 #1236

**Comment by jvonau** [comment]
https://github.com/iiab/iiab/issues/234 needs to be dealt with first, the funky setting of mysql's service name can be removed form 0-init and use the values from os.yml exclusively.

**Comment by holta** [comment]
_Higher Priority?_ I want to rewrite ["Any other networking tips?"](http://wiki.laptop.org/go/IIAB/FAQ#Any_other_networking_tips.3F) within http://FAQ.IIAB.IO (Item 17) later this month when @jvonau has time to talk this over.
