### ISSUE TITLE
Cannot reliably ssh or route to RPi's wlan0 192.168.0.* after WiFi-installing IIAB

### ISSUE THREAD

**Issue by holta** [iiab/iiab#1257]
Confoundingly, "ssh pi@10.8.0.x" and routing to RPi's OpenVPN address (10.8.0.x) DO work reliably!

Even as these OpenVPN connections are routing over the very same WiFi connection that does NOT work reliably &mdash; when used directly ("ssh pi@192.168.0.x" often fails, at the very same time, when run from the very same machines on this same 192.168.0.* network).

The Failure/Symptom: every 30min (or every hour or so, more often on some machines than others) the other machines on this 192,168.0.x network cannot route to the RPi 3 B+ in question, showing this error:
```
root@box:~# ssh pi@192.168.0.102
ssh: connect to host 192.168.0.102 port 22: No route to host
```
Astonishingly, this only happens to some of the machine on this 192.168.0.x, for about 30min at a time, and affects different machines are affected each time, no matter if they are Windows machines or Linux machines.

More Context:
- MIN-sized http://download.iiab.io/6.7 (master branch of IIAB) was installed onto Raspbian Lite 2018-10-09 on RPi 3 B+.
- No Ethernet cord is attached.
- `iiab-hotspot-on` has not yet been run.
- The RPi's WiFi interface (wlan0) continues to work reliably as a WiFi client (for outgoing ssh connections and similar) as confirmed/seen by the existence of "wpa_supplicant" in the output of `systemctl status dhcpcd`
- "Permanently" disabling promiscuous mode on the RPi's wlan0 interface and rebooting does not help.
- This particular WiFi router has its WiFi "Address Lease Time" set to 120min
- @jvonau suggested monitoring the output of `arp -an` to track recent attempts at incoming ssh connections.  This command does indeed work, but (so far anyway) does not show any of the (failed) incoming ssh attempts.

**Comment by holta** [comment]
Tangentially related: #989 #926

**Comment by jvonau** [comment]
stale ticket flaky firmware
