### ISSUE TITLE
modify iiab-make-kiwix-lib.py to use bookid instead of array index

### ISSUE THREAD

**Issue by tim-moody** [iiab/iiab#1290]
https://github.com/kiwix/kiwix-tools/issues/228

**Comment by holta** [comment]
Clarif from @tim-moody:

> the problem is our code, not theirs. need to rewrite to accommodate https://github.com/kiwix/kiwix-tools/issues/228

**Comment by holta** [comment]
Appears resolved by PR #1292

Please continue testing!
