### ISSUE TITLE
rpi clock setup require change to local_vars

### ISSUE THREAD

**Issue by tim-moody** [iiab/iiab#13]
rtc_id: ds3231

must be in local_vars.yml or clock not setup

**Comment by tim-moody** [comment]
we should have a Raspbian.yml vars file that takes care of this
can still be overridden in local_vars

**Comment by tim-moody** [comment]
looks like ansible_distribution is Debian on rpi rather than Raspian and ansible_lsb['id'] is not defined on Centos!

**Comment by tim-moody** [comment]
actually on Centos 7.3 I get

  },
        "ansible_lsb": {
            "codename": "Core",
            "description": "CentOS Linux release 7.3.1611 (Core)",
            "id": "CentOS",
            "major_release": "7",
            "release": "7.3.1611"

so using ansible_lsb id should work

**Comment by georgejhunt** [comment]
There are many places in the playbook where we use ansible_distribution. I'd be in favor of changing them all  to ansible_lsb.id (smoke test required, I think)

**Comment by tim-moody** [comment]
I am working on this.

I think we should start with xsce.yml and OS.yml

later we should find ansible_distribution, presumably when: ansible_distribution == OS and change to use our is_OS flags

**Comment by tim-moody** [comment]
Another question is whether we should provide a default clock chip, which we didn't do in the past for some reason, e.g. 

rtc_id: ds3231

**Comment by georgejhunt** [comment]
no reason not to default to the current rtc_id.  +1

**Comment by holta** [comment]
DS3231 is the most common.

But we should support DS1307 as well: what instructions should I add to http://FAQ.IIAB.IO ?

(In 2016 I tested @georgejhunt's code worked with both chips, confirming the time was retained after yanking out Ethernet and rebooting: very oddly both worked!)

**Comment by jvonau** [comment]
[second commit](https://github.com/iiab/iiab/pull/58/commits/9ea621297c88561691d1ba38a0c8a7587b707a12) of #58

**Comment by tim-moody** [comment]
probably the default could go in raspian.yml, since we assume that os="raspian" is a marker for an rpi.

**Comment by jvonau** [comment]
#58 pushed, this issue can be closed.
