### ISSUE TITLE
offline testing w/ Ansible 2.3.1

### ISSUE THREAD

**Issue by jvonau** [iiab/iiab#132]
I ran across this error while testing ansible 2.3.1 with no internet cable present, should be reproducible with `./runtags prep` or a run of ansible under the console, addressed in PR #131 Possibly related [upstream issue](https://github.com/ansible/ansible/issues/16948), and the fix in [2.3.1](https://github.com/ansible/ansible/commit/cb7060c9fe28ba90c0ab16c95031eeadd484ea5b)

TASK [1-prep : Find active gateway config based on macaddress] ****************************************
skipping: [127.0.0.1]

TASK [1-prep : Set has ifcfg gw based on on macaddress if found] **************************************
fatal: [127.0.0.1]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'dict object' has no attribute 'stdout'\n\nThe error appears to have been in '/opt/schoolserver/iiab/roles/1-prep/tasks/detected_network.yml': line 102, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Set has ifcfg gw based on on macaddress if found\n  ^ here\n"}
	to retry, use: --limit @/opt/schoolserver/iiab/iiab.retry

Can somebody else pull the internet plug and test as above to confirm or dismiss this issue. 
On a positive note the playbooks that have *_install: True from http://download.iiab.io/6.3/rpi/local_vars.yml worked correctly, as in no ansible failures while offline. Functional testing not preformed, but proper service de/activation passed for the *_enabled part of the playbook.

**Comment by holta** [comment]
Is #66 important/relevant?

(Deprecation warnings with ansible 2.3+)

**Comment by jvonau** [comment]
Think the warning have been silenced.
