### ISSUE TITLE
"Captive Portal fails when IIAB installed on Ubuntu"

### ISSUE THREAD

**Issue by holta** [iiab/iiab#1366]
@georgejhunt

Am opening a new tkt as #1323 appears to largely solve Android 8/9 issues?

Whereas "Captive Portal fails completely" (or so it would appear!) when IIAB is installed on Ubuntu 18.04 or 16.04: https://github.com/iiab/iiab/issues/1323#issuecomment-452546824

**Comment by holta** [comment]
@georgejhunt has not tested Captive Portal on Ubuntu 18.04 or any other OS's aside from Raspbian on RPi 3 (or 3 B+).

While important, this work may need to be delayed until IIAB 7.0.

For now I've documented this problem at the bottom of:
https://github.com/iiab/iiab/wiki/IIAB-6.7-Release-Notes#known-issues

**Comment by holta** [comment]
@georgejhunt there are more than a few people that would love Captive Portal to work on Ubuntu, but I'm assuming this is not possible before IIAB 7.1 is released on/around 2020-01-30 ?

**Comment by jvonau** [comment]
works on U20 with wifi firmware
