### ISSUE TITLE
Make en-oob.json far more inviting & instructive (incl video screencast if poss!)

### ISSUE THREAD

**Issue by holta** [iiab/iiab#1410]
I can helping with the writing making [en-oob.json](https://github.com/iiab/iiab-admin-console/blob/master/roles/js-menu/files/menu-files/menu-defs/en-oob.json) more instructive & enticing/approachable, while @georgejhunt is working on a short screencast to show off new Dynamic Menuing so implementers visually+rapidly understand their options.

@kananigit suggests using VokoScreen on Ubuntu?  Other screencasting packages are also possible: https://itsfoss.com/best-linux-screen-recorders/

Refs:
#1002 "Update iiab-menu with all recent Content Pack descriptions/logos"
#1031 "sampler.html page (used by http://box/home/index.html OOB) needs an overhaul [actually removal!]"
iiab/iiab-menu#9 "Redevelopment Plans"

**Comment by holta** [comment]
I will add a link to @georgejhunt's video in coming days:

> From: George Hunt
> Date: Sat, Jan 19, 2019 at 3:19 PM
> Subject: First iiab video -- 12 minutes, 30MB
>
> I played around some trying to find a free open source tool set to use
to generate screen casts. But in the end, it seemed better to use what
was already available to me on my Mac.
>
> I used QuickTime player to record, iMovie to edit, and VLC to shrink
from 200MB to 30MB.
>
> The results are at https://youtu.be/aYdF4STl97s

**Comment by holta** [comment]
As discussed in today's community/team call (http://minutes.iiab.io) @georgejhunt might also:

- _(short term)_ publish an MP4 and WebM version of the above video, for those wanting to play it offline, in support of almost all browsers/modern OS's.
- _(medium term)_ fix a couple factual errors in the vid, that @tim-moody pointed out
- _(long term)_ re-record the 13min video as a series of much shorter 2-to-4min videos on different introductory topics.

**Comment by georgejhunt** [comment]
I edited the 13 minute source into smaller chunks, and created webm format
(which as Tim said, just plays in a browser with no player).

The new stuff is at http://d.iiab.io/content/video.

**Comment by holta** [comment]
> @georgejhunt can you please publish these 3 to YouTube ?

1) This is important so we don't abuse donated bandwidth.
2) Secondarily, was .mp4 avoided at http://d.iiab.io/content/videos/ for a reason?  (I was talking to a volunteer who publishes community videos yesterday, and .mp4 is by far the most popular video format as of today anyway!)

**Comment by holta** [comment]
@m-anish willing to help with short IIAB DIY videos, and recommends:
- https://creatoracademy.youtube.com/page/browse tips to enhance your YouTube channel
- https://obsproject.com software to stream directly to YouTube (overlaying diff screens capture vs. logo vs. scene of room)

**Comment by holta** [comment]
@georgejhunt thanks for publishing the three shorter/topical (nicely edited) .mp4 videos here!
http://d.iiab.io/content/videos/

Can you publish these to YouTube in the coming 24h if poss?

**Comment by georgejhunt** [comment]
Done.
https://youtu.be/mWEDMY5a-WY
https://youtu.be/P-NYNTe17gg
https://youtu.be/mmwyLVlEqrg

**Comment by holta** [comment]
> https://youtu.be/mmwyLVlEqrg

Small typo here: opening title of video says "IIAB 2.7" instead of 6.7 :)

**Comment by holta** [comment]
@georgejhunt a small [TOC](http://d.iiab.io/content/videos/HEADER.html) was added at the top of http://d.iiab.io/content/videos

LMK if this needs revising?

**Comment by holta** [comment]
Tangentially related Admin Console / Menuing tickets...as we prep for IIAB 6.7 RC3 on Feb 11:

15 [now 12] issues:
https://github.com/iiab/iiab-admin-console/issues

2 [now 0] PR's:
https://github.com/iiab/iiab-admin-console/pulls

**Comment by holta** [comment]
Central Challenge—we need to articulate to the "public" (novice implementers) how we can all improve [menu def] descriptions & logos together:

https://github.com/iiab/iiab/issues/1002#issuecomment-462183401

**Comment by holta** [comment]
Crucially, http://FAQ.IIAB.IO Number 14 (http://wiki.laptop.org/go/IIAB/FAQ#How_do_I_customize_my_server.27s_home_page.3F) [since renamed to [http://wiki.laptop.org/go/IIAB/FAQ#How_do_I_customize_my_Internet-in-a-Box_home_page.3F](http://wiki.laptop.org/go/IIAB/FAQ#How_do_I_customize_my_Internet-in-a-Box_home_page.3F) and renumbered to Number 15] needs to be rewritten.

I'll start work on that today, so that IIAB 6.7 can be substantially more understandable to "activist teachers" and the global public eagerly wanting to give this a try, customizing their own Internet-in-a-Box to the needs of their own community.

Future: editing of Content Pack (menuItemDef) descriptions & logos might be possible from the browser itself as part of IIAB 7.0, per @tim-moody's ongoing R&D: https://github.com/iiab/iiab/issues/1002#issuecomment-462183401
