### ISSUE TITLE
Remove stale branches

### ISSUE THREAD

**Issue by m-anish** [iiab/iiab#1417]
There seem to be a few stale branches in the upstream repo iiab/iiab. Should we take a call at removing them sometime?

**Comment by holta** [comment]
I'll remove all these stale branches...

https://github.com/iiab/iiab/branches

Preserving the release branches...

Unless there are objections in coming hours?

**Comment by holta** [comment]
Done:

Most all branches have been removed from https://github.com/iiab/iiab/branches
