### ISSUE TITLE
Rename stuff from xsce to iiab

### ISSUE THREAD

**Issue by m-anish** [iiab/iiab#1419]
Lots of places in the iiab repo contain the phrase [xsce](https://github.com/iiab/iiab/search?q=xsce&unscoped_q=xsce). Should we try to address that sometime?

**Comment by holta** [comment]
@m-anish can you paste in a few examples that need fixing?

Or post a PR?

**Comment by m-anish** [comment]
That's easy... 

https://github.com/iiab/iiab/search?q=xsce&unscoped_q=xsce

Don't have bandwidth this week for a PR, but can look into it. Move it to 7.0 perhaps?

**Comment by holta** [comment]
@m-anish if you don't want to be the owner, just LMK :)

**Comment by holta** [comment]
@m-anish good enough for now, can we close this as a result of your PR #2106?
