### ISSUE TITLE
iiab-make-kiwix-lib generates menu item def even though already exists

### ISSUE THREAD

**Issue by tim-moody** [iiab/iiab#1422]
download wikipedia_as_all_novid from adm cons

as-wikipedia_as_all_novid.json gets generated even though already exists and overwrites original

**Comment by holta** [comment]
@tim-moody is this resolved?

(Or still an issue?)

**Comment by tim-moody** [comment]
no idea

**Comment by holta** [comment]
@tim-moody wrote:
> has anyone observed this, https://github.com/iiab/iiab/issues/1422? I don't think it is still true.

I wrote:
> I haven't observed anything like that recently.

Let's close this ticket.

(Please re-open if there's any reason to!)
