### ISSUE TITLE
deb 9 and 10 have bind9 and isc-dhcp-server [change vars/<OS>.yml files to dnsmasq?]

### ISSUE THREAD

**Issue by tim-moody** [iiab/iiab#1436]
dns_service: bind9
dhcp_service: isc-dhcp-server
dns_user: bind

there may be others.

we should either control here (my preference) or with named_install in local vars, but not both

**Comment by holta** [comment]
@m-anish, @arky, @jvonau & @georgejhunt can you take a look?  @tim-moody seems to be suggesting we overhaul the 3+3 lines below to use dnsmasq instead?

https://github.com/iiab/iiab/blob/master/vars/debian-9.yml#L5-L7
https://github.com/iiab/iiab/blob/master/vars/debian-10.yml#L5-L7

Does this apply to Raspbian, Ubuntu and other distros too?  e.g. the same lines appear here:

https://github.com/iiab/iiab/blob/master/vars/raspbian-9.yml#L8-L10
https://github.com/iiab/iiab/blob/master/vars/ubuntu-18.yml#L5-L7
https://github.com/iiab/iiab/blob/master/vars/centos-7.yml#L5-L6

**Comment by jvonau** [comment]
Just provides a mapping of the service to deb package names just like apache, squid, mysql.

**Comment by tim-moody** [comment]
so the deb package name for dnsmasq is bind9?

**Comment by holta** [comment]
Should these variable names be improved (or a line just above clarifying their purpose?) so newcomers understand what these variables within each [/opt/iiab/iiab/vars/[OS].yml](https://github.com/iiab/iiab/tree/master/vars) really mean & what they are for &mdash; without us accidentally creating confusion?

**Comment by tim-moody** [comment]
let's just add a comment above that these names only apply if named_install and/or ?dhcpd_install is true

and not to dnsmasq

**Comment by holta** [comment]
> let's just add a comment above that these names only apply if named_install and/or ?dhcpd_install is true
> 
> and not to dnsmasq

@jvonau is the above accurate/complete?
