### ISSUE TITLE
[Debian 10] MongoDB not installable due to missing packages [for Sugarizer]

### ISSUE THREAD

**Issue by arky** [iiab/iiab#1437]
There is no package named 'mongodb' on Debian 10. More work needs to be done to enable mongodb service on Debian 10.

https://github.com/iiab/iiab/blob/c461767777ef6a69f8afcb9ea50114ce90d01df3/roles/mongodb/tasks/main.yml#L5

Refer: https://docs.mongodb.com/manual/tutorial/install-mongodb-on-debian/

**Comment by holta** [comment]
Ref: #1387 #1449

**Comment by deldesir** [comment]
mongodb package exists now on Debian 10 @arky.

**Comment by holta** [comment]
> mongodb package exists now on Debian 10 @arky.

Do you have a link?  What version of MongoDB is currently being offered?

**Comment by holta** [comment]
This appears to be MongoDB 3.4.18 for now, and might even work on RPi potentially ?

https://packages.debian.org/source/buster/mongodb
https://packages.debian.org/buster/mongodb
https://packages.debian.org/buster/mongodb-server

**Comment by holta** [comment]
> This appears to be MongoDB 3.4.18 for now, and might even work on RPi potentially ?
> 
> https://packages.debian.org/source/buster/mongodb
> https://packages.debian.org/buster/mongodb
> https://packages.debian.org/buster/mongodb-server

Once again MongoDB was removed from Debian 10 "Buster" — the links above no longer work.

Also note Red Hat announced last week that it is removing MongoDB from RHEL 8.

@llaske is there an idea how Sugarizer will navigate this?

**Comment by llaske** [comment]
@holta If MongoDB is no longer include as a Debian package, it's still possible to install it by hand.
On our side we're using a Docker container to avoid deployment issues.
See a schema of the architecture here: https://github.com/llaske/sugarizer-server/blob/dev/docs/architecture.md

**Comment by floydianslips** [comment]
Mongo is still not available on Debian 10. Are there any suggestions on how to move forward? It would appear it is not coming back.

**Comment by holta** [comment]
> Mongo is still not available on Debian 10. Are there any suggestions on how to move forward? It would appear it is not coming back.

Let's discuss during Thursday's call (http://minutes.iiab.io).

RHEL and therefore CentOS are also dropping MongoDB so we have a bigger dilemma growing here e.g. if Ubuntu drops it too?

(We may need a few months to understand what long-term strategy makes most sense?)

**Comment by floydianslips** [comment]
If Sugarizer doesn't require a document based db perhaps it can be made to
use the postgres DB that we already have.

**Comment by holta** [comment]
> If Sugarizer doesn't require a document based db perhaps it can be made to use the postgres DB that we already have.

@tim-moody found these links which suggest similar:

https://www.simform.com/mongodb-vs-mysql-databases/

https://www.theguardian.com/info/2018/nov/30/bye-bye-mongo-hello-postgres

> “But postgres isn’t a document store!” I hear you cry. Well, no, it isn’t, but it does have a JSONB column type, with support for indexes on fields within the JSON blob

**Comment by llaske** [comment]
Sugarizer require MongoDB because it store, explore and update JSON content coming from client. It will be a huge work to move to PostgresSQL.

**Comment by holta** [comment]
Seems we can defer decisionmaking here until Q3 2019, for IIAB 7.1

(I'm assuming Debian 10 will be released after IIAB 7.0...but then again I could be entirely wrong...which would force our hand here!)

**Comment by holta** [comment]
@llaske mentions that MongoDB might be compiled from source (e.g. on Debian 10 Buster and other distros?) using these instructions: https://github.com/iiab/iiab/issues/1449#issuecomment-493371944

**Comment by holta** [comment]
@tarunsinghal92 and @NikhilM98 do you have ideas/recommendations towards getting MongoDB running on Debian 10 &mdash; whose final release is this coming Saturday 2019-07-06 &mdash; so that Sugarizer can run on this mainstream Linux distro used by Internet-in-a-Box?

@llaske had earlier suggested avoiding PostgreSQL, and perhaps compiling MongoDB from source?

Or are there other approaches you recommend, possibly by installing .deb's from https://docs.mongodb.com/manual/tutorial/install-mongodb-on-debian/ or similar?

**Comment by holta** [comment]
CC'ing @georgejhunt who observed this same dilemma (https://github.com/iiab/iiab/issues/1814) that we're all officially facing, starting Saturday, when Debian 10 Buster is released:

https://www.phoronix.com/scan.php?page=news_item&px=Debian-Installer-Buster-RC3

**Comment by llaske** [comment]
@NikhilM98 tried to compile MongoDB from source but without success. Take too long time and resource. 
We've tried alternate method like [this one](https://tecadmin.net/install-mongodb-server-on-debian/) but without success. As mentioned in [comments](https://tecadmin.net/install-mongodb-server-on-debian/#comment-41521), it seems that MongoDB use a library deprecated in Debian 10 (libcurl3). So an update is required in MongoDB source code to support Debian 10.
I think we've no choice to wait for an official MongoDB for Debian 10 package which should be available here soon: https://docs.mongodb.com/manual/tutorial/install-mongodb-on-debian/
In the mean time the only possibility to host Sugarizer on Debian 10 is to use it [from a Docker container](https://github.com/llaske/sugarizer-server/blob/dev/docs/install.md#run-sugarizer-using-docker) or using the [no server mode](https://github.com/llaske/sugarizer/issues/356).

**Comment by holta** [comment]
> @NikhilM98 tried [several ways]

Profound Thanks to @NikhilM98 & @llaske who's "paying his salary" ;-)

Please keep us updated if progress is hopefully possible later this summer !

**Comment by holta** [comment]
Am deferring this tough issue to the IIAB 7.1 Milestone, so we can get [IIAB 7.0](https://github.com/iiab/iiab/wiki/IIAB-7.0-Release-Notes) out the door i.e. released in coming days hopefully!

Ref PRs #1850 #1852

**Comment by jvonau** [comment]
close

**Comment by holta** [comment]
This appears no longer true.

Due to recent work of @jvonau, see: https://github.com/iiab/iiab/tree/master/roles/mongodb/tasks arising from PRs #2493 #2494 #2495 #2499 #2501 etc.

However it appears True Debian[*] on aarch64 (64-bit ARM) is still out of reach.

[*] where "True Debian" = Debian that is not RaspiOS-pretending-to-be-Debian.

**Comment by jvonau** [comment]
Only because there was no volunteer who came forward to test Debian-10 on the arm64 platform and said that this works. If somebody using that combo wants to test feel free to # out the test. We can have a flag to turn the test on and off easily, or just remove the test and hope for the best.
