### ISSUE TITLE
Add http://box/nodered (and possibly also http://box/sugar ?)

### ISSUE THREAD

**Issue by holta** [iiab/iiab#1456]
@m-anish if you can add http://nodered (if not others) that'd be great!

Context: teachers love these rapid-access short URL's so kids don't get distracted by http://box and go immediately to the lesson material.

Ref: #923 "Failing/Short URL's—parent tkt to consolidate diverse issues"

**Comment by tim-moody** [comment]
minetest is not a web app, so there is no point in having box/minetest. a browser visiting it will get nothing

**Comment by holta** [comment]
@m-anish & all decided not to bother with http://box/sugar during our community/team call today (http://minutes.iiab.io) as that might get complicated, and http://box/sugarizer is enough.
