### ISSUE TITLE
Test IIAB 6.7 on Ubuntu 18.04.2 ETA Thur Feb 14

### ISSUE THREAD

**Issue by holta** [iiab/iiab#1459]
Something to do after [IIAB 6.7](https://github.com/iiab/iiab/wiki/IIAB-6.7-Release-Notes) is released?

e.g. if we decide to release IIAB 6.7 before Ubuntu 18.04.2's ISO images appear, that's fine with me:

https://discourse.ubuntu.com/t/ubuntu-18-04-2-testing-delayed-until-feb-14th/9704

**Comment by m-anish** [comment]
FWIW, 18.04.2 is out!

Also, for those testing via VM, the latest ubuntu/bionic64 vagrant image is also 18.04.2

**Comment by m-anish** [comment]
The BIG sized install went to completion twice on 18.04.2 and the server seems good in the basic tests I was able to do. 

So, in a nutshell, it works!
