### ISSUE TITLE
Open 5060, 5160:5161 and 10000:20000 so that asterisk can talk over SIP on WAN

### ISSUE THREAD

**Issue by m-anish** [iiab/iiab#1474]
* Asterisk needs ports 5060, 5160:5161 and 10000:20000 to operate. 
* These are open by default on LAN side
* They need to be open on the WAN side

- [x] Create a PR for this -> #1478 
- [x] Fix [documentation](https://github.com/iiab/iiab/wiki/IIAB-Networking#list-of-open-ports--services)
- [x] Ensure iiab_gen_iptables is as per #1478

**Comment by holta** [comment]
Resolved by @m-anish's PR #1478
