### ISSUE TITLE
Change js-menu to use /nodered instead of port

### ISSUE THREAD

**Issue by holta** [iiab/iiab#1502]
@georgejhunt @tim-moody can you help here today?

Requested by @m-anish due to Apache change he made.

**Comment by holta** [comment]
CORRECTION: the URL should be http://box/nodered

**Comment by m-anish** [comment]
So the essential change I am looking for is a shift from `:1880` to `/nodered` in the menudefinition.

Full disclosure
* `:1880` won't work
* `:1880/nodered` works
* `/nodered` works, and we want this

**Comment by tim-moody** [comment]
what does this have to do with the admin console?
I guess you mean the js-menu part.

**Comment by tim-moody** [comment]
since nodered_web_path is only in the role's default vars it is not visible to js-menu

**Comment by holta** [comment]
Can this be closed now as a result of https://github.com/iiab/iiab-admin-console/pull/149 ?

**Comment by m-anish** [comment]
@tim-moody would it help if `nodered_web_path: nodered` was in default_vars?

**Comment by m-anish** [comment]
I can confirm that this works as expected. Nodered menuitem on homepage links to `/nodered`

**Comment by holta** [comment]
> @tim-moody would it help if `nodered_web_path: nodered` was in default_vars?

Happening in PRs #1508 #1509
