### ISSUE TITLE
"Captive Portal doesn't work if Ethernet cable removed" [TK Kang report]

### ISSUE THREAD

**Issue by holta** [iiab/iiab#1504]
Reported by TK Kang 

Please work with him by email to solve this, those who can!

**Comment by holta** [comment]
Please help us get this right:

> "Caution: this prototype functionality might not work at all if an Ethernet cable is not simultaneously in use."  https://github.com/iiab/iiab/wiki/IIAB-6.7-Release-Notes#known-issues

Which also cautions:

> "[Captive Portal](http://wiki.laptop.org/go/IIAB/FAQ#Captive_Portal_Administration:_What_tips_.26_tricks_exist.3F) currently doesn't work if IIAB is installed on OS's other than Raspbian."  #1366

**Comment by holta** [comment]
@georgejhunt is this confirmed & also resolved, as a result of PR #1510?

**Comment by holta** [comment]
@tim-moody ran some tests after @georgejhunt's PR #1510 fix:
- Android 8 & Windows 10 worked UNTIL REBOOT
  - Captive Portal continues to work if you yank out Ethernet cord, so long as you don't reboot!
  - BUT Captive Portal does NOT work if you boot w/o Ethernet :-(
- Curiously this behavior is just like Nodogsplash
- SOMETHING needs an upstream connection it appears...Tim wonders if IPv6 might be the underlying cause?

@georgejhunt is also helping a lot testing here...

**Comment by tim-moody** [comment]
I would leave all related issues open until all problems are resolved.

**Comment by holta** [comment]
@georgejhunt do you believe TK's Ethernet issue is possibly now solved as a result of PR #1518 ?

**Comment by georgejhunt** [comment]
No I do not think so. I was unable to do a before, after change that went
from no work, to work, on android.
I expect that whatever problems TK was having, will persist

**Comment by holta** [comment]
@georgejhunt cannot reproduce this: can someone talk to TK to verify this is still an issue?

**Comment by holta** [comment]
@georgejhunt did testing alongside PR #2070 and believes this can 
now be closed.

(But please re-open as nec!)
