### ISSUE TITLE
Admin Console's "Content Menus" tab doesn't auto-load menus, showing a popup error

### ISSUE THREAD

**Issue by holta** [iiab/iiab#1513]
Popup error is "Unable to Load Menu. Waiting for All Menu Item Definitions to Load. Please try again." when I login to Admin Console and/or reload http://box/admin then click on the "Content Menus" tab, on an Ubuntu Server 18.04 VM installed Feb 16th.

@tim-moody took a look: FYI this might take a while to fix.

Question: does this presumably apply to RPi too?

**Comment by tim-moody** [comment]
applies to all platforms. it is an async error.

**Comment by holta** [comment]
@tim-moody fixed this in https://github.com/iiab/iiab-admin-console/pull/153
