### ISSUE TITLE
Outstanding IIAB issues (network & Node-RED) on Ubuntu Server 19.04 [released 2019-04-18]

### ISSUE THREAD

**Issue by holta** [iiab/iiab#1586]
- [x] @jvonau @floydianslips "A start job is running for Wait for Network to be Configured" holds up boot (for more than 2 min) every time, on BIG-sized IIAB install on Ubuntu Server 19.04 Beta, in a VM.

  Likely affects MIN-sized & MEDIUM-sized too?

  What are the best ways to diagnose this?

- [x] @m-anish "systemctl start nodered" fails every time on Ubuntu 19.04 Beta:

  > root@box:~# systemctl status nodered
● nodered.service - Node-RED
Loaded: loaded (/etc/systemd/system/nodered.service; enabled; vendor preset: enabled)
Active: failed (Result: exit-code) since Fri 2019-03-29 00:49:53 PDT; 29min ago
Process: 1986 ExecStart=/usr/bin/node-red-pi -v (code=exited, status=203/EXEC)
Main PID: 1986 (code=exited, status=203/EXEC)
  >
  > Mar 29 00:49:53 box.lan systemd[1]: nodered.service: Service RestartSec=100ms expired, scheduling restart.
Mar 29 00:49:53 box.lan systemd[1]: nodered.service: Scheduled restart job, restart counter is at 5.
Mar 29 00:49:53 box.lan systemd[1]: Stopped Node-RED.
Mar 29 00:49:53 box.lan systemd[1]: nodered.service: Start request repeated too quickly.
Mar 29 00:49:53 box.lan systemd[1]: nodered.service: Failed with result 'exit-code'.
Mar 29 00:49:53 box.lan systemd[1]: Failed to start Node-RED.

- [x] Verify that nodejs & npm hopefully install cleanly on their own as part BIG-sized IIAB install on Ubuntu 19.04 upon it's final release 2019-04-18.  Until then, this manual workaround is (likely) necessary, e.g. during early April 2019: https://github.com/iiab/iiab/blob/master/roles/nodejs/tasks/main.yml#L74-L76

- [ ] MySQL database password-changing failure during fresh install of IIAB on Ubuntu 19.04, when using `sudo` to install IIAB, as per the official http://download.iiab.io instructions: #1714

Refs: #1387 #1500 #1577 #1580 PR #1585 #1714

**Comment by m-anish** [comment]
Difficult to spend any cognitive energy on this. Check nodesource's readme where they themselves say they do not support 19.04. Its not even out yet! 

https://github.com/nodesource/distributions

Please test this "bug" maybe a month after 19.04 is out, and nodesource officially supports this.

**Comment by holta** [comment]
Disco Dingo (Ubuntu 19.04) Final Freeze was a couple hours ago.

Final release expected in a week from today (April 18).

**Comment by holta** [comment]
Ubuntu 19.04 was released earlier today:
https://wiki.ubuntu.com/DiscoDingo/ReleaseNotes
http://releases.ubuntu.com/19.04/

**Comment by holta** [comment]
Tagging @deldesir & @floydianslips just in case either has time to test IIAB 7.0/master (http://d.iiab.io) on the newly released [Ubuntu 19.04](http://releases.ubuntu.com/19.04/) ?

**Comment by holta** [comment]
@floydianslips will test http://d.iiab.io on Ubuntu Server 19.04

(We're looking for someone else to test on Ubuntu Desktop 19.04 if poss!)

**Comment by holta** [comment]
@floydianslips installed BIG-sized http://d.iiab.io onto Ubuntu Server 19.04 and it appears to have worked flawlessly...

**Comment by holta** [comment]
This ticket's issues (appear) resolved...but do re-open as nec.

**Comment by holta** [comment]
@floydianslips clarified that the last remaining issue with BIG-sized http://d.iiab.io on Ubuntu Server 19.04 persists...the issue is:

> "A start job is running for Wait for Network to be Configured" holds up boot (for more than 2 min) every time, on BIG-sized IIAB install on Ubuntu Server 19.04 Beta, in a VM.
>
> Likely affects MIN-sized & MEDIUM-sized too?
>
> What are the best ways to diagnose this?

**Comment by floydianslips** [comment]
Adding optional: true to /etc/netplan/50-cloud-init.yaml seems to solve the reboot issue. I don't know if it causes any issues down the chain but it reboots quickly and renders IIAB menu. 

network:
    ethernets:
        enp0s3: 
            dhcp: true
            _optional: true_
        version: 2

**Comment by holta** [comment]
> Adding `optional: true` to /etc/netplan/50-cloud-init.yaml seems to solve the reboot issue. I don't know if it causes any issues down the chain

@georgejhunt @jvonau should this be wrapped within an Ansible condition?  If so, what condition (e.g. is_ubuntu_19 or similar) is appropriate?  And where's the best place for this code within roles/network if so?

**Comment by floydianslips** [comment]
The `optional: true` allows the boot process to continue and then it brings up the network interface when it is ready. I have only tried this on a VM where the host is connected via ethernet.

**Comment by holta** [comment]
> The `optional: true` allows the boot process to continue and then it brings up the network interface when it is ready. I have only tried this on a VM where the host is connected via ethernet.

I'm hoping @georgejhunt or @jvonau can assist you in creating a PR...or just feel free to throw one together for their review??

**Comment by holta** [comment]
> The optional: true allows the boot process to continue and then it brings up the network interface when it is ready. I have only tried this on a VM where the host is connected via ethernet.

@floydianslips I've reconfirmed with a fresh install that MEDIUM-sized Ubuntu Server 19.04 pauses for more than 2min during boot, with message `A start job is running for Wait for Network to be Configured`

_(Please go ahead and create the above-mentioned PR !)_

**Comment by holta** [comment]
CLARIF: PR #1633 doesn't hurt, but incorporating that fix and then running `cd /opt/iiab/iiab` followed by `./iiab-network` ...is NOT sufficient to overcome Ubuntu Server 19.04's stalling for 2+ minutes during each boot:
```
A start job is running for Wait for Network to be Configured
```

**Comment by holta** [comment]
PR #1633 is now merged, per @jvonau's recommendation, bringing Ubuntu 19.04 in line with 18.04's behavior.  So...

FYI **prior** to running IIAB's roles/network, Ubuntu 19.04's /etc/netplan contains one single file **50-cloud-init.yaml** here:
```
# This file is generated from information provided by
# the datasource.  Changes to it will not persist across an instance.
# To disable cloud-init's network configuration capabilities, write a file
# /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg with the following:
# network: {config: disabled}
network:
    ethernets:
        enp0s3:
            dhcp4: true
    version: 2
```
FYI **after** running IIAB's roles/network, Ubuntu 19.04's /etc/netplan contains one single file **01-iiab-config.yaml** here:
```
network:
  version: 2
  renderer: networkd
  ethernets:
    enp0s3:
      dhcp4: yes
#
```

**Comment by holta** [comment]
Should @floydianslips perhaps consider adding the line he's found to work...
```
optional: true
```
...after `dhcp4: yes` in https://github.com/iiab/iiab/blob/master/roles/network/templates/network/netplan.j2#L18 ?  (i.e. this is the file that's used as a template by IIAB, to create /etc/netplan/01-iiab-config.yaml on all versions of Ubuntu 18.04 and higher)

**Comment by jvonau** [comment]
Attach iiab.ini, need to see which network backend was detected

**Comment by holta** [comment]
1) @jvonau called and helped figure out this telltale sign: `systemctl status systemd-networkd-wait-online` was failing (on this Ubuntu 19.04 VM) until I added `optional: true` within /etc/netplan/01-iiab-config.yaml &mdash; which got rid of the 2+ min delay on boot &mdash; and correspondingly allows the `systemd-networkd-wait-online` service to run properly.

> Attach iiab.ini, need to see which network backend was detected

2) Here are the 3 network sections from the Ubuntu 19.04 VM's /etc/iiab/iiab.ini
```
[detected_network]
has_ifcfg_gw = none
prior_gateway_(device_gw2) = "enp0s3"
dhcpcd_result =
network_manager_active = False
systemd_networkd_active = True
wan_in_interfaces = False
wireless_list_1(wifi1) = not found-1
wireless_list_2(wifi2) = not found-2
num_wifi_interfaces = 0
discovered_wireless_iface = none
discovered_wired_iface = none
num_lan_interfaces = 0
gui_static_wan = False
iiab_lan_iface = none
iiab_wan_iface = enp0s3
[computed_network]
iiab_wan_enabled = True
user_wan_iface = enp0s3
iiab_wan_iface = enp0s3
iiab_lan_enabled = True
user_lan_iface = auto
iiab_lan_iface = none
iiab_network_mode = Appliance
hostapd_enabled = True
host_ssid = u19-srv-may-2-iarchive
host_wifi_mode = g
host_channel = 6
[network]
dansguardian_enabled = False
squid_enabled = False
wondershaper_enabled = False
iiab_network_mode_applied = Appliance
dhcpd_enabled = False
dhcp_service2 = dnsmasq disabled
named_enabled = False
dnsmasq_enabled = False
no_net_restart = False
```
