### ISSUE TITLE
map_functions.js [possible duplicate osm-vector-maps code?]

### ISSUE THREAD

**Issue by tim-moody** [iiab/iiab#1642]
this file is in iiab and iiab-admin-console. are they the same?

**Comment by holta** [comment]
Other possible duplicate code instances:

https://github.com/iiab/iiab-admin-console/pull/197
https://github.com/iiab/iiab-admin-console/pull/198

**Comment by tim-moody** [comment]
not quite the same. one is with regards to a file and the others to functions within the file

**Comment by holta** [comment]
Conversation moved to #1647
