### ISSUE TITLE
Question: do map_functions.js and iiab-update.map belong in both iiab and iiab-admin-console? [OSM]

### ISSUE THREAD

**Issue by tim-moody** [iiab/iiab#1647]

**Comment by tim-moody** [comment]
also, if I change code in the iiab-admin-console version do I risk breaking something somewhere else?

**Comment by georgejhunt** [comment]
yes, I don't know how to do the splash page without  javascript, and I
don't want two start from scratch creating a new one when the one I have is
good enough.
I want there to be some function in IIAB without requiring the console.
Then there's the forwar dependency issue. If I rely on a javascript file in
the console, which is not yet installed, it's more complicated in ansible

**Comment by tim-moody** [comment]
This seems similar to the dilemma I faced between js-menu.js and js-menu-functions.js. In the end I found there was much less in common than I originally thought and I let them diverge.

**Comment by tim-moody** [comment]
In terms of dependencies, I agree that all roles in iiab should function without iiab-admin-console having been installed. But then they will function without js-menu, which means they don't need any of the assets that js-menu needs, like menu defs or zim_version_idx.json, etc. 

As far as I know the only thing required is library.xml. So iiab_update_menus, etc. and even the catalogs are only really needed by iiab-admin-console.

**Comment by tim-moody** [comment]
So far we have

https://github.com/iiab/iiab/blob/master/roles/osm-vector-maps/templates/iiab-update-map
https://github.com/iiab/iiab-admin-console/blob/master/roles/console/templates/iiab-update-map
https://github.com/iiab/iiab-admin-console/blob/master/roles/js-menu/templates/iiab-update-map.py

I'd like to settle on the 2nd of these as the location; not yet sure about which has the right the functionality.

**Comment by tim-moody** [comment]
found another one
https://github.com/iiab/iiab-admin-console/blob/master/roles/cmdsrv/templates/scripts/iiab_update_menus.py

**Comment by tim-moody** [comment]
Actually I think a 4th location (cmdsrv/scripts) is best. Any idea which is the right code between cmdsrv/templates/scripts/iiab_update_menus.py and js-menu/templates/iiab-update-map.py? Both are being installed and the js-menu version wins but has syntax errors.

**Comment by tim-moody** [comment]
looks like the one installed by iiab works and the others are not used.

**Comment by tim-moody** [comment]
done
