### ISSUE TITLE
Should vars/raspbian-9.yml have "is_debian_9: True" ?

### ISSUE THREAD

**Issue by tim-moody** [iiab/iiab#165]
should this have is_debian_9: True?

**Comment by holta** [comment]
@jvonau do you have an opinion?

Is Raspbian Stretch similar enough to deserve "is_debian_9: True" ?

**Comment by jvonau** [comment]
yes, that is PR #138

**Comment by holta** [comment]
@tim-moody @jvonau can we close this, or does it need discussion in Monday's community/team call?  (http://minutes.iiab.io)

**Comment by tim-moody** [comment]
not an enhancement. it is either a bug or not necessary, but it has not yet been implemented in master.
can't say if it is in a PR

**Comment by jvonau** [comment]
I've reworked #138 to address just the missing dependencies on raspbian-9 so I will now go with no not needed.

**Comment by holta** [comment]
@tim-moody we need a verdict here to move forward: can you help us reach a conclusion now?

**Comment by tim-moody** [comment]
yes. raspbian9 is debian 9
