### ISSUE TITLE
--non-interactive flag for "sudo iiab" installer

### ISSUE THREAD

**Issue by holta** [iiab/iiab#1656]
@floydianslips requests that IIAB installer https://github.com/iiab/iiab-factory/blob/master/iiab be enhanced with a `--non-interactive` command-line flag.  This is the bash script that is saved to `/usr/sbin/iiab` and invoked by the http://download.iiab.io (d.iiab.io) install process.

He's well aware that "sudo iiab" has interactive UX aspects that are critical to keep newbie installers on track &mdash; so they don't get completely stuck &mdash; and/or worse, badly shoot themselves in the foot.

These bits of interactive guidance have proved urgently necessary, greatly streamlining the IIAB install process over the past year, in an era when few people read instructions.

All that being true, @floydianslips is also very hopeful that the same script could be modified for IIAB "test automation" regimes and similar, where {apt updates, reboots, loud warnings, etc} are all _intentionally_ avoided.

This should be doable early in the IIAB 7.1 release cycle ideally?

_[A few design questions need to be sorted out too...e.g. I'm not sure it's wise to remove the automated checks for published passwords...so blocking in a few of these cases [where testers too shoot themselves in the foot!] is probably still advisable?]_

**Comment by jvonau** [comment]
Think I have something in the works without resorting to --non-interactive, what if the "read" waiting for $ans had a timeout value in iiab? Should that not just wait for input and proceed anyway after waiting? Given if you prepopulate local_vars.yml most of the questions are skipped and the same if the system was recently updated, what else can be streamlined?

**Comment by jvonau** [comment]
Think this --non-interactive is addressed in https://github.com/iiab/iiab-factory/pull/73, I was testing other code and didn't want to wait for a reboot because an update that just showed up... :)

**Comment by jvonau** [comment]
iiab/iiab-factory#134

**Comment by holta** [comment]
I had a short conversation with @floydianslips in person last week on why I don't agree with this proposal.

In short:

- Ppl who use a proper password won't be nagged and never have been.
- Ppl who continuously use a published password should pay a price (being nudged, to stop putting themselves and their community at risk).
- Ppl who truly want bad security can hit [Enter] today if they want the published password — a single keystroke is not worth crying over.
- Likewise implementers can and always have been able to pre-position `/etc/Iiab/local_vars.yml` — i.e. people who are organized don't have to face inappropriate reminders and never have.
- CTRL-C works to exit the 1-line-installer, and that's a really important skill for everyone to learn (in life) if they want to pre-position `/etc/Iiab/local_vars.yml` or fix their password etc, before continuing the 1-line-installer later — by running `sudo iiab` as we continuously remind them to do!

Refs:

- PR iiab/iiab-factory#156 "easy exit for editing or supplying custom local_vars.yml file"
- PR iiab/iiab-factory#158 "1-line-installer: facilitate testing w/ instant install of CLI-specified PR's e.g. 'sudo iiab 361 2607'"

**Comment by holta** [comment]
@floydianslips it took 2 years, but two new options are now available:

- For Clueful Testing People:
  `curl d.iiab.io/fast.txt | sudo bash`
  If interrupted, continue with... `sudo iiab -f` or `--fast`
- For DareDevs:
  `curl d.iiab.io/risky.txt | sudo bash`
  If interrupted, continue with... `sudo iiab -F` or `--risky`

Related:

- #1028
- PR #iiab/iiab-factory#182
