### ISSUE TITLE
Moodle 3.5.7 LTS released "2019-07-08" fails w/ PHP 7.3

### ISSUE THREAD

**Issue by holta** [iiab/iiab#1658]
ETA [2019-07-08](https://docs.moodle.org/dev/Releases#Moodle_3.5_.28LTS.29) but that might slip by a week or so...the date can often change, due to unforeseen circumstances...as Moodle folks try to warn us:
```
"All releases are preceded by a one week warning."
```

> Bad news is Moodle 3.5.x LTS is starting to show its age. Perhaps we should consider non-LTS Moodle 3.7.x when it's released in coming weeks — or Moodle 3.8.x when it's released by/around December 2019?
>
> Or possibly holding off til "Moodle 3.9.x LTS" in Q2 2020 ??
>
> ASIDE: people like @ericnitschke @kananigit @mikkokotila are starting to look at more nimble alternative LMS's even including WordPress, for more focused responses to very low-income community/school needs~

Ref: #1529

**Comment by holta** [comment]
Draft release notes for Moodle 3.5.7 should appear here in coming days, prior to its release:

https://docs.moodle.org/dev/Moodle_3.5.7_release_notes

**Comment by holta** [comment]
> Draft release notes for Moodle 3.5.7 should appear here in coming days, prior to its release:
> 
> https://docs.moodle.org/dev/Moodle_3.5.7_release_notes

Released/Confirmed!

Please all who can test Moodle 3.5.7 going forward.

**Comment by georgejhunt** [comment]
When I bring up the install page, (rpi,buster,big), I get at the top of the validation page:
PHP version 7.3 is not supported.
Reading moodle docs at: https://docs.moodle.org/dev/Moodle_3.5_release_notes

<quite> 
PHP version: minimum PHP 7.0.0 Note: minimum PHP version has increased since Moodle 3.3. PHP 7.1.x and 7.2.x are supported too. PHP 7.x could have some engine limitations.
</quote>
and 
https://docs.moodle.org/dev/Moodle_and_PHP7
"PHP 7.3 can be used with Moodle 3.6.4, Moodle 3.7 and later releases." ( buster installs php7.3)

**Comment by holta** [comment]
Thank @georgejhunt for catching this.

Can we consider dumping Moodle 3.5.x LTS in favor of 3.7.x ?

**Comment by georgejhunt** [comment]
Or perhaps just dropping support for moodle entirely.

Do you know of any moodle users?

**Comment by holta** [comment]
> Or perhaps just dropping support for moodle entirely. Do you know of any moodle users?

Many implementers try it.

Few follow through to use it long-term.

It seems that its main purpose is to rapidly trial the Moodle experience.

Interestingly this is the main purpose of BIG-sized IIAB too: to provide a live working environment to help educate implementers learning the ropes, establishing what kinds of LMS-like features their communities can rapidly learn & take advantage of...

**Comment by holta** [comment]
I've upgraded [IIAB 7.0 DRAFT Release Notes](https://github.com/iiab/iiab/wiki/IIAB-7.0-Release-Notes) to Moodle 3.7.1 which solves the problem on Raspbian Buster on RPi 4, and hopefully other OS's too.

**Comment by holta** [comment]
> > Do you know of any moodle users?
> 
> Many implementers try it.
> 
> Few follow through to use it long-term.

(One of) the reasons, is that we've never made it easy to adopt Moodle.

Specifically everyone that's tried to use Moodle with IIAB has struggled with its URL's.

As I believe IIAB's Moodle URL's (like http://box/moodle) all force a redirect to http://box.lan/moodle) which is not what everyone wants...

Not that there's a magical, easy fix.  But we have a chicken+egg situation here:

#10 Moodle erroneously redirects to schoolserver.lan/moodle (bad enough on LAN, worse on WAN)
#551 How to mitigate campuswide failures for Nextcloud, WordPress, Moodle, Elgg etc?
#941 http://10.0.0.x/moodle must be customized on installation

Whereas with WordPress we've cleanly documented several solutions, that people use regularly:

http://FAQ.IIAB.IO -> ITEM 33 `"WordPress & Moodle Administration: What tips & tricks exist?"` -> `"How do I set the WordPress URL (like http://box/wordpress) so it works for everyone?"`
