### ISSUE TITLE
current master fails on raspbian stretch: "networking.service failed"

### ISSUE THREAD

**Issue by tim-moody** [iiab/iiab#166]
TASK [network : reset the eth0 interface] **************************************
fatal: [127.0.0.1]: FAILED! => {"changed": true, "cmd": ["ifdown", "etho"], "delta": "0:00:00.012559", "end": "2017-08-26 19:32:19.178094", "failed": true, "rc": 1, "start": "2017-08-26 19:32:19.165535", "stderr": "ifdown: unknown interface etho", "stdout": "", "stdout_lines": [], "warnings": []}
...ignoring

TASK [network : restart the networking service] ********************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to restart service networking: Job for networking.service failed because the control process exited with error code.\nSee \"systemctl status networking.service\" and \"journalctl -xe\" for details.\n"}
        to retry, use: --limit @/opt/iiab/iiab/iiab.retry

N.B. cmd": ["ifdown", "etho"], unlikely was ever smoke tested.

**Comment by jvonau** [comment]
I caught this when I reviewed the [XSCE PR](https://github.com/XSCE/xsce/pull/913) but it was never corrected.

**Comment by jvonau** [comment]
typo fix #168

**Comment by tim-moody** [comment]
looking further, I don't think the etho typo is not the root cause as there is an  ignore_errors: True clause and this never gave a problem before. I notice that the error that killed it is the next one where networking failed to start with the message ifup: failed to bring up eth0 (no typo)

the rpi3 I'm running on does not have an eth0, but rather an enxb827eb6f70ac device as the gateway. I don't understand that, but it is recently purchased and/or stretch changed the naming.

**Comment by jvonau** [comment]
> the rpi3 I'm running on does not have an eth0, but rather an enxb827eb6f70ac device as the gateway. I don't understand that, but it is recently purchased and/or stretch changed the naming.

PR #156 should of forced that to be eth0, but a reboot is needed to take effect. stretch changed the naming, are you on the latest master?

**Comment by jvonau** [comment]
> looking further, I don't think the etho typo is not the root cause as there is an ignore_errors: True clause and this never gave a problem before. I notice that the error that killed it is the next one where networking failed to start with the message ifup: failed to bring up eth0 (no typo)

ifdown:  was suppose to release "eth0" but didn't so that blocks trying use that interface when bringing up the network in the next stanza. Edit: my bad, the hardcoding supplied to the template caused the ifup failure before the reboot for the name change back to eth0 could take effect.

**Comment by jvonau** [comment]
I'll see if I can softcode the variables in rpi_debian.yml so either way works.

**Comment by jvonau** [comment]
softcoding part of #169, see the comments there also. the change in rpi_debian.yml should be enough to deal with the new interface names.

**Comment by tim-moody** [comment]
Further experiments:

Rpi3 A                 with jessie have eth0  with stretch have eth0
Rpi3 B (new)       with jessie have eth0  with stretch have enxb827eb6f70ac, but after reboot have eth0

and if I rerun ansible it now succeeds ?!

**Comment by tim-moody** [comment]
this was without applying #168 or #169

**Comment by jvonau** [comment]
There is a need to reboot for this piece of code to work: 5fdbe61aab9c9a459f576cfb9a4b377c2ff6b376 with the need to reboot forced to take place sooner with PR #160

**Comment by jvonau** [comment]
Now test to see if these work:
iiab_lan_enabled: False
iiab_wan_enabled: False

**Comment by jvonau** [comment]
>  ifup: failed to bring up eth0 
> stretch have enxb827eb6f70ac, but after reboot have eth0
> and if I rerun ansible it now succeeds ?!

Yea, it now matches the hardcoding of eth0 in rpi_debian.yml which was not found when the device was known as enx....

**Comment by jvonau** [comment]
IIAB on Ubuntu email thread has the manual --> dhcp from #156 change now causing dhcpcd to fail in debian.yml. Think you can confirm that the generated /etc/network/interface template works as a gateway on rasbian-9 with 'dhcp' and it is shared. So lets not start 'dhcpcd' on ubuntu? or revert?

**Comment by jvonau** [comment]
IIAB on Ubuntu email thread:
> .  "not running dhcpcd because /etc/network/interfaces defines some interfaces that will use DHCP client"

https://paste.fedoraproject.org/paste/yTf~C23nrVtgW9HCunCyUw
2017-08-27 19:43:46,194 p=26505 u=root |  changed: [127.0.0.1]
2017-08-27 19:43:46,291 p=26505 u=root |  TASK [network : start up the dhcpcd service] ***********************************
2017-08-27 19:43:47,396 p=26505 u=root |  fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to start service dhcpcd: Job for dhcpcd.service failed because the control process exited with error code. See \"systemctl status dhcpcd.service\" and \"journalctl -xe\" for details.\n"}
2017-08-27 19:43:47,404 p=26505 u=root |  	to retry, use: --limit @/opt/iiab/iiab/iiab.retry

2017-08-27 19:43:47,407 p=26505 u=root |  PLAY RECAP *********************************************************************
2017-08-27 19:43:47,409 p=26505 u=root |  127.0.0.1                  : ok=197  changed=122  unreachable=0    failed=1   

The manual --> dhcp from #156 I believe is causing dhcpcd to fail in debian.yml, and stopping at that point. Think you can confirm that the generated /etc/network/interface template works as a gateway on raspbian-9 with 'dhcp' and it is shared, so disable dhcpcd with c06a8f8c9a5a85ece9fc7eb344be2cab13b495f1 on non-rpi?  or revert?

**Comment by jvonau** [comment]
I'm thinking ubuntu-16, debian-9, raspbian-9 more or less behave the same in respect to how the network can be configured, based on the reaction of the systems to dhcp in the currently supplied interfaces file and would be the preferred method. I'm thinking raspbian-8 needing the manual method is the exception, with that note there is a wip branch as part of #171.

**Comment by tim-moody** [comment]
perhaps we should abandon jessie.

**Comment by jvonau** [comment]
With a bit of work and testing I think #171 will be able to support all flavours in short order.

**Comment by holta** [comment]
I agree with Tim that supporting Jessie+derivatives is not worth it going forward.

(To avoid burning out our small group especially, we are not IBM!)

**Comment by jvonau** [comment]
related #7

**Comment by jvonau** [comment]
#178 replacing #168 #169

**Comment by jvonau** [comment]
[JK-dhcpcd.txt](https://github.com/iiab/iiab/files/1265977/JK-dhcpcd.txt) selected interesting results of systemctl list-unit-files from JK's rpi set with a static ip
one in /etc/systemd/system/ 
one in /lib/systemd/system/ 
dhcpcd5 
dhcpcd

**Comment by jvonau** [comment]
systemd's https://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames/
Nice list of [network managers](https://wiki.archlinux.org/index.php/Network_configuration#Change_device_name) and other useful info.
PR #178 updated to supply dhcpcd.conf

**Comment by jvonau** [comment]
PR #178 should be testable

**Comment by holta** [comment]
Ref #198 (rpi ex virgine: dhcpcd research)

**Comment by holta** [comment]
@tim-moody I do not see "networking.service failed" during ./runansible so am closing this issue (please re-open if helpful & nec!)
