### ISSUE TITLE
Freepbx-15 broken upstream

### ISSUE THREAD

**Issue by m-anish** [iiab/iiab#1685]
Opening a ticket here to keep track of this...

https://github.com/FreePBX/framework/pull/71#issuecomment-494390926

**Comment by m-anish** [comment]
PR #1686

**Comment by holta** [comment]
@m-anish is FreePBX-15 now fixed upstream?

Why was PR #1686 closed?

Can this tkt be closed too?

**Comment by holta** [comment]
No response from @m-anish as to why he closed PR #1686.

@m-anish please share the status of FreePBX as part of your IIAB playbook `pbx` when you can!
