### ISSUE TITLE
Static IP Address can be set manually, but Admin Console too confusing?

### ISSUE THREAD

**Issue by holta** [iiab/iiab#1702]
@mikerjensen reports:

> instructions from the FAQ for setting the static IP work, while the setting in the admin interface doesn't seem to

Background/details @ #1576

**Comment by holta** [comment]
Instructions posted to https://github.com/iiab/iiab/issues/1576#issuecomment-497007006 [ items (3A) and (3B) ] for @mikerjensen in case the Admin Console's user interface remains too confusing.

**Comment by jvonau** [comment]
#1744

**Comment by holta** [comment]
Still confusing to many people, but the manual instructions were refined extensively in 2019, so good enough for now:

http://faq.iiab.io -> Item 22. ("How do I set a static IP address?")
