### ISSUE TITLE
All 15 links are broken in OER2Go/RACHEL module menu-defs/en-afristory.html

### ISSUE THREAD

**Issue by holta** [iiab/iiab#1719]
Good news is there's at least one link that works (the title link) to showcase 5 stories: (in English)

http://iiab.me/modules/en-afristory/

Bad news is all 15 links displayed by its menuDef here are broken -- likely this file needs fixing or replacing:

https://github.com/iiab/iiab-admin-console/blob/master/roles/js-menu/files/menu-files/menu-defs/en-afristory.html

FYI these 15 broken links are quite prominent as a result of http://oer2go.org/viewmod/en-afristory being the topmost OER2Go/RACHEL module offered right on top of Admin Console's downloader, i.e. http://box.lan/admin > Install Content > Get OER2Go(RACHEL) Modules

**Comment by tim-moody** [comment]
don't know where the html file came from, but completely unrelated to this module.

**Comment by tim-moody** [comment]
should be

<ul>
<li><a href="<?php echo $dir ?>/firstwords.html">First Words</a></li>
<li><a href="<?php echo $dir ?>/firstsentences.html">First Sentences</a></li>
<li><a href="<?php echo $dir ?>/firstparagraphs.html">First Paragraphs</a></li>
<li><a href="<?php echo $dir ?>/longerparagraphs.html">Longer Paragraphs</a></li>
<li><a href="<?php echo $dir ?>/readaloud.html">Read Aloud</a></li>
</ul>

**Comment by holta** [comment]
Appears fixed by https://github.com/iiab/iiab-admin-console/pull/210
