### ISSUE TITLE
Logos for Wikiquote & Wikispecies appear broken at http://box; Wiktionary/Wikispecies show too few entries

### ISSUE THREAD

**Issue by holta** [iiab/iiab#1721]
(1) Likely the 2 missing/broken logo images have something to do with these menuDefs, which also need explanatory/clean descriptions:  (what end users will see on their schools IIAB home page, e.g. http://box )

https://github.com/iiab/iiab-admin-console/blob/master/roles/js-menu/files/menu-files/menu-defs/en-wikiquote_en_all.json
https://github.com/iiab/iiab-admin-console/blob/master/roles/js-menu/files/menu-files/menu-defs/en-wikispecies_en_all.json

(2) Wiktionary's incorrect count of total entries shows "5,309,521" whereas the ZIM itself shows "5,630,670" &mdash; the description etc should be suitably adjust here:

https://github.com/iiab/iiab-admin-console/blob/master/roles/js-menu/files/menu-files/menu-defs/en-wiktionary_en_all_novid.json

Likewise this one shows "4,772,815" and should be suitable adjusted:

https://github.com/iiab/iiab-admin-console/blob/master/roles/js-menu/files/menu-files/menu-defs/en-wiktionary_en_all.json

(3) Likewise Wikispecies menuDef incorrectly show "481,973" and should instead somewhere indicate "592,787+" :

https://github.com/iiab/iiab-admin-console/blob/master/roles/js-menu/files/menu-files/menu-defs/en-wikispecies_en_all.json

**Comment by tim-moody** [comment]
> (2) Wiktionary's incorrect count of total entries shows "5,309,521" whereas the ZIM itself shows "5,630,670" — the description etc should be suitably adjust here:

These have the wrong number because they were hard coded. Instead of changing the number use substitution variables or we can never catch up.

Also the convention is to put this in the Footnote.

**Comment by tim-moody** [comment]
Ncwikiquote2.png and 102px-Wikispecies_001.png are both in the current repo

**Comment by holta** [comment]
Largely solved by https://github.com/iiab/iiab-admin-console/pull/210

Further refined by https://github.com/iiab/iiab-admin-console/pull/212 that will hopefully be merged soon.
