### ISSUE TITLE
Use mysql native auth instead of unix socket auth

### ISSUE THREAD

**Issue by m-anish** [iiab/iiab#1729]
I'd like to implement mysql auth using the option #1 solution identified here, where mysql auth can happen remotely without invoking sudo. 

https://stackoverflow.com/questions/39281594/error-1698-28000-access-denied-for-user-rootlocalhost

This would allow installing apps over the web where mysql root credentials are required to create databases. 

This might be a security issue so need to be clear on it, AND that it wont break anything else. 

@holta @tim-moody @jvonau @georgejhunt

**Comment by holta** [comment]
@tim-moody can you help here, if possible killing 2 birds (#1714) with 1 stone?

**Comment by m-anish** [comment]
Okay, I am not in full favor of this as well. It might break something else. Let me think of alternate solutions.

**Comment by holta** [comment]
Background: @m-anish was trying to make [YouPHPTube](https://www.youphptube.com/) work, per #1546
