### ISSUE TITLE
iiab-hotspot-on fails if wlan0 in use

### ISSUE THREAD

**Issue by tim-moody** [iiab/iiab#1731]
If wlan0 is associated with an ssid (and has an ip address?) iiab-hotspot-on fails because it needs to disconnect before putting wlan0 in the bridge. Probably #439 is related.

**Comment by jvonau** [comment]
Didn't #1701 address this issue?

**Comment by holta** [comment]
@jvonau asks:

> So it's not enough to just ip link down?

@tim-moody wrote:

> I'll make a clean image and try again.

> But I just ran the new iiab-hotspot-on and couldn't ssh in

> after reboot it's fine, but if you can't get in you can't reboot

@jvonau asks:

> killall wpa_supplicant might be better than ip link

**Comment by tim-moody** [comment]
well now it works. I guess #1701 fixed it. closing for now
