### ISSUE TITLE
 IIAB-CMDSRV failed to initialize

### ISSUE THREAD

**Issue by mikerjensen** [iiab/iiab#1741]
on going to box.local/admin i get: (same problem after a reboot)

GET-WHLIST FAILED and reported IIAB-CMDSRV failed to initialize
clicking on the OK button, gives:
GET-VARS FAILED and reported IIAB-CMDSRV failed to initialize
clicking on the OK button, gives:
GET-ZIM-STAT FAILED and reported IIAB-CMDSRV failed to initialize
then:
GET-OER2GO-STAT FAILED and reported IIAB-CMDSRV failed to initialize
then:
GET-SPACE-AVAIL FAILED and reported IIAB-CMDSRV failed to initialize.. 
the page background has:
Starting Application
6/18/2019, 12:37:54 PM: initConfigVars found empty data
6/18/2019, 12:37:54 PM: procOneCatalog found empty data
6/18/2019, 12:37:54 PM: procOneCatalog found empty data
6/18/2019, 12:34:13 PM: GET-CONF FAILED and returned IIAB-CMDSRV failed to initialize
6/18/2019, 12:34:12 PM: GET-ANS FAILED and returned IIAB-CMDSRV failed to initialize
6/18/2019, 12:34:12 PM: GET-IIAB-INI FAILED and returned IIAB-CMDSRV failed to initialize
6/18/2019, 12:34:12 PM: GET-EXTDEV-INFO FAILED and returned IIAB-CMDSRV failed to initialize
6/18/2019, 12:34:12 PM: GET-SPACE-AVAIL FAILED and returned IIAB-CMDSRV failed to initialize
6/18/2019, 12:34:12 PM: GET-OER2GO-STAT FAILED and returned IIAB-CMDSRV failed to initialize
6/18/2019, 12:34:12 PM: GET-ZIM-STAT FAILED and returned IIAB-CMDSRV failed to initialize
6/18/2019, 12:34:12 PM: Successfully connected to Server
6/18/2019, 12:34:12 PM: GET-VARS FAILED and returned IIAB-CMDSRV failed to initialize
6/18/2019, 12:34:12 PM: GET-WHLIST FAILED and returned IIAB-CMDSRV failed to initialize
6/18/2019, 12:34:12 PM: Command GET-EXTDEV-INFO sent to server
6/18/2019, 12:34:12 PM: Command GET-SPACE-AVAIL sent to server
6/18/2019, 12:34:11 PM: Command GET-OER2GO-STAT sent to server
6/18/2019, 12:34:11 PM: Command GET-ZIM-STAT sent to server
6/18/2019, 12:34:11 PM: Command GET-IIAB-INI sent to server
6/18/2019, 12:34:11 PM: Command GET-CONF sent to server
6/18/2019, 12:34:11 PM: Command GET-ANS sent to server
6/18/2019, 12:34:11 PM: Command GET-VARS sent to server
6/18/2019, 12:34:11 PM: Command GET-WHLIST sent to server
6/18/2019, 12:34:11 PM: Checking Server Connection
6/18/2019, 12:34:11 PM: Starting init

**Comment by holta** [comment]
Thanks @mikerjensen:

Can you give a bit more context so @tim-moody can dig into this more?

Please post the URL's resulting from these commands:
```
pastebinit < /etc/iiab/iiab.env
pastebinit < /etc/iiab/iiab.ini
pastebinit < /etc/iiab/local_vars.yml
```
PS have you verified that your disk (microSD) is working well (and not full!) using `df -h` or similar?

**Comment by tim-moody** [comment]
When the cmdsrv fails to initialize, the app can't start, and it's links are not activated.

So the question is why does iiab-cmdsrv fail to initialize. Probably there is something unexpected in storage devices or networking devices.

@mikerjensen the easiest way to troubleshoot is to do the following after sshing into iiab:

sudo su -
systemctl stop iiab-cmdsrv
cd /opt/admin/cmdsrv
./iiab-cmdsrv

now go into the admin console and then go back to the ssh session. there should be an error on the screen.

alternatively, if you give me access I can do this.

**Comment by mikerjensen** [comment]
Thanks Tim, I tried that and immediately upon starting
      iiab-cmdsrv (before going to the admin console) i got the below
      text. Going to the admin console doesn't result in any further
      output in the ssh session...
    Mike
    
    root@box:/opt/admin/cmdsrv# ./iiab-cmdsrv
      Traceback (most recent call last):
        File "./iiab-cmdsrv", line 2770, in <module>
          main()
        File "./iiab-cmdsrv", line 169, in main
          init()
        File "./iiab-cmdsrv", line 2240, in init
          read_iiab_vars()
        File "./iiab-cmdsrv", line 2337, in read_iiab_vars
          local_vars = yaml.load(stream)
        File "/usr/lib/python2.7/dist-packages/yaml/__init__.py", line
      71, in load
          return loader.get_single_data()
        File "/usr/lib/python2.7/dist-packages/yaml/constructor.py",
      line 37, in get_single_data
          node = self.get_single_node()
        File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line
      36, in get_single_node
          document = self.compose_document()
        File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line
      55, in compose_document
          node = self.compose_node(None, None)
        File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line
      84, in compose_node
          node = self.compose_mapping_node(anchor)
        File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line
      127, in compose_mapping_node
          while not self.check_event(MappingEndEvent):
        File "/usr/lib/python2.7/dist-packages/yaml/parser.py", line 98,
      in check_event
          self.current_event = self.state()
        File "/usr/lib/python2.7/dist-packages/yaml/parser.py", line
      428, in parse_block_mapping_key
          if self.check_token(KeyToken):
        File "/usr/lib/python2.7/dist-packages/yaml/scanner.py", line
      116, in check_token
          self.fetch_more_tokens()
        File "/usr/lib/python2.7/dist-packages/yaml/scanner.py", line
      156, in fetch_more_tokens
          self.scan_to_next_token()
        File "/usr/lib/python2.7/dist-packages/yaml/scanner.py", line
      777, in scan_to_next_token
          self.forward()
        File "/usr/lib/python2.7/dist-packages/yaml/reader.py", line
      103, in forward
          self.update(length+1)
        File "/usr/lib/python2.7/dist-packages/yaml/reader.py", line
      170, in update
          exc.encoding, exc.reason)
      yaml.reader.ReaderError: 'utf8' codec can't decode byte #xc2:
      invalid continuation byte
        in "/etc/iiab/local_vars.yml", position 2220
      root@box:/opt/admin/cmdsrv# 
      
    
    On 18/06/19 14:56, Tim Moody wrote:
    
    
      
      When the cmdsrv fails to initialize, the app can't start, and
        it's links are not activated.
      So the question is why does iiab-cmdsrv fail to initialize.
        Probably there is something unexpected in storage devices or
        networking devices.
      @mikerjensen
        the easiest way to troubleshoot is to do the following after
        sshing into iiab:
      sudo su -
        systemctl stop iiab-cmdsrv
        cd /opt/admin/cmdsrv
        ./iiab-cmdsrv
      now go into the admin console and then go back to the ssh
        session. there should be an error on the screen.
      alternatively, if you give me access I can do this.
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or mute the thread.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/iiab/iiab/issues/1741?email_source=notifications\u0026email_token=ABOY56UEWOXXDXDNLN2Q4GTP3DSSHA5CNFSM4HY7DSCKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODX6WTJI#issuecomment-503146917",
"url": "https://github.com/iiab/iiab/issues/1741?email_source=notifications\u0026email_token=ABOY56UEWOXXDXDNLN2Q4GTP3DSSHA5CNFSM4HY7DSCKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODX6WTJI#issuecomment-503146917",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by mikerjensen** [comment]
Thanks, 
    
    urls below....when i try to do the last one it results in the
      below error message..
    disk is not full....not sure how i check its integrity without
      taking the SD card out?
    Filesystem      Size  Used Avail Use% Mounted on
      /dev/root        30G   11G   18G  38% /
      devtmpfs        459M     0  459M   0% /dev
      tmpfs           464M  8.0K  464M   1% /dev/shm
      tmpfs           464M   13M  451M   3% /run
      tmpfs           5.0M  4.0K  5.0M   1% /run/lock
      tmpfs           464M     0  464M   0% /sys/fs/cgroup
      /dev/mmcblk0p1   43M   23M   21M  53% /boot
      tmpfs            93M  8.0K   93M   1% /run/user/1000
      /dev/sda1       1.8T  1.7T   43G  98% /media/usb0
    
    
    http://paste.debian.net/1088320/
    http://paste.debian.net/1088321/
      
    
     pastebinit < /etc/iiab/local_vars.yml
      Traceback (most recent call last):
        File "/usr/bin/pastebinit", line 424, in <module>
          params = urlencode(params)
        File "/usr/lib/python3.5/urllib/parse.py", line 801, in
      urlencode
          v = quote_via(str(v), safe, encoding, errors)
        File "/usr/lib/python3.5/urllib/parse.py", line 729, in
      quote_plus
          string = quote(string, safe + space, encoding, errors)
        File "/usr/lib/python3.5/urllib/parse.py", line 707, in quote
          string = string.encode(encoding, errors)
      UnicodeEncodeError: 'utf-8' codec can't encode character '\udcc2'
      in position 2220: surrogates not allowed
      
    
    On 18/06/19 13:30, A Holt wrote:
    
    
      
      Thanks @mikerjensen:
      Can you give a bit more context so @tim-moody
        can dig into this more?
      Please post the URL's resulting from these commands:
      pastebinit < /etc/iiab/iiab.env
pastebinit < /etc/iiab/iiab.ini
pastebinit < /etc/iiab/local_vars.yml

      PS have you verified that your disk (microSD) is working well
        (and not full!) using df -h or similar?
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or mute the thread.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/iiab/iiab/issues/1741?email_source=notifications\u0026email_token=ABOY56RMGIC5XUAKLFOLOWDP3DIP3A5CNFSM4HY7DSCKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODX6G66I#issuecomment-503082873",
"url": "https://github.com/iiab/iiab/issues/1741?email_source=notifications\u0026email_token=ABOY56RMGIC5XUAKLFOLOWDP3DIP3A5CNFSM4HY7DSCKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODX6G66I#issuecomment-503082873",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by tim-moody** [comment]
looks like /etc/iiab/local_vars.yml has a unicode string that can't be decoded either by pastebinit or iiab-cmdsrv

**Comment by tim-moody** [comment]
the two pastebin links are iiab.env and iiab.ini. can you email me /etc/iiab/local_vars.yml

**Comment by tim-moody** [comment]
what if you cat /etc/iiab/local_vars.yml

**Comment by tim-moody** [comment]
or another question would be what changes have you made to local vars?

**Comment by tim-moody** [comment]
https://www.charbase.com/dcc2-unicode-invalid-character seems to be the offending character.

**Comment by mikerjensen** [comment]
No problem catting the file.... which is apparently: 
    
    file $_
      /etc/iiab/local_vars.yml: ISO-8859 text
    attached..
    i don't think i've ever touched this file manually...
    
    
    
    On 18/06/19 15:21, Tim Moody wrote:
    
    
      
      the two pastebin links are iiab.env and iiab.ini. can you email
        me /etc/iiab/local_vars.yml
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or mute the thread.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/iiab/iiab/issues/1741?email_source=notifications\u0026email_token=ABOY56WDH4MX5BDJ3RVRCQ3P3DVOLA5CNFSM4HY7DSCKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODX6ZHBY#issuecomment-503157639",
"url": "https://github.com/iiab/iiab/issues/1741?email_source=notifications\u0026email_token=ABOY56WDH4MX5BDJ3RVRCQ3P3DVOLA5CNFSM4HY7DSCKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODX6ZHBY#issuecomment-503157639",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by tim-moody** [comment]
I don't see the attachment

**Comment by tim-moody** [comment]
how did you install iiab, script from download.iiab.io? If you have not customized it we could just copy over one of the sample local vars.

**Comment by mikerjensen** [comment]
Strange, i just checked my sent folder - the file is there
      attached, but here it is again, and also pasted into the message
      body below.
    I installed IIAB according to the instructions here:
    https://github.com/internetarchive/dweb-mirror/blob/master/INSTALLATION-iiab-raspberry.md
    which reminds me i did edit the local_vars.yml file to enable
      internet archive..
    MIke
    
    
    
     
    # This is local_vars_min.yml -- copy it to /etc/iiab/local_vars.yml then...
# modify variables below, to override /opt/iiab/iiab/vars/default_vars.yml
wan_ip: 192.168.1.218
wan_netmask: 255.255.255.0
wan_gateway: 192.168.1.1
wan_nameserver: 8.8.8.8


# PLZ READ http://wiki.laptop.org/go/IIAB/local_vars.yml AND http://FAQ.IIAB.IO
# Orig Idea: branch github.com/xsce/xsce-local for your deployment/community


# Ansible's default timeout for "get_url:" downloads (10 seconds) often fails
download_timeout: 200

# Languages (for Apache)
default_language: en
language_priority: en es fr

# Set iiab_admin_user_install: False if you don't want iiab_admin_user & wheel
# group auto-created in roles/iiab-admin/tasks/main.yml (hence disabling sudo-
# checks/warnings of published passwds like pi/raspberry & iiab-admin/g0adm1n).
iiab_admin_user_install: True
# If iiab_admin_user_install: False, set iiab_admin_user (below) to an existing
# Linux user that has sudo access, for login to Admin Console http://box/admin
iiab_admin_user: iiab-admin
# Password hash to be used if Ansible creates the above user:
iiab_admin_pwd_hash: $6$xsce51$D.IrrEeLBYIuJkGDmi27pZUGOwPFp98qpl3hxMwWV4hXigFGmdSvy3s/j7tn6OnyTTLmlV7SsN0lCUAFzxSop.
# Obtain a password hash - NEW MORE SECURE WAY:
#    python3 -c 'import crypt; print(crypt.crypt("<plaintext>", crypt.mksalt(crypt.METHOD_SHA512)))'
# Obtain a password hash - OLD WAY:
#    python -c 'import crypt; print crypt.crypt("<plaintext>", "$6$<salt>")'

iiab_hostname: box
iiab_domain: lan

# Homepage: set to /home or /wordpress or /mediawiki or /wiki (for DokuWiki)
iiab_home_url: /home

# Raspbian requires Wi-Fi country since March 2018.  Please set it here:
host_country_code: US
host_ssid: "Internet in a Box"
host_wifi_mode: g
host_channel: 6
hostapd_secure: False
hostapd_password: changeme

# Enable "campus access" to ~10 common IIAB services like Kiwix (3000), KA Lite
# (8008) and Calibre (8010 or 8080) etc, on the WAN side of your IIAB server.
# Only 1 of the 6 lines below should be uncommented:
#
#ports_externally_visible: 0    # none
#ports_externally_visible: 1    # ssh only
#ports_externally_visible: 2    # ssh + http-or-https (for Admin Console's box.lan/admin too)
#�ports_externally_visible: 3     # ssh + http-or-https + common IIAB services
#ports_externally_visible: 4    # ssh + http-or-https + common IIAB services + Samba
ports_externally_visible: 5    # all but databases
#
# Or further customize your iptables firewall by editing:
# /opt/iiab/iiab/roles/network/templates/gateway/iiab-gen-iptables
# And then run: cd /opt/iiab/iiab; ./iiab-network

# Make this True if client machines should have access to WAN/Internet:
iiab_gateway_enabled: False

dhcpd_install: False
dhcpd_enabled: False

# named (BIND)
named_install: False
named_enabled: False

# dnsmasq - handles DHCP and DNS
dnsmasq_install: True
dnsmasq_enabled: True

# Enable AFTER installing IIAB!  Then run "cd /opt/iiab/iiab; ./iiab-network"
dns_jail_enabled: False

# Python-based Captive Portal, that @m-anish & @jvonau experimented with in
# July 2018 (https://github.com/iiab/iiab/pull/870) and that @georgejhunt
# extensively refined later in 2018 (PRs #1179, #1300, #1327).
captive_portal_install: False
captive_portal_enabled: False
# In a pinch, disable Captive Portal using instructions in http://FAQ.IIAB.IO

# Set to "False" if you want to revert to the older Dynamic Menuing system
# (prior to IIAB 6.7, this had used https://github.com/iiab/iiab-menu)
js_menu_install: True

# Unmaintained as of October 2017: https://github.com/iiab/iiab/pull/382
# wondershaper_install: False
# wondershaper_enabled: False


# 1-PREP

# roles/sshd & roles/iiab-admin run here
# SEE IIAB-ADMIN VARIABLES NEAR TOP OF THIS FILE:
# e.g. iiab_admin_user_install, iiab_admin_user, iiab_admin_pwd_hash

# SECURITY WARNING: See http://wiki.laptop.org/go/IIAB/Security
openvpn_install: True
openvpn_enabled: False
# Set /etc/iiab/openvpn_handle in advance here:
openvpn_handle: 
# The following seems necessary on CentOS:
# openvpn_cron_enabled: True


# 2-COMMON

# exFAT_enabled: True is auto-enabled in roles/2-common/tasks/packages.yml
# as set in 0-init/defaults/main.yml AND 0-init/tasks/main.yml

# /usr/libexec/iiab-startup.sh is much like autoexec.bat & /etc/rc.local
# It's put in place by 2-common/tasks/iiab-startup.yml at the end of Stage 2.


# 3-BASE-SERVER

# Make this False to disable http://box/common/services/power_off.php button:
apache_allow_sudo: True
# For schools that use WordPress and/or Moodle intensively, see iiab/iiab #1147
# WARNING: Enabling this might cause excess use of RAM/disk or other resources!
apache_high_php_limits: False
# SEE ALSO VARIABLES NEAR TOP OF THIS FILE: default_language, language_priority

# roles/mysql runs here (mandatory)


# 4-SERVER-OPTIONS

# DNS prep (dnsmasq, named &/or dhcpd) run here.  The full network stage runs
# after 9-LOCAL-ADDONS (or manually run "cd /opt/iiab/iiab; ./iiab-network")

squid_install: False
squid_enabled: False

# DansGuardian REQUIRES Squid (above) be installed & enabled
dansguardian_install: False
dansguardian_enabled: False

# PostgreSQL - auto-installed by Moodle and/or Pathagar - no need to touch!
postgresql_install: False
postgresql_enabled: False

# Unmaintained
# authserver_install: False
# authserver_enabled: False

# Common UNIX Printing System (CUPS)
cups_install: False
cups_enabled: False

# At Your Own Risk: take a security audit seriously before deploying this
samba_install: False
samba_enabled: False

# Show entire contents of USB sticks/drives (at http://box/usb)
iiab_usb_lib_show_all: True


# 5-XO-SERVICES

# Lesser-supported XO services need additional testing.  Please contact
# http://lists.laptop.org/pipermail/server-devel/ if you're able to help test.

# xo_services_install: False
# xo_services_enabled: False

# activity_server_install: False
# activity_server_enabled: False

# Please instead consider 'ejabberd' in Stage 6-GENERIC-APPS below
# ejabberd_xs_install: False
# ejabberd_xs_enabled: False

# Change calibre_port from 8080 to 8010 below, if you enable idmgr
# idmgr_install: False
# idmgr_enabled: False


# 6-GENERIC-APPS

dokuwiki_install: False
dokuwiki_enabled: False

mediawiki_install: False
mediawiki_enabled: False

ejabberd_install: False
ejabberd_enabled: False

elgg_install: False
elgg_enabled: False

# Gitea (lightweight self-hosted "GitHub") from https://gitea.io
gitea_install: False
gitea_enabled: False

# Lokole (email for rural communities) from https://ascoderu.ca
lokole_install: False
lokole_enabled: False

# MQTT pub-sub broker for IoT on Raspberry Pi etc
mosquitto_install: False
mosquitto_enabled: False

# Flow-based visual programming for wiring together IoT hardware devices etc
nodered_install: False
nodered_enabled: False

nextcloud_install: False
nextcloud_enabled: False

# A full-featured PBX (for rural telephony, etc) based on Asterisk and FreePBX.
# Works on Ubuntu 18.04, Debian 9. Experimental on Rasp/RPi 3. Uses Node.js 10.x
pbx_install: False
pbx_enabled: False
asterisk_chan_dongle: False

# If using WordPress intensively, set apache_high_php_limits in 3-BASE-SERVER
wordpress_install: False
wordpress_enabled: False


# 7-EDU-APPS

# KA Lite - SEE THE "Transmission" BITTORRENT DOWNLOADER FURTHER BELOW, TO INSTALL THOUSANDS OF VIDEOS
kalite_install: True
kalite_enabled: True
# Unused in 2018; but remains as placeholder for Fedora 18 legacy (XO laptops)
kalite_cron_enabled: True

kolibri_install: False
kolibri_enabled: False

kiwix_install: True
kiwix_enabled: True

# Warning: Moodle is a serious LMS, that takes a while to install
moodle_install: False
moodle_enabled: False
# If using Moodle intensively, set apache_high_php_limits in 3-BASE-SERVER

# Regional OSM vector maps use much less disk space than bitmap/raster versions
osm_vector_maps_install: True
osm_vector_maps_enabled: True

# Might stall MongoDB on Power Failure: github.com/xsce/xsce/issues/879
# Sugarizer 1.0.1+ strategies to solve? github.com/iiab/iiab/pull/957
sugarizer_install: False
sugarizer_enabled: False


# 8-MGMT-TOOLS

# BitTorrent downloader for large Content Packs etc
transmission_install: False
transmission_enabled: False
# A. UNCOMMENT LANGUAGE(S) TO DOWNLOAD KA Lite VIDEOS TO /library/transmission
#    using http://pantry.learningequality.org/downloads/ka-lite/0.17/content/
transmission_kalite_languages:
  #- english
  #- french
  #- hindi
  #- portugal-portuguese
  #- brazilian-portuguese
  #- spanish
  #- swahili
# B. Monitor BitTorrent downloads at http://box:9091 using Admin/changeme
#    until the download is confirmed complete (can take hours if not days!)
# C. Carefully move all videos/thumbnails into /library/ka-lite/content
#    (DO NOT OVERWRITE SUBFOLDERS assessment, locale, srt !)
# D. Log in to KA Lite at http://box:8008/updates/videos/ using Admin/changeme
#    then click "Scan content folder for videos" (can take many minutes!)
# E. READ "KA Lite Administration: What tips & tricks exist?" AT http://FAQ.IIAB.IO

awstats_install: True
awstats_enabled: True

monit_install: False
monit_enabled: False

munin_install: True
munin_enabled: True

# Handy for maintaining tables, but DANGEROUS if not locked down
phpmyadmin_install: False
phpmyadmin_enabled: False

vnstat_install: True
vnstat_enabled: True


# 9-LOCAL-ADDONS

# Calibre E-Book Library
# WARNING: CALIBRE INSTALLS GRAPHICAL LIBRARIES SIMILAR TO X WINDOWS & OPENGL
# ON (HEADLESS, SERVER, LITE) OS'S THAT DON'T ALREADY HAVE THESE INSTALLED.
calibre_install: False
calibre_enabled: False
# Change calibre_port to 8010 if you're using XO laptops needing above idmgr ?
calibre_port: 8080
# Change calibre to XYZ to add your own mnemonic URL like: http://box/XYZ
calibre_web_path: calibre  #NEEDS WORK: https://github.com/iiab/iiab/issues/529
# Avoid collisions with calibreweb_url: below!

# WARNING: Calibre-Web (below) depends on Calibre's own /usr/bin/ebook-convert
# program, so we recommend you also install Calibre (above!)

# Calibre-Web alternative to Calibre, offers a clean/modern UX
calibreweb_install: False
calibreweb_enabled: False
calibreweb_port: 8083    # PORT VARIABLE HAS NO EFFECT (as of January 2019)
# http://box/books works.  Add {box/libros, box/livres, box/livros, box/liv} etc?
calibreweb_url: /books
calibreweb_home: "{{ content_base }}/calibre-web"    # /library/calibre-web

# Internet Archive Decentralized Web - create your own offline version box:4244
# (or http://box/archive) arising from digital library https://dweb.archive.org
internetarchive_install: True
internetarchive_enabled: True

# Minetest is an open source clone of the Minecraft building blocks game
minetest_install: False
minetest_enabled: False


# CONSIDER THESE 2 NEW OPENSTREETMAP (OSM) APPROACHES INSTEAD, AS OF 2018:
# - http://download.iiab.io/content/OSM/vector-tiles/
# - http://oer2go.org/viewmod/en-worldmap-10
#
# DOWNLOAD EITHER OSM MANUALLY, OR BETTER YET TRY IIAB'S ADMIN CONSOLE:
#   http://box/admin -> Install Content -> Get OER2GO(RACHEL) Modules
#
# Unmaintained
# osm_install: False
# osm_enabled: False

# Unmaintained (better to install from http://teamviewer.com or prep scripts at http://download.iiab.io)
# teamviewer_install: False
# teamviewer_enabled: False

# Unmaintained
# docker_install: False
# docker_enabled: False

# Unmaintained
# schooltool_install: False
# schooltool_enabled: False

# Unmaintained
# debian_schooltool_install: False
# debian_schooltool_enabled: False

# Unmaintained (consider Calibre or Calibre-Web above?)
# pathagar_install: False
# pathagar_enabled: False

# Unmaintained
# sugar_stats_install: False
# sugar_stats_enabled: False

# Unmaintained
# xovis_install: False
# xovis_enabled: False
    
      pre { font-family: "Liberation Mono", monospace; font-size: 10pt; background: transparent none repeat scroll 0% 0%; }p { margin-bottom: 0.25cm; line-height: 115%; background: transparent none repeat scroll 0% 0%; }
    
    
    On 18/06/19 15:53, Tim Moody wrote:
    
    
      
      how did you install iiab, script from download.iiab.io? If you
        have not customized it we could just copy over one of the sample
        local vars.
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or mute the thread.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/iiab/iiab/issues/1741?email_source=notifications\u0026email_token=ABOY56SC7TMAU5AJ2M4LD5LP3DZGFA5CNFSM4HY7DSCKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODX64ZUI#issuecomment-503172305",
"url": "https://github.com/iiab/iiab/issues/1741?email_source=notifications\u0026email_token=ABOY56SC7TMAU5AJ2M4LD5LP3DZGFA5CNFSM4HY7DSCKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODX64ZUI#issuecomment-503172305",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by tim-moody** [comment]
bingo : #�ports_externally_visible: 3

**Comment by mikerjensen** [comment]
Phew! thanks! all working now...
    
    
    On 18/06/19 16:26, Tim Moody wrote:
    
    
      
      bingo : #�ports_externally_visible: 3
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or mute the thread.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/iiab/iiab/issues/1741?email_source=notifications\u0026email_token=ABOY56UWPOTFD3YXEU753ZLP3D5BDA5CNFSM4HY7DSCKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODX7AHZA#issuecomment-503186404",
"url": "https://github.com/iiab/iiab/issues/1741?email_source=notifications\u0026email_token=ABOY56UWPOTFD3YXEU753ZLP3D5BDA5CNFSM4HY7DSCKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODX7AHZA#issuecomment-503186404",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by holta** [comment]
> Phew! thanks! all working now... On 18/06/19 16:26, Tim Moody wrote: bingo : #�ports_externally_visible: 3

@mikerjensen how did that illegal char get in there...any idea what editor you were using etc...that might have caused it?

**Comment by tim-moody** [comment]
my bet is a del or destructive backspace key stroke that the terminal emulator took as a literal and recorded between the # and the ports
