### ISSUE TITLE
dnsmasq can take up to 100% cpu in some cases

### ISSUE THREAD

**Issue by m-anish** [iiab/iiab#1747]
I did a IIAB install with docker as part of the initial install (azuracast role), and that caused dnsmasq to not startup at system boot

output of brctl show is this
```
bridge name	bridge id		STP enabled	interfaces
br-dc6d86a97ce0		8000.0242053d1c42	no		veth56337fa
							veth75efaf8
							vethc29d6ab
							vethd306b78
							vethf09e42c
br0		8000.02e5a74cf78f	no		wlp58s0
docker0		8000.02421c6334fb	no	
```

Then when I start dnsmasq as `service dnsmasq start`, after a little while, it takes 100% cpu
```

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                            
  773 systemd+  20   0   71884   7448   5596 R  98.7  0.1   4:14.61 systemd-resolve                                                    
 4422 dnsmasq   20   0   51580   2692   2300 R  49.5  0.0   2:05.83 dnsmasq 
```

**Comment by m-anish** [comment]
Hardware: Intel NUC
OS: Ubuntu 18.04.2 LTS

**Comment by holta** [comment]
Thanks @m-anish.

It turns out [dnsmasq](http://www.thekelleys.org.uk/dnsmasq/doc.html) has more issues than we ever imagined.

Thanks everyone for your patience as @jvonau & others are helping to work thru these issues one at a time, e.g. dnsmasq sometimes doesn't start at all with static IP address situations like this one, that we're working on at this moment:

#1687, #1744, PR #1745

**Comment by m-anish** [comment]
While this gets resolved, can you suggest how I should go about installing IIAB in LAN-controller mode?

My current plan is:
* Install IIAB in gateway
* Install azuracast
* Remove USB-ethernet
* Rerun install OR rerun network setup

Thoughts?

**Comment by tim-moody** [comment]
I would skip the last step. For me there is no difference between Lan controller and Gateway without a WAN and it means the USB-ethernet can be reconnected at any time.

**Comment by holta** [comment]
@m-anish please run `/usr/bin/iiab-diagnostics` to post more detailed diagnostics when possible / where possible towards solving this in coming days?

As explained here:
https://github.com/iiab/iiab/blob/master/scripts/iiab-diagnostics.README.md

Per PR #1763

**Comment by m-anish** [comment]
Dnsmasq and systemd-resolved are taking 100% cpu again

/etc/resolv.conf
http://paste.ubuntu.com/p/PH4MSBG9CK/ 

/etc/systemd/resolved.conf
http://paste.ubuntu.com/p/NPWzVRR7mp/

**Comment by m-anish** [comment]
service systemd-resolved status
http://paste.ubuntu.com/p/yZZ5FPGp7K/

**Comment by m-anish** [comment]
systemd-resolve --status
http://paste.ubuntu.com/p/dwf9nJnYbw/

**Comment by m-anish** [comment]
systemd-resolve --status
http://paste.ubuntu.com/p/dwf9nJnYbw/

**Comment by m-anish** [comment]
this is the ``tcpdump -i any -n -p port 53`` output when the system's going crazy 

https://paste.ubuntu.com/p/QhNfQF5h6Y/

**Comment by jvonau** [comment]
Upstream reference https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1670959

**Comment by m-anish** [comment]
Checkout #1773 which fixes this!
