### ISSUE TITLE
Admin Console > Install Content > Manage Content freezes screen (Ubuntu & Debian)

### ISSUE THREAD

**Issue by holta** [iiab/iiab#1758]
The Admin Console GUI (in browser) fades (screen becomes somewhat dark but still visible) when you click `Install Content` > `Manage Content` &mdash; i.e. when trying to copy content to/from external disks etc.  This happens even after reboot on:
- Ubuntu 18.04 http://10.8.0.26/admin
- "Debian 10" http://10.8.0.22/admin

This doesn't happen on Raspbian.

(If this is hard to fix, perhaps the "Manage Content" button should just be grayed out so Ubuntu/Debian folks don't click on it?  Or perhaps a popup should say "this functionality is supported on Raspbian only for now" ?  Or if this turns out to be fixable across Ubuntu/Debian, great!)

**Comment by tim-moody** [comment]
I am looking at this on a ub 18 vm and not seeing this. I pulled the latest version and don't see it there either.

**Comment by tim-moody** [comment]
this is probably a javascript problem. use f12 to view console

**Comment by holta** [comment]
> this is probably a javascript problem. use f12 to view console

I'm away from computer most of today. Can you check these 2 URL's directly?

> Ubuntu 18.04 http://10.8.0.26/admin
> "Debian 10" http://10.8.0.22/admin
This doesn't happen on Raspbian.

**Comment by tim-moody** [comment]
likely a race condition on modal

**Comment by holta** [comment]
Solved by https://github.com/iiab/iiab-admin-console/pull/215 ?

**Comment by holta** [comment]
> Solved by [iiab/iiab-admin-console#215](https://github.com/iiab/iiab-admin-console/pull/215) ?

Is this likely resolved?

**Comment by holta** [comment]
Is this being solved by the similar-sounding ?

https://github.com/iiab/iiab-admin-console/pull/223 "remove fade that causes race condition on spinner modal"

**Comment by tim-moody** [comment]
thinks so, but testing appreciated. not totally happy with the solution, but seems to work.

**Comment by holta** [comment]
Thanks @tim-moody -- clicking http://box.lan/admin -> `Install Content` > `Manage Content` now works on both!
- Ubuntu 18.04 http://10.8.0.26/admin
- "Debian 10" http://10.8.0.22/admin
