### ISSUE TITLE
RPi Prob: "Copy script to restart dnsmasq whenever br0 comes up" (Destination directory /etc/networkd-dispatcher/routable.d does not exist)

### ISSUE THREAD

**Issue by holta** [iiab/iiab#1767]
Error is:

> TASK [network : Copy script to restart dnsmasq whenever br0 comes up] **********
fatal: [127.0.0.1]: FAILED! => {"changed": false, "checksum": "50de730947aa4cccc1586ff91d9f6bfc984b5127", "msg": "Destination directory /etc/networkd-dispatcher/routable.d does not exist"}
>
> 
PLAY RECAP *********************************************************************
127.0.0.1                  : ok=551  changed=143  unreachable=0    failed=1    skipped=241  rescued=0    ignored=0

Machine/OS (10.8.0.30) background details: http://paste.debian.net/1088961/

Ref: PR #1765 "Dnsmasq fixes"

**Comment by m-anish** [comment]
okay, there should be a check somewhere. ill take a look

**Comment by holta** [comment]
Solved by PR #1768 it appears, Thanks @m-anish !
