### ISSUE TITLE
links to old xs- (and xsce- ?) script names fail if the old script exists

### ISSUE THREAD

**Issue by tim-moody** [iiab/iiab#177]
/usr/bin/xs-handle
/usr/bin/xs-gen-iptables

**Comment by holta** [comment]
@tim-moody what links exist to these old scripts?

(Did a couple old references sneak by, that @georgejhunt & all of us missed?)

**Comment by holta** [comment]
@tim-moody I think I know what's your talking about -- this happened to me too during an upgrade earlier this summer.

The workaround being to delete those /usr/bin/xs-* scripts, when things indeed went haywire.

**Comment by jvonau** [comment]
fixed in #144

**Comment by georgejhunt** [comment]
fixed by pr144. Remove attempt to create a link, which might be an older file of same name.
