### ISSUE TITLE
San Jose map pack doesn't show additional detail (when zooming in) [OSM]

### ISSUE THREAD

**Issue by holta** [iiab/iiab#1783]
@georgejhunt, @avni observed this problem:

While the initial screen looks good (upon loading http://box/maps into your browser...) any subsequent zooming in does not fill in map data or satellite / photographic data.

See these two example machines:

- <strike>http://10.8.0.70/osm-vector-maps/en-osm-omt_san_jose_2017-07-03_v0.23/ 2GB RAM RPi 4 Raspbian Buster With Desktop</strike> (no longer online)

- http://10.8.0.74/osm-vector-maps/en-osm-omt_san_jose_2017-07-03_v0.23/ 2GB RAM RPi 4 Raspbian Buster Lite

Can you help us figure this out?

**Comment by holta** [comment]
@georgejhunt do you know if this problem will affect the other 10 Map Packs as well?

**Comment by avni** [comment]
I downloaded the Central America map and do not have the same problem! I can zoom in just fine on that map.

**Comment by avni** [comment]
See attached images showing the difference.

San Jose: 
<img width="180" alt="image" src="https://user-images.githubusercontent.com/47825/60397682-7cb36800-9b1d-11e9-8c1b-62dd781ec332.png">

Central America: 
<img width="1007" alt="Screen Shot 2019-06-30 at 10 00 46 AM" src="https://user-images.githubusercontent.com/47825/60397703-b4221480-9b1d-11e9-9b69-c7dc59b45d38.png">

**Comment by holta** [comment]
@georgejhunt if this is not possible to fix in the coming week, consider removing "San Jose" from the live catalog?

(As it does not serve much practical purpose, aside from testing.)

**Comment by georgejhunt** [comment]
I tried to remove san_jose from regions.json. I cannot do it via my private
ssh key directly. And I cannot copy it from my home directory, using the
password that worked on the older instance.

**Comment by holta** [comment]
> I tried to remove san_jose from regions.json.

I've fixed the group write bit, which was set wrong on the new server.

Please try again, thanks!

**Comment by georgejhunt** [comment]
I was able to update via shared key, but I'm not able to change my
password, or to copy a file from home to /var/www/d.iiab.io via sudo,
because what I remember and what it remembers,
 for my password, are different.

Can you just set it for me using root, and then I'll be able to manage from
here.

**Comment by holta** [comment]
My understanding is that San Jose's Map Pack has been removed, resolving this issue.

While a tiny Map Pack is really great for testing, and might once again be appropriate at some point in time in the future, removing this appears to be the most expeditious solution for now, thanks George for making that happen.

Separately, @georgejhunt & I are discussing fileserver security practices/choices around d.iiab.io

**Comment by holta** [comment]
Confirmed, works great during testing per https://github.com/iiab/iiab/wiki/IIAB-Maps

Thanks @avni & @georgejhunt for getting us closer to [IIAB 7.0](https://github.com/iiab/iiab/wiki/IIAB-7.0-Release-Notes) final release-
