### ISSUE TITLE
Feature Request: Admin Console: One alert when deleting multiple jobs

### ISSUE THREAD

**Issue by avni** [iiab/iiab#1788]
### Expected behavior and actual behavior.
If I select multiple jobs to cancel, I would like one alert that summarizes  the cancelation success/failure of each job. Currently a new alert popups up for each job.

### Steps to reproduce the problem.
Go to http://box.lan/admin/, Select "Utilities", Select "Display Job Status", Select multiple jobs, Click "Cancel Checked Jobs" button.

### Specifications like the version of the IIAB, operating system version, or hardware details.
Macbook Pro 2.7 Ghz 8 GB Ram
Mac OS Sierra 10.12.6
Chrome Version 74.0.3729.169
Server: RPI 4B Buster Lite
IIAB: 7.0 pre-release

**Comment by holta** [comment]
Related:

#1786 Feature Request: Admin Console: Grouping related jobs
#1787 Feature: Admin Console: Make it easier to delete multiple jobs

**Comment by avni** [comment]
Just tested on the latest IIAB 7.1 pre-release. This now works.
