### ISSUE TITLE
Bug: Admin Console: Estimated Space Required incorrect after first region is installed [OSM]

### ISSUE THREAD

**Issue by avni** [iiab/iiab#1791]
### Expected behavior and actual behavior.
Estimated space required does not update after first region is installed.

### Steps to reproduce the problem.
Go to http://box.lan/admin/, Select "Install Content", Select "Get Map Region", Select one region, Click "Install Selected region", Uncheck the region that was first selected, select another region, "Estimated space required" does not update

### Specifications like the version of the IIAB, operating system version, or hardware details.
Macbook Pro 2.7 Ghz 8 GB Ram
Mac OS Sierra 10.12.6
Chrome Version 74.0.3729.169
Server: RPI 4B Buster Lite
IIAB: 7.0 pre-release

**Comment by holta** [comment]
Somewhat related:

#1785 Bug: Admin Console: Selecting one vs multiple regions - checkboxes/radio buttons [OSM]
#1789 Bug: Admin Console: Region stays checked after installation [OSM]
#1793 ~= iiab/iiab-admin-console#229 Admin Console reports osm region as installed when it isn't

**Comment by tim-moody** [comment]
there is a bug in admin_console.js sumMapWip() that causes map space estimate to fail.

**Comment by holta** [comment]
@tim-moody summarizes this progress (during this week's http://minutes.iiab.io call) as 2 bugs:

- wrong variable name he just fixed
- OSM (maps) don't report size / how much space is required as other content types [or more specifically Admin Console's backend] do report to Admin Console

Conclusion: when new [OSM] maps appear later this year, Tim will get back to solving this properly (very complicated, but the short version is that the back-end reports these size estimates... ongoing installs / queue / etc need this!)

**Comment by holta** [comment]
> there is a bug in admin_console.js sumMapWip() that causes map space estimate to fail.

@tim-moody is this fixed now, do you know?

**Comment by tim-moody** [comment]
>Conclusion: when new [OSM] maps appear later this year, Tim will get back to solving this properly (very complicated, but the short version is that the back-end reports these size estimates... ongoing installs / queue / etc need this!)

No plans to address this until all changes to maps are complete. Users should download maps first, so that space has been occupied and will be correct for other content.

**Comment by holta** [comment]
@avni can you confirm this is closeable, with IIAB's new OSM Map Pack install process?

Outlined @ https://github.com/iiab/iiab/wiki/IIAB-Maps > "For 7.2 and later Maps, How do I Select and Install Tiles for my region?"

**Comment by avni** [comment]
This issue is not relevant anymore on http://192.168.0.172/osm-vector-maps/installer/ as the estimated space required text is no longer there (and does not need to be given the UI has moved to having a radio button, which limits the user to one selection).
