### ISSUE TITLE
Bug: Admin Console: Font selection in Manage Content Menus does not seem to be doing anything? 

### ISSUE THREAD

**Issue by avni** [iiab/iiab#1795]
### Expected behavior and actual behavior.
When selecting a new font from the "Manage Content Menus" admin function, I expect the font to change real-time. It does not. Not clear how to make the selection stick/have the desired effect.

### Steps to reproduce the problem.
Go to http://box.lan/admin/, Select "Content Menus", Go to "Select Desktop Header Font" dropdown, Select a new font. No fonts change.

### Specifications like the version of the IIAB, operating system version, or hardware details.
Macbook Pro 2.7 Ghz 8 GB Ram
Mac OS Sierra 10.12.6
Chrome Version 74.0.3729.169
Server: RPI 4B Buster Lite
IIAB: 7.0 pre-release

**Comment by holta** [comment]
Related:

#1794 "Feature Request: Admin Console: Modify select lists in Manage Content Menus to display font"

**Comment by tim-moody** [comment]
Took "Manage Content Menus" Menu Properties changed Select Desktop Header Font from finger paint to freckle face. saved the menu. reloaded the menu in browser. the font changed.

did the same for mobile. font changed

**Comment by avni** [comment]
Tested on Chrome and Safari in OS X and no change. Font family when I go into the inspector is: font-family: 'Open Sans', sans-serif; In safari I do see the failures that are showing in the screenshot 

<img width="1275" alt="Screen Shot 2019-06-30 at 6 32 30 PM" src="https://user-images.githubusercontent.com/47825/60402990-37b32400-9b65-11e9-9424-36b784509384.png">

**Comment by tim-moody** [comment]
![image](https://user-images.githubusercontent.com/5678731/60403550-c37c7e80-9b6c-11e9-9fab-b4817b6536d7.png)

**Comment by tim-moody** [comment]
works as designed. only header font is affected as the prompt says.
