### ISSUE TITLE
rpi stretch ssh remote access foiled by corrupted host keys

### ISSUE THREAD

**Issue by georgejhunt** [iiab/iiab#186]
Fixed by doing:
sudo rm /etc/ssh/ssh_host*
sudo dpkg-reconfigure openssh-server

Not sure this is just my image. Or we might need to put it temporarily in playbook

**Comment by holta** [comment]
So Crazy :)

Have not witnessed this on 4 Raspbian Stretch Lite installs, so far anyway!

**Comment by georgejhunt** [comment]
another sd, another duplication, no problems. The keys were all there. Same image download
