### ISSUE TITLE
Mounting USB sticks - doesnt always get to /media/pi

### ISSUE THREAD

**Issue by mitra42** [iiab/iiab#1875]
### Expected behavior and actual behavior.
Plug in exfat ( I believe) USB stick

### Steps to reproduce the problem.
it seems to get into /media/pi/MITRA64GB when inserted, but 
sometimes on rebooting it only appears in /media/usb0/MITRA64GB

### Specifications like the version of the IIAB, operating system version, or hardware details.
IIAB v7

**Comment by holta** [comment]
Does https://github.com/iiab/iiab/issues/1874#issuecomment-511503003 help?

**Comment by mitra42** [comment]
Yes - it helps - somewhere I got the idea that IIAB mounted drives in one place - on /media/pi (as a link to the /media/usb/* location. The funny thing is that this DOES happen when you insert a USB stick but not when its rebooted. I'll change my code to look in each of the /media/usb*/ locations.

**Comment by holta** [comment]
@mitra42 can I close this thumbdrive question?  (Or is there an ongoing/remaining issue?)

**Comment by mitra42** [comment]
I guess its only an ongoing issue if anyone is expecting to find USB's at /media/pi/xxx which is where for some reason I'd expected to find them on IIAB (I forget where I read that, or if I discovered it myself) and is only now true if the USB is inserted after restart and the PI isn't restarted. ... (I've discarded the test for disks at /media/pi/xxx now so its not an issue for me)

**Comment by holta** [comment]
Ok, good enough, thanks @mitra42 for explaining.
