### ISSUE TITLE
Nextcloud missing PHP modules "imagick" (on RPi, works on Ubuntu 18.04)

### ISSUE THREAD

**Issue by holta** [iiab/iiab#1943]
How does one add this PHP module (imagick) which appears on IIAB on Ubuntu 18.04 but not Raspbian?

The Nextcloud warning in http://box/nextcloud > Settings (top right, after clicking on circle) > Administration/Overview (halfway down left column) is:

> - This instance is missing some recommended PHP modules. For improved performance and better compatibility it is highly recommended to install them.
>   - **imagick**

**Comment by jvonau** [comment]
The [playbook](https://github.com/iiab/iiab/blob/master/roles/nextcloud/tasks/install.yml#L71-L91) didn't install the php support of imagick, just figure out the package name used on debian and add it.
