### ISSUE TITLE
IIAB's 1-line installer should *require* a recent OS e.g. (a recent version of) Raspberry Pi OS ?

### ISSUE THREAD

**Issue by holta** [iiab/iiab#1960]
Consider a school that recently installed IIAB onto a 2017 version of Raspbian from almost 2 years ago, and then asked for support again and again and again... :/

**Comment by holta** [comment]
During yesterday's IIAB weekly call (http://minutes.iiab.io) we discussed several ways to implement this:

- Check the timestamp on a file like `/etc/issue` and refuse to install if it's too old?
- Contents of `/etc/os-release` could also be checked but unclear exactly how to parse its contents (its VERSION field is used inconsistently across distros!)
- Easiest is probably to act on `/etc/debian_version` &mdash; and then explain (as nec) that IIAB no longer supports OS's based on versions of Debian < 10.x

   To that end, here's what `/etc/debian_version` shows in various OS's...
  - Raspbian Buster shows "10.1"
  - Debian 10.1 shows "10.1"
  - Debian 9.11 shows "9.11" **(likely we should disallow these going forward / soon!)**
  - Ubuntu 18.04 and 19.10 show "buster/sid"
  - Ubuntu 16.04 shows "stretch/sid" **(likely we should disallow these going forward / soon!)**

**Comment by jvonau** [comment]
first touch point is 'iiab' so this really should addressed in iiab-factory

**Comment by jvonau** [comment]
related #2501

**Comment by holta** [comment]
Related:
- #2497 "Concerning 1 line install on Raspberry pi 3b+ [kolibri.service failed to start due to Ansible 2.9.12; 'ansible_userspace_architecture' is undefined; WiFi flaky due to RaspiOS kernel 5.4.51-v7+ #1333 ?]"
- iiab/iiab-factory#133 "add kernel warning for RaspOS"

**Comment by jvonau** [comment]
implemented

**Comment by holta** [comment]
Good enough, yes!
