### ISSUE TITLE
Admin Console removes comments from local_vars.yml

### ISSUE THREAD

**Issue by holta** [iiab/iiab#1964]
This bug is not a blocker preventing the release of [IIAB 7.0](https://github.com/iiab/iiab/wiki/IIAB-7.0-Release-Notes), but as mentioned in PR #1962 it definitely should be fixed in coming weeks if at all possible.  Specifically: Admin Console has accidentally introduced a bug whereby things in [/etc/iiab/local_vars.yml](http://wiki.laptop.org/go/IIAB/FAQ#What_is_local_vars.yml_and_how_do_I_customize_it.3F) like...

```
# Unmaintained
# osm_install: False
# osm_enabled: False

# Unmaintained
# docker_install: False
# docker_enabled: False
```

Become...

```
# Unmaintained

# Unmaintained
```

(This happens after use of Admin Console, e.g. to enable/disable services.)

My personal opinion is: explanatory comments (especially '#' signs to the right side of variables, and other contextual/implementer comments) should be guaranteed to remain untouched and preserved in all circumstances.

Ref: #1952 https://github.com/iiab/iiab-admin-console/pull/256

**Comment by jvonau** [comment]
after running ICO to see the full extent of the difference try 
diff -u /opt/iiab/iiab/vars/local_vars_medium.yml /etc/iiab/local_vars.yml

**Comment by jvonau** [comment]
http://paste.debian.net/1105380/ of above diff

**Comment by holta** [comment]
> http://paste.debian.net/1105380/ of above diff

Above page disappears in 7 days.  I've reposted it here (disappears in 1 year) so we don't lose it:

https://paste.ubuntu.com/p/5pSMPGmBCf/

**Comment by holta** [comment]
My belief is that Admin Console should not modify any comments of any kind, ever, in /etc/iiab/local_vars.yml

For those who don't read diffs, here are just a few of the many comments (beginning with the '#' character) that Admin Console is currently deleting from local_vars.yml:

- all explanatory URL's appear to be deleted, presumably because they contain the character ':'
- all English sentences are deleted, apparently on lines where they happen to contain the character ':'
- explanatory documentation is deleted, when it (very intentionally) refers to actual example variable usage, e.g.

```
# kiwix_install: True is REQUIRED, if you install IIAB's Admin Console
```

**Where English sentences remain, they become incoherent when commented-out variables on nearby lines suddenly disappear.**

Separately: stale comments are accidentally being added back into local_vars.yml, in the place of the latest explanations that are silently disappearing.

Let's avoid all the above and similar problems.  For all these reasons, I believe we need to continue allowing implementers full artistic license and full control over their own comments, in their own file.

Rather than trying to programmatically change their human-generated explanations &mdash; which would perpetually mangle the intent and comments that people are very intentionally placing &mdash; as contextual and explanatory reminders of their own choosing.

**Comment by tim-moody** [comment]
None of the items you mention was put there by an implementer; all were put there by you. As far as I am aware, no implementer has ever added a comment. local_vars.yml is a configuration file. Put documentation in documentation. 

If you comment out kalite_enable: True, there is no way for Admin Console to set it to False without uncommmenting, or adding a line at the bottom, which was not desired I thought.

There is no reasonable way to distinguish between 

```
# xxx_install: True is a really good thing to do
and
# xxx_install: True
```

And the bottom line is that no variables in this configuration file have the wrong values as a result of this process, only comments that should not be there in the first place.

Comments in the configuration file create a huge maintenance problem in that they must be maintained in every variant of local vars, min, med, and big, not to mention medical, which doesn't even make the list. Further, most variables get copied from defaults to variants of local vars, so the user has trouble telling how each configuration differs and this is made even worse by an overwhelming set of comments.

Furthermore, install and enable variables should have two states, True or False. But allowing commented variables adds a third state, undefined, another unnecessary complication.

**Comment by holta** [comment]
> adding a line at the bottom, which was not desired I thought

That's precisely what should happen (variables should be added at the bottom of local_vars.yml, if any such variables are not yet defined, and need to be added programmatically).

The [/usr/bin/iiab-support](https://github.com/iiab/iiab/blob/master/iiab-support) command does exactly this, for exactly these kinds of reasons &mdash; preserving implementer/operator control over their own /etc/iiab/local_vars.yml file.

For 2 years people have been reading and benefitting from carefully crafted explanations while editing local_vars.yml, explaining their initial options on how to set up IIAB, that I've invested many hundreds of hours in, after consulting with dozens of others on how to explain these options in simple language.

Randomly removing these coaching/comments (those that happen to contain colons, censoring URLs, etc) defies reason; nobody will suggest this with a straight face.

Similarly sending comments into faraway documentation (removing essential context & helpfulness) is counterproductive and not a serious suggestion in the least.

In the end what implementers want and need is context & control as explanatory comments guide their initial IIAB configuration, including their own comments and those generated by volunteers / field implementers / whoever came before them, no matter who that happens to be in the past or future is irrelevant &mdash; the crux is that IIAB's sometimes painful complexity is becoming increasingly much more approachable and understandable every day due to explanations of this sort.

(Perhaps it goes without saying: but these critical explanatory setup comments are exactly the same kind of contextual options that can and increasingly should inform Admin Console selection/configuration interfaces, as whatever [re]configuration needs become increasingly proven and broadly popular, are the areas where a GUI becomes increasingly/evidently required...)

**Comment by holta** [comment]
Known regexp problem, as discussed by @tim-moody on today's IIAB call (http://minutes.iiab.io) that we're hoping to solve in coming months, even if worst case after [IIAB 7.1](https://github.com/iiab/iiab/milestone/6) is released.

**Comment by holta** [comment]
Change would happen herein:
https://github.com/iiab/iiab-admin-console/blob/master/roles/cmdsrv/files/iiab-cmdsrv3.py#L2669-L2814

And especially here in this "if commented out" section:
https://github.com/iiab/iiab-admin-console/blob/master/roles/cmdsrv/files/iiab-cmdsrv3.py#L2685-L2701

**Comment by tim-moody** [comment]
This should be combined with a planned change to the backend function such that a subset of local vars can be saved, for example only to enable a single service.

**Comment by tim-moody** [comment]
I have a rewrite with the following caveat. All comments are preserved as is. There is no attempt to find a commented out variable which has its value changed and uncomment it. The new value will simply be appended.

**Comment by tim-moody** [comment]
> My belief is that Admin Console should not modify any comments of any kind, ever, in /etc/iiab/local_vars.yml

if there is general agreement to this we can proceed.

**Comment by holta** [comment]
There is general agreement with @jvonau, @georgejhunt and @m-anish.

If you have a rewrite as mentioned [4-5 hours ago](https://github.com/iiab/iiab/issues/1964#issuecomment-617201168) that sounds great.

**Comment by holta** [comment]
See https://github.com/iiab/iiab-admin-console/pull/305 "functions to write local vars"

**Comment by holta** [comment]
> See [iiab/iiab-admin-console#305](https://github.com/iiab/iiab-admin-console/pull/305) "functions to write local vars"

Now merged: thanks @tim-moody & thanks all for testing Admin Console & [IIAB 7.1](https://github.com/iiab/iiab/wiki/IIAB-7.1-Release-Notes) pre-releases in general...in preparation for release hopefully very soon, ideally around 2020-05-01!

**Comment by holta** [comment]
Great news this appears to be solved according to https://github.com/iiab/iiab/pull/2368#issuecomment-620607502
