### ISSUE TITLE
Have some kind of watchdog for kiwix [beyond our current cron job?]

### ISSUE THREAD

**Issue by m-anish** [iiab/iiab#1997]
### Expected behavior and actual behavior.
Starting the kiwix service during boot can sometimes timeout when the system is otherwise under load. So it would be nice to have a watchdog (a simple cronjob that checks if kiwix is running, and start it if its not).

### Steps to reproduce the problem.
I full sized install on an old Celeron NUC can sometimes trigger this problem.

### Specifications like the version of the IIAB, operating system version, or hardware details.
IIAB-6.7

**Comment by tim-moody** [comment]
unit file has restart on crash. I'm surprised that that does not work.

**Comment by m-anish** [comment]
I can try producing a log, but this does definitely happen :)

**Comment by m-anish** [comment]
@holta Please assign this issue to me so I can keep a track of it.

**Comment by holta** [comment]
> @holta Please assign this issue to me so I can keep a track of it.

Thanks!  Hopefully the worst Kiwix problems are taken care of for us as #1993 resolves itself in coming days (with new RPi kernel etc).

**Comment by m-anish** [comment]
I think lets close this for now. Can always reopen if the problem reappears.
