### ISSUE TITLE
Nextcloud stores its data in /opt/ instead of /library/

### ISSUE THREAD

**Issue by m-anish** [iiab/iiab#2021]
### Expected behavior and actual behavior.
I had experienced this on the IIAB in Zanskar so I am creating an issue so that it can be checked against latest master.

Nextcloud creates and stores user data in `/opt/` rather than `/library/`. For IIAB setups that have these directories in different partitions, this presents a problem. Even though there is a nextcloud directory in `/library` (IIRC), it still stores its data in a directory in `/opt`

**Comment by holta** [comment]
Thanks @m-anish!

Can I assign this tkt to you to investigate solution(s)?

**Comment by holta** [comment]
@m-anish can you investigate if this is still a serious issue?

**Comment by m-anish** [comment]
I'll fix this as part of the ongoing nginx port.

**Comment by holta** [comment]
> I'll fix this as part of the ongoing nginx port.

Thanks!  Resolved by PR #2255 that built upon @m-anish's PR #2119
