### ISSUE TITLE
NGINX: http://box/dokuwiki erroneously redirects to http://127.0.0.1:8090/dokuwiki/ [time to deprecate DokuWiki]

### ISSUE THREAD

**Issue by holta** [iiab/iiab#2056]
FYI testing occurred after installing BIG-sized http://d.iiab.io on Debian 10.2 VM 10.8.0.10

Presumably this regression is a result of IIAB's transitioning to NGINX?

Refs: PR https://github.com/iiab/iiab/pull/2042#issuecomment-557318946, PR #2052, #2055

**Comment by holta** [comment]
@m-anish & All:

If this is too hard to fix we should say so promptly in the coming week or so &mdash; and deprecate DokuWiki entirely.

**Comment by holta** [comment]
After much discussion during our recent calls (http://minutes.iiab.io) it's now time to begin deprecating DokuWiki.  Given its lack of use, and our overall need to focus on high-quality offerings _(that are broadly tested and broadly used)_.

**Comment by holta** [comment]
FYI the deprecation of DokuWiki will happen shortly, thanks to PR #2086 with a related PR.

**Comment by tim-moody** [comment]
short term dokuwiki_url: /wiki can be changed to dokuwiki_url: /dokuwiki in default vars

**Comment by holta** [comment]
Subject line changed as a result of merging PR #2086, which attempts to rassign DokuWiki to http://box/dokuwiki (if it was working anyway!)

**Comment by holta** [comment]
> short term dokuwiki_url: /wiki can be changed to dokuwiki_url: /dokuwiki in default vars

FYI the above part is now complete, thanks to PR #2086.

**Comment by holta** [comment]
Initial deprecation of DokuWiki begun, in these 2 places:
- PR #2098 "Begin deprecating DokuWiki, per #2056"
- http://FAQ.IIAB.IO -> Item 9. = "What services (IIAB apps) are suggested during installation?"

**Comment by m-anish** [comment]
I agree with deprecating dokuwiki
