### ISSUE TITLE
NGINX: http://box/gitea displays 404 and broken images

### ISSUE THREAD

**Issue by holta** [iiab/iiab#2057]
Regardless whether visiting http://10.8.0.10/gitea/ or http://192,168.0.162/gitea/

Presumably this regression is a result of IIAB's transitioning to NGINX?

FYI testing occurred after installing BIG-sized http://d.iiab.io on Debian 10.2 VM 10.8.0.10

Refs: PR https://github.com/iiab/iiab/pull/2042#issuecomment-557318946, PR #2052, #2055, #2056

**Comment by tim-moody** [comment]
The page tries to load css and js from gitea/vendor, but the directory does not exist. I doubt this is nginx's fault.

**Comment by holta** [comment]
> The page tries to load css and js from gitea/vendor, but the directory does not exist. I doubt this is nginx's fault.

FYI @jvonau & @aidan-fitz, can you confirm?

**Comment by holta** [comment]
@aidan-fitz I'm now installing a BIG-sized IIAB on Debian 10.2 (10.8.0.30 = 162-deb102-svr-BIG-0102) to monitor if Gitea 10.2 might possibly offer any improvement w.r.t. 404's and broken images, do you know?

**Comment by holta** [comment]
@aidan-fitz @jvonau @tim-moody Gitea 1.10.2 (PR #2091) did not improve the situation (i.e. on today's fresh install of http://10.0.8.30/gitea on Debian 10.2).

What else could be causing all these 404 / broken image failures?

**Comment by tim-moody** [comment]
go back to the last one that worked and install it in the nginx environment.

**Comment by holta** [comment]
> go back to the last one that worked and install it in the nginx environment.

That didn't help.  See http://10.8.0.30/gitea using 2019-09-07's Gitea 1.9.3 as used by IIAB 7.0

What NGINX files need to be tweaked here to deal with these 404's?

**Comment by holta** [comment]
CLARIF: this appears to now be solved, thanks to @tim-moody and PR #2095 !
