### ISSUE TITLE
Runrole regressions [overstrict checking of local_vars.yml & let's restore dashes in role names]

### ISSUE THREAD

**Issue by georgejhunt** [iiab/iiab#2062]
At a minimum, ./runrole should check vars/default_vars.yml, as well as /etc/iiab/local_vars.yml.

I cannot change the config of nginx, without running ./iiab-install --reinstall.

**Comment by jvonau** [comment]
For local testing just add nginx_install: True and nginx_enabled: True to your local_vars.yml file to use runrole. 
You could also try running ./iiab-configure which would be the equivalent of using the admin-console's 'save configuration' & 'install configured options' in place of ./iiab-install --reinstall.

**Comment by holta** [comment]
Whatever's decided, let's please document these practices within http://FAQ.IIAB.IO !

**Comment by jvonau** [comment]
or add nginx_install: True and nginx_enabled: True to the 3 local_vars.yml files

**Comment by holta** [comment]
Under discussion during today's http://minutes.iiab.io call...

@jvonau is trying to avoid the counter being reset when `./runrole` invokes one of the 9-10 aggregate roles: (stages)

https://github.com/iiab/iiab/wiki/IIAB-Contributors-Guide#ansible

@tim-moody suggests `./runrole` include a `--force` flag for people who really want to run one of those 9-10 aggregate roles / stages.

**Comment by holta** [comment]
Call Summary: @jvonau is mulling over a redesign, so power users (advanced implementers etc) aren't impeded by overstrict checking.

**Comment by holta** [comment]
Ref:

#1557 ./runrole options

**Comment by holta** [comment]
ASIDE: "./runrole gitea" used to just work, e.g. to install a newer or older version etc!

Now one also needs to remove the line "gitea_installed: True" from /etc/iiab/iiab_state.yml

(What's the best way to bring back operator simplicity here?)

Ref: #2057

**Comment by holta** [comment]
> ASIDE: "./runrole gitea" used to just work, e.g. to install a newer or older version etc!
> 
> Now one also needs to remove the line "gitea_installed: True" from /etc/iiab/iiab_state.yml

Instead of the above, one can apparently run:

```
cd /opt/iiab/iiab
./runrole --reinstall gitea
```

**Comment by holta** [comment]
PR #2126 "runrole - remove installed lockout" resolves half of this (overstrict checking is now removed).

_...but does [./runrole](https://github.com/iiab/iiab/blob/master/runrole) now allow for dashes-in-role-names ?_

**Comment by holta** [comment]
@jvonau explains that this is solve, as can be confirmed by running...

```
sudo su -
cd /opt/iiab/iiab
./runrole all-vars
```
