### ISSUE TITLE
Master is broken by incorrect /etc/hosts.dnsmasq

### ISSUE THREAD

**Issue by georgejhunt** [iiab/iiab#2064]
On clean install of lite via one liner using local-min.
A client accessing via http://box.lan gets an error when connected via wifi.
/etc/hosts:
127.0.0.1     box.lan localhost.localdomain localhost box box box.lan
::1      localhost ip6-localhost ip6-loopback
ff02::1     ip6-allnodes
ff02::2     ip6-allrouters

127.0.1.1   raspberrypi

A client is not directed to 172.18.96.1 as she should be
~                                                                               
~Now I see that hosts is deprecated.
But still I observe that "ping box.lan" does not resolve. Where is the new config that substitutes for hosts?

**Comment by holta** [comment]
Likely due to PR #2051.

**Comment by georgejhunt** [comment]
uncommenting L668 in /etc/dnsmasq.conf does not fix the problem for me.
I'm stuck.

**Comment by holta** [comment]
> uncommenting L668 in /etc/dnsmasq.conf does not fix the problem for me.

What is L668 ?

In any case, I've asked @jvonau to look into this as soon as he can.

**Comment by georgejhunt** [comment]
I think 2065 fixes it
