### ISSUE TITLE
BUG: IIAB Home Page http://192.168.0.100 redirects to http://192.168.0.100//home/

### ISSUE THREAD

**Issue by holta** [iiab/iiab#2073]
Apparently PR #2068 was insufficiently tested:

It should redirect to http://192.168.0.100/home/ (without the double slash).

@jvonau suggests `$1/{{ iiab_home_url }}`  should be just `$1{{ iiab_home_url }}` somewhere ?

Ref: #2067

**Comment by tim-moody** [comment]
https://github.com/iiab/iiab/blob/master/roles/nginx/templates/iiab.conf.j2 line 2

**Comment by holta** [comment]
Yesterday's call consensus (http://minutes.iiab.io) seemed to be that NGINX should change from _rewrite_ to _redirect_ ?

Is that change also now needed, and what exactly is needed if so?
