### ISSUE TITLE
NGINX: http://box/maps "404 Not Found"

### ISSUE THREAD

**Issue by holta** [iiab/iiab#2079]
http://ip-or-hostname/maps should work like Apache, redirecting to show either:
1) http://ip-or-hostname/osm-vector-maps/maplist/ if no Map Packs have yet been downloaded, or...
2) The actual osm-vectors-maps Map Pack, as downloaded by the IIAB implementer, using Admin Console.

**Comment by tim-moody** [comment]
will be fixed in #2080

**Comment by holta** [comment]
> will be fixed in #2080

Make that PR #2086 (which is building on what #2080 began).
