### ISSUE TITLE
Header Fonts not rendering in Firefox-on-Windows, Safari, Chrome-on-macOS

### ISSUE THREAD

**Issue by holta** [iiab/iiab#2097]
When clicking http://box/admin > Content Menus > Menu Properties > "Select Mobile Header Font" OR "Select Desktop Header Font" it should appear as follows...

![image](https://user-images.githubusercontent.com/2458907/71756225-a5197780-2e5c-11ea-8311-d4c3625d6085.png)

Unfortunately these fonts are not rendering or visualizable within Firefox, Safari or Chrome on iOS &mdash; a typical result being:

![image](https://user-images.githubusercontent.com/2458907/71756295-07727800-2e5d-11ea-984f-6c0617f9ef03.png)

Somewhat Related: #1794 "Modify select lists in Manage Content Menus to display font"

**Comment by avni** [comment]
This may not be easily fixable: https://developer.mozilla.org/en-US/docs/Learn/Forms/Advanced_styling_for_HTML_forms

**Comment by tim-moody** [comment]
I confirm the problem on FF on Win 10.
I don't see how this can be fixed and I don't see any relevance of the above link which does not mention external fonts that I can see.
