### ISSUE TITLE
local_vars.yml has been committed and should not be

### ISSUE THREAD

**Issue by tim-moody** [iiab/iiab#21]

**Comment by holta** [comment]
Confirmed this was a central issue blocking many folks.  Resolved here:
https://github.com/iiab/iiab/commit/5c7263174d9c0adf1fb3c9a2b19c436ea6bddbf4

PS installer script http://download.iiab.io/6.3/rpi/load-master.txt modified to mitigate the damage (verifying that /opt/iiab/iiab/vars/local_vars.yml does NOT exist) in case this kind of across-the-board failure happens again, for whatever reason!
