### ISSUE TITLE
phpmyadmin needs to be ported to nginx or proxied

### ISSUE THREAD

**Issue by m-anish** [iiab/iiab#2122]
AFAICT, php uses apache2 as of now, and apache default port 8090 isnt allowed through iptables (Atleast for appliance mode). So, one of three things should happen
* Port phpmyadmin to nginx
* Proxy phpmyadmin via nginx
* ~~Allow port 8090 to be open.~~

**Comment by jvonau** [comment]
Apache using port 8090 only listens on 127.0.0.1, no need to meddle with iptables.

**Comment by m-anish** [comment]
> Apache using port 8090 only listens on 127.0.0.1, no need to meddle with iptables.

Updated bug description to reflect this :)

**Comment by jvonau** [comment]
or drop supporting phpmyadmin

**Comment by jvonau** [comment]
close
