### ISSUE TITLE
Some IIAB installs contain a partial/old version of PHP at /etc/php/7.0 etc [on Raspbian only...due to WikiHow's php-stem?]

### ISSUE THREAD

**Issue by holta** [iiab/iiab#2123]
Thanks @jvonau for finding this:

```
root@box:~# cat /etc/issue.net
Raspbian GNU/Linux 10

root@box:~# apt -a list php
Listing... Done
php/stable 2:7.3+69 all

root@box:~# locate php | grep 7\\.0
/etc/php/7.0
/etc/php/7.0/apache2
/etc/php/7.0/mods-available
/etc/php/7.0/apache2/conf.d
/etc/php/7.0/apache2/conf.d/20-stem.ini
/etc/php/7.0/mods-available/stem.ini

root@box:~# du -hsc /etc/php/*
20K     /etc/php/7.0
468K    /etc/php/7.3
488K    total
```

**Comment by jvonau** [comment]
suspect is the contents of [php-stem.rpi.tar](https://github.com/iiab/iiab/blob/master/roles/httpd/tasks/php-stem.yml)

**Comment by holta** [comment]
> suspect is the contents of [php-stem.rpi.tar](https://github.com/iiab/iiab/blob/master/roles/httpd/tasks/php-stem.yml)

If so, that would be caused by...
https://github.com/iiab/iiab/blob/master/roles/httpd/tasks/main.yml which calls...
https://github.com/iiab/iiab/blob/master/roles/httpd/tasks/php-stem.yml
http://download.iiab.io/packages/php-stem.rpi.tar
http://download.iiab.io/packages/php-stem.x64.tar <- "no longer relevant, as this one's only installed for Debian 9"

**Comment by jvonau** [comment]
also creates /usr/lib/php/20151012/stem.so

**Comment by holta** [comment]
@tim-moody is your above php-stem patch to fix WikiHow module's search still working?  (Or is it obsolete?)

**Comment by holta** [comment]
June/July 2018 refs:

#829 "Is Spanish WikiHow's search fixable? (works on RACHEL site!)"
PR #925 "php-stem fixes search @ http://box/modules/es-wikihow"

**Comment by holta** [comment]
Call proposed to comment out line 8 here for now:
https://github.com/iiab/iiab/blob/master/roles/httpd/tasks/main.yml#L8

As no modern OS's are using PHP 7.0...

(Even if stem.so might/maybe work in Raspbian new dir /usr/lib/php/20180731 which replaces the old /usr/lib/php/20151012 ?)

**Comment by holta** [comment]
Thanks to @tim-moody who tried to get that old PHP 7.0 stuff (.so shared object etc) to work in Raspbian's latest PHP 7.3, even if no luck!

Good enough for now...mitigated by PR #2189 which comments out the 2018 workaround.

**Comment by holta** [comment]
Re-opening this tkt as @tim-moody made a lot of progress here over the past 24h:

> decided to rebuild php-stem.so. first on vm. it works

Towards fixing Spanish WikiHow's (es-wikihow) search &mdash; on newer platforms shipping more recent versions of PHP than Raspbian Stretch's PHP 7.0...
- PHP 7.2 (Ubuntu 18.04)
- PHP 7.3 (Debian 10 Buster, Raspbian Buster)
- PHP 7.4 (Ubuntu 20.04 ?)

**Comment by tim-moody** [comment]
I have built php-stem.so for 7.2 x64 and 7.3 for rpi and x64. tested successfully 7.3 on rpi and ubuntu 19.10 vm.

need to upload tar files to d.iiab.io
need to modify playbook to install and to add symlink to /etc/php/7.3/fpm/conf.d, which is no longer in tar file.
