### ISSUE TITLE
Stub /etc/nginx/conf.d/nodered-nginx.conf to port Node-RED natively to NGINX? (http://box/nodered)

### ISSUE THREAD

**Issue by holta** [iiab/iiab#2154]
@m-anish as suggested by @jvonau if either of you have hopefully validate this?

```
location /nodered/ {
#  proxy_pass http://127.0.0.1:8090/nodered;
  proxy_pass http://127.0.0.1:1880/nodered/;
}

location /nodered/debug/ws/ {
  proxy_pass http://127.0.0.1:1880/nodered/debug/ws;
}

location /nodered/comms/ {
  proxy_pass http://127.0.0.1:1880/nodered/comms;
}
```

Ref: #2092 "http://box/nextcloud implemented natively with NGINX"

**Comment by holta** [comment]
In any case, let's build off the minimal [nodered/templates/nodered-nginx.conf.j2](https://github.com/iiab/iiab/blob/master/roles/nodered/templates/nodered-nginx.conf.j2) here:

```
location /nodered/ {
  proxy_pass http://127.0.0.1:{{ apache_port }}/nodered/;
}
```

**Comment by holta** [comment]
@m-anish please review this...@jvonau has done basic tests...can you test for corner cases etc?

**Comment by jvonau** [comment]
close

**Comment by jvonau** [comment]
> In any case, let's build off the minimal [nodered/templates/nodered-nginx.conf.j2](https://github.com/iiab/iiab/blob/master/roles/nodered/templates/nodered-nginx.conf.j2) here:
> 
> ```
> location /nodered/ {
>   proxy_pass http://127.0.0.1:{{ apache_port }}/nodered/;
> }
> ```

fff83cd5fb5425809244548e5ebf4be83efae134 https://github.com/iiab/iiab/pull/2137#issuecomment-573444615 introduced the trailing slash after /nodered with the change being carried forward.
