### ISSUE TITLE
Startup menu of IIAB menus:  example

### ISSUE THREAD

**Issue by llovemixo** [iiab/iiab#2161]
IIAB's Dynamic menuing allows easy construction of menus pointing to applications.
It also allows the construction of a menu item pointing to other menus.
The following is an example of a startup menu and a menu item pointing to a submenu.

![Menu_of_menus_r](https://user-images.githubusercontent.com/59588484/72634381-53b6c100-390f-11ea-99ea-dc3694a2a31d.png)
![Compressing_menu_r](https://user-images.githubusercontent.com/59588484/72634484-8a8cd700-390f-11ea-80b0-dad84e84af51.png)

Menus items are constructed by replicating directory "home/ to other names (i.e., kinder/) in /library/www/html/ 
A "tag", as a menu item, is constructed by cloning the "Credits" menu item and changing menu code (to en-kinder) and start URL (to /kinder).  The "tag" menu item can be added to any other menu.

**Comment by holta** [comment]
@llovemixo add screenshots above if poss, directly onto the GitHub ticket, using drag+drop!

Refs: #2110 #2136

**Comment by holta** [comment]
@tim-moody @avni please see the screenshots @llovemixo added above, if you haven't!
