### ISSUE TITLE
Elgg 2.3.3 CSS/images missing (master, Raspbian Stretch)

### ISSUE THREAD

**Issue by holta** [iiab/iiab#217]
Pages are almost unusably ugly!

Can the CSS be repaired so images etc appear?

Background: installed using http://download.iiab.io/6.4/rpi/load-vpn.txt (master) onto Raspbian Stretch Lite on RPi3.

ASIDE: the forced redirect from http://<IP OR NAME>/elgg to http://box/elgg/action/login during Elgg login makes this unusable in most LAN/campus environments, per #214 (in case anybody's so lucky as to crack that!)

**Comment by holta** [comment]
Ref PR #218 (thought elgg state=directory was in)

**Comment by jvonau** [comment]
> ASIDE: the forced redirect from http:///elgg to http://box/elgg/action/login during Elgg login makes this unusable in most LAN/campus environments

ProxyPass?

**Comment by holta** [comment]
To solve this CSS problem (nothing much appears at http://box/elgg) here is @georgejhunt's workaround that worked on an older install of Elgg on NUC:

1. As root, go into the command line mysql tool "mysql"
2. show databases;
3. drop database elggdb;
4. show databases;
5. quit
6. go to /opt/iiab/iiab
7. ./runtags elgg
8. test whether the CSS is fixed

Unfortunately this does not work on master ([IIAB 6.4 RC2](https://github.com/iiab/iiab/releases/) +) on RPi3!  _Any similar ideas out there?_

**Comment by jvonau** [comment]
What other services are being installed at the same time? attach the local_vars to this issue. Think there might be a missing dependence that might be covered in a different play.

**Comment by holta** [comment]
All tests were done with our ["medium-sized" local_vars.yml](http://wiki.laptop.org/go/IIAB/local_vars.yml)

Aside/Recap from earlier in September: this is building off #202 (Elgg upgrade 1.12.16 LTS to 2.3.3; Nextcloud - add php's zip mbstring).

**Comment by holta** [comment]
Clarif: our ["medium-sized" local_vars.yml](http://wiki.laptop.org/go/IIAB/local_vars.yml) was of course enhanced from:
```
elgg_install: True
elgg_enabled: False
```
...to:
```
elgg_install: True
elgg_enabled: True
```
And then "cd /opt/iiab/iiab; ./runtags elgg" was run.

**Comment by holta** [comment]
I'd thought #188 (Elgg 1.12.12 & 1.12.16 don't show anything in browser (500 Internal Server Error)) was solved.

But is this still relevant?

**Comment by jvonau** [comment]
see my comments in #188 it's a dns issue that might be able to solved with some url rewrite trickery

![screenshot_2017-09-23_13-13-41](https://user-images.githubusercontent.com/5579710/30775827-3068665c-a061-11e7-9626-ec97c9efc65d.png)

**Comment by holta** [comment]
Thanks @jvonau you've confirmed this is more than a CSS issue!

e.g. http://10.8.0.10/elgg and http://192.168.0.131/elgg etc appear to insist on loading all CSS/images from http://box (which never load) hence causing the ugly/unusable Elgg pages.

**Comment by jvonau** [comment]
Elgg should work perfect from the LAN side as 'box' will resolve correctly, proxypass or mod-rewrite should be able to capture "some base url" that is in the browser and change that to "box" for php to use.

**Comment by jvonau** [comment]
oh yea /opt/elgg s/b owned by www-data:www-data otherwise you get a 403 prohibited error

**Comment by holta** [comment]
fyi 1 - in #305 @jvonau is working on a [(partial for now) fix](https://github.com/iiab/iiab/pull/305/files#diff-1460b7c549aa9ce1a2a72a38aed3cd65) that might enable Elgg across all URL's, regardless of http://localhost/elgg, http://box/elgg, http://192.168.0.x/elgg, http://10.8.0.y/elgg, http://[CAMPUS-SITE-NAME]/elgg etc.

fyi 2 - NGINX may obviate the need for this in [IIAB 6.5](https://github.com/iiab/iiab/milestone/2) or [IIAB 6.6](https://github.com/iiab/iiab/milestone/3).

**Comment by holta** [comment]
Ref #309 (Elgg - Fix permissions & handle upgrades)
