### ISSUE TITLE
Smaller Map Pack needed for both (1) testing & (2) rapid understanding of what IIAB offers [OSM Vector Maps]

### ISSUE THREAD

**Issue by holta** [iiab/iiab#2207]
Currently testing is onerously & unnecessarily slow as a result our not having a small OSM Map Pack available.

Example: currently the smallest clickable/available Map Pack is ~3.77GB "Central America" which takes a long time to download, and cannot be installed on 20GB VM disks where BIG-sized IIAB has already been installed.  As it needs almost double the size to unzip even this smallest zip file: https://archive.org/download/en-osm-omt_central_america_2017-07-03_v0.23/

This is a known issue of course!  (But prioritizing testing/demoing as such is important _both_ to enable rapid understanding/adoption of our work _and_ to refine a quality product!)  So let's fix it in coming days/weeks/months as soon as @georgejhunt finds it realistic to do that.

**Comment by georgejhunt** [comment]
I put san_jose back in and labeled it "World to Zoom 10".

**Comment by holta** [comment]
Done, Thanks @georgejhunt

**Comment by holta** [comment]
@georgejhunt I installed this on BIG-sized Ubuntu 18.04 VM http://10.8.0.86/maps = http://10.8.0.86/osm-vector-maps/en-osm-omt_san_jose_2017-07-03_v0.23/ and streets do not show up after you zoom in past the satellite photos.

No matter whether I zoom into San Jose or Boston or otherwise.

As a testing tool it's absolutely fine with satellite photos alone of course &mdash; but are you aware of this issue?  FWIW I was testing using Chrome 79.0.3945.130.

**Comment by holta** [comment]
@georgejhunt you're aware of this glitch right?

i.e. all streets not showing up when you zoom in, no matter where in the world you zoom in (even if you zoom into San Jose!)

Regardless whether classify this as "wontfix" or whatev...let us know what's likely happening here...if you know!  As originates from: https://archive.org/download/en-osm-omt_san_jose_2017-07-03_v0.23/en-osm-omt_san_jose_2017-07-03_v0.23.zip

**Comment by holta** [comment]
Summary from this week's http://minutes.iiab.io call:

@georgejhunt is aware of the issue, but we don't fully understand yet why this San Jose map pack "displayed streets ~9 months ago, but it no longer does."  As can be seen here, where it was installed last night:

http://10.8.0.58/maps

Not a big deal as "World to Zoom 10 1.69 GB" is really just a demo map pack for testing &mdash; but next time we'll try to arrange a cleaner demo map pack.

PS George if you figure out what the issue was in coming months, let us know if poss~

**Comment by georgejhunt** [comment]
I changed regions.json at unleashkids.org to point to  version v.2 of
san_jose map pack rather than v.23 and did a clean install on rpi4 of lite
9/26/19. The san_jose pack works correctly now. Thanks for noticing.
