### ISSUE TITLE
iiab_admin_user_install: False trap

### ISSUE THREAD

**Issue by tim-moody** [iiab/iiab#2222]
If you set iiab_admin_user_install: False, iiab-install will fail in stage 4. However, it is not enough to go back and set it to True, because the stage in which it is to be set has already been marked as complete. Therefore you must begin again with iiab-install --reinstall.

**Comment by holta** [comment]
> Therefore you must begin again with iiab-install --reinstall.

Tangentially Related, is a design question about whether './iiab-install --reinstall' should 'rm /etc/iiab/iiab_state.yml' (or most/all of its contents?)

Background:
- './runrole --reinstall [ROLE NAME]' deletes (1 line) from /etc/iiab/iiab_state.yml
- './iiab-install --reinstall' does not currently delete (any lines) from /etc/iiab/iiab_state.yml

Somewhat related to:

#2210 "'./runrole pbx' fails due to predefined var 'pbx_installed' in pbx/defaults/main.yml -- illustrates weakness of var validation when invoked from ./iiab-install (instead of from ./runrole)"

**Comment by jvonau** [comment]
Great bug report 'stage 4 failure', recall which sub-role was involved? I'll go out on a limb and suggest it was iiab_lib as #1228 suggest that iiab_admin_user is the owner of the content directory.

**Comment by holta** [comment]
> Great bug report

#2222 is easy to remember too (two too to... ;)

**Comment by tim-moody** [comment]
> recall which sub-role was involved?

no. which is why I didn't speculate.

**Comment by holta** [comment]
I'm assuming this was closed by accident?

(Seems like something that should be fixed eventually.)

**Comment by jvonau** [comment]
> If you set iiab_admin_user_install: False, iiab-install will fail in stage 4. However, it is not enough to go back and set it to True, because the stage in which it is to be set has already been marked as complete. Therefore you must begin again with iiab-install --reinstall.



> > Therefore you must begin again with iiab-install --reinstall.
> 
> Tangentially Related, is a design question about whether './iiab-install --reinstall' should 'rm /etc/iiab/iiab_state.yml' (or most/all of its contents?)
> 
> Background:
> 
>     * './runrole --reinstall [ROLE NAME]' deletes (1 line) from /etc/iiab/iiab_state.yml
> 
>     * './iiab-install --reinstall' does not currently delete (any lines) from /etc/iiab/iiab_state.yml
> 
I feel --reinstall is more targeted at replacing files that iiab provides in stage 1-3 when we have something changing in the base install, like adding a font in httpd or tinkering with iiab_lib.py
I'd suggest --upgrade for any planned programmatic deletions from /etc/iiab/iiab_state.yml where we know in advance when some app's release versions have been bumped.

**Comment by holta** [comment]
Thanks @jvonau for uncovering the link to #1228 which I'd missed earlier, as mentioned during this week's IIAB call (http://minutes.iiab.io).

I'll make that change to `/library/www/html/local_content` group perm shortly, per @jvonau & @tim-moody's recommendation.

**Comment by holta** [comment]
Mitigated by PR #2250.

@tim-moody will also address this within https://github.com/iiab/iiab-admin-console to make things more robust.
