### ISSUE TITLE
pbx requires nodejs 10.x, blocks install.

### ISSUE THREAD

**Issue by jvonau** [iiab/iiab#2241]
> TASK [pbx : FAIL (STOP THE INSTALL) IF nodejs_installed is undefined] **********
skipping: [127.0.0.1]
TASK [pbx : Fail if nodejs_version is incorrect] *******************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "PBX: Refusing to install as nodejs_version is not 10.x.  Please fix that (looking into /etc/iiab/local_vars.yml and /opt/iiab/iiab/vars/default_vars.yml) and then rerun."}
PLAY RECAP *********************************************************************
127.0.0.1                  : ok=127  changed=41   unreachable=0    failed=1    skipped=60   rescued=0    ignored=0

**Comment by holta** [comment]
@m-anish I noticed this as well, in recent weeks, since IIAB transitioned from Node.js 10.x to 12.x a couple months ago.

Do you think roles/pbx might in fact run under 12.x these days?

**Comment by holta** [comment]
Unrelated to #2210 per se...except that both recent issues involve @m-anish's PBX work from 2018 especially...and we could definitely use your guidance Anish on how to navigate and prioritize these together!

**Comment by holta** [comment]
@m-anish I'm assigning this to you just so we can together come to a decision here...tolerating Node 12.x even if it's a risk?

**Comment by jvonau** [comment]
php-gettext removed from ubuntu-20 https://answers.launchpad.net/ubuntu/+source/php-gettext/+question/690678

**Comment by holta** [comment]
@jvonau should we close this now?

**Comment by jvonau** [comment]
addressed with #2489
