### ISSUE TITLE
newcomers need installs to run to completion

### ISSUE THREAD

**Issue by holta** [iiab/iiab#227]
If ./runansible must reboot (unlike in the past, TBD if Raspbian Stretch for some reason requires that?) then indeed newcomers require install scripts like the following to run right-thru-to-completion — but in some other way:

http://download.iiab.io/6.4/rpi/load-min.txt ~6 apps
http://download.iiab.io/6.4/rpi/load.txt ~12 apps "classic"
http://download.iiab.io/6.4/rpi/load-big.txt ~20 apps

**Comment by georgejhunt** [comment]
If you want the load-*.txt scripts to run to completion, we can create a
script, and document the following 2 step process:

   1.    curl download.iiab.io/6.4/first.txt|sudo bash
   2.    curl download.iiab.io/6.4/load-*.txt | sudo bash

**Comment by holta** [comment]
Every time we ask for manual intervention during the middle of an installation, we've just lost 50-to-90% of community enthusiasm/participation — likely permanently, people whose 1st impressions are soured, and will likely tell others.

A zero-bureaucracy install is needed, that completes on its own fully from beginning to end.

We can outline how to get this right on Monday, e.g. if a continuation script needs to be triggered automatically (upon reboot if indeed the reboot is suddenly required going forward, for whatever reason, let's also document in [FAQ.IIAB.IO](http://faq.iiab.io) what this new reason is).

**Comment by jvonau** [comment]
The root cause of needing a reboot is the current code in rpi_debian.yml has hard-coded interface names done by this piece of code:
`
- name: set the interface variables based upon gui_desired_role
  set_fact: 
       discovered_wireless_iface: wlan0
discovered_wan_iface: eth0
`

**Comment by jvonau** [comment]
Edit: opps wrong issue

**Comment by georgejhunt** [comment]
I think that is true. And we could just let the people who want to copy an
SD card deal with the complexity. That is a much smaller group, and not the
group that Adam is focused on at the moment.

That could involve setting a local_vars.yml flag, and running
./iiab-network before finalizing and shrinking the partition.

**Comment by holta** [comment]
Profound thanks Jerry & George:

Monday morning during our community call (http://minutes.iiab.io) I'll also implement the long-overdue automated reboot **at the end of** [download.iiab.io/6.4/rpi/load.txt](http://download.iiab.io/6.4/rpi/load.txt)

For the reasons stated therein:

```
# 4. When this script completes (might take an hour or more!) please set
#    /etc/iiab/handle IF YOU USE openvpn@xscenet AND REGARDLESS REBOOT
#    which sets the hostname, while improving RTC settings + memory mgmt
```

_Unless of course you tell me a better way +)_

**Comment by jvonau** [comment]
> That could involve setting a local_vars.yml flag, and running ./iiab-network before finalizing and shrinking the partition.

I'd remove whatever file is being used to create the bridge prior to shrinking the image. I'd go with running running iiab-network on first boot after cloning, that would work nicely should the /boot//wpa_supplicant.conf file (testing needed to confirm this works) be present to set the default gateway via wifi. We learned in #198 that an unmodified image is using wlan0 out of the box due to the device being tied to the sdio interface so it should not change. There is a webpage that states that but can't find it right now, so I'll rely on observed behaviour for the moment. We know that no file needs to be, and is [discouraged by upstream](cant find it atm) configured to have the wired ethernet port become the gateway.

**Comment by holta** [comment]
> running iiab-network on first boot after cloning

If this happens automatically, that's great!

But a warning that community groups need to continue to be able to "dd" (clone) IIAB images that simply work on first boot, without post-production bureaucracy.

In short, the way this works today: I (and others in Haiti etc) follow George's routine to "rm /etc/iiab/uuid /etc/iiab/handle" on the source image, and then after dd cloning... a /etc/iiab/uuid is automatically created(*) during the first boot of each clone.

(*) this works on RPi3 but there is a timing bug on RPi Zero W machines, such that /etc/iiab/uuid is never created.  So far we've happily ignored this bug, as /etc/iiab/uuid does not seem to be a critical file for the most common IIAB uses...but this Zero W bug should definitely be rooted out later if poss :)

**Comment by holta** [comment]
Ref #229 (/etc/iiab/uuid is never created if SD's 1st boot is in RPi Zero W)

**Comment by jvonau** [comment]
#160

**Comment by holta** [comment]
Install scripts like http://download.iiab.io/6.4/rpi/load-vpn.txt run straight through to completion(*) so am closing this bug, Thanks All who made this possible!

(*) in about 80min in the above case.  Other install scripts at http://download.iiab.io/6.4/rpi/ take significantly less/more time.
