### ISSUE TITLE
lokole does not install on 64bit ubuntu on rpi

### ISSUE THREAD

**Issue by tim-moody** [iiab/iiab#2297]
ubuntu 19.10.1 64 bit on rpi 4 2G

TASK [lokole : DEFAULT: pip install opwen_email_client (Lokole, latest available version) from PyPI to /library/lokole/venv, if above vars both UNdefined] ***********************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "cmd": ["/library/lokole/venv/bin/pip3", "install", "--no-cache-dir", "opwen_email_client"], "msg": "stdout: Collecting opwen_email_client\n  Downloading https://files.pythonhosted.org/packages/2e/f9/c13ee81848ad475981fb26b2df208c9115668b5d19fff02a40c1612af315/opwen_email_client-0.5.11.tar.gz (605kB)\nRequirement already satisfied: Babel==2.8.0 in /library/lokole/venv/lib/python3.7/site-packages (from opwen_email_client) (2.8.0)\nRequirement already satisfied: Flask-BabelEx==0.9.3 in /library/lokole/venv/lib/python3.7/site-packages (from opwen_email_client) (0.9.3)\nRequirement already satisfied: Flask-Caching==1.8.0 in /library/lokole/venv/lib/python3.7/site-packages (from opwen_email_client) (1.8.0)\nRequirement already satisfied: Flask-Cors==3.0.8 in /library/lokole/venv/lib/python3.7/site-packages (from opwen_email_client) (3.0.8)\nRequirement already satisfied: Flask-Migrate==2.5.2 in /library/lokole/venv/lib/python3.7/site-packages (from opwen_email_client) (2.5.2)\nRequirement already satisfied: Flask-SQLAlchemy==2.4.1 in /library/lokole/venv/lib/python3.7/site-packages (from opwen_email_client) (2.4.1)\nRequirement already satisfied: Flask-Script==2.0.6 in /library/lokole/venv/lib/python3.7/site-packages (from opwen_email_client) (2.0.6)\nRequirement already satisfied: Flask-Security==3.0.0 in /library/lokole/venv/lib/python3.7/site-packages (from opwen_email_client) (3.0.0)\nRequirement already satisfied: Flask-Testing==0.7.1 in /library/lokole/venv/lib/python3.7/site-packages (from opwen_email_client) (0.7.1)\nRequirement already satisfied: Flask-WTF==0.14.2 in /library/lokole/venv/lib/python3.7/site-packages (from opwen_email_client) (0.14.2)\nRequirement already satisfied: Flask==1.1.1 in /library/lokole/venv/lib/python3.7/site-packages (from opwen_email_client) (1.1.1)\nCollecting Pillow==7.0.0 (from opwen_email_client)\n  Downloading https://files.pythonhosted.org/packages/39/47/f28067b187dd664d205f75b07dcc6e0e95703e134008a14814827eebcaab/Pillow-7.0.0.tar.gz (38.2MB)\nRequirement already satisfied: SQLAlchemy==1.3.13 in /library/lokole/venv/lib/python3.7/site-packages (from opwen_email_client) (1.3.13)\nRequirement already satisfied: WTForms==2.2.1 in /library/lokole/venv/lib/python3.7/site-packages (from opwen_email_client) (2.2.1)\nRequirement already satisfied: Werkzeug==0.16.1 in /library/lokole/venv/lib/python3.7/site-packages (from opwen_email_client) (0.16.1)\nCollecting apache-libcloud==3.0.0rc1 (from opwen_email_client)\n  Downloading https://files.pythonhosted.org/packages/1a/67/4672f3c50b9ac7a67addffa2224c3beab9057ad4b3db26435c57af50920d/apache_libcloud-3.0.0rc1-py2.py3-none-any.whl (3.3MB)\nCollecting bcrypt==3.1.7 (from opwen_email_client)\n  Downloading https://files.pythonhosted.org/packages/fa/aa/025a3ab62469b5167bc397837c9ffc486c42a97ef12ceaa6699d8f5a5416/bcrypt-3.1.7.tar.gz (42kB)\n  Installing build dependencies: started\n  Installing build dependencies: finished with status 'done'\nCollecting beautifulsoup4==4.8.2 (from opwen_email_client)\n  Downloading https://files.pythonhosted.org/packages/cb/a1/c698cf319e9cfed6b17376281bd0efc6bfc8465698f54170ef60a485ab5d/beautifulsoup4-4.8.2-py3-none-any.whl (106kB)\nCollecting cached-property==1.5.1 (from opwen_email_client)\n  Downloading https://files.pythonhosted.org/packages/3b/86/85c1be2e8db9e13ef9a350aecd6dea292bd612fa288c2f40d035bb750ded/cached_property-1.5.1-py2.py3-none-any.whl\nCollecting celery[sqlalchemy]==4.4.0 (from opwen_email_client)\n  Downloading https://files.pythonhosted.org/packages/47/53/6e2ccc87b18ddc582d2de31b3ed9144c72a68062659e9e4a68e19312d254/celery-4.4.0-py2.py3-none-any.whl (421kB)\nCollecting environs==7.1.0 (from opwen_email_client)\n  Downloading https://files.pythonhosted.org/packages/8c/e0/0f97feb7728de5acd6cb1c42fe4bbc9eb779c1c1e8a641e08b069a4aa441/environs-7.1.0-py2.py3-none-any.whl\nCollecting gunicorn==20.0.4 (from opwen_email_client)\n  Downloading https://files.pythonhosted.org/packages/69/ca/926f7cd3a2014b16870086b2d0fdc84a9e49473c68a8dff8b57f7c156f43/gunicorn-20.0.4-py2.py3-none-any.whl (77kB)\nCollecting mkwvconf==0.1.1 (from opwen_email_client)\n  Downloading https://files.pythonhosted.org/packages/de/d2/03c75327ce5295a98f0d5e205aaae9dfef651bacb76ca95fc7f93bd117dd/mkwvconf-0.1.1.tar.gz\nRequirement already satisfied: passlib==1.7.2 in /library/lokole/venv/lib/python3.7/site-packages (from opwen_email_client) (1.7.2)\nCollecting python-crontab==2.4.0 (from opwen_email_client)\n  Downloading https://files.pythonhosted.org/packages/bc/03/852f9c5f8da7f58abce06fe8ae769cbcf6502f1c60684b16bad72ffcced3/python-crontab-2.4.0.tar.gz (50kB)\nCollecting requests==2.22.0 (from opwen_email_client)\n  Downloading https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl (57kB)\nCollecting typing==3.7.4.1 (from opwen_email_client)\n  Downloading https://files.pythonhosted.org/packages/fe/2e/b480ee1b75e6d17d2993738670e75c1feeb9ff7f64452153cf018051cc92/typing-3.7.4.1-py3-none-any.whl\nCollecting tzlocal==2.0.0 (from opwen_email_client)\n  Downloading https://files.pythonhosted.org/packages/ef/99/53bd1ac9349262f59c1c421d8fcc2559ae8a5eeffed9202684756b648d33/tzlocal-2.0.0-py2.py3-none-any.whl\nCollecting watchdog==0.10.1 (from opwen_email_client)\n  Downloading https://files.pythonhosted.org/packages/34/65/dca6d9653656630169e9f71fe3fcf2a487b671a096cf11dc3011c822a408/watchdog-0.10.1.tar.gz (94kB)\nCollecting xtarfile[zstd]==0.0.2 (from opwen_email_client)\n  Downloading https://files.pythonhosted.org/packages/3f/cb/b8bc79b4dafea85b754e59d6c337e2611a6f4e80fba1eea6874fe3716039/xtarfile-0.0.2.tar.gz\nRequirement already satisfied: pytz>=2015.7 in /library/lokole/venv/lib/python3.7/site-packages (from Babel==2.8.0->opwen_email_client) (2019.3)\nRequirement already satisfied: Jinja2>=2.5 in /library/lokole/venv/lib/python3.7/site-packages (from Flask-BabelEx==0.9.3->opwen_email_client) (2.11.1)\nRequirement already satisfied: speaklater>=1.2 in /library/lokole/venv/lib/python3.7/site-packages (from Flask-BabelEx==0.9.3->opwen_email_client) (1.3)\nRequirement already satisfied: Six in /library/lokole/venv/lib/python3.7/site-packages (from Flask-Cors==3.0.8->opwen_email_client) (1.14.0)\nRequirement already satisfied: alembic>=0.7 in /library/lokole/venv/lib/python3.7/site-packages (from Flask-Migrate==2.5.2->opwen_email_client) (1.4.2)\nRequirement already satisfied: itsdangerous>=0.21 in /library/lokole/venv/lib/python3.7/site-packages (from Flask-Security==3.0.0->opwen_email_client) (1.1.0)\nRequirement already satisfied: Flask-Login>=0.3.0 in /library/lokole/venv/lib/python3.7/site-packages (from Flask-Security==3.0.0->opwen_email_client) (0.5.0)\nRequirement already satisfied: Flask-Principal>=0.3.3 in /library/lokole/venv/lib/python3.7/site-packages (from Flask-Security==3.0.0->opwen_email_client) (0.4.0)\nRequirement already satisfied: Flask-Mail>=0.7.3 in /library/lokole/venv/lib/python3.7/site-packages (from Flask-Security==3.0.0->opwen_email_client) (0.9.1)\nRequirement already satisfied: click>=5.1 in /library/lokole/venv/lib/python3.7/site-packages (from Flask==1.1.1->opwen_email_client) (7.1.1)\nCollecting cffi>=1.1 (from bcrypt==3.1.7->opwen_email_client)\n  Downloading https://files.pythonhosted.org/packages/05/54/3324b0c46340c31b909fcec598696aaec7ddc8c18a63f2db352562d3354c/cffi-1.14.0.tar.gz (463kB)\nCollecting soupsieve>=1.2 (from beautifulsoup4==4.8.2->opwen_email_client)\n  Downloading https://files.pythonhosted.org/packages/05/cf/ea245e52f55823f19992447b008bcbb7f78efc5960d77f6c34b5b45b36dd/soupsieve-2.0-py2.py3-none-any.whl\nCollecting vine==1.3.0 (from celery[sqlalchemy]==4.4.0->opwen_email_client)\n  Downloading https://files.pythonhosted.org/packages/7f/60/82c03047396126c8331ceb64da1dc52d4f1317209f32e8fe286d0c07365a/vine-1.3.0-py2.py3-none-any.whl\nCollecting kombu<4.7,>=4.6.7 (from celery[sqlalchemy]==4.4.0->opwen_email_client)\n  Downloading https://files.pythonhosted.org/packages/34/7e/44445f7d9031e82b4a1160141de35ca810f44041bf5065b45c68ab0ec9e8/kombu-4.6.8-py2.py3-none-any.whl (183kB)\nCollecting billiard<4.0,>=3.6.1 (from celery[sqlalchemy]==4.4.0->opwen_email_client)\n  Downloading https://files.pythonhosted.org/packages/e8/5e/7591866ff45b370354bd20291cb6f87ddb2eef1f1c88c890a38412037e11/billiard-3.6.3.0-py3-none-any.whl (89kB)\nCollecting python-dotenv (from environs==7.1.0->opwen_email_client)\n  Downloading https://files.pythonhosted.org/packages/7f/ee/e0cd2d8ba548e4c3e8c9e70d76e423b3e8b8e4eec351f51292d828c735d2/python_dotenv-0.12.0-py2.py3-none-any.whl\nCollecting marshmallow>=2.7.0 (from environs==7.1.0->opwen_email_client)\n  Downloading https://files.pythonhosted.org/packages/d8/0b/bb43d7610e71d87e8537025841c248471dbf938c676d32b8f94c82148c04/marshmallow-3.5.1-py2.py3-none-any.whl (45kB)\nRequirement already satisfied: setuptools>=3.0 in /library/lokole/venv/lib/python3.7/site-packages (from gunicorn==20.0.4->opwen_email_client) (40.8.0)\nRequirement already satisfied: python-dateutil in /library/lokole/venv/lib/python3.7/site-packages (from python-crontab==2.4.0->opwen_email_client) (2.8.1)\nCollecting chardet<3.1.0,>=3.0.2 (from requests==2.22.0->opwen_email_client)\n  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)\nCollecting certifi>=2017.4.17 (from requests==2.22.0->opwen_email_client)\n  Downloading https://files.pythonhosted.org/packages/b9/63/df50cac98ea0d5b006c55a399c3bf1db9da7b5a24de7890bc9cfd5dd9e99/certifi-2019.11.28-py2.py3-none-any.whl (156kB)\nCollecting idna<2.9,>=2.5 (from requests==2.22.0->opwen_email_client)\n  Downloading https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl (58kB)\nCollecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests==2.22.0->opwen_email_client)\n  Downloading https://files.pythonhosted.org/packages/e8/74/6e4f91745020f967d09332bb2b8b9b10090957334692eb88ea4afe91b77f/urllib3-1.25.8-py2.py3-none-any.whl (125kB)\nCollecting pathtools>=0.1.1 (from watchdog==0.10.1->opwen_email_client)\n  Downloading https://files.pythonhosted.org/packages/e7/7f/470d6fcdf23f9f3518f6b0b76be9df16dcc8630ad409947f8be2eb0ed13a/pathtools-0.1.2.tar.gz\nCollecting zstandard>=0.10.2 (from xtarfile[zstd]==0.0.2->opwen_email_client)\n  Downloading https://files.pythonhosted.org/packages/b1/3d/b95e8beb3b2d165726c6105a728a1f59ae88d6bf1e3dc66375fbe149afcd/zstandard-0.13.0.tar.gz (659kB)\nRequirement already satisfied: MarkupSafe>=0.23 in /library/lokole/venv/lib/python3.7/site-packages (from Jinja2>=2.5->Flask-BabelEx==0.9.3->opwen_email_client) (1.1.1)\nRequirement already satisfied: Mako in /library/lokole/venv/lib/python3.7/site-packages (from alembic>=0.7->Flask-Migrate==2.5.2->opwen_email_client) (1.1.2)\nRequirement already satisfied: python-editor>=0.3 in /library/lokole/venv/lib/python3.7/site-packages (from alembic>=0.7->Flask-Migrate==2.5.2->opwen_email_client) (1.0.4)\nRequirement already satisfied: blinker in /library/lokole/venv/lib/python3.7/site-packages (from Flask-Principal>=0.3.3->Flask-Security==3.0.0->opwen_email_client) (1.4)\nCollecting pycparser (from cffi>=1.1->bcrypt==3.1.7->opwen_email_client)\n  Downloading https://files.pythonhosted.org/packages/ae/e7/d9c3a176ca4b02024debf82342dab36efadfc5776f9c8db077e8f6e71821/pycparser-2.20-py2.py3-none-any.whl (112kB)\nCollecting importlib-metadata>=0.18; python_version < \"3.8\" (from kombu<4.7,>=4.6.7->celery[sqlalchemy]==4.4.0->opwen_email_client)\n  Downloading https://files.pythonhosted.org/packages/8b/03/a00d504808808912751e64ccf414be53c29cad620e3de2421135fcae3025/importlib_metadata-1.5.0-py2.py3-none-any.whl\nCollecting amqp<2.6,>=2.5.2 (from kombu<4.7,>=4.6.7->celery[sqlalchemy]==4.4.0->opwen_email_client)\n  Downloading https://files.pythonhosted.org/packages/fc/a0/6aa2a7923d4e82dda23db27711d565f0c4abf1570859f168e3d0975f1eb6/amqp-2.5.2-py2.py3-none-any.whl (49kB)\nCollecting zipp>=0.5 (from importlib-metadata>=0.18; python_version < \"3.8\"->kombu<4.7,>=4.6.7->celery[sqlalchemy]==4.4.0->opwen_email_client)\n  Downloading https://files.pythonhosted.org/packages/b2/34/bfcb43cc0ba81f527bc4f40ef41ba2ff4080e047acb0586b56b3d017ace4/zipp-3.1.0-py3-none-any.whl\nInstalling collected packages: Pillow, chardet, certifi, idna, urllib3, requests, apache-libcloud, pycparser, cffi, bcrypt, soupsieve, beautifulsoup4, cached-property, vine, zipp, importlib-metadata, amqp, kombu, billiard, celery, python-dotenv, marshmallow, environs, gunicorn, mkwvconf, python-crontab, typing, tzlocal, pathtools, watchdog, zstandard, xtarfile, opwen-email-client\n  Running setup.py install for Pillow: started\n    Running setup.py install for Pillow: finished with status 'error'\n    Complete output from command /library/lokole/venv/bin/python3 -u -c \"import setuptools, tokenize;__file__='/tmp/pip-install-rv3sln_0/Pillow/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\\r\\n', '\\n');f.close();exec(compile(code, __file__, 'exec'))\" install --record /tmp/pip-record-2n26rx7e/install-record.txt --single-version-externally-managed --compile --install-headers /library/lokole/venv/include/site/python3.7/Pillow:\n    running install\n    running build\n    running build_py\n    creating build\n    creating build/lib.linux-aarch64-3.7\n    creating build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/ContainerIO.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/ImagePath.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/_binary.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/ImageGrab.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/ImageTransform.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/ImageStat.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/Image.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/GribStubImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/XbmImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/PyAccess.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/MspImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/ImageTk.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/ImageChops.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/FpxImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/JpegPresets.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/TiffTags.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/ImageCms.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/ImageColor.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/ImageFilter.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/_util.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/BdfFontFile.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/BlpImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/ImageMath.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/TgaImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/BmpImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/features.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/PdfParser.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/CurImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/ImImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/__init__.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/ImageSequence.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/FtexImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/MicImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/PsdImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/ImageShow.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/ExifTags.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/SunImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/_version.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/XVThumbImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/IcnsImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/ImageFile.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/PcdImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/TarIO.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/XpmImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/MpoImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/IcoImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/Jpeg2KImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/PpmImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/PSDraw.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/FliImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/ImtImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/WmfImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/ImageOps.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/WebPImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/WalImageFile.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/ImageMorph.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/PalmImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/PngImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/ImagePalette.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/EpsImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/SpiderImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/GifImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/ImageQt.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/PdfImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/PaletteFile.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/SgiImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/PcfFontFile.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/ImageFont.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/ImageMode.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/ImageDraw.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/ImageWin.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/Hdf5StubImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/FitsStubImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/MpegImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/McIdasImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/PcxImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/__main__.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/ImageDraw2.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/DdsImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/GbrImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/TiffImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/ImageEnhance.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/_tkinter_finder.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/JpegImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/GimpGradientFile.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/IptcImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/FontFile.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/GdImageFile.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/BufrStubImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/DcxImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/GimpPaletteFile.py -> build/lib.linux-aarch64-3.7/PIL\n    copying src/PIL/PixarImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL\n    running egg_info\n    writing src/Pillow.egg-info/PKG-INFO\n    writing dependency_links to src/Pillow.egg-info/dependency_links.txt\n    writing top-level names to src/Pillow.egg-info/top_level.txt\n    reading manifest file 'src/Pillow.egg-info/SOURCES.txt'\n    reading manifest template 'MANIFEST.in'\n    warning: no files found matching '*.c'\n    warning: no files found matching '*.h'\n    warning: no files found matching '*.sh'\n    warning: no previously-included files found matching '.appveyor.yml'\n    warning: no previously-included files found matching '.coveragerc'\n    warning: no previously-included files found matching '.codecov.yml'\n    warning: no previously-included files found matching '.editorconfig'\n    warning: no previously-included files found matching '.readthedocs.yml'\n    warning: no previously-included files found matching 'azure-pipelines.yml'\n    warning: no previously-included files matching '.git*' found anywhere in distribution\n    warning: no previously-included files matching '*.pyc' found anywhere in distribution\n    warning: no previously-included files matching '*.so' found anywhere in distribution\n    no previously-included directories found matching '.azure-pipelines'\n    no previously-included directories found matching '.travis'\n    writing manifest file 'src/Pillow.egg-info/SOURCES.txt'\n    running build_ext\n    \n    \n    The headers or library files could not be found for jpeg,\n    a required dependency when compiling Pillow from source.\n    \n    Please see the install instructions at:\n       https://pillow.readthedocs.io/en/latest/installation.html\n    \n    Traceback (most recent call last):\n      File \"/tmp/pip-install-rv3sln_0/Pillow/setup.py\", line 892, in <module>\n        zip_safe=not (debug_build() or PLATFORM_MINGW),\n      File \"/library/lokole/venv/lib/python3.7/site-packages/setuptools/__init__.py\", line 145, in setup\n        return distutils.core.setup(**attrs)\n      File \"/usr/lib/python3.7/distutils/core.py\", line 148, in setup\n        dist.run_commands()\n      File \"/usr/lib/python3.7/distutils/dist.py\", line 966, in run_commands\n        self.run_command(cmd)\n      File \"/usr/lib/python3.7/distutils/dist.py\", line 985, in run_command\n        cmd_obj.run()\n      File \"/library/lokole/venv/lib/python3.7/site-packages/setuptools/command/install.py\", line 61, in run\n        return orig.install.run(self)\n      File \"/usr/lib/python3.7/distutils/command/install.py\", line 589, in run\n        self.run_command('build')\n      File \"/usr/lib/python3.7/distutils/cmd.py\", line 313, in run_command\n        self.distribution.run_command(command)\n      File \"/usr/lib/python3.7/distutils/dist.py\", line 985, in run_command\n        cmd_obj.run()\n      File \"/usr/lib/python3.7/distutils/command/build.py\", line 135, in run\n        self.run_command(cmd_name)\n      File \"/usr/lib/python3.7/distutils/cmd.py\", line 313, in run_command\n        self.distribution.run_command(command)\n      File \"/usr/lib/python3.7/distutils/dist.py\", line 985, in run_command\n        cmd_obj.run()\n      File \"/usr/lib/python3.7/distutils/command/build_ext.py\", line 340, in run\n        self.build_extensions()\n      File \"/tmp/pip-install-rv3sln_0/Pillow/setup.py\", line 687, in build_extensions\n        raise RequiredDependencyException(f)\n    __main__.RequiredDependencyException: jpeg\n    \n    During handling of the above exception, another exception occurred:\n    \n    Traceback (most recent call last):\n      File \"<string>\", line 1, in <module>\n      File \"/tmp/pip-install-rv3sln_0/Pillow/setup.py\", line 907, in <module>\n        raise RequiredDependencyException(msg)\n    __main__.RequiredDependencyException:\n    \n    The headers or library files could not be found for jpeg,\n    a required dependency when compiling Pillow from source.\n    \n    Please see the install instructions at:\n       https://pillow.readthedocs.io/en/latest/installation.html\n    \n    \n    \n    ----------------------------------------\n\n:stderr: Command \"/library/lokole/venv/bin/python3 -u -c \"import setuptools, tokenize;__file__='/tmp/pip-install-rv3sln_0/Pillow/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\\r\\n', '\\n');f.close();exec(compile(code, __file__, 'exec'))\" install --record /tmp/pip-record-2n26rx7e/install-record.txt --single-version-externally-managed --compile --install-headers /library/lokole/venv/include/site/python3.7/Pillow\" failed with error code 1 in /tmp/pip-install-rv3sln_0/Pillow/\n"}

**Comment by holta** [comment]
fyi @c-w & @aidan-fitz &mdash; with much more context at #2296

(i.e. schools around the world ask for and very much need 32 WiFi connections not just 18, hence the ongoing push from the Raspbian OS to Ubuntu on Raspberry Pi.)

**Comment by jvonau** [comment]
> RequiredDependencyException:\n \n 
The headers or library files could not be found for jpeg,\n 
a required dependency when compiling Pillow from source.

missing libjpeg-dev for the headers if compiling?

**Comment by jvonau** [comment]
Adding libjpeg-dev to the list of packages lets lokole complete the installation on U-20

**Comment by holta** [comment]
Should be solved by @jvonau's PR #2301 -- thanks to everyone who can help with ongoing testing.
