### ISSUE TITLE
Cannot update MySQL root password for localhost root accounts.

### ISSUE THREAD

**Issue by siriuswapnil** [iiab/iiab#2332]
### Hi everyone. I encountered the following error( screenshot) while installing IIAB. Cannot update MySQL root passwords for localhost root accounts. Moreover, on giving command 
`mysql`
It says, :  `access denied : for user`

### Running 
`sudo iiab`
 
for installing IIAB onto Virtualmachine.

### IIAB version : 7.1
<img width="872" alt="VirtualBox_Ubuntu 18 04_09_04_2020_12_01_45" src="https://user-images.githubusercontent.com/41196801/78865203-cb057800-7a5a-11ea-99be-c468b62fb801.png">

**Comment by holta** [comment]
@tim-moody @jvonau do you know what's happening here?  Does this relate to #1714 in any way?

@siriuswapnil can you please try the same thing with the latest daily build of Ubuntu 20.04 LTS?

Ref: #2325 "DB warnings recently began appearing during IIAB install: "did not set no_log for no_password_changes" [caused by Ansible 2.9.6?]"

**Comment by tim-moody** [comment]
Swapni, you need to run the install as root. For some reason sudo doesn't
work with setting the mysql password.

I assume the vm is ubuntu server with nothing installed except sshd.

**Comment by holta** [comment]
@jvonau believes this is indeed a duplicate ticket, the same as #1714.

But let's leave it open for @siriuswapnil to confirm, Thanks!

**Comment by siriuswapnil** [comment]
Yes @holta . I went throught what @tim-moody said. I was also having some issues with my VM. Had to reinstall everything. Thanks for the help.

**Comment by holta** [comment]
Just fyi @siriuswapnil IIAB no longer supports Ubuntu 18.04 as a mainline OS, now that Ubuntu 20.04 has been released.

Apologies!  For more details, please see: https://github.com/iiab/iiab/wiki/IIAB-Platforms
