### ISSUE TITLE
Confusing use of mysql_service between 'os'.yml and computed_vars.yml

### ISSUE THREAD

**Issue by jvonau** [iiab/iiab#234]
Should be handled like apache_config_dir is done, nothing in 1-prep and use os.yml to set the variable to account for differences in the distros.

**Comment by holta** [comment]
@jvonau can you explain this during a live call if poss — or resolve?

**Comment by holta** [comment]
@jvonau plz help bring to a conclusion as IIAB 6.5's feature freeze approaches in 5 days?

Or can we defer this to [IIAB 6.6](https://github.com/iiab/iiab/milestone/3)'s Milestone ?

**Comment by tim-moody** [comment]
and should consider doing mysql the ansible way by removing from aggregates and triggering with meta for roles that need it. install and enable would be True

**Comment by holta** [comment]
Database installation approach extensively discussed during Monday Oct 30 community/team call (http://minutes.iiab.io) and documented with PR #476 "Clarifies MySQL & PostgreSQL in local_vars.yml & default_vars.yml"

Plz re-open as nec for IIAB 6.6 as our Feature Freeze has now passed.

**Comment by holta** [comment]
@jvonau asked me to re-open this during today's community/team call (http://minutes.iiab.io) even if this slips to IIAB 6.6 Milestone.

**Comment by holta** [comment]
Moving to [IIAB 6.6](https://github.com/iiab/iiab/milestone/2) milestone as Code Freeze was last Thursday and Feature Freeze 2 weeks ago.

**Comment by holta** [comment]
@tim-moody encouraged us to make this happen (during today's community/team call @ http://minutes.iiab.io) but understands there's no PR so all agreed to wait for the [IIAB 6.6](https://github.com/iiab/iiab/milestone/3) timeframe.

**Comment by holta** [comment]
@jvonau please update or close your tkt, if poss?

Thanks, as [IIAB 6.6](http://download.iiab.io/6.6/) release is now converging!

We can also move this to our [IIAB 6.7 Milestone](https://github.com/iiab/iiab/milestone/4) if you prefer.

**Comment by holta** [comment]
@jvonau if this is important for IIAB 6.7 (release target December) please definitely shout.

**Comment by holta** [comment]
Talked with @jvonau: this should just require PR #1279 (on fresh install) which looks like it's just about good to go.

Some chance fl.yml (file layout) might need to run in 1-prep instead of 2-common (testing will confirm!)

**Comment by holta** [comment]
Can I close this tkt now that computed_vars.yml no longer exists?

FYI `mysql_service:` values were just fixed across many of the [OS].yml files in [/opt/iiab/iiab/vars](https://github.com/iiab/iiab/tree/master/vars) thanks to yesterday's PR https://github.com/iiab/iiab/pull/1348

**Comment by holta** [comment]
Closed during our community/team call (http://minutes.iiab.io) as the consensus is:
- this is resolved by PR #1348
- computed_vars.yml lives on within by Stage 0
