### ISSUE TITLE
Test Kolibri 0.13.3 when it's released in coming days?

### ISSUE THREAD

**Issue by holta** [iiab/iiab#2423]
See https://github.com/learningequality/kolibri/milestone/51 and #1532

**Comment by benjaoming** [comment]
> 0.13.3b1 has been released to pypi (https://pypi.org/project/kolibri/0.13.3b1/) and kolibri-proposed PPA (https://launchpad.net/~learningequality/+archive/ubuntu/kolibri-proposed)

**Comment by holta** [comment]
Kolibri 0.13.3 looks good so far.
