### ISSUE TITLE
http://box/osm-vector-maps/installer/ often (1) offers each Map Pack twice (2) shows no Map Packs at all (with Firefox especially)

### ISSUE THREAD

**Issue by holta** [iiab/iiab#2496]
@jvonau showed me this is reproducible almost every time in Firefox, after cookies are deleted &mdash; i.e. what appears on the left side of http://box/osm-vector-maps/installer/ under "Select One at a Time".

If a 2nd tab is quickly opened, also with URL http://box/osm-vector-maps/installer/ ...this also tends to show each available Map Pack twice.

If a 3rd tab (and any additional tabs, also with URL http://box/osm-vector-maps/installer/) are opened, they usually fail to show _any_ available Map Packs :/  (In contrast, these 3rd-4th-and-additional tabs tend to work properly in the Chrome browser.)

CLARIFS:

(1) The 1st tab (after Firefox cookies are deleted) sometimes properly shows each of the 12 Map Packs exactly once each (as it should!) but this seems to be rare :/

(2) These problems with http://box/osm-vector-maps/installer/ were confirmed in Firefox-on-Linux and Firefox-on-Windows.  Unclear why these problems appear much worse in Firefox than Chrome.

**Comment by holta** [comment]
Is this possibly solved by PR https://github.com/iiab/maps/pull/27 ?  ("7.2 maps...fix a race condition in getting map-catalog.json")

**Comment by georgejhunt** [comment]
Thanks for your help. It's much easier to fix something when it fails all
the time, so testing it on firefox was the breakthrough.

You will need to run "./runroles osm-vector-maps" to fix a machine that is
already installed once

**Comment by holta** [comment]
Fantastic @georgejhunt if this is likely fixed.

Thanks to @jvonau for noticing the situation with Firefox.
