### ISSUE TITLE
Missing python3-packaging?

### ISSUE THREAD

**Issue by jvonau** [iiab/iiab#2590]
https://gist.github.com/sptankard/1dbe2957abd14b2cd96f783235dbc136 mentions python3-packaging having to be installed by hand,
iiab/iiab-factory#154 contains further discussion mentions #2532

**Comment by holta** [comment]
Thanks especially to @sptankard

Who also asked whether Admin Console should install apt package `python3-requests` :

iiab/iiab-admin-console#354

**Comment by jvonau** [comment]
#2532 hidden in milestone 8

**Comment by holta** [comment]
Should be solved now by PR #2591.

But if there's any reason to re-open this, by all means.
