### ISSUE TITLE
Re-scrape 'Scale of the Universe' now that it's JavaScript instead of .swf ?

### ISSUE THREAD

**Issue by holta** [iiab/iiab#2628]
@darkenvy @floydianslips can you take a quick look as to how easy/hard it is to scrape http://htwins.net/scale2/ ("sotu 2.1") for offline use?

Their rewrite (JavaScript instead of Flash?) appears to now work in all browsers, which is great as this single-page interactive visualization is urgently demanded/desired by most all countries/schools worldwide.

As background, its famous .swf (Flash-based) predecessor is available here: http://oer2go.org/viewmod/en-scale-of-universe

This legacy file [Scale-of-the-Universe-2.swf](http://iiab.me/modules/en-scale-of-universe/Scale-of-the-Universe-2.swf) is increasingly not relevant to modern browssers, but if necessary can be seen as part of an IIAB installation here: http://iiab.me/modules/en-scale-of-universe/
<br>
PS the English version would certainly be sufficient for starters.  And if that turns out to be easy, later on the Spanish and French (if not a few other languages) would most certainly also be heavily used too !

**Comment by shanti-bhardwa** [comment]
not clear how I can install JavaScript version?. the .swf fom old version plays fine if you have off-line flash-palyer on your desktop

**Comment by psiie** [comment]
Yea, I will give a shot ripping it. I'm pretty optimistic that it shouldn't be too hard to offline the whole thing.

**Comment by holta** [comment]
@darkenvy & @floydianslips should both get Nobel Prizes, for solving very practical front-end needs faced by people everywhere.

See "Scale of the Universe" halfway down http://iiab.me/jamaica in all 20 languages, that should now work in all modern browsers (no need for Adobe Flash!)

Published for all here: http://d.iiab.io/content/SofU.zip (14.3 MB)

**Comment by holta** [comment]
Another JavaScript/HTML content glitch is here, if anyone has the answer?

"http://box/modules/en-algebra2go/ won't load over WiFi, i.e. when offline (LAN-side of IIAB)" (#2625)

**Comment by holta** [comment]
FYI an Internet-in-a-Box "menu def" [*] for @darkenvy's new scraping of "Scale of the Universe 2.1" is here:
https://github.com/iiab-share/js-menu-files/blob/master/menu-defs/en-scale-of-universe-2.json

[*] A "menu def" is a description and logo, for the main page of any IIAB, as summarized here:
https://github.com/iiab/iiab/wiki/IIAB-Menuing

**Comment by holta** [comment]
IIAB Catalog http://med.iiab.me/catalog/iiab_catalog.json is an "auxiliary" catalog of useful offline Content Packs that Internet-in-a-Box volunteers have helped scrape/repackage and generally make beautiful...to supplement other "offline content Sears Catalogs" like:

- http://oer2go.org (RACHEL)
- http://download.kiwix.org/zims (Kiwix)
- https://catalog.learningequality.org/ (Kolibri)
- Etc!

It gets merged with the OER2Go catalog when that is downloaded, so a user of Admin Console just sees one catalog of modules.

To help push this forward, @tim-moody has published a "reference copy" of @darkenvy's scrape of "sotu 2.1" to help with wider distribution:
http://med.iiab.me/modules/en-scale-of-universe-2/

And I've put a symlink here in case that helps more people find/understand/use Cary Huang & Matthew Martori's great work here:
http://d.iiab.io/content/en-scale-of-universe-2.zip

**Comment by holta** [comment]
This is now available for everyone to install (non-technical IIAB implementers included) using IIAB's Admin Console > Install Content > Get OER2Go(RACHEL) Modules !

Thanks to @tim-moody's:

- https://github.com/iiab/iiab-admin-console/pull/368 "Add new scale of univ to catalog"
- https://github.com/iiab/iiab-admin-console/blob/master/assets/iiab_catalog.json

**Comment by holta** [comment]
BAD NEWS FIRST: http://iiab.me/modules/en-scale-of-universe-2 warns you not to run it on smartphones :/

GOOD NEWS NEXT: if you force your mobile browser to request "Desktop site" [*] then Scale of the Universe 2 **works great,** in landscape mode especially!

[*] e.g. Android's Chrome browser lets you check a box ("Desktop site") in the top right, after clicking on the vertical ellipsis.  Firefox on Android similarly.

**Comment by holta** [comment]
This mobile trick is now documented for all in [en-scale-of-universe-2.json](https://github.com/iiab-share/js-menu-files/blob/master/menu-defs/en-scale-of-universe-2.json#L10) here:

```
  "extra_description": "On a mobile device, use your browser settings (e.g. touch <b>&vellip;</b> in the top-right) to check the box for &quot;Desktop site&quot;.",
```

As visible halfway down the page if you do a hard-reload of http://iiab.me/jamaica

**Comment by psiie** [comment]
Yea, it might be the best solution. The "Desktop Site" button expands the viewport in the browser. 
Once you get into the app, everything is drawn in canvas. So it's not easy to make modifications to make it friendly. I see why they made an iOS application.

Good solution @holta for now :)

**Comment by matttt** [comment]
@holta @darkenvy 

Hey all! I found this thread by chance when I happened to look up my name for other reasons 😅 I built the new version of Scale of the Universe and if there is anything I can do to help, like build a special version that disables the mobile warning or hardcodes a specific language I can definitely do so! This is so freaking cool.

**Comment by tim-moody** [comment]
@matttt any chance it can be straight up html5, css, js and not need a running node app?
