### ISSUE TITLE
Scrape StatPearls [Continuing Medical Education for doctors/physicians/etc]

### ISSUE THREAD

**Issue by tim-moody** [iiab/iiab#2631]
@darkenvy @floydianslips can you have a look at https://statpearls.com/articlelibrary/. I already have all the 8K articles, but I'd like a home page (index.html) along the lines of this page, but without all the extensive header and footer, just the logo and a title.  The article list is in https://statpearls.com/articlelibrary/partialpublishedarticles/ and I also have a json file.

Articles once converted will look something like http://iiab.me/modules/en-statpearls/articles/article-16989.html.

**Comment by holta** [comment]
@tim-moody created statpearls_en_all_maxi_2020-11.zim (2.5 GB, 8033 articles, 4181 media) viewable here:

http://iiab.me/kiwix/statpearls_en_all_maxi_2020-11/
