### ISSUE TITLE
can we deprecate roles/rachel ? any others?

### ISSUE THREAD

**Issue by holta** [iiab/iiab#272]
@tim-moody do you have an opinion?

**Comment by tim-moody** [comment]
yes

our modules are not just rachel any more, so we should create /library/www/html/modules where we create docroot and eliminate references to rachel_doc_root in fl.yml (but keep for future reference in default vars)

**Comment by holta** [comment]
Ref #199 (clean default_vars.yml & deprecate ~12 playbooks to roles/deprecated)

**Comment by holta** [comment]
Ref #295 (add modules directory)

**Comment by holta** [comment]
It was decided during our call (http://minutes.iiab.io) to leave bitrotting playbooks in /opt/iiab/iiab/roles for now.

The maintainer (and all of us) have a strong responsibility to communicate this to new implementers of course _(which ones are *solid* and which are...shall we say depreciating!!!)_
