### ISSUE TITLE
Admin Console GET-EXTDEV-INFO fails if kiwix not installed

### ISSUE THREAD

**Issue by holta** [iiab/iiab#2720]
See:

- https://github.com/iiab/iiab-admin-console/issues/388 "GET-EXTDEV-INFO failed when kiwix is not installed"
- PR https://github.com/iiab/iiab-admin-console/pull/389 "remove kiwix test"
- PR https://github.com/iiab/iiab-admin-console/pull/390 "if kiwix not installed"

**Comment by tim-moody** [comment]
I thought there was consensus that kiwix will always be installed, and Admin Console expects this to be true.

**Comment by holta** [comment]
We can set the policy either way.

(Either way things can occasionally get messy!?)

PS I've run into a few communities and NGO's that want IIAB without Kiwix, but these are very rare.

**Comment by holta** [comment]
I closed this by accident.

I don't know if Admin Console should require Kiwix or not.

Aside: Certainly kiwix-serve changes quite dramatically approximately annually, but that's a reality that we live with.

**Comment by holta** [comment]
Good enough as is.  Yes there are a few IIAB implementers who do not want Kiwix (e.g. Kolibri-only shops) but more generally Kiwix is a soft requirement for those who want to install IIAB.

Certainly IIAB implementers who want to use Admin Console should install Kiwix, as changing Admin Console to be able to work without Kiwix is too much work at this time.
