### ISSUE TITLE
Lokole install blows up

### ISSUE THREAD

**Issue by jvonau** [iiab/iiab#2756]
### Steps to reproduce the problem:
lokole_install True
### IIAB version, OS version, hardware details:
master Ubuntu-21.04 rpi4 
>exception occurred during task execution. 
To see the full traceback, use -vvv. The error was: UnicodeEncodeError: 'ascii' codec can't encode character '\u2014' in position 177: ordinal not in range(128) failed: [127.0.0.1] (item={'option': 'description', 'value': '"Lokole is an email service that works offline, for rural communities.  With a 3G/4G modem, you can arrange to batch-upload / batch-download emails once per night — for almost no cost at all — depending on mobile data plans in your country."'}) => {"ansible_loop_var": "item", "changed": false, "item": {"option": "description", "value": "\"Lokole is an email service that works offline, for rural communities.  With a 3G/4G modem, you can arrange to batch-upload / batch-download emails once per night — for almost no cost at all — depending on mobile data plans in your country.\""}, "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1619563516.5549765-137083-5628021869192/AnsiballZ_ini_file.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1619563516.5549765-137083-5628021869192/AnsiballZ_ini_file.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1619563516.5549765-137083-5628021869192/AnsiballZ_ini_file.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.community.general.plugins.modules.ini_file', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.9/runpy.py\", line 210, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_ini_file_payload_86prp13_/ansible_ini_file_payload.zip/ansible_collections/community/general/plugins/modules/ini_file.py\", line 336, in <module>\n  File \"/tmp/ansible_ini_file_payload_86prp13_/ansible_ini_file_payload.zip/ansible_collections/community/general/plugins/modules/ini_file.py\", line 316, in main\n  File \"/tmp/ansible_ini_file_payload_86prp13_/ansible_ini_file_payload.zip/ansible_collections/community/general/plugins/modules/ini_file.py\", line 271, in do_ini\nUnicodeEncodeError: 'ascii' codec can't encode character '\\u2014' in position 177: ordinal not in range(128)\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

https://github.com/iiab/iiab/blob/master/roles/lokole/tasks/main.yml#L76-L77, making the string simpler got around the issue.

**Comment by holta** [comment]
Somehow the EM DASH character ("\u2014") is no longer allowed here.

Presumably as a newer version of Ansible or OS starts enforcing stricter requirements going forward.

Good to know.
