### ISSUE TITLE
usbmount creates symlink in the root of the mounted device that persists after unmounting

### ISSUE THREAD

**Issue by jvonau** [iiab/iiab#2758]
and usb1 -> /media/usb1 can still appear in the mounted device

_Originally posted by @tim-moody in https://github.com/iiab/iiab/issues/2282#issuecomment-603999619_

**Comment by jvonau** [comment]
Created by /etc/usbmount/mount.d/00_create_model_symlink, supplied by the usbmount package.

**Comment by jvonau** [comment]
https://github.com/iiab/iiab/pull/2282#issuecomment-604426628

**Comment by holta** [comment]
Anyone feel free to revise the ticket subject line, if that helps clarify the core question(s) ?!

**Comment by jvonau** [comment]
[unmount could be cleaner?]  Think the unmounting is fine, the issue is none of the /etc/usbmount/unmount.d/ scripts are triggered anymore needing workarounds like #2326, so the link is never cleaned up. Just remove the mount.d/00_create_model_symlink action and the problem link is not created to begin with, there would be nothing to clean up upon unmounting.

**Comment by holta** [comment]
Should be resolved by PR #2760.

(Or re-open as nec!)
