### ISSUE TITLE
NGINX advice on making http://box/cups and http://box/print work?

### ISSUE THREAD

**Issue by holta** [iiab/iiab#2766]
If a volunteer can be found to help here, @georgejhunt suggests this is a pretty easy job!  If one follows https://anthe.studio/blog/en/cups-nginx-reverse-proxy ?

Background:

- PR #2761 "cups - drop apache"
- https://github.com/iiab/iiab/tree/master/roles/cups
- https://github.com/iiab/iiab/tree/master/roles/nginx (README.md)

Ref:

- #2762 "Notes : Stalled progress on NGINX front"

**Comment by deldesir** [comment]
Good. I'll do it.

**Comment by deldesir** [comment]
See https://github.com/iiab/iiab/pull/2775.

**Comment by holta** [comment]
> See #2775.

Let's finalize this one way or another.  Thanks @deldesir

**Comment by holta** [comment]
Good Enough for now?

http://box/print and http://box/print/ now work in all cases, thanks to PR #2858 inspired by PR #2775.

(@deldesir thanks for pushing to make this to happen.  Please re-open this ticket — or any other — to push this or any similar further!)
