### ISSUE TITLE
php-stem for PHP 7.4 (e.g. Raspberry Pi OS 11, Debian 11, Ubuntu 21.04) and PHP 8.0 (e.g. Ubuntu 21.10) -> PHP 8.1 (e.g. Ubuntu 22.04) -> PHP 8.2 Dec 2022 [for wikiHow in Spanish]

### ISSUE THREAD

**Issue by holta** [iiab/iiab#2864]
As discussed on this week's http://minutes.iiab.io call-

We'll work on adding these soon (e.g. when Raspberry Pi OS 11 is released in not so many days) which will need this or similar:

- http://d.iiab.io/packages/php7.4-stem.rpi.tar

We should probably also compile php-stem files for PHP 8.0 (released November 2020) as IIAB has been well-tested on Ubuntu 21.10 daily builds over the past month:

- #2814
- #2818

(Creating these should be easier than in the past thanks to https://github.com/iiab/php-stem that @tim-moody set up recently!)

Recap: http://oer2go.org/viewmod/es-wikihow needs this for full-text searching.

Refs:

- #2797
- PR #2799
- #2835
- PR #2837
- https://github.com/iiab/php-stem/issues/2

**Comment by jvonau** [comment]
How about using the pinned issue for FAQ type subjects in place of frivolous issues that are targeted at a single fix of a 5 year old php website scraping. Use this real estate wisely.

**Comment by holta** [comment]
@deldesir we should help @tim-moody who is interested in solving this more methodically in coming days, for PHP 7.4 and 8.0 initially, and then for PHP 8.1 sometime later, after that is released [2021-11-25](https://stitcher.io/blog/new-in-php-81).

For PHP 8.0, Ubuntu 21.10 (released 5 days ago) should be sufficient.

For PHP 7.4, we can use Debian 11 "Bullseye" on a VM.  But let's also upgrade Raspberry Pi OS from PHP 7.3 to 7.4 &mdash; by manually changing *both* these Raspberry Pi OS files from `buster` to `bullseye`:

- `/etc/apt/sources.list`
- `/etc/apt/sources.list.d/raspi.list`

And then upgrading its ~500 OS packages by running something like:

```
apt update
apt -y dist-upgrade
reboot
apt -y autoremove
```

This is to simulate and test the ~6 new Raspberry Pi OS 11 "Bullseye" installers arriving very shortly in coming weeks &mdash; to replace the 6 older Raspberry Pi OS 10 "Buster" installers below: 

(So we should pick a few of these 6 OS's below to test carefully, and confirm it all works!  i.e. testing that the search box really works, after installing the 12.6G [wikiHow in Spanish](https://rachel.worldpossible.org/viewmod/es-wikihow))

- 32-bit ["with desktop and recommended software"](https://downloads.raspberrypi.org/raspios_full_armhf/images/raspios_full_armhf-2021-05-28/) a.k.a. FULL (2.8G)
- 32-bit ["with desktop"](https://downloads.raspberrypi.org/raspios_armhf/images/raspios_armhf-2021-05-28/) (1.2G)
- 32-bit ["Lite"](https://downloads.raspberrypi.org/raspios_lite_armhf/images/raspios_lite_armhf-2021-05-28/) (444M)
- 64-bit ["with desktop"](https://downloads.raspberrypi.org/raspios_arm64/images/) (1.0G)
- 64-bit ["Lite"](https://downloads.raspberrypi.org/raspios_lite_arm64/images/) (387M)
- for PC ["Debian Buster with Raspberry Pi Desktop"](https://downloads.raspberrypi.org/rpd_x86/images/) (2.9G)

Refs:

- #2749
- #2818
- #2820

**Comment by holta** [comment]
Possibly relevant:

- https://library.kiwix.org/wikihow_en_maxi
- https://download.kiwix.org/zim/wikihow/

Noting that the above 19 ZIM files ("wikiHow in all 19 languages") cannot yet be used with search & suggestions &mdash; until kiwix-tools is released "later this year" with a new version of kiwix-serve.

Which is awaiting resolution of these 4 libkiwix 10.0.0 tickets:

- https://github.com/kiwix/libkiwix/milestone/1

Related:

- #2965

**Comment by holta** [comment]
Almost a year after its Nov 2020 release and slow adoption, PHP 8.x is likely to grow dramatically over the coming year:

> "78% of the web powered by PHP, 1% on PHP 8"
>
> "PHP 7 loses active support next month and loses security support in one year" (Extended support for PHP 7.4 will end on November 28, 2022)
>
> "after November 28, 2022, Microsoft will no longer support PHP"
>
> https://haydenjames.io/78-of-the-web-powered-by-php-1-on-php-8/

**Comment by deldesir** [comment]
I am experiencing compile errors when trying to build php-stem from source (right at the "make" step). Command pecl install <stem archive> returns same error. The test was done with PHP 8.0.

```
  311 | ZEND_API const char *get_active_function_name(void);
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~
/tmp/pear/temp/stem/stem.c:335:9: warning: implicit declaration of function ‘php_strtolower’; did you mean ‘php_strtok_r’? [-Wimplicit-function-declaration]
  335 |         php_strtolower(z->p, arglen);
      |         ^~~~~~~~~~~~~~
      |         php_strtok_r
/tmp/pear/temp/stem/stem.c:339:37: error: macro "RETVAL_STRINGL" passed 3 arguments, but takes just 2
  339 |         RETVAL_STRINGL(z->p, z->l, 1);
      |                                     ^
In file included from /usr/include/php/20200930/main/php.h:36,
                 from /tmp/pear/temp/stem/stem.c:16:
/usr/include/php/20200930/Zend/zend_API.h:718: note: macro "RETVAL_STRINGL" defined here
  718 | #define RETVAL_STRINGL(s, l)                    ZVAL_STRINGL(return_value, s, l)
      |
/tmp/pear/temp/stem/stem.c:339:9: error: ‘RETVAL_STRINGL’ undeclared (first use in this function)
  339 |         RETVAL_STRINGL(z->p, z->l, 1);
      |         ^~~~~~~~~~~~~~
/tmp/pear/temp/stem/stem.c: In function ‘zif_stem_enabled’:
/tmp/pear/temp/stem/stem.c:365:51: error: expected ‘)’ before ‘TSRMLS_CC’
  365 |         if (zend_parse_parameters(ZEND_NUM_ARGS() TSRMLS_CC, "l", &lang) == FAILURE) {
      |                                  ~                ^~~~~~~~~
/tmp/pear/temp/stem/stem.c:365:13: error: too few arguments to function ‘zend_parse_parameters’
  365 |         if (zend_parse_parameters(ZEND_NUM_ARGS() TSRMLS_CC, "l", &lang) == FAILURE) {
      |             ^~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/php/20200930/main/php.h:36,
                 from /tmp/pear/temp/stem/stem.c:16:
/usr/include/php/20200930/Zend/zend_API.h:304:22: note: declared here
  304 | ZEND_API zend_result zend_parse_parameters(uint32_t num_args, const char *type_spec, ...);
      |                      ^~~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:208: stem.lo] Error 1
ERROR: `make' failed

```

**Comment by holta** [comment]
FYI @tim-moody:

@deldesir isn't sure how to proceed with PHP 8.0 above &mdash; so he'll try this out on PHP 7.4 (likely using Debian 11 Bullseye VM's) &mdash; and might your use suggestions on how to proceed at that point.

Tangentially related:

- #2749
- #2818

**Comment by tim-moody** [comment]
Not sure if a function signature changed between php 7 and 8, which might require changing the source. Good idea to try 7.4 first or something already known to compile.

**Comment by jvonau** [comment]
Need to build and provide php7.4-stem.rpi.tar now that a 32bit version of php7.4 is installed in RaspiOS bullseye, there are only arm64 and amd64 available to download that are used to support Ubuntu but the arm64 version should support the 64bit version of RaspiOS bullseye as is.

**Comment by holta** [comment]
> Need to build and provide php7.4-stem.rpi.tar now that a 32bit version of php7.4 is installed in RaspiOS bullseye

Yes as the extremely popular <strike>3.2 GB https://rachel.worldpossible.org/viewmod/es-GCF2015</strike> 12.6 GB https://rachel.worldpossible.org/viewmod/es-wikihow will again be searchable across ~600 million Spanish-speakers in ~30 countries.

If https://github.com/iiab/php-stem can be made to work without compile errors ??

ASIDE:

1) The 20GB http://download.kiwix.org/zim/wikihow/wikihow_es_maxi_2021-10.zim bodes well but is too big for many schools :/

2) Likewise @tim-moody's http://iiab.me/modules/es-gcf_learn_2021/edu.gcfglobal.org/es/topics/ bodes extremely well.

   But it's not searchable last I checked (hopefully Tim can update us if that's changed?)

   FYI this es-gcf_learn_2021 appears to be about 15GB according to: https://github.com/iiab-share/iiab-content/blob/main/catalogs/iiab-module-cat.json#L724 so a subsetting strategy...might also make a lot of sense.

**Comment by holta** [comment]
PHP 7.4 is finally taken care of!  Thanks to:

- PR iiab/php-stem#3
- PR #3080
- PR #3081 
- PR #3082

_Compiling the [3 stem.so files](https://github.com/iiab/php-stem/tree/main/so) for PHP 8.0 and/or 8.1 might be harder ?_

In any case, that question can be addressed if they are needed after 2022-04-21, when Ubuntu 22.04 LTS ("Jammy Jellyfish") is released.

**Comment by holta** [comment]
FYI there was speculation during Dec 30th's http://minutes.iiab.io call that [stem-php might not be that hard to compile](https://github.com/iiab/php-stem) for PHP 8.0 and/or 8.1 after all?

So we'll try again in a few months — by/around the time Ubuntu 22.04 (with PHP 8.1) is released on 2022-04-21.

**Comment by holta** [comment]
Just FYI PHP 8.2 is released.

We'll monitor the consequences as OS's like Debian 12 "Bookworm" and/or Ubuntu 23.04 "Lunar Lobster" begin to incorporate this.

**Comment by holta** [comment]
FYI new IIAB installs now auto-detect the OS's PHP version (whether or not PHP is installed) by parsing `apt list php` :

- PR #3439

**Comment by holta** [comment]
Progress here, thanks to @randytate:

- PR iiab/php-stem#4

**Comment by holta** [comment]
Huge thanks to @randytate and @tim-moody who brought us this far.

PHP 7.4 and 8.1 are the most important versions if we support this, as Ubuntu-like OS's bypassed PHP 8.0 entirely.

Then PHP 8.2 (released earlier this month) may well dominate in a year from now, if in the end that's what Debian 12 Bookworm and Raspberry Pi OS Bookworm finalize upon in Q1 or Q2 of 2023.

**Comment by holta** [comment]
> PHP 7.4 and 8.1 are the most important versions if we support this

Just FYI PHP 7.4 was end-of-life'd 2 months ago in November 2022 ("there will be no bug or security fixes made to any of the PHP 7 versions") as mentioned here:

- #3467

PRAGMATICALLY: RasPiOS Bullseye will of course continue to be very popular with PHP 7.4 for a few more months, even despite :smile:

**Comment by jvonau** [comment]
@holta @tim-moody @avni Given this entire php-stem issue involves one old wikihow Spanish OER module have you considered giving the latest [zim](https://mirrors.dotsrc.org/kiwix/zim/wikihow/?C=M&O=D) version a whirl? Going with the zim file, should it work, would negate the need for maintaining php-stem going forward.

**Comment by holta** [comment]
Indeed a good idea:

While wikiHow ZIM files had many serious problems in 2022, hopefully these problems are fully going away in 2023.

**Comment by holta** [comment]
Nextcloud has moved away from the EOL'd PHP 7.4 and we should soon too...

(Especially now that wikiHow ZIM files are likely good enough going forward.)
