### ISSUE TITLE
Validate just-released Node-RED 2.0.0+ ⁠(did dependencies slightly change?)

### ISSUE THREAD

**Issue by holta** [iiab/iiab#2868]
Node-RED 2.0.0 is now part of IIAB, and its dependencies/requirements should be quickly verified here:

- https://nodered.org/blog/2021/07/20/version-2-0-released
- https://github.com/node-red/node-red/blob/master/CHANGELOG.md
- https://nodered.org/docs/

To check that everything looks solid here: https://github.com/iiab/iiab/tree/master/roles/nodered !

Refs:

- PR #2833
- PR #2840
- #2842
- PR #2843

**Comment by holta** [comment]
Node-RED 2.0.1 is now released:
https://github.com/node-red/node-red/releases/tag/2.0.1

**Comment by holta** [comment]
All seems to work.

But a more formal checkup into Node-RED's official/latest requirements would also be wise in the coming year.

**Comment by jvonau** [comment]
status?

**Comment by holta** [comment]
Node-RED is probably working on many more OS's now (?) but should be verified on Ubuntu 22.04 pre-releases in coming days/weeks.

(Ubuntu 21.10 is no longer the priority...)

**Comment by holta** [comment]
Seems good...with Node-RED 3.0.0 landing shortly!
