### ISSUE TITLE
Unable to log in to http://box/admin/ with user iiab-admin password set during installation or default password

### ISSUE THREAD

**Issue by boholder** [iiab/iiab#2985]
### Expected behavior and actual behavior:

Use the 1-line installer to install. 
The installation process prompted for a user password for `iiab-admin`, so I entered a custom password. 

After a successful installation and reboot, I logged into the administration interface on the host using http://box/admin, 
but both the custom password entered during installation and the default password (`g0adm1n`) showed `invalid login` (username as `iiab-admin`).

After searched for issues, I found that it seems that the password uses the password of the unix user system directly, so I tried to change the password of the user `iiab-admin` on the system (use `passwd` command) and reboot, but it still did not work.

Any suggestions, or how I can change that password directly using the command line?

(BTW, the installation process was rocky (due to poor internet connection and ISP active blocking policies), I manually configured various software images and proxies, but I kept running the single line install script over and over again, so maybe I didn't screwed up iiab itself?)

### Steps to reproduce the problem:

N/A

### IIAB version, OS version, hardware details:

IIAB: 7.2, Debian 11 amd64 (bullseye) (in virtualbox), host is Windows10

### Please run the `iiab-diagnostics` command, to generate a URL summarizing your IIAB configuration, for volunteers seeking to help you: (Include that short URL here, Thanks!)

http://sprunge.us/jLQuPl

**Comment by holta** [comment]
Thanks @boholder for reporting this!

Admin Console does not support Debian 11 Bullseye's default password hashing scheme (yescrypt) at this time, as used to record passwords in `/etc/shadow`

As a temporary workaround, can you force the Linux user to hash its password using SHA-512 instead of yescrypt ?

Here is one way to do this:

1. Modify `/etc/pam.d/common-password`

   Find the line that looks like:

    ```password [success=1 default=ignore] pam_unix.so obscure yescrypt```
	
    ...and replace `yescrypt` with `sha512`

2. Change the password for user `iiab-admin` (or any user that is a member of *group* `iiab-admin`) as explained here:

    - https://github.com/iiab/iiab/tree/master/roles/iiab-admin
    - https://github.com/iiab/iiab-admin-console/blob/master/Authentication.md

3. OPTIONAL: Verify its password is hashed using SHA-512 instead of yescrypt in `/etc/shadow`

4. Log in to Admin Console

Apologies!  This will be fixed, likely soon in coming weeks.

Tangentially:

- https://github.com/iiab/iiab/issues/1501#issuecomment-926831697

**Comment by boholder** [comment]
Yep, thanks for the detailed guide, I solved the problem by changing the password hashing scheme and the password of user `iiab-admin`.
(I was really relieved when I saw that it was a bug with a clear cause, thanks again for your prompt reply.)

**Comment by holta** [comment]
@boholder it's useful to keep this ticket open, to help others track the issue until it's solved, if that's Ok!

**Comment by holta** [comment]
@boholder & @tim-moody:

An interim fix is here:

- https://github.com/iiab/iiab-admin-console/pull/428

**Comment by holta** [comment]
Thanks @boholder & @tim-moody for helping to fix this for many others, Done!

(This PR / patch below is now tested quite carefully, and merged...)

- https://github.com/iiab/iiab-admin-console/pull/428

**Comment by portna** [comment]
I'm having the same difficulty described here, but with Ubuntu and in 2026. Any advice would be greatly appreciated. I cannot log into admin using default credentials. I tried changing the password on the console. It works when logging in at the computer, but not on the browser. Thanks.

**Comment by holta** [comment]
Hi @portna

1. Would you be able to send the URL resulting from... ?

   ```
   sudo iiab-diagnostics
   ```

2. And also any screenshots or photos if possible?

(Thanks if possible, to help us understand what you're facing!!)

**Comment by portna** [comment]
Yes! Thanks for your prompt reply. https://paste.centos.org/view/0df9fb9e

**Comment by portna** [comment]
<img width="623" height="455" alt="Image" src="https://github.com/user-attachments/assets/caa564a6-6b8c-4b9e-a037-98e359ebb7cc" />
