### ISSUE TITLE
Not able to access Azuracast though Web

### ISSUE THREAD

**Issue by rickgurmet** [iiab/iiab#2991]
### Expected behavior and actual behavior:

Azuracast is working within the server when accessed through the server using (lynx localhost:10080) but when I access the same on a browser using the URL http://box.lan:10080 it doesn't work.

### IIAB version, OS version, hardware details:
IIAB version: Cloned the version as of 15-Sep-2021
Hardware: Intel NUC i3, 10th Gen
OS version: Ubuntu 21.04

### Please run the `iiab-diagnostics` command, to generate a URL summarizing your IIAB configuration, for volunteers seeking to help you: (Include that short URL here, Thanks!)

http://sprunge.us/rI2zR9

**Comment by holta** [comment]
@m-anish are you familiar with this issue, or do you understand it?

**Comment by holta** [comment]
@rickgurmet it's very important that the `sprunge.us` URL be included, that is output when you run `iiab-diagnostics` on the particular machine where you are experiencing this AzuraCast problem.

Can you please reply with that?

Thanks!

**Comment by rickgurmet** [comment]
I have updated it. 
Here is the sprunge.us URL http://sprunge.us/rI2zR9

**Comment by jvonau** [comment]
#2739 #2865 #2943 #2946

**Comment by jvonau** [comment]
0871592ed61704f9cb95048bd6ebf8760ebdf6be

**Comment by holta** [comment]
Just FYI the problem occurs with all browsers that @rickgurmet tried.

He just sent me this screenshot from Chrome:

![image](https://user-images.githubusercontent.com/2458907/184671247-067b176d-ff94-4b9e-9ca6-e8b433476832.png)

**Comment by jvonau** [comment]
client side [issue](https://www.google.com/search?q=err_unsafe_port) 
https://www.youtube.com/watch?v=rfKoYw4UIMY

**Comment by holta** [comment]
Interesting that browsers now ban port 10080, e.g. with the ERR_UNSAFE_PORT error message:

Firefox's `gBadPortList` appears to include these 81 values:
https://hg.mozilla.org/mozilla-central/file/tip/netwerk/base/nsIOService.cpp#l106

Chrome's equivalent `kRestrictedPorts` list:
https://superuser.com/questions/188058/which-ports-are-considered-unsafe-by-chrome/188070#188070
https://chromium.googlesource.com/chromium/src.git/+/refs/heads/master/net/base/port_util.cc#23

A more "official" list of blocked ports appears to be:
https://fetch.spec.whatwg.org/#port-blocking

**Comment by holta** [comment]
Appears solved by:

- PR #2946

Thanks @m-anish, @rickgurmet & @jvonau!
