### ISSUE TITLE
Test ansible-core 2.12 pre-releases

### ISSUE THREAD

**Issue by holta** [iiab/iiab#2996]
ansible-core 2.12 **requires Python 3.8+** so do not try this on Raspberry Pi OS 10 (Buster).

ansible-core 2.12 final release ETA is [2021-11-08](https://docs.ansible.com/ansible-core/devel/roadmap/ROADMAP_2_12.html#expected) &mdash; but you can try out their pre-releases (e.g. their Beta release from 2021-09-27) with IIAB as follows:

1. apt install python3-pip
2. [sudo pip install ansible-core==2.12.0b1](https://pypi.org/project/ansible-core/#history) _[2.12.0b2 released 2021-10-11, 2.12.0rc1 released 2021-10-18]_
3. And then [install IIAB](https://download.iiab.io/), that should be it!  But if you want to be 100% sure Ansible doesn't revert from 2.12.0 Beta 1 back to 2.11.5 etc, you can comment out [Line 171 of /opt/iiab/iiab/scripts/ansible](https://github.com/iiab/iiab/blob/master/scripts/ansible#L171)

Background:

- http://FAQ.IIAB.IO -> "7 What OS should I use?"
- https://github.com/iiab/iiab/wiki/IIAB-Platforms

Refs:

- #2749
- #2818
- #2820

**Comment by holta** [comment]
@deldesir can you try installing ansible-core 2.12.0b2 (as explained [above](https://github.com/iiab/iiab/issues/2996#issue-1021417105)) before installing IIAB in coming days, e.g. on Ubuntu 21.10 and/or other OS's?

(Obviously this will not work on Raspberry Pi OS 10 / Buster, but that's ok as Raspberry Pi OS 11 / Bullseye should finally appear to replace it, very shortly in coming weeks!)

**Comment by holta** [comment]
Really great news that ansible-core 2.12 Beta 2 just works, without many warnings at all it appears:

- https://github.com/iiab/iiab/issues/2818#issuecomment-945009787

@deldesir can you confirm that ansible-core 2.12 doesn't generate too many new/red warnings, as compared to 2.11?

(With 2.12's final release being only "3 weeks away" ETA Monday Nov 8!)

**Comment by deldesir** [comment]
Tests went ok on :
RPI 4 with Ubuntu 21.10 (Desktop): http://sprunge.us/yuWi4Y
RPI 4 with Ubuntu 21.10 (Server): http://sprunge.us/VPfqFH
VM with Ubuntu 21.10 (Desktop): http://sprunge.us/dfFLF2
VM with Ubuntu 21.10 (Server):
http://sprunge.us/VKkTHJ 

Only this deprecation warning from the logs of the last two VMs above:

[DEPRECATION WARNING]: "include" is deprecated, use include_tasks/import_tasks/import_playbook instead. This feature will be removed in version 2.16. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg. 2021-10-16 16:01:30,809 p=11929 u=root n=ansible

**Comment by holta** [comment]
> Only this deprecation warning from the logs of the last two VMs above:
> 
> [DEPRECATION WARNING]: "include" is deprecated, use include_tasks/import_tasks/import_playbook instead. This feature will be removed in version 2.16. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg. 2021-10-16 16:01:30,809 p=11929 u=root n=ansible

Thanks @deldesir:

Where does IIAB need fixes to prepare for ansible-core 2.16 ?

Do you have time to create this PR?

**Comment by deldesir** [comment]
Yes PR is done.
https://github.com/iiab/iiab/pull/2998

**Comment by holta** [comment]
@deldesir can you fix https://github.com/iiab/iiab/blob/master/roles/pbx/tasks/main.yml#L27 as well, if possible?

```
root@box:/opt/iiab/iiab# grep -rn include:
roles/pbx/tasks/main.yml:27:  include: chan_dongle.yml
```

**Comment by holta** [comment]
Many thanks to @deldesir:

IIAB is now in great shape in preparation for the release of ansible-core 2.12 expected on Nov 8th in 3 weeks from today!

**Comment by holta** [comment]
It appears @deldesir has also lightly tested 2.12.0rc1 released 6 days ago 2021-10-18.

Recap: ansible-core 2.12 is expected to be released in just over 2 weeks, on 2021-11-08.

**Comment by holta** [comment]
ansible-core 2.12 worked great to install IIAB 7.2 (pre-release) onto the new Raspberry Pi OS 'Lite' and 'with desktop' on RPi 4.

Thanks @deldesir and @jvonau who helped make this possible over recent months!

Finally, more functionality/community testing could be definitely be helpful here in coming days, to be sure:

- #2820
