### ISSUE TITLE
Enhance [and test!] roles/remoteit so it works on RaspiOS Bullseye, Ubuntu, Mint & Debian too [user testing & documentation for remote.it remote support]

### ISSUE THREAD

**Issue by holta** [iiab/iiab#3006]
If you can help, please see:

- https://github.com/iiab/iiab/pull/3005#issuecomment-953502502

**Comment by holta** [comment]
@jvonau has thankfully pointed out that this new [roles/remoteit](https://github.com/iiab/iiab/tree/master/roles/remoteit) also fails on the very-soon-to-be-released Raspberry Pi OS 11 Bullseye:

- https://github.com/iiab/iiab/pull/3005#issuecomment-953505445

In Short: the situation really needs to be cleaned up and verified across [all 4 mainline OS's](https://github.com/iiab/iiab/wiki/IIAB-Platforms) and/or the most common CPU architectures. And hopefully very soon in coming days.

**Comment by holta** [comment]
This #3006 might already be solved a few hours later:

Please test on different OS's & architectures, those who can!

Huge thanks to @jvonau for this PR which is now merged:

- PR #3007

**Comment by holta** [comment]
1) I've changed the title (subject line) of this ticket to make sure our focus going forward is practical and real-world usability testing — across different OS's — thanks to these 3 remote.it PR's now merged:

   - #3003
   - #3005
   - #3007

2) Thanks in advance to everyone who can quickly review our brand new README.md here!

   - https://github.com/iiab/iiab/tree/master/roles/remoteit

cc: @deldesir

**Comment by jvonau** [comment]
Not sure stage1 is the right location for this new role as unlike openvpn there is user interaction required to allow the service to function.

**Comment by holta** [comment]
Absolutely it's a complicated question for sure.

Both OpenVPN and remote.it (each installed but disabled by default) can be real lifesavers when an install goes wrong, permitting efficient remote coaching / intervention as needed.

For these kinds of reasons, my preference at the moment is to try to help people to "call 911" from the get-go — so they can quickly enable either remote support option as necessary — e.g. with a phone call to a Linux expert who quickly guides them through enabling/activating either one.
