### ISSUE TITLE
Admin Console -> Quick Pick -> EN School leads to 1 + 4 broken links

### ISSUE THREAD

**Issue by icebox827** [iiab/iiab#3065]
@tim-moody @avni 

After doing these steps on a freshly installed IIAB on a Raspberry Pi 400 : http://10.8.0.30/admin -> Quick Pick -> Install Content -> English speaking School 128G Sampler, @avni and I identified 1 + 4 broken links: 

All the 17 jobs show status SUCCEEDED in http://10.8.0.30/admin -> Utilities -> Display Jobs Status
![2021-12-13 (2)](https://user-images.githubusercontent.com/2903437/145849619-f20b8d92-b071-4a2f-999d-1da264a2408e.png)

1. Clicking on **PhET module** leads to **404 Not Found**
![2021-12-13](https://user-images.githubusercontent.com/2903437/145837022-d7e616c7-0df2-46f4-9531-f101e22ee872.png)

2. Clicking on **Wikispecies, Raspberry Pi Stack Exchange, Chemistry Stack Exchange, and Wiktionary in Simple English** leads to **Undefined Zim in a Menu Definition**
![2021-12-13 (1)](https://user-images.githubusercontent.com/2903437/145837533-2a7b2393-bd7c-472c-a588-f65ee6a6afb7.png)

Can you help me understand where these links are breaking?

[**iiab-diagnostics:**](http://sprunge.us/X4dYBG?en)

**Comment by holta** [comment]
Thanks @icebox827 & @avni for your very hard work over the weekend here!

Related:

- #3062

**Comment by tim-moody** [comment]
I can confirm that the preset has the wrong names for each of the items you mentioned. Do you mind if I use your install to test the changes?

**Comment by icebox827** [comment]
@tim-moody 

Sure! It is a great idea.

**Comment by tim-moody** [comment]
@holta should we change from the html PhET to zim?

**Comment by holta** [comment]
> @holta should we change from the html PhET to zim?

Definitely a good idea.  Yes please do that if possible.

**Comment by tim-moody** [comment]
Having trouble sorting this out. The zim names are wrong as are the menu defs. Not sure if Kiwix changed the names or I just got it wrong. Thought each of the original presets were tested.

**Comment by holta** [comment]
@icebox827 please see:

- PR iiab/iiab-admin-console#441

**Comment by tim-moody** [comment]
@icebox827 I have pulled iiab-admin-console#441, installed it and rerun installing the preset. Please verify.

**Comment by tim-moody** [comment]
#3066 is irrelevant to this issue as it deals with a networking problem, not a preset configuration problem.

**Comment by icebox827** [comment]
> @icebox827 I have pulled iiab-admin-console#441, installed it and rerun installing the preset. Please verify.

Thanks @tim-moody , I will verify.

**Comment by holta** [comment]
> #3066 is irrelevant to this issue.

For sure, #3066 is a security issue about MediaWiki.

The critical larger question however: new and non-experienced but very intelligent persons currently face severe confusion as to which main page content is breaking for which reasons, as they try different **http://box.lan/admin > Install Content > Quick Pick**(s).

The original question asked above was:

> Can you help me understand where these links are breaking?

If order to answer the question pragmatically, for the general public and in the general case, we need to consider both clarifying (and/or auto-validating, and/or including key files within [iiab-diagnostics](https://github.com/iiab/iiab/blob/master/scripts/iiab-diagnostics.README.md) ?) which content links are breaking for what reasons.

As #3062 and #3067 both make clear: some kind of escalation path needs to be articulated here, so regular folks have an increasingly clear path to navigate + extricate themselves efficiently...from these very regular networking problems (and every other kind of content/curatorial glitches!)

So regular persons in all countries with all kinds of networking / content struggles...can quickly understand what recourse they have, and take corrective action...as best we can shine bright lights on these evolving community/curatorial needs moving forward into 2022.

_Not that UX design (writ large!) is easy, Far From It :-)  But certainly: a very central question towards helping everyone help themselves over coming weeks and years~_
