### ISSUE TITLE
For Discussion: Nextcloud 'news' is 64-bit only?

### ISSUE THREAD

**Issue by jvonau** [iiab/iiab#3069]
https://github.com/nextcloud/server/issues/30169
https://github.com/nextcloud/server/issues/28926
https://github.com/nextcloud/nextcloudpi/issues/1318
https://github.com/nextcloud/news/issues/1320

**Comment by jvonau** [comment]
The user base on 32bit RaspiOS might run into [this](https://github.com/nextcloud/news/issues/1423) at some point post-install in the field.

**Comment by jvonau** [comment]
https://github.com/nextcloud/server/issues/27797
https://help.nextcloud.com/t/howto-install-nextcloud-20-on-ubuntu-20-04-1-the-classic-way-wiki/98755/42, good overall read and hints.

**Comment by holta** [comment]
Can we close this ticket?

Especially now that 64-bit Raspberry Pi OS has proved very solid[*] over the past 3-4 months.

[*] And "48% faster" according to extensive tests run by Phoronix.

**Comment by jvonau** [comment]
Not that we install any of the plugins, but there should be a warning to not enable the 'news' plugin post install. Have you documented nextcloud's 'news' issue on 32 bit RaspiOS somewhere? If you have the warning in place feel free to close this issue.
