### ISSUE TITLE
DNS Errors with box/wordpress (box’s DNS  could not be found. Diagnosing the problem.) and box/moodle (DNS_PROBE_FINISHED_NXDOMAIN).  Both  fail to connect. 

### ISSUE THREAD

**Issue by shanti-bhardwa** [iiab/iiab#3071]
I have IIAB 7.2 Installed on Linux Mint 20.2 on a DELL laptop. It is wired with Ethernet to a TP-Link Router  configured as Local Access Point  with DHCP Server . The router is NOT connected to the Internet. It provides the local LAN. 

Wordpress and Moodle are installed on IIAB 

The router provides IIAB server the IP Address  192.168.0.101.
I have another Client machine. Connected to the same router and it has the address 192.168.0.100

From this Client machine I am using Chrome as my browser.

I get the home page with 192.168.0.101/home and then clicking on Wordpress Icon the url is changed to box/wordpress and the connection fails with these errors.

Chrome gives this error.
This site can’t be reached,
box’s DNS  could not be found. Diagnosing the problem.
DNS_PROBE_STARTED
No Internet
Then
No Internet
No Internet
Try:
    • Checking the network cables, modem and router
    • Reconnecting to Wi-Fi
DNS_PROBE_FINISHED_NO_INTERNET

192.169.1.99/moodle  turns into http://box.lan/moodle
and  the error is 

This site can’t be reached
Check if there is a typo in box.lan.
DNS_PROBE_FINISHED_NXDOMAIN
The following entries work
192.168.0.101/home
192.168.0.101/admin
192.168.0.101/kolibri
192.168.0.101/kiwix
192.168.0.101/usb
192.168.0.101/modules

**Comment by shanti-bhardwa** [comment]
We are using Wordpress in Kenya and the the servers are connected to local router as the wifi-access point, so this needs to work.

**Comment by tim-moody** [comment]
this is a feature of wp that it expects to know its host or domain name and return urls with that name.

can  you turn  on dns  in the router so that it will resolve box?

**Comment by tim-moody** [comment]
alternatively if iiab has a fixed ip, you may be able to point wp to it

**Comment by tim-moody** [comment]
https://wpengine.com/resources/change-domains-wordpress/

**Comment by jvonau** [comment]
https://wiki.laptop.org/go/IIAB/FAQ#WordPress_.26_Moodle_Administration:_What_tips_.26_tricks_exist.3F

**Comment by holta** [comment]
> https://wiki.laptop.org/go/IIAB/FAQ#WordPress_.26_Moodle_Administration:_What_tips_.26_tricks_exist.3F

Please use IIAB's new http://FAQ.IIAB.IO if possible!  i.e. see item number 36 of 48 here:

[https://wiki.iiab.io/go/FAQ#WordPress_&_Moodle_Administration:_What_tips_&_tricks_exist?](https://wiki.iiab.io/go/FAQ#WordPress_&_Moodle_Administration:_What_tips_&_tricks_exist?)

**Comment by jvonau** [comment]
Since you have control over the the DNS at the router level what have you configured the router to hand out for the clients to use? Try `cat /etc/resolv.conf` from the iiab box and the chrome client machine and attach the results to this issue. How far along are you, as in this is just a test box or you have a ton of content installed? These 2 programs install and run best when in they are in their final deployed environment not juggling around across the different subnet's. I can get this to work but I would have to walk you through step by step from a fresh install with the install passing though the router that you are going to deploy with becoming a matched set. Maybe turn the experience into a how-to along the way?

**Comment by jvonau** [comment]
Some screen shots of the router's config would be helpful also, and a description of what you expect to type/appear in the address bar of the browser.

**Comment by jvonau** [comment]
I recall fiddling with trusted_domains in https://github.com/iiab/iiab/blame/master/roles/nextcloud/tasks/setup.yml#L90-L93 with upstream nextcloudpi being explicit in the definitions used:  
```
pi@nextcloudpi:~ $ sudo ncc config:list
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": {
            "0": "localhost",
            "7": "nextcloudpi",
            "5": "nextcloudpi.local",
            "8": "nextcloudpi.lan",
            "3": "nextcloudpi",
            "11": "public ip on internet",
            "1": "private ip on local lan",
            "14": "nextcloudpi"
        },
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "22.2.2.0",
        "overwrite.cli.url": "https:\/\/nextcloudpi\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "tempdirectory": "\/var\/www\/nextcloud\/data\/tmp",
        "mail_smtpmode": "sendmail",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "preview_max_x": "2048",
        "preview_max_y": "2048",
        "jpeg_quality": "60",
        "overwriteprotocol": "https",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***"
    },
    "apps": {
        "accessibility": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": ""
        },
        "activity": {
            "enabled": "yes",
            "installed_version": "2.15.0",
            "types": "filesystem"
        },
        "backgroundjob": {
            "lastjob": "33"
        },
        "calendar": {
            "enabled": "yes",
            "installed_version": "3.0.1",
            "types": ""
        },
        "circles": {
            "enabled": "yes",
            "installed_version": "22.1.1",
            "loopback_tmp_path": "\/",
            "loopback_tmp_scheme": "https",
            "maintenance_run": "0",
            "maintenance_update": "{\"maximum\":3,\"3\":1639809001,\"2\":1639812002,\"1\":1639812301,\"4\":1639792801,\"5\":1639623601}",
            "types": "filesystem,dav"
        },
        "cloud_federation_api": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": "filesystem"
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "1.12.0",
            "types": "logging"
        },
        "contacts": {
            "enabled": "yes",
            "installed_version": "4.0.6",
            "types": "dav"
        },
        "contactsinteraction": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "dav"
        },
        "core": {
            "backgroundjobs_mode": "cron",
            "installedat": "1639560005.3419",
            "lastcron": "1639812301",
            "lastupdatedat": "1639560005.3467",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "theming.variables": "10ec5003aae639e42ebfacab1a5e478d",
            "vendor": "nextcloud"
        },
        "dashboard": {
            "enabled": "yes",
            "installed_version": "7.2.0",
            "types": ""
        },
        "dav": {
            "enabled": "yes",
            "installed_version": "1.19.0",
            "types": "filesystem"
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.12.0",
            "types": ""
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "1.12.0",
            "types": "authentication"
        },
        "files": {
            "enabled": "yes",
            "installed_version": "1.17.0",
            "types": "filesystem"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "2.3.1",
            "types": ""
        },
        "files_rightclick": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "installed_version": "1.14.0",
            "types": "filesystem"
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.12.0",
            "types": "filesystem,dav"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.15.0",
            "types": "filesystem,dav"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "1.11.0",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "2.11.0",
            "types": "logging"
        },
        "logreader": {
            "enabled": "yes",
            "installed_version": "2.7.0",
            "types": ""
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.10.0",
            "types": "authentication"
        },
        "news": {
            "enabled": "yes",
            "installed_version": "17.0.1",
            "types": ""
        },
        "nextcloud_announcements": {
            "enabled": "yes",
            "installed_version": "1.11.0",
            "pub_date": "Thu, 24 Oct 2019 00:00:00 +0200",
            "types": "logging"
        },
        "nextcloudpi": {
            "enabled": "yes",
            "installed_version": "0.0.1",
            "types": ""
        },
        "notes": {
            "enabled": "yes",
            "installed_version": "4.2.0",
            "types": ""
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "2.10.1",
            "types": "logging"
        },
        "notify_push": {
            "base_endpoint": "https:\/\/nextcloudpi\/push",
            "cookie": "260881115",
            "enabled": "yes",
            "installed_version": "0.3.0",
            "types": "filesystem"
        },
        "oauth2": {
            "enabled": "yes",
            "installed_version": "1.10.0",
            "types": "authentication"
        },
        "password_policy": {
            "enabled": "yes",
            "installed_version": "1.12.0",
            "types": "authentication"
        },
        "photos": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": ""
        },
        "preview": {
            "jpeg_quality": "60"
        },
        "previewgenerator": {
            "enabled": "yes",
            "heightSizes": "256",
            "installed_version": "99.99.99",
            "squareSizes": "32 256",
            "types": "filesystem",
            "widthSizes": "256 384"
        },
        "privacy": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.12.0",
            "types": "prevent_group_restriction"
        },
        "recommendations": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": ""
        },
        "serverinfo": {
            "cached_count_filecache": "171",
            "cached_count_storages": "2",
            "enabled": "yes",
            "installed_version": "1.12.0",
            "types": ""
        },
        "settings": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": ""
        },
        "sharebymail": {
            "enabled": "yes",
            "installed_version": "1.12.0",
            "types": "filesystem"
        },
        "support": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": "session"
        },
        "survey_client": {
            "enabled": "yes",
            "installed_version": "1.10.0",
            "types": ""
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "1.12.0",
            "types": "logging"
        },
        "tasks": {
            "enabled": "yes",
            "installed_version": "0.14.2",
            "types": ""
        },
        "text": {
            "enabled": "yes",
            "installed_version": "3.3.0",
            "types": "dav"
        },
        "theming": {
            "backgroundMime": "image\/png",
            "enabled": "yes",
            "installed_version": "1.13.0",
            "logoMime": "image\/svg+xml",
            "name": "NextCloudPi",
            "slogan": "***REMOVED SENSITIVE VALUE***",
            "types": "logging",
            "url": "***REMOVED SENSITIVE VALUE***"
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "installed_version": "1.11.0",
            "types": ""
        },
        "updatenotification": {
            "enabled": "no",
            "installed_version": "1.12.0",
            "types": ""
        },
        "user_status": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "viewer": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": ""
        },
        "weather_status": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "2.4.0",
            "types": "filesystem"
        }
    }
}
```
I don't recall the significance of the numbers on the left side of trusted_domains other than being a key pair value.

**Comment by shanti-bhardwa** [comment]
I have tried this fix and it works for me.

1. Connected my TP_LINK router to IIAB server on DELL PC using Ethernet.

2. Fixed the IP address of IIAB server based on its MAC address using Address Reservation with Router's DHCP. This means the router will always give this IP address to the Server.

        DELL PC  MAC address is  D4-BE-D9-3E-BA-70 and the IP is fixed at 192.168.0.100

3. Then I have edited this file /library/wordpress/wp-config.php and added these two lines to the file.

You will have to do sudo nano /library/wordpress/wp-config.phpto edit

        define('WP_Home', 'http://192.168.0.100/wordpress');

        define('WP_SITEURL', 'http://192.168.0.100/wordpress');

4. Then from another laptop connected to the same router using Ethernet, I can do 192.168.0.100/wordpress and get the Site home page

5. Also from IIAB home page, Clicking on Wordpress ICON works as expected.

6. Connecting to Router's WIFI SSID and then using 192.168.0.100/wordpress also works but NOT 172.18.96.1/wordpress or box/wordpress

7. Connecting to IIAB Server's SSID ( e.g. Kenya IIAB) works with 172.18.96.1/wordpress and also 192.168.0.100/wordpress
 
Will do some more testing with couple of other routers and also play with DNS within the router

**Comment by jvonau** [comment]
> 6. Connecting to Router's WIFI SSID and then using 192.168.0.100/wordpress also works but NOT 172.18.96.1/wordpress or box/wordpress

 172.18.96.1/wordpress will never be reachable from the other subnet on 192.168.0.0/24. they are completely different networks, but getting box/wordpress to work would be at the router level where you would map the static ip address to the name 'box'. What is the router using as a domain name for the clients? That is the info from /etc/resolv.conf I asked for above. FWIW moodle is not as easy, but still do-able.

**Comment by tim-moody** [comment]
>172.18.96.1/wordpress will never be reachable from the other subnet

and even if it were reachable, wp is a one host animal, though there have been attempts to softcode host.

**Comment by jvonau** [comment]
The idea to have both the wired wan side and wireless lan side resolve to the same name on both subnets, but these considerations really need to be in place before installing and local_vars will need to be tweaked to match the layout.

**Comment by jvonau** [comment]
Depending on if the other clients on 192.168.0.0/24 have the support installed using http://box.local might be viable as that is a different name resolution stack using mdns working with local broadcasts. From one of the clients on 192.168.0.0/24 try `ping box.local` and see if that responds, might have to drop the firewall on the box machine for ping to work.

**Comment by jvonau** [comment]
I see moodle has gotten easier over the years, there is a search and replace [tool](https://www.inmotionhosting.com/support/edu/moodle/change-url-moodle/) and better directions available.

**Comment by shanti-bhardwa** [comment]
have tried this in wp-config.php 
define('WP_Home', 'http://box.local/wordpress');
define('WP_SITEURL', 'http://box.local/wordpress');

and works with two different  routers .Will test more.

**Comment by shanti-bhardwa** [comment]
How do I configure the DNS in my router to use dnsmasq with IIAB?. Generally DNS is set up with Primary & Secondary servers e.g. with Google 8..8.8.8 & 8.8.4.4

**Comment by jvonau** [comment]
Yea I was kind of thinking like that if your router doesn't support dynamic dns hostname entries from dhcp leases, replace 8.8.8 & 8.8.4.4 with the reserved address of 192.168.0.100 for the mac of the iiab box. Now there would be some tinkering on the IIAB box dnsmasq wise, but answering my questions makes this exercise less painful, documented, allows me some time so I can form some answers|actions in advance, quickest is with vpn access but I want a step by step done in plain sight

**Comment by jvonau** [comment]
https://discourse.pi-hole.net/t/how-do-i-configure-my-devices-to-use-pi-hole-as-their-dns-server/245 is the basic idea substitute IIAB for Pi-Hole in that routine.

**Comment by holta** [comment]
@shanti-bhardwa can we close this yet?

**Comment by shanti-bhardwa** [comment]
yes can be closed Thanks
