### ISSUE TITLE
"Refresh OER2Go Catalog" fails [quite often, e.g. 60% of the time]

### ISSUE THREAD

**Issue by tim-moody** [iiab/iiab#3092]
not sure if this is reproducible

**Comment by holta** [comment]
Whether this is reproducible or not, the failure output is here:

- https://github.com/iiab/iiab/issues/3091#issue-1091752250

Tangentially related:

- #853

**Comment by holta** [comment]
I just ran `/usr/bin/iiab-get-oer2go-cat` 10 times, and it failed 8 times, while succeeding 2 times: (regardless which IIAB machine I tried)

```
root@box:~# iiab-get-oer2go-cat
SUCCESSroot@box:~# iiab-get-oer2go-cat
Traceback (most recent call last):
  File "/opt/admin/cmdsrv/scripts/get_oer2go_catalog", line 183, in <module>
    main()
  File "/opt/admin/cmdsrv/scripts/get_oer2go_catalog", line 85, in main
    err_num, err_str, oer2go_catalog = get_oer2go_cat()
  File "/opt/admin/cmdsrv/scripts/get_oer2go_catalog", line 157, in get_oer2go_cat
    url_handle = urllib.request.urlopen(adm.CONST.oer2go_cat_url)
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 1352, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.7/urllib/request.py", line 1327, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.7/http/client.py", line 1352, in getresponse
    response.begin()
  File "/usr/lib/python3.7/http/client.py", line 310, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.7/http/client.py", line 279, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
Getting the OER2Go/RACHEL Catalog Failed.
Please run iiab-get-oer2go-cat again later.
```

Whereas success on the very same machine (just moments before/later) appears as follows:

```
root@box:~# iiab-get-oer2go-cat
SUCCESS
```

@tim-moody do you have any guesses...as to why the failure rate is so very high?

**Comment by tim-moody** [comment]
RemoteDisconnected suggests that the remote disconnected.

http://dev.worldpossible.org/cgi/json_api_v1.pl seems to work.

so no idea.

**Comment by tim-moody** [comment]
I did a couple of url_handle = urllib.request.urlopen(adm.CONST.oer2go_cat_url) (line that fails) with no failure.

any pattern in the OS or version of python?

I don't like what I'm reading about urllib.request and it's handlers. maybe they are retaining state and are busy at the os level.

this could be made a lot simpler with 

```
r = requests.get(adm.CONST.oer2go_cat_url)
if r.status_code == 200:
    oer2go_catalog = r.json()
else:
    oer2go_catalog = None
```

**Comment by holta** [comment]
> any pattern in the OS or version of python?

It appears to fail regardless of OS (Raspberry Pi OS "Lite" or "with desktop" or Ubuntu 22.04 daily build).

The failure rate is currently about 60% (about 3 in 5 attempts failed, after I tried running `iiab-get-oer2go-cat` about 50 times).

I can't see a pattern to date.  Almost as if it's completely random.  Certainly I don't understand it.

**Comment by holta** [comment]
Should this ticket possibly be closed?
(If the situation's much less severe 5-6 months later?)

As an aside, oer2go_catalog_json was just refined in roles/cmdsrv/templates/scripts/get_oer2go_catalog3.py here:

- PR iiab/iiab-admin-console#497

**Comment by tim-moody** [comment]
there are two problems. 1) the catalog is not always available or perhaps times out. 2) when that situation is trapped there is a programming error. I just addressed the second problem.

**Comment by holta** [comment]
> there are two problems. 1) the catalog is not always available or perhaps times out. 2) when that situation is trapped there is a programming error. I just addressed the second problem.

Problem 1) too!

- PR iiab/iiab-admin-console#498

**Comment by jvonau** [comment]
>Just a data point while installing IIAB onto RPi 4 today:
"Finished writing to /etc/iiab/kiwix_catalog.json
SUCCESSRetrying download of catalog.
Retrying download of catalog.
Retrying download of catalog.
Retrying download of catalog.
Retrying download of catalog.
OER2Go Catalog download failed. Using existing catalog."

>will never succeed until the Indonesia casino implements it

>RACHEL is "disappearing" all references to OER2Go it would appear:
https://github.com/rachelproject/oer2go-web

**Comment by holta** [comment]
Thanks to @tim-moody for this important fix/workaround a week ago:

- PR iiab/iiab-admin-console#506

**Comment by tim-moody** [comment]
why is this still open?

**Comment by holta** [comment]
Seems reliable (or reliable enough!) in recent months.

So let's close this.
