### ISSUE TITLE
Files from USB Drive Fail to Appear [double mounting on Graphical Desktop OS's e.g. Ubuntu MATE]

### ISSUE THREAD

**Issue by jackrodonnell** [iiab/iiab#3105]
I have a USB stick which contains html files.  I've mounted the USB on my Lenovo T440p laptop which is running with UbuntuMate 20.04.3 and IIAB 8.0  I select "Insert a USB key/drive to publish files here" from the menu.  I see my mounted Parent Directory and my mounted USB as USB0.  However none of the HTML files appear when I select USB0

 http://sprunge.us/2zzXQZ
Thanks

**Comment by jackrodonnell** [comment]
The HTML files that failed to display were on a USB with ext4.  I moved the files to a USB with Fat32.  Same problem. I removed the HTML files and added a PDF file on each of these USBs.  Both PDF files on these 2 USBs were visible via IIAB.  I then placed one HTML file and one PDF file on each of these 2 USBs.  IIAB was not able to display any of these files

**Comment by tim-moody** [comment]
>I select "Insert a USB key/drive to publish files here" from the menu

what menu is that?

what url are you viewing when you say the files do not display? what when they do? http://box/USB?

what does ll /library/www/html/local_content/ show?

>I then placed one HTML file and one PDF file on each of these 2 USBs

was the html file named index.html? something else?

**Comment by jackrodonnell** [comment]
Tim
See the screenshot for the menu.  
![Screenshot at 2022-01-17 10-18-33](https://user-images.githubusercontent.com/16327335/149805757-422a495c-81d8-4561-b324-2f082fc8ea3b.png)

Concerning the URL: On my local laptop that is running IIAB, I have tried both http://172.18.96.1/usb and box/usb.  Neither one results in a display of the HTML files. However I just tried accessing IIAB from my phone.  When I enter http://172.18.96.1/usb the HTML files DO NOT  appear on my phone.  When I access using box/usb the HTML files DO appear on my phone

Concerning /library/www/html/local_content/  I'm not sure where this directory is at??

Concerning "was the html file named index.html?"   YES.  When I accessed IIAB on my phone I could open index.html and all of the subsequent links functioned

Thanks
Jack

**Comment by tim-moody** [comment]
what happens if you use box/local_content as the url on the two devices?

**Comment by jackrodonnell** [comment]
When I access box/local_content/USB0 on my local device with IIAB or remotely on my  iPhone, the HTML files are not visible

**Comment by tim-moody** [comment]
puzzling. It can happen that the mount and unmount functions get confused in creating and removing links to the usb. I would try examining the file system with the Mate File Manager, especially /library/www/html/local_content/.

You could also try removing the USB and rebooting.

**Comment by jackrodonnell** [comment]
I suspected a mounting/unmounting issue.  I've constantly rebooted and restarted IIAB both locally on the IIAB laptop and on my phone.  
I've checked mounted devices and see

iiab-admin@box:~$ df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            7.7G     0  7.7G   0% /dev
tmpfs           1.6G  1.8M  1.6G   1% /run
/dev/sda5       916G  199G  671G  23% /
tmpfs           7.7G   12M  7.7G   1% /dev/shm
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           7.7G     0  7.7G   0% /sys/fs/cgroup
/dev/loop2       56M   56M     0 100% /snap/core18/2284
/dev/loop3      165M  165M     0 100% /snap/gnome-3-28-1804/161
/dev/loop1       56M   56M     0 100% /snap/core18/2128
/dev/loop0      128K  128K     0 100% /snap/bare/5
/dev/loop4       66M   66M     0 100% /snap/gtk-common-themes/1519
/dev/loop5       16M   16M     0 100% /snap/ubuntu-mate-welcome/626
/dev/loop7      128K  128K     0 100% /snap/software-boutique/54
/dev/loop6      168M  168M     0 100% /snap/spotify/56
/dev/loop8       16M   16M     0 100% /snap/ubuntu-mate-welcome/646
/dev/loop9       44M   44M     0 100% /snap/snapd/14295
/dev/loop10      33M   33M     0 100% /snap/snapd/12704
/dev/sda1       511M  4.0K  511M   1% /boot/efi
tmpfs           1.6G   28K  1.6G   1% /run/user/1001
/dev/sdb1       113G   18G   90G  17% /media/usb0

Just now I rebooted the laptop and phone and cleared caches.  I attempted to view box/usb/USB0 on my phone and this time it failed to appear on both laptop anIfd phone.

I know it would be nice to solve this mystery but I'm setting up for 12 laptops going to a school in Haiti.  By using the USB with IIAB I was trying to consolidate WorldComputerExchange Content with IIAB Content.  There seems to be a USB issue which I dont want to pass on to those in Haiti.  All of the Content on my USB is on the hard drive of the computers that we will send.  So I may just leave the content in 2 places.  I can create web links on the laptops that will lead to the IIAB or to the hard drive content

**Comment by holta** [comment]
Thanks @jackrodonnell for pushing.

Just to be clear this feature[*] is Rock Solid for others, so we definitely do want to help you get closer to identifying what's not working (intermittently?) in your unique situation??

Does a call help in coming days — simply to review all facts + assumptions, so others can try to reproduce exactly what's failing for you?

[*] http://FAQ.IIAB.IO -> **"4 Can teachers display their own content?"**

Tangential USB mounting issue, affecting USB boot drives / media:

- #2552

**Comment by jackrodonnell** [comment]
Yes a call would be fine
      773-316-2944
    Tues-Fri best
      Jack
    
    On 1/17/22 1:49 PM, A Holt wrote:
    
    
      
      Thanks @jackrodonnell
        for pushing.
      Just to be clear this feature[*] is Rock Solid for
        others, so we definitely do want to help you get closer to
        identifying what's not working (intermittently?) in your unique
        situation??
      Does a call help in coming days — simply to review
        all facts + assumptions, so others can try to reproduce exactly
        what's failing for you?
        
        
        [*] http://FAQ.IIAB.IO -> "4
          Can teachers display their own content?"
      —
        Reply to this email directly, view it on GitHub, or unsubscribe.
        Triage notifications on the go with GitHub Mobile for iOS or Android.
        
        You are receiving this because you were mentioned.Message
          ID: ***@***.***>
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/iiab/iiab/issues/3105#issuecomment-1014844934",
"url": "https://github.com/iiab/iiab/issues/3105#issuecomment-1014844934",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by holta** [comment]
@jackrodonnell FYI I also do IIAB work in Haiti — please do feel free to write / coordinate on these topics anytime:

holt@unleashkids.org

**Comment by tim-moody** [comment]
As long as the server is still connected to the internet you could give me remote access by issuing the command

/usr/bin/iiab-vpn-on

if you like.

**Comment by jvonau** [comment]
```
=IIAB==========================================================================
COMMAND: /usr/bin/systemctl is-active display-manager.service    # Graphical Desktop?

active
```

**Comment by jvonau** [comment]
https://github.com/iiab/iiab/issues/2456#issuecomment-649807106

**Comment by holta** [comment]
> [#2456 (comment)](https://github.com/iiab/iiab/issues/2456#issuecomment-649807106)

Perfect, thanks @jvonau.

I just spoke live with @jackrodonnell and suggested this to him.

Tonight and later this week he will do more testing and follow up when he has more time!

**Comment by jackrodonnell** [comment]
Thanks everyone for the support and suggestions
After speaking with @holta today and reading @jvonau suggestion  #2456.  I ran "gsettings set org.mate.media-handling automount false"  Prior to this I was experiencing my USB mounting twice when I boot the laptop and started IIAB.  I thought this may be contributing to my inability to see some files both on the IIAB interface of my laptop and on my iphone which is connect to the laptops hotspot.

The progress is that now the issue is consistent.  Here is a summary.  I have repeated this 4 times tonight.  Each starting with a fresh reboot.

I have 2 USB sticks: 

- USB0 has a folder.  In the folder are 2 files: a PDF and an index.html file
- USB1 has a folder. In the folder is an index.html file and a number of subfolders which have HTML,CSS,video files etc

 
ON THE LAPTOP RUNNING IIAB
I boot the computer with the USBs in place and delete the cache on Chrome. Then I start IIAB on Chrome.  
When I check /library/www/html/local_content/ both USBs are present.
When I go to box/usb I see both USBs.  
When I open the folder on USB0,index.html is displayed as it should look but the PDF isn't visible at all
When I open the folder on USB1 I see a white screen.  Nothing displayed


ON THE IPHONE CLIENT
Before opening Chrome I delete the cache
When I open the folder on USB0,index.html is displayed as it should look but the PDF isn't visible at all
When I open the folder on USB1 I see a white screen  Nothing displayed

**Comment by holta** [comment]
@jackrodonnell what happens if you remove the index.html file from each USB stick?

Any chance this allows the other {PDF, video, css} files to then be seen within http://box/usb ?

**Comment by jackrodonnell** [comment]
I've removed the index.html file from both USBs.  They are the same file.  Now the USB feature on the laptop and on the iPhone are acting exactly as they should.   In the case of USB1 all of the various subfolders can be displayed,opened and explored from the Laptop and iPhone.   I've attached the index.html file.  It is lacking the images and the CSS formatting.  I had to send it as index.txt since this feature on GitHub doesnt allow HTML to be upload
[index.txt](https://github.com/iiab/iiab/files/7893940/index.txt)

**Comment by holta** [comment]
@jackrodonnell great progress.

Can you fix up an index.html customized for each USB stick — that is if your goal is a prettier web page — to showcase the PDF(s) and video files (etc) on each stick?

**Comment by jackrodonnell** [comment]
@holta
Hi Adam... you suggested I delete the index.html file from the USB which did successfully allow me to view the other contents of the USB(a series of folders containing HTML, CSS, image, PDFs, video etc) The content are the folders are an educational digital archive. The index.html file I deleted is in fact "an index.html customized for each USB stick ........to showcase the PDF(s) and video files (etc) on each stick"
![Index](https://user-images.githubusercontent.com/16327335/150146075-a2fc832f-741e-42ae-b81e-41595fa0cc7b.png)

**Comment by jackrodonnell** [comment]
@holta @jvonau @tim-moody 
I took the same Lenovo T440p laptop and installed Mint Mate 20.3 and then reinstalled a minimal package of IIAB. I ran "gsettings set org.mate.media-handling automount false"   The results with attached USBs were identical to what I saw in Ubuntu Mate 20.04. I experimented with making folders and testing the behavior of file types. Results on server and client are the same
I'm convince that the issue is connected with .html file types.  If a folder contains an Index.html file, the USB0 displays on IIAB but when the folder is opened it appears empty of all contents.


I took some screen shots with descriptions,  Picture are numbered 1-4

![1_noIndexhtml](https://user-images.githubusercontent.com/16327335/150436405-4418b17a-2358-4bb8-b4d2-e05a523b7955.png)
![2_IndexhtmlFolder2](https://user-images.githubusercontent.com/16327335/150436404-20d34efa-23db-4ba7-b1df-865414652d05.png)
![3MainhtmlFolder2](https://user-images.githubusercontent.com/16327335/150436402-fae5d869-1294-478c-8565-14fcd9338322.png)
![4_blankscreen](https://user-images.githubusercontent.com/16327335/150436401-80fb2b9a-e116-4836-b842-8bee5ce0a03c.png)

**Comment by holta** [comment]
@jackrodonnell can you call me so we can get to the bottom of this efficiently?

Your index.html displays without problem for me &mdash; e.g. when placed on a USB stick &mdash; as you can see in the 2 screenshots below:

![image](https://user-images.githubusercontent.com/2458907/150439367-6521d1d3-68c5-4b03-867f-1253305cfc3d.png)

(When index.html is renamed to main.html on the stick, it also appears in browser for me, as seen below...)

![image](https://user-images.githubusercontent.com/2458907/150439310-862f57ed-b11d-4169-afbe-dcc6083a9dd9.png)

**Comment by jvonau** [comment]
```
COMMAND: /usr/sbin/blkid    # Mount point details
/dev/sda5: UUID="386a0fa4-2a42-4939-805a-48c9b87c4361" TYPE="ext4" PARTUUID="3ce9a89c-05"
/dev/loop0: TYPE="squashfs"
/dev/loop1: TYPE="squashfs"
/dev/loop2: TYPE="squashfs"
/dev/loop3: TYPE="squashfs"
/dev/loop4: TYPE="squashfs"
/dev/loop5: TYPE="squashfs"
/dev/loop6: TYPE="squashfs"
/dev/loop7: TYPE="squashfs"
/dev/sda1: UUID="9FF4-0A75" TYPE="vfat" PARTUUID="3ce9a89c-01"
/dev/loop8: TYPE="squashfs"
/dev/loop9: TYPE="squashfs"
/dev/loop10: TYPE="squashfs"
/dev/sdb1: LABEL="LaptopImage" UUID="1ddf9f13-64af-40ae-b4f9-91642584249c" TYPE="ext4" PARTUUID="eebe4afc-01"

```
Think you are running into a filesystem type/permissions issue, vfat does not support the needed file ownership that the webserver requires.

**Comment by jackrodonnell** [comment]
@holta @jvonau @tim-moody I discovered the source of my problems.  I had copied a web site that I have created and have used to the USB.  This kept giving the errors I've outlined over the last few days.  After yesterday post I recopied the site to the same USB.  Everything now works as expected.

I retrieved the old files from my Trash and replicated the errors I once saw.  When I inspected the index.html page from the Trash version found it to be totally blank

How this happened is a mystery,  I appreciate your help and regret the time I've taken from an error I caused

**Comment by holta** [comment]
Eureka, thanks @jackrodonnell for updating us!

As final clarification, regarding @jvonau's theory from about 10h ago:

> vfat does not support the needed file ownership that the webserver requires

I considered that idea.

This theory doesn't hold up however.

Specifically: my tests (screenshots above, 14h ago) used a VFAT USB stick, and @jackrodonnell's earlier index.html (renamed from his index.txt above, 58h ago) appeared successfully at http://box/usb/USB0 without problems.

**Comment by holta** [comment]
(Actually let's leave this ticket open for now, to help drive awareness of the Graphical Desktop double-mounting issue, even if there's no magical answer to deal with all such Visual/Graphical Desktop OS's at this time ;-)

**Comment by jvonau** [comment]
I suggest that this issue be 'pinned'

**Comment by jvonau** [comment]
> @holta @jvonau @tim-moody I discovered the source of my problems. I had copied a web site that I have created and have used to the USB. This kept giving the errors I've outlined over the last few days. After yesterday post I recopied the site to the same USB. Everything now works as expected.
> 
> I retrieved the old files from my Trash and replicated the errors I once saw. When I inspected the index.html page from the Trash version found it to be totally blank
> 
> How this happened is a mystery, I appreciate your help and regret the time I've taken from an error I caused

Think you ran into some filesystem corruption at some point.

**Comment by jvonau** [comment]
> Eureka, thanks @jackrodonnell for updating us!
> 
> As final clarification, regarding @jvonau's theory from about 10h ago:
> 
> > vfat does not support the needed file ownership that the webserver requires
> 
> I considered that idea.
> 
> This theory doesn't hold up however.
> 
> Specifically: my tests (screenshots above, 14h ago) used a VFAT USB stick, and @jackrodonnell's earlier index.html (renamed from his index.txt above, 58h ago) appeared successfully at http://box/usb/USB0 without problems.

How the usb stick is formatted (ie vfat, exfat, ntfs) does have an effect on what you can serve from the usbstick
https://en.wikipedia.org/wiki/Comparison_of_file_systems#OS_support

**Comment by holta** [comment]
> I suggest that this issue be 'pinned'

Done, at the top of: https://github.com/iiab/iiab/issues

This OpenStreetMap issue was unpinned for now, to make room:

- https://github.com/iiab/iiab/issues/3077

**Comment by holta** [comment]
> How the usb stick is formatted (ie vfat, exfat, ntfs) does have an effect on what you can serve from the usbstick https://en.wikipedia.org/wiki/Comparison_of_file_systems#OS_support

Is there an example of some files working with IIAB (while some other files are not working with IIAB) when using the very same USB stick/drive filesystem?

(In this case with @jackrodonnell, that was not the issue.)

**Comment by jvonau** [comment]
vfat holding a zim that is larger that 4.3 GB comes to the top of my head as an example

**Comment by jvonau** [comment]
> Yes a call would be fine 773-316-2944 Tues-Fri best Jack 
On 1/17/22 1:49 PM, A Holt wrote: Thanks @jackrodonnell for pushing. 

@jackrodonnell Do I have the right person https://www.whitepages.com/phone/1-773-316-2944 of Somerville, MA using the https://twitter.com/jackrodonnell handle from https://worldcomputerexchange.org/? I'll be trying to contact you directly later today.

**Comment by jackrodonnell** [comment]
May not work;I'll be driving all day.  
Jack

**Comment by jvonau** [comment]
Email me directly your preferred contact info.

**Comment by jackrodonnell** [comment]
Jerry

The best contact is either ***@***.*** or 773-316-2944 via text or WhatsApp
Jack

**Comment by jvonau** [comment]
close
