### ISSUE TITLE
Some links don't work in medical preset

### ISSUE THREAD

**Issue by jvonau** [iiab/iiab#3108]
https://support.mozilla.org/en-US/kb/xframe-neterror-page?as=u&utm_source=inproduct
### Expected behavior and actual behavior:
link opens
### Steps to reproduce the problem:
http://104.193.111.252/modules/en-medline_plus
http://104.193.111.252/modules/en-stanford_em

**Comment by tim-moody** [comment]
was this on a failed or successful install?

**Comment by tim-moody** [comment]
I can access both of the above links

**Comment by jvonau** [comment]
doesn't open when clicking on the link from within http://104.193.111.252/home/

**Comment by tim-moody** [comment]
I tried both from that home page and both opened

**Comment by holta** [comment]
Should this be relabeled as a question instead of a bug?

**Comment by holta** [comment]
@jvonau clarified this can be closed.
