### ISSUE TITLE
Can we auto-hide the "Power Off" button when it's not meant to work?

### ISSUE THREAD

**Issue by holta** [iiab/iiab#3109]
Might there be any pragmatic way that IIAB could auto-hide or obfuscate the "Power Off" button when it's not meant to work?

e.g. when IIAB implementers want the URL http://box/js-menu/menu-files/services/power_off.php fully disabled &mdash; to avoid students abusing this.

Context: I just did a standard fresh install of IIAB, taking all defaults, and the "Power Off" button appears on the bottom-left of the resulting IIAB page (at http://box.lan).  It really shouldn't, in these circumstances, if we can possibly find a way for it not to appear in these common cases?

Background: `apache_allow_sudo: False` is set as a result of these changes discussed (http://minutes.iiab.io) earlier today:

- PR #3104
- PR iiab/iiab-admin-console#458

**Comment by tim-moody** [comment]
just turn it off in menu properties

**Comment by holta** [comment]
The question is how to auto-hide it.

(But possibly that's not easy.)

**Comment by holta** [comment]
Definitely good enough for now:

- https://github.com/iiab/iiab-admin-console/pull/459

Thanks @tim-moody
