### ISSUE TITLE
 Regression: Using preset does not install zims defined in content.json & Can't install zims from pick list.

### ISSUE THREAD

**Issue by jvonau** [iiab/iiab#3125]
### Expected behavior and actual behavior:
Install what zim files are listed in content.json for en-medical when using preset, the zim jobs are not present in "display job status" only 26 jobs as opposed to 32. the 6 zim jobs are not included in the listing. Prior installs of iiab-admin-console at efaf6e4194dd921b016d3285e23cce1da428a320 installed the zims with a total of 32 jobs to be run.
### Steps to reproduce the problem:
use preset, note if zims are installed.
### IIAB version, OS version, hardware details:
latest master

**Comment by jvonau** [comment]
There is something wrong with the pick list, the older commit shows
![Screenshot from 2022-02-22 23-03-11](https://user-images.githubusercontent.com/5579710/155264443-c00efa85-9be1-4c86-a35e-1e1be8275005.png)
The newer version is lacking the sub-headings shows just with nothing current.
![Screenshot from 2022-02-22 23-03-25](https://user-images.githubusercontent.com/5579710/155264543-aef170f7-3d64-47f6-a84f-26616325ebed.png)

**Comment by jvonau** [comment]
Might be the cause of #3124?

**Comment by jvonau** [comment]
```
Downloading Catalogs and Building Local Data Files.
Traceback (most recent call last):
  File "/opt/admin/cmdsrv/scripts/get_kiwix_catalog", line 11, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'
Getting the Kiwix Catalog Failed.
Please run iiab-get-kiwix-cat again later.
SUCCESSWaiting to run iiab-make-kiwix-lib.py
```

**Comment by jvonau** [comment]
`sudo apt install python3-bs4` is the fix

**Comment by jvonau** [comment]
https://github.com/iiab/iiab-admin-console/pull/464

**Comment by jvonau** [comment]
still unable to install any zims, but the pick list has the sub-menus now.

**Comment by jvonau** [comment]
Further to can't install zims, select zim to install: 
![Screenshot from 2022-02-23 08-57-05](https://user-images.githubusercontent.com/5579710/155345100-8e8bda35-c5c3-4d59-9d5a-888085b2be53.png)
press 'Install Selected Zims'
![Screenshot from 2022-02-23 08-57-19](https://user-images.githubusercontent.com/5579710/155345097-b1ff7238-fa9d-4e14-aa58-d3b4b519327c.png)
observer error flashed to screen with the job not being added to the job queue.
![Screenshot from 2022-02-23 08-57-25](https://user-images.githubusercontent.com/5579710/155345091-e31c3035-2819-4154-b5cc-2a9c7613730c.png)

**Comment by tim-moody** [comment]
![image](https://user-images.githubusercontent.com/5678731/155347060-1d4fc6fc-dcc8-454e-90d1-512a5d3ab6d6.png)

**Comment by tim-moody** [comment]
looks to me like the front end knows of an id that the backend doesn't know. did you run get kiwix cat manually? cmdsrv would not have reloaded it

can you run refresh kiwix cat through adm cons and see if that fixes it.

if not then
can you restart cmdsrv and see if the problem persists?

**Comment by jvonau** [comment]
ran `sudo /opt/admin/cmdsrv/scripts/get_kiwix_catalog -v` then "Refresh Kixix Catalog" and the pick list now works while presets don't populate the pick list.

**Comment by tim-moody** [comment]
there is a second bug. url attribute missing from root.xml catalog

**Comment by holta** [comment]
> there is a second bug. url attribute missing from root.xml catalog

Fix is apparently:

- https://github.com/iiab/iiab-admin-console/pull/465

**Comment by jvonau** [comment]
@holta I gather the statement "Pre-releases of Internet-in-a-Box (IIAB) undergo continuous QA / continuous integration / continuous deployment and are strongly recommended!" is no longer true?

> ```
> Downloading Catalogs and Building Local Data Files.
> Traceback (most recent call last):
>   File "/opt/admin/cmdsrv/scripts/get_kiwix_catalog", line 11, in <module>
>     from bs4 import BeautifulSoup
> ModuleNotFoundError: No module named 'bs4'
> Getting the Kiwix Catalog Failed.
> Please run iiab-get-kiwix-cat again later.
> SUCCESSWaiting to run iiab-make-kiwix-lib.py
> ```

The installer should of stopped at this point of the install, when the underlying cause was already known and is fatal but becomes hidden because the bash script did not stop. The underling cause of this behavior is rooted in the lack of use of the '-e' flag within https://github.com/iiab/iiab-admin-console/blob/master/install

**Comment by holta** [comment]
> The installer should of stopped at this point of the install, when the underlying cause was already known and is fatal but becomes hidden because the bash script did not stop.  The underling cause of this behavior is rooted in the lack of use of the '-e' flag within https://github.com/iiab/iiab-admin-console/blob/master/install

This sounds like a potentially great idea?

@tim-moody should this be considered?

**Comment by tim-moody** [comment]
>I gather the statement "Pre-releases of Internet-in-a-Box (IIAB) undergo continuous QA / continuous integration / continuous deployment and are strongly recommended!" is no longer true?

which pre-release are we in?

**Comment by holta** [comment]
> @holta I gather the statement "Pre-releases of Internet-in-a-Box (IIAB) undergo continuous QA / continuous integration / continuous deployment and are strongly recommended!" is no longer true?

QA is of course a human endeavor, with everyone attempting their best.

This ticket is extremely helpful.

Likewise @tim-moody has made really incredible progress thanks to @bernardroth in recent days:

- #3124

It's a powerful testament to the hard work of QA that some blithely take for granted, but so many others dedicate themselves to contributing to help each other.

**Comment by holta** [comment]
> which pre-release are we in?

DRAFT release notes for pre-release IIAB 8.0 are here:

https://github.com/iiab/iiab/wiki/IIAB-8.0-Release-Notes

It's great that 2022 is yielding real progress month by month.

**Comment by tim-moody** [comment]
so my understanding of the agreement at the last release was that we now enter a period where master is in flux and those who want stability should install from the most recent release up to the point where a pre-release is declared

**Comment by holta** [comment]
There is a lot of vital volunteer-contributed testing of many different kinds, happening almost every single week, and definitely every single month &mdash; and not infrequently every single day.

This brings a new pre-release almost every single week (and sometimes every single day).  Occasionally one of these pre-releases is highlighted to attract even more testing in particular situations, e.g. IIAB 8.0 Beta 1 about a month ago: https://github.com/iiab/iiab/releases/tag/8.0-beta-1

Also occasionally IIAB's master branch contains a particularly nasty/intricate issue that's slipped by all of us.  It happens.  As QA is a human process after all.  The sky does not fall.  And when this occasionally happens, we are all human beings doing our best &mdash; probing + fixing as efficiently as we can in those cases.

In essense, the [CI/CD](https://en.wikipedia.org/wiki/CI/CD) workflow / workstream isn't perfect (nothing is!) but it works extremely well &mdash; and certainly far better than the brittle/bureaucratic machinery of a waterfall release process.

Of course, classical releases _DO_ still have an important outreach/marketing purpose (e.g. to give people something to Tweet about, etc).

**Comment by holta** [comment]
@jvonau's `bash -e` suggestion (above) is now implemented, thanks to @tim-moody:

- iiab/iiab-admin-console#469

**Comment by tim-moody** [comment]
This was probably a mistake as a failed oer2go catalog download will now break the entire install, which was the reason I didn't do this in the first place.

**Comment by holta** [comment]
> This was probably a mistake as a failed oer2go catalog download will now break the entire install, which was the reason I didn't do this in the first place.

Good point.

If necessary, subtasks of any bash script can be made to appear to succeed &mdash; e.g. using syntax like:

```
program-that-fails || true
```

**Comment by jvonau** [comment]
> This was probably a mistake as a failed oer2go catalog download will now break the entire install, which was the reason I didn't do this in the first place.

There can be any number of reasons for a download to fail, as strangeness is noted in #3092. At this point in the 'install' all the support files that admin-console/cmd-server use are in place, the part that is failing is priming the data source as not to fail when GET-OER2GO-STAT or GET-ZIM-STAT is called when entering the admin-console page, but the catalogs can be retrieved using the supplied 'retrieve catalog' buttons, hardly a fatal error but now a PITA requiring user intervention anyway. I'd suggest that the four lines at https://github.com/iiab/iiab-admin-console/blob/master/install#L48-L51 be moved to it's own sub-script as not to have to re-run the entire install for a failed catalog download.
