### ISSUE TITLE
IIAB installs fail on Ubuntu 22.04 (ETA 2022-04-21) due to "No package matching 'usbmount' is available"

### ISSUE THREAD

**Issue by holta** [iiab/iiab#3126]
If Ubuntu 22.04 (7+ weeks away) will no longer include apt package [usbmount](https://github.com/rbrito/usbmount) (?) that would be a real disappointment:

```
TASK [usb_lib : Install usbmount from OS repo for Ubuntu variants] *****************************************************************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "No package matching 'usbmount' is available"}
```

Very odd if true, as Ubuntu 21.10 (released 4 months ago) as well as all recent versions of Ubuntu, all include usbmount 0.0.22:

https://launchpad.net/ubuntu/+source/usbmount

Should this issue possibly be posted upstream in other place(s) than just https://bugs.launchpad.net/ubuntu/+source/usbmount/+bug/1962377 ?

Refs:

- #3105

**Comment by holta** [comment]
In the interim until this is solved, the following 2 lines can be added to [/etc/iiab/local_vars.yml](https://wiki.iiab.io/go/FAQ#What_is_local_vars.yml_and_how_do_I_customize_it?) so that IIAB installs can at least complete...

```
usb_lib_install: False
usb_lib_enabled: False
```

I've posted this warning to https://github.com/iiab/iiab/wiki/IIAB-Platforms -> Ubuntu 22.04 LTS (Jammy Jellyfish).

**Comment by holta** [comment]
Or Lines 44-48 might need to be revised here...

https://github.com/iiab/iiab/blob/c0cedd17298d2044fb0b46aca03a53daff78fffe/roles/usb_lib/tasks/install.yml#L37-L48

**Comment by jvonau** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=774149
https://github.com/rbrito/usbmount

**Comment by holta** [comment]
Unfortunately `usbmount` seems to have been suddenly removed from Debian and Ubuntu 2 months ago:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1002945

**Comment by holta** [comment]
Very tangential, but still somewhat related issue we should eventually investigate:

- #2552

(The http://box/usb UX should be cleaner when Raspberry Pi's are booted from an external USB SSD or HDD etc, if possible not showing USB0 and USB1.  Also partitions should really not be mounted R/W if possible!)

**Comment by holta** [comment]
This is likely now resolved by:

- PR #3155

Thanks to @jvonau for the patch suggestion.

Functionality testing should follow later (using a non-VM PC and/or Raspberry Pi running Ubuntu 22.04) to be 100% sure...

**Comment by jvonau** [comment]
Close

**Comment by holta** [comment]
ASIDE: There are *lots* of Ubuntu 22.04 testing issues like this ahead (I spent some time on this yesterday) but that's life, and will require some patience as various LMS-like apps solidify their own support for PHP 8.1 etc — hopefully in not too many weeks...
