### ISSUE TITLE
Fedora 25: "iiab-make-kiwix-lib" "mysql" command not found

### ISSUE THREAD

**Issue by arky** [iiab/iiab#313]
Please add Fedora support in './runansible'  command. 

> ==> fedora: + ansible --version
> ==> fedora: + grep -q 'AttributeError: '\''module'\'' object has no attribute '\''HAVE_DECL_MPZ_POWM_SEC'\'''
> ==> fedora: + cd /opt/iiab/iiab/vars
> ==> fedora: + '[' Fedora == Raspbian ']'
> ==> fedora: + read -p 'Press enter to Install or ctl-c to STOP and edit local vars'
> ==> fedora: + cd /opt/iiab/iiab
> ==> fedora: + ./runansible
> ==> fedora: IIAB supports raspbian, debian, ubuntu, centos, and OLPC - exiting now...
> ==> fedora: + cd /opt/iiab/iiab-admin-console
> ==> fedora: + ./install
> ==> fedora: + '[' -f /etc/iiab/iiab.env ']'
> ==> fedora: + echo 'IIAB Config not found.'
> ==> fedora: IIAB Config not found.

Automated Fedora 25 builds report that 'iiab-make-kiwix-lib' and 'mysql' commands are missing on the machine. 

> ==> fedora: samples/sampler.html
> ==> fedora: samples/test.html
> ==> fedora: samples/test.json
> ==> fedora: sent 67,167 bytes  received 419 bytes  135,172.00 bytes/sec
> ==> fedora: total size is 65,668  speedup is 0.97
> ==> fedora: ./cp-menus: line 31: iiab-make-kiwix-lib: command not found
> ==> fedora: cp: 
> ==> fedora: cannot create regular file '/var/www/html/home/index.html'
> ==> fedora: : No such file or directory
> ==> fedora: files copied
> ==> fedora: ./cp-menus: line 61: mysql: command not found
> ==> fedora: ./cp-menus: line 64: mysql: command not found
> ==> fedora: ./cp-menus: line 68: mysql: command not found
> ==> fedora: database created

Complete output is here https://pastebin.com/PYdNYXdV

**Comment by jvonau** [comment]
Tim & Geroge have backed away from Fedora in general since F23 but I wish to bring the support back into focus as ansible is a redhat product. I've aware of some differences between the last successful Fedora installs and what is available in Fedora today. One issue is the renaming of some python/mysql/zmq packages in later Fedora's but the playbooks do not reflect the latest names as the focus has not been on the redhat side of the code.

**Comment by holta** [comment]
@jvonau can I defer this to IIAB 6.6?

**Comment by jvonau** [comment]
Yes, I'll look at fedora at some point in the future.

**Comment by holta** [comment]
@arky please update or close your tkt, if poss?

Thanks, as [IIAB 6.6](http://download.iiab.io/6.6/) release is now converging!

We can also move this to our [IIAB 6.7 Milestone](https://github.com/iiab/iiab/milestone/4) if you prefer.

**Comment by arky** [comment]
@holta Looks like I need setup the CI system again to check if issue still exists. Please assign this to me.

**Comment by holta** [comment]
> @holta Looks like I need setup the CI system again to check if issue still exists. Please assign this to me.

Oops, sorry @arky I missed this in July!

**Comment by holta** [comment]
@arky plz re-open as nec, Thanks!
