### ISSUE TITLE
Calibre-Web fails to install on latest Ubuntu 22.04 daily builds: "Unable to find pip in the virtualenv, /usr/local/calibre-web-py3, under any of these names: pip3, pip. Make sure pip is present in the virtualenv." [ansible-core not finding pip?]

### ISSUE THREAD

**Issue by holta** [iiab/iiab#3130]
Is this a transient issue that a future daily build of Ubuntu 22.04 might possibly resolve ?

Issue's summarized within:

- https://github.com/iiab/iiab/pull/3129#issuecomment-1060884667

Other issue(s) installing IIAB onto Ubuntu 22.04:

- #3126
- https://github.com/iiab/iiab/wiki/IIAB-Platforms -> Section 2.

**Comment by holta** [comment]
RECAP: 10 days ago Calibre-Web installed successfully on the Ubuntu 22.04 pre-release from that time &mdash; but there appears to be a change to VENV / PIP since then &mdash; within latest daily Ubuntu 22.04 pre-releases it appears:

> TASK [calibre-web : Download Calibre-Web dependencies (using pip) into python3 virtual environment /usr/local/calibre-web-py3] ***
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Unable to find pip in the virtualenv, /usr/local/calibre-web-py3, under any of these names: pip3, pip. Make sure pip is present in the virtualenv."}

Here's the Ansible code that's failing:

https://github.com/iiab/iiab/blob/b482018b1a6d9fc569164faa360b744e0fcf46f0/roles/calibre-web/tasks/install.yml#L46-L51

**Comment by holta** [comment]
Further explained on this upstream ticket, in case someone has ideas:

- janeczku/calibre-web#2327

**Comment by holta** [comment]
Mysterious but good news:

Calibre-Web can now be installed on more recent pre-release versions of Ubuntu 22.04

**Comment by jvonau** [comment]
un-pin?
