### ISSUE TITLE
Lokole won't install on recent OS's with Python 3.9+ [affects all LARGE-sized IIAB installs]

### ISSUE THREAD

**Issue by holta** [iiab/iiab#3132]
[This particular example occurred on 64-bit RasPiOS on RPi 4.]

Whether or not this is easily fixable, just FYI here's the error:

> TASK [lokole : Create Lokole admin user with password, for http://box/lokole] ******************************************************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": true, "cmd": "while read envvar; do export \"$envvar\"; done < /home/lokole/state/settings.env\n/library/lokole/venv/bin/manage.py createadmin --name='admin' --password='changeme'\n", "delta": "0:00:00.473349", "end": "2022-03-10 20:24:36.573274", "msg": "non-zero return code", "rc": 1, "start": "2022-03-10 20:24:36.099925", "stderr": "Traceback (most recent call last):\n  File \"/library/lokole/venv/bin/manage.py\", line 9, in <module>\n    from flask_migrate import MigrateCommand\n  File \"/library/lokole/venv/lib/python3.9/site-packages/flask_migrate/__init__.py\", line 6, in <module>\n    from flask import current_app\n  File \"/library/lokole/venv/lib/python3.9/site-packages/flask/__init__.py\", line 19, in <module>\n    from . import json\n  File \"/library/lokole/venv/lib/python3.9/site-packages/flask/json/__init__.py\", line 15, in <module>\n    from itsdangerous import json as _json\nImportError: cannot import name 'json' from 'itsdangerous' (/library/lokole/venv/lib/python3.9/site-packages/itsdangerous/__init__.py)", "stderr_lines": ["Traceback (most recent call last):", "  File \"/library/lokole/venv/bin/manage.py\", line 9, in <module>", "    from flask_migrate import MigrateCommand", "  File \"/library/lokole/venv/lib/python3.9/site-packages/flask_migrate/__init__.py\", line 6, in <module>", "    from flask import current_app", "  File \"/library/lokole/venv/lib/python3.9/site-packages/flask/__init__.py\", line 19, in <module>", "    from . import json", "  File \"/library/lokole/venv/lib/python3.9/site-packages/flask/json/__init__.py\", line 15, in <module>", "    from itsdangerous import json as _json", "ImportError: cannot import name 'json' from 'itsdangerous' (/library/lokole/venv/lib/python3.9/site-packages/itsdangerous/__init__.py)"], "stdout": "", "stdout_lines": []}

CC: @nzola

Refs:

- #2833
- #2986
- #3047

**Comment by holta** [comment]
Another failure was reported overnight, on 32-bit RasPiOS on her RPi 4:

- #3133

(Whereas this #3132 occurred on 64-bit RasPiOS on my RPi 4.)

**Comment by holta** [comment]
This issue appears likely solved by...

- PR #3149

But @jvonau can confirm.

**Comment by jvonau** [comment]
@nzola mentioned a successful install, just wondering where the iiab-diagnostics info is at.

**Comment by nzola** [comment]
COMPLETE! Your diagnostics file (164K, 2354 lines) is:

   /etc/iiab/diag/8.0_raspbian-11_2022-03-29_02:02:15_BST_Nzola

Publish it to a web pastebin? [Y/n] y

PUBLISHING TO URL... http://sprunge.us/muPIRd

**Comment by jvonau** [comment]
Looks good at a glance, issue should be closed, revert when fixed upstream. @holta Might want to clone the upstream repo in place of using what is available on pypi for the install source.

**Comment by holta** [comment]
> revert when fixed upstream.

Ok

> @holta Might want to clone the upstream repo in place of using what is available on pypi for the install source.

Possibly wait until Lokole itself is revised?

**Comment by holta** [comment]
Thanks @nzola and @jvonau for pushing this forward.

And the new person too, if they choose to participate.

(We have enough orphans in this world already!)

**Comment by jvonau** [comment]
> > @holta Might want to clone the upstream repo in place of using what is available on pypi for the install source.
> 
> Possibly wait until Lokole itself is revised?

No, I don't think upstream will ever be released on pypi again until somebody tags a new release so the most recent changes in git will not be used in the install. I would always just clone the git source bypassing the need for released packaged versions to be updated.

**Comment by holta** [comment]
@nzola is your new person going to fix the requirements.txt file soon, as Jerry outlined on ascoderu/lokole#585 here?

- https://github.com/ascoderu/lokole/issues/585 ?

> I would always just clone the git source bypassing the need for released packaged versions to be updated.

Quite possibly IIAB should clone from ascoderu/lokole's master branch (during IIAB installation) in general, to tighten the feedback loop allowing for more responsive Lokole QA.  I'd be in favor if @jvonau wants to go that route.

If so, all 3 of IIAB's pip installs of Lokole would presumably be commented out hereunder?

https://github.com/iiab/iiab/blob/4ede465c232c94862370e39bd8d875535a24e071/roles/lokole/tasks/install.yml#L38-L67

**Comment by jvonau** [comment]
No, just don't pin the install to a git hash, tinker with line 43 (use other roles as a model) and comment out 47 <-> 67

**Comment by holta** [comment]
To the new person working with @nzola:

If I'm understanding @jvonau correctly, he may be suggesting changing...

https://github.com/iiab/iiab/blob/4ede465c232c94862370e39bd8d875535a24e071/roles/lokole/tasks/install.yml#L43 to something like...

```
    name: "git+https://github.com/ascoderu/lokole.git#egg=opwen_email_client"
```

**Comment by jvonau** [comment]
To @holta as maintainer it's up to you to approve any changes, you could fix this yourself if you chose to.

**Comment by holta** [comment]
During today's http://minutes.iiab.io weekly call, @jvonau recommends closing this for now.

Awaiting the upstream fix here soon hopefully:

- ascoderu/lokole#585

**Comment by jvonau** [comment]
#3276
