### ISSUE TITLE
Test + Streamline RACHEL-style http://10.10.10.10 instead of http://172.18.96.1 — alongside {box/, http://box, http://box.lan}

### ISSUE THREAD

**Issue by holta** [iiab/iiab#3170]
This can happen in 2023 or possibly beforehand as part of IIAB 8.0 much sooner, e.g. depending on popular demand (e.g. if more and more educators keep transitioning from RACHEL to Internet-in-a-Box, who all seem to want that!)

In short, whether http://10.10.10.10 should be an option or become mainline remains to be seen.

In any case, this would certainly depend on many things.  Including for example (a) testing with internal and external hotspots, (b) sanity-checking all current uses of 172.18.96.1 and associated masks etc &mdash; and (c) validating that any new arrangement works well with standard short URL's like:

1. `box/`
2. http://box
3. http://box.lan

**Comment by jvonau** [comment]
This was pretty much soft-coded from the start, should be straight forward.

**Comment by jvonau** [comment]
#3264

**Comment by holta** [comment]
Done:

- PR #3281
- PR #3299
