### ISSUE TITLE
having a wrong and unused value for map_catalog_url in vars/default_var.yml is confusing

### ISSUE THREAD

**Issue by tim-moody** [iiab/iiab#3193]
either set it to the correct value and make it definitive (my preference)
or remove it

**Comment by tim-moody** [comment]
it is made worse by the incorrect comment in role osm install line 15

**Comment by holta** [comment]
PR #3165 was just merged so comments are in transition.

I'll work to make them accurate, though it seems @jvonau has likely already done that here, if this PR (or very similar) moves forward quickly:

- PR #3192

Concrete examples of variable values are very useful in comments to some of us &mdash; but I do agree they should say "e.g." whenever possible, for those who are too busy to check the actual variable value in `ROLE/defaults/main.yml` and similar places.

RECAP &mdash; not everyone agrees with what's stated hereunder, but yes the sentiment is well understood and respected:

- #3194

**Comment by tim-moody** [comment]
I don't see vars/default_vars.yml in any of the current PRs

**Comment by holta** [comment]
> I don't see vars/default_vars.yml in any of the current PRs

FWIW @jvonau has proposed changes to vars/default_vars.yml in his PR here:

- PR #3192

(Hopefully @georgejhunt can also weigh in, whatever's desired!)

**Comment by holta** [comment]
No longer an issue, right?
