### ISSUE TITLE
iiab-hotspot-on|off should tell you if 'can_be_ap: False' -- also move it from templates/network to templates/hostapd

### ISSUE THREAD

**Issue by holta** [iiab/iiab#3224]
Thanks @tim-moody for the suggestion.

This tkt is just a placeholder so we don't forget.

Building on:

- PR #3222

Somewhat related:

- #1520
- PR #3179
  - Originally: PR #3173
  - PR #3226
- Roll-up PR #3216

**Comment by jvonau** [comment]
now in master, implemented with
7c72b2f983e24009428dc68bb17febf3d28f6020
35750850ac3c387b3a356371440ff48138f64123
