### ISSUE TITLE
Admin Console's GET-SPACE-AVAIL sometimes fails

### ISSUE THREAD

**Issue by tim-moody** [iiab/iiab#3231]
This caused Linux Mint 20.3 to become unstable - kept refreshing the Desktop.

This issue seems to be related to disk space.

But in my case the 16GB SSD running the O/S and iiab had 2.2GB free space left on it.

However there was also an external USB carrying the library files which had 0 bytes left on it.  But I don't see why after freeing up some space the issue was still there after a reboot?

![image](https://user-images.githubusercontent.com/106379847/170728082-f9dc967d-3fd9-423c-9cdf-4754cfb44cb5.png)

_Originally posted by @andrewclark5 in https://github.com/iiab/iiab/issues/3106#issuecomment-1139715863_

**Comment by tim-moody** [comment]
https://github.com/iiab/iiab/issues/3106#issuecomment-1140787150

**Comment by tim-moody** [comment]
https://github.com/iiab/iiab/issues/3106#issuecomment-1141095253

**Comment by tim-moody** [comment]
https://github.com/iiab/iiab/issues/3106#issuecomment-1140529868

**Comment by tim-moody** [comment]
GET-STORAGE-INFO used lsblk and was notoriously unreliable when parsed. GET-SPACE-AVAIL is its replacement and only uses df. The former is still available in utilities, but is just displayed and not parsed.

**Comment by tim-moody** [comment]
As far as I know df only generates an error on Mint and only there if the desktop is used as root. I am not clear if double mounting will cause a problem for parsing df output, but I would avoid it.

**Comment by tim-moody** [comment]
I tried df -a and df -m. Both gave the same error.

**Comment by tim-moody** [comment]
df -x fuse.portal may solve the problem. put into LinuxMint.yml

**Comment by jvonau** [comment]
`mount | grep portal` to check

**Comment by holta** [comment]
> df -x fuse.portal may solve the problem. put into [Linux%20Mint.yml](https://github.com/iiab/iiab-admin-console/blob/master/vars/Linux%20Mint.yml)

Related:

- https://github.com/iiab/iiab/blob/master/vars/linuxmint-20.yml
- https://github.com/iiab/iiab/blob/master/vars/linuxmint-21.yml

> `mount | grep portal` to check

Thanks @andrewclark5 for helping us get much closer to solving this &mdash; during IIAB's community call (http://minutes.iiab.io) over the past 2 h.

Tangentially related:

- https://github.com/iiab/iiab-admin-console/issues/493

**Comment by jvonau** [comment]
https://github.com/codemicro/bar/commit/5675c40295d6edeeb742786f129cb609cc1508e1

**Comment by tim-moody** [comment]
>Tangentially related:

one has to do with adm cons and the other with menuing, one with df and the other with ajax. why clutter up this issue with that one?

**Comment by holta** [comment]
> one has to do with adm cons and the other with menuing

Yes.  These are the 2 issues @andrewclark5 cares about most for Malawi and that's noteworthy for some of us.

**Comment by holta** [comment]
@andrewclark5 FYI this `df` workaround was merged 35min ago:

- PR iiab/iiab-admin-console#495

_So if you install the [very latest IIAB 8.0 pre-release](https://download.iiab.io/) onto Linux Mint 20.3, we strongly suspect the problem is now solved._

**Comment by holta** [comment]
Progress is ongoing:

- #3247
- iiab/iiab-admin-console#502
- PR iiab/iiab-admin-console#503

**Comment by tim-moody** [comment]
https://github.com/iiab/iiab-admin-console/pull/503 merged
