### ISSUE TITLE
debian:  [WARNING]: Consider using yum, dnf or zypper module rather than running rpm

### ISSUE THREAD

**Issue by arky** [iiab/iiab#325]
Harmless warning from Ansible. Report from nightly Jenkins CI run. Please kindly close the bug if it is low priority.  

==> debian: 
==> debian: TASK [network : Checking for NetworkManager-config-server] *********************
==> debian: changed: [127.0.0.1]
==> debian:  [WARNING]: Consider using yum, dnf or zypper module rather than running rpm
==> debian: 
==> debian: TASK [network : Found Checking for NetworkManager-config-server] ***************
==> debian: skipping: [127.0.0.1]
==> debian:

**Comment by holta** [comment]
@jvonau & @arky please re-open if this is important!
