### ISSUE TITLE
Workaround leads to need for cascading changes

### ISSUE THREAD

**Issue by jvonau** [iiab/iiab#3268]
### Expected behavior and actual behavior:
Error reported remoteit role fails on Linux Mint ["Your OS or distribution is not supported by this install script."] #3199
https://github.com/iiab/iiab/issues/3106#issuecomment-1146659973 https://github.com/iiab/iiab/issues/3106#issuecomment-1146663307 https://github.com/iiab/iiab/issues/3106#issuecomment-1146681454 https://github.com/iiab/iiab/issues/3106#issuecomment-1146683602

The workaround employed in #3201 and leaving the workaround in place led to requiring other changes in the ecosystem:
use iiab fact os instead of ansible distribution [#496](https://github.com/iiab/iiab-admin-console/pull/496)
using iiab facts means raspbian is its own os [#499]( https://github.com/iiab/iiab-admin-console/pull/499)

The takeaway is the 'fix' permanently altered what OS ansible detected in "ansible_distribution", this might come back to haunt the future in some unforeseen way, the line should be removed prior to leaving the install.yml task.

**Comment by tim-moody** [comment]
>The takeaway is the 'fix' permanently altered what OS ansible detected in "ansible_distribution"

sorry, don't understand at all; how was ansible's os parsing changed?

**Comment by jvonau** [comment]
The addition of "IIAB_LIKE=Ubuntu" in /etc/os-release by the remoteit role lead to the different behavior between Tim's and Andrew's [installs](https://github.com/iiab/iiab/issues/3106#issuecomment-1146663307), the difference being the addition of the one line leading to the change in reporting within "ansible_distribution" by ansible. This could confuse other installers that parse /etc/os-release also.

**Comment by tim-moody** [comment]
iiab should not be modifying /etc/os-release. fyi, on my vm I have

NAME="Linux Mint"
VERSION="20.3 (Una)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 20.3"
VERSION_ID="20.3"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=una
UBUNTU_CODENAME=focal

on my nuc I have

NAME="Linux Mint"
VERSION="20.3 (Una)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 20.3"
VERSION_ID="20.3"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=una
UBUNTU_CODENAME=focal

still not sure why you mentioned 496 and 499 as neither modifies a system file.

**Comment by tim-moody** [comment]
rereading this I wonder why or even how ansible would use a non-canonical parameter, IIAB_LIKE to determine the OS.

**Comment by holta** [comment]
> rereading this I wonder why or even how ansible would use a non-canonical parameter, IIAB_LIKE to determine the OS.

Indeed, Ansible is very sloppy in this regard.  I'll make the fix.

**Comment by jvonau** [comment]
Think the difference is the only entry in /etc/os-release that begins with an uppercase letter would be 'NAME' with the 'fix' there would be 2.

**Comment by jvonau** [comment]
> still not sure why you mentioned 496 and 499 as neither modifies a system file.

Changes you had to make to get the df fix into Andrew's machine when "ansible_distribution" was wrong because of the remoteit workaround being present.

**Comment by jvonau** [comment]
> Indeed, Ansible is very sloppy in this regard. I'll make the fix.

No, the workaround was sloppy.

**Comment by tim-moody** [comment]
>Changes you had to make to get the df fix into Andrew's machine when "ansible_distribution" was wrong because of the remoteit workaround being present.

think it was wrong on mint even without remoteit, but hard to reconstruct

**Comment by holta** [comment]
Thanks @jvonau for confirming.

Ansible like remote.it are both very crude in using secret sauce to rather blindly scan wholesale for 'Ubuntu' instead of 'ubuntu' across the entire /etc/os-release (as their OS detection mechanism) but now we now.

Problem is now solved and tested:

- PR #3269

**Comment by jvonau** [comment]
> > Changes you had to make to get the df fix into Andrew's machine when "ansible_distribution" was wrong because of the remoteit workaround being present.
> 
> think it was wrong on mint even without remoteit, but hard to reconstruct

Not really, on the VM where 'Linux Mint' was detected try:
`cd /opt/iiab/iiab && ansible -i ansible_hosts localhost -m setup -c local | grep distribution`
sample output from 22.04
```
        "ansible_distribution": "Ubuntu",
        "ansible_distribution_file_parsed": true,
        "ansible_distribution_file_path": "/etc/os-release",
        "ansible_distribution_file_variety": "Debian",
        "ansible_distribution_major_version": "22",
        "ansible_distribution_release": "jammy",
        "ansible_distribution_version": "22.04",
```
as a test I added IIAB_LIKE=Debian to /etc/os-release on my 22.04 VM
```
ubuntu@libraryimg:/opt/iiab/iiab$ ansible -i ansible_hosts localhost -m setup -c local | grep distribution
        "ansible_distribution": "Debian",
        "ansible_distribution_file_parsed": true,
        "ansible_distribution_file_path": "/etc/os-release",
        "ansible_distribution_file_variety": "Debian",
        "ansible_distribution_major_version": "22",
        "ansible_distribution_release": "Jammy Jellyfish",
        "ansible_distribution_version": "22.04",
```

**Comment by jvonau** [comment]
There is a bit of a standard for [/etc/os-release](https://www.freedesktop.org/software/systemd/man/os-release.html)
