### ISSUE TITLE
debian:  [WARNING]: Consider using get_url or uri module rather than running wget

### ISSUE THREAD

**Issue by arky** [iiab/iiab#327]
Harmless warning from Ansible. Report from nightly Jenkins CI run. Please kindly close the bug if it is low priority.

==> debian: skipping: [127.0.0.1] => (item=[]) 
==> debian: 
==> debian: TASK [2-common : Download usbmount -- not in debian-9] *************************
==> debian: changed: [127.0.0.1]
==> debian:  [WARNING]: Consider using get_url or uri module rather than running wget
==> debian: 
==> debian: TASK [2-common : Install usbmount for debian-9] ********************************
==> debian: changed: [127.0.0.1]
==> debian: 
==> debian: TASK [2-common : Install packages for Debian] **********************************

**Comment by jvonau** [comment]
code merged
