### ISSUE TITLE
dnsmasq failure when installing IIAB 8.0 fast [when lxd in use]

### ISSUE THREAD

**Issue by avni** [iiab/iiab#3286]
### Expected behavior and actual behavior:
Expecting successful install. Getting: 
TASK [1-prep : Don't use stock dnsmasq systemd unit file during boot but start now] ********************************************************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Unable to start service dnsmasq: Job for dnsmasq.service failed because the control process exited with error code.\nSee \"systemctl status dnsmasq.service\" and \"journalctl -xeu dnsmasq.service\" for details.\n"}

PLAY RECAP ******************************************************************************
127.0.0.1                  : ok=34   changed=13   unreachable=0    failed=1    skipped=2    rescued=0    ignored=0   

### Steps to reproduce the problem:
curl iiab.io/fast.txt | sudo bash -s 3173

### IIAB version, OS version, hardware details:
**IIAB:** 
IIAB 8.0 (http://iiab.io/fast.txt)

**OS:** 
iiab-admin@pete-SEi:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04 LTS
Release:	22.04
Codename:	jammy

**Hardware:** 
iiab-admin@pete-SEi:~$ lshw
WARNING: you should run this program as super-user.
stow-vm4-zero-pr3173        
    description: Computer
    width: 64 bits
    capabilities: smp vsyscall32
  *-core
       description: Motherboard
       physical id: 0
     *-memory
          description: System memory
          physical id: 0
          size: 24GiB
     *-cpu
          product: Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
          vendor: Intel Corp.
          physical id: 1
          bus info: cpu@0
          version: 6.142.10
          size: 1516MHz
          capacity: 4100MHz
          width: 64 bits

### Please run the `iiab-diagnostics` command, to generate a URL summarizing your IIAB configuration, for volunteers seeking to help you: (Include that short URL here, Thanks!)

http://sprunge.us/GAjsXP

**Comment by holta** [comment]
networkd-dispatcher error `ERROR:Unknown state for interface NetworkctlListState` for each of the 4 network interfaces — excerpted from http://sprunge.us/GAjsXP?en :

```
1187 COMMAND: /usr/bin/sudo journalctl -b 0 -u networkd-dispatcher    # networkd-dispatcher log
1188 
1189 Jul 04 01:01:55 pete-SEi systemd[1]: Starting Dispatcher daemon for systemd-networkd...
1190 Jul 04 01:02:00 pete-SEi networkd-dispatcher[727]: No valid path found for iw
1191 Jul 04 01:02:00 pete-SEi networkd-dispatcher[913]: WARNING: systemd-networkd is not running, output will be incomplete.
1192 Jul 04 01:02:00 pete-SEi networkd-dispatcher[727]: ERROR:Unknown state for interface NetworkctlListState(idx=1, name='lo', type='loopback', operational='n/a', administrative='unmanaged'): n/a
1193 Jul 04 01:02:00 pete-SEi networkd-dispatcher[727]: Traceback (most recent call last):
1194 Jul 04 01:02:00 pete-SEi networkd-dispatcher[727]:   File "/usr/bin/networkd-dispatcher", line 298, in trigger_all
1195 Jul 04 01:02:00 pete-SEi networkd-dispatcher[727]:     self.handle_state(iface_name,
1196 Jul 04 01:02:00 pete-SEi networkd-dispatcher[727]:   File "/usr/bin/networkd-dispatcher", line 348, in handle_state
1197 Jul 04 01:02:00 pete-SEi networkd-dispatcher[727]:     raise UnknownState(operational_state)
1198 Jul 04 01:02:00 pete-SEi networkd-dispatcher[727]: UnknownState: n/a
1199 Jul 04 01:02:00 pete-SEi networkd-dispatcher[727]: ERROR:Unknown state for interface NetworkctlListState(idx=2, name='enp1s0', type='ether', operational='n/a', administrative='unmanaged'): n/a
1200 Jul 04 01:02:00 pete-SEi networkd-dispatcher[727]: Traceback (most recent call last):
1201 Jul 04 01:02:00 pete-SEi networkd-dispatcher[727]:   File "/usr/bin/networkd-dispatcher", line 298, in trigger_all
1202 Jul 04 01:02:00 pete-SEi networkd-dispatcher[727]:     self.handle_state(iface_name,
1203 Jul 04 01:02:00 pete-SEi networkd-dispatcher[727]:   File "/usr/bin/networkd-dispatcher", line 348, in handle_state
1204 Jul 04 01:02:00 pete-SEi networkd-dispatcher[727]:     raise UnknownState(operational_state)
1205 Jul 04 01:02:00 pete-SEi networkd-dispatcher[727]: UnknownState: n/a
1206 Jul 04 01:02:00 pete-SEi networkd-dispatcher[727]: ERROR:Unknown state for interface NetworkctlListState(idx=3, name='wlp3s0', type='wlan', operational='n/a', administrative='unmanaged'): n/a
1207 Jul 04 01:02:00 pete-SEi networkd-dispatcher[727]: Traceback (most recent call last):
1208 Jul 04 01:02:00 pete-SEi networkd-dispatcher[727]:   File "/usr/bin/networkd-dispatcher", line 298, in trigger_all
1209 Jul 04 01:02:00 pete-SEi networkd-dispatcher[727]:     self.handle_state(iface_name,
1210 Jul 04 01:02:00 pete-SEi networkd-dispatcher[727]:   File "/usr/bin/networkd-dispatcher", line 348, in handle_state
1211 Jul 04 01:02:00 pete-SEi networkd-dispatcher[727]:     raise UnknownState(operational_state)
1212 Jul 04 01:02:00 pete-SEi networkd-dispatcher[727]: UnknownState: n/a
1213 Jul 04 01:02:00 pete-SEi networkd-dispatcher[727]: ERROR:Unknown state for interface NetworkctlListState(idx=4, name='br-enp1s0', type='bridge', operational='n/a', administrative='unmanaged'): n/a
1214 Jul 04 01:02:00 pete-SEi networkd-dispatcher[727]: Traceback (most recent call last):
1215 Jul 04 01:02:00 pete-SEi networkd-dispatcher[727]:   File "/usr/bin/networkd-dispatcher", line 298, in trigger_all
1216 Jul 04 01:02:00 pete-SEi networkd-dispatcher[727]:     self.handle_state(iface_name,
1217 Jul 04 01:02:00 pete-SEi networkd-dispatcher[727]:   File "/usr/bin/networkd-dispatcher", line 348, in handle_state
1218 Jul 04 01:02:00 pete-SEi networkd-dispatcher[727]:     raise UnknownState(operational_state)
1219 Jul 04 01:02:00 pete-SEi networkd-dispatcher[727]: UnknownState: n/a
1220 Jul 04 01:02:00 pete-SEi systemd[1]: Started Dispatcher daemon for systemd-networkd.

**Comment by avni** [comment]
This may be due to me running 'sudo iiab' post-install on the host machine instead of the VM (though I think technically the install should work on both).

**Comment by holta** [comment]
> on the host machine instead of the VM

I've confirmed an IIAB install was accidentally attempted on the host PC instead of the VM starting 10:01 am EDT this morning!  This might seem regrettable, but in fact it's an incredible learning opportunity.  Here's why:

Very unexpectedly IIAB's install (very thankfully!!) failed on this Ubuntu Desktop 22.04 host PC &mdash; and failed **very early on** during IIAB's install (incredible convenient!!) so as to cause very little damage.

_I'd love to understand why_ :smile:

Until then, here are a couple observations + suggestions to help unroll (undo) the accidental changes to the host PC:

```
iiab-admin@pete-SEi:~$ systemctl status dnsmasq
× dnsmasq.service - dnsmasq - A lightweight DHCP and caching DNS server
     Loaded: loaded (/lib/systemd/system/dnsmasq.service; disabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Mon 2022-07-04 10:27:39 EDT; 6h ago
    Process: 22775 ExecStartPre=/etc/init.d/dnsmasq checkconfig (code=exited, status=0/SUCCESS)
    Process: 22783 ExecStart=/etc/init.d/dnsmasq systemd-exec (code=exited, status=2)
        CPU: 17ms

iiab-admin@pete-SEi:~$ sudo journalctl -u dnsmasq
Jul 04 10:27:35 stow-vm4-zero-PR3173 systemd[1]: Starting dnsmasq - A lightweight DHCP and caching DNS server...
Jul 04 10:27:35 stow-vm4-zero-PR3173 dnsmasq[22503]: dnsmasq: failed to create listening socket for port 53: Address already in use
Jul 04 10:27:35 stow-vm4-zero-PR3173 dnsmasq[22503]: failed to create listening socket for port 53: Address already in use
Jul 04 10:27:35 stow-vm4-zero-PR3173 dnsmasq[22503]: FAILED to start up
Jul 04 10:27:35 stow-vm4-zero-PR3173 systemd[1]: dnsmasq.service: Control process exited, code=exited, status=2/INVALIDARGUMENT
Jul 04 10:27:35 stow-vm4-zero-PR3173 systemd[1]: dnsmasq.service: Failed with result 'exit-code'.
Jul 04 10:27:35 stow-vm4-zero-PR3173 systemd[1]: Failed to start dnsmasq - A lightweight DHCP and caching DNS server.
Jul 04 10:27:39 stow-vm4-zero-PR3173 systemd[1]: Starting dnsmasq - A lightweight DHCP and caching DNS server...
Jul 04 10:27:39 stow-vm4-zero-PR3173 dnsmasq[22783]: dnsmasq: failed to create listening socket for 10.161.33.1: Address already in use
Jul 04 10:27:39 stow-vm4-zero-PR3173 dnsmasq[22783]: failed to create listening socket for 10.161.33.1: Address already in use
Jul 04 10:27:39 stow-vm4-zero-PR3173 dnsmasq[22783]: FAILED to start up
Jul 04 10:27:39 stow-vm4-zero-PR3173 systemd[1]: dnsmasq.service: Control process exited, code=exited, status=2/INVALIDARGUMENT
Jul 04 10:27:39 stow-vm4-zero-PR3173 systemd[1]: dnsmasq.service: Failed with result 'exit-code'.
Jul 04 10:27:39 stow-vm4-zero-PR3173 systemd[1]: Failed to start dnsmasq - A lightweight DHCP and caching DNS server.
```

And here are my quick suggestions for a checklist of things to try to unroll (undo) all-or-most-all traces of IIAB, prior to rebooting this host PC:

1. Remove `stow-vm4-zero-PR3173.lan`, `stow-vm4-zero-PR3173` (and maybe a few other things?) from `/etc/hosts` here:

   ```
   127.0.0.1     stow-vm4-zero-PR3173.lan localhost.localdomain localhost stow-vm4-zero-PR3173 box box.lan
   127.0.1.1       pete-SEi

   # The following lines are desirable for IPv6 capable hosts
   ::1     ip6-localhost ip6-loopback
   fe00::0 ip6-localnet
   ff00::0 ip6-mcastprefix
   ff02::1 ip6-allnodes
   ff02::2 ip6-allrouters
   ```

2. Run `hostnamectl hostname pete-SEi` to fully restore the PC's hostname.

3. Run `dnsdomainname` similar to the above, to try to remove domain `.lan`

4. Run `rm -f /etc/systemd/system/iiab-dnsmasq.service /etc/dnsmasq.d/dnsmasq-iiab`

5. ~Run `apt purge dnsmasq`~

6. Other stuff I've likely forgotten?!

7. And after a reboot of the host PC hopefully works well...  sanity check than all its Ethernet/WiFi/VM networking works... and if so then let's clean up more completely with: `sudo rm -rf /etc/iiab /opt/iiab /usr/sbin/iiab`

**Comment by jvonau** [comment]
> I'd love to understand why

From GAjsXP:
 982     inet 10.161.33.1/24 scope global mpbr0
1027 mpbr0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
1028         inet 10.161.33.1  netmask 255.255.255.0  broadcast 0.0.0.0
1101 Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
1102 tcp        0      0 10.161.33.1:53          0.0.0.0:*               LISTEN      1448/dnsmasq        
```
1469    1145 ?        00:00:00   daemon.start
1470    1331 ?        00:01:03     lxd
1471    1448 ?        00:00:00       dnsmasq
1472   19021 ?        00:00:00       virtiofsd
1473   19049 ?        00:00:00         virtiofsd
1474    1311 ?        00:00:00   lxcfs
```
lxd started dnsmasq binding 10.161.33.1 to that dnsmasq process.

> Other stuff I've likely forgotten?!

The creation of the iiab-admin user during curl on the main host machine?

**Comment by jvonau** [comment]
> Run systemctl purge dnsmasq

systemctl purge dnsmasq
Unknown command verb purge.

Good thing you wrote 'systemctl' and not 'apt', which I think is what you wanted, as apt purge might cause other apt packages to be removed.

**Comment by jvonau** [comment]
>Very unexpectedly IIAB's install (very thankfully!!) failed on this Ubuntu Desktop 22.04 host PC — and failed very early on during IIAB's install (incredible convenient!!) so as to cause very little damage.

A real install or any other PR would have done far more damage, 1-prep would of been nearly completed, than my 3173 did. I think that is a vote in favor of the revised sequencing of the network role.

**Comment by holta** [comment]
> A real install or any other PR would have done far more damage

@pickypet helped me restore the host PC an hour ago :heavy_check_mark: 

(It's in great shape and this was a very useful learning experience.)

See also:

- #3173

**Comment by jvonau** [comment]
#3264

**Comment by jvonau** [comment]
The cause seems to be user error. What is the outstanding issue here?

**Comment by holta** [comment]
> The cause seems to be user error. What is the outstanding issue here?

Systemic user error indeed.

Many people make this kind of mistake &mdash; when they have many terminal windows open on the screen, and are in a hurry &mdash; typically when using `multipass shell name-of-vm` especially (as they do not notice when their VM reboots, leading them to run dangerous commands on their host machine w/o realizing it...)

Best we can do is try to educate people who circumvent instructions (typically by running [fast.txt](https://github.com/iiab/iiab-factory/blob/master/fast.txt) or [risky.txt](https://github.com/iiab/iiab-factory/blob/master/risky.txt), instead of [install.txt](https://github.com/iiab/iiab-factory/blob/master/install.txt)) so that they understand that it's their own doing when they shoot themselves in the foot.
