### ISSUE TITLE
Calibre install problems on CentOS

### ISSUE THREAD

**Issue by georgejhunt** [iiab/iiab#336]
The medium local_vars has calibre enabled. Causes runansible to fail

**Comment by holta** [comment]
@georgejhunt & @jvonau can I close this?

**Comment by jvonau** [comment]
Let's revisit with a CentOS on hadron in the future, I suspect with the revised systemd unit file with the latest calibre revisions should take care of this.

**Comment by holta** [comment]
Thanks.  Am deferring to IIAB 6.6

**Comment by holta** [comment]
@georgejhunt please update or close your ticket, if possible?

Thanks, as [IIAB 6.6](http://download.iiab.io/6.6/) release is now converging!

**Comment by georgejhunt** [comment]
I guess we are deciding to remove centos from our supported OS's, or we no longer have the resources to keep up with the churn.
