### ISSUE TITLE
Mint 21 pop-up error / warning "loading /etc/profile" "sudo: a password is required"

### ISSUE THREAD

**Issue by holta** [iiab/iiab#3404]
Apparently this occurs when booting all recent IIAB installs on Mint 21:

![IMG-20221016-WA0006](https://user-images.githubusercontent.com/2458907/196058812-17b5002c-5e66-474d-9879-dcab50f77cdb.jpg)

iiab-diagnostics: http://sprunge.us/FMrBYY?bash

`sudo -n` might possibly be related here:

- #3368

**Comment by avni** [comment]
Despite the warning, IIAB works as expected on these new installs.

/cc @pickypet

**Comment by holta** [comment]
As https://github.com/iiab/iiab/pull/3368#issuecomment-1253196311 mentions, `sudo -n` is explained in sudo's man page here:

> -n, --non-interactive
Avoid prompting the user for input of any kind. If a password is required for the command to run, sudo will display an error message and exit.

In short this pop-up is somewhat intentional, obviously annoying, and essentially harmless.

However if `/etc/profile*` can be refined in a future-proof way, without dragging IIAB into endless/costly per-distro customizations, this should definitely be considered.

**Comment by jvonau** [comment]
#3300

**Comment by holta** [comment]
Fixed by:

- PR #3405
