### ISSUE TITLE
roles/osm-vector-maps installs fail repeatedly when GitHub throttling or ISP peering slowdowns cause 1 of ~40 file downloads (at random) to stall

### ISSUE THREAD

**Issue by holta** [iiab/iiab#3468]
Problem occurred repeatedly all morning and again this afternoon, despite other downloads working perfectly.  On the 4th try (keep running `sudo iiab` many times ;) it finally worked!

Summary: IIAB's OSM role can fail (consistently, in a different place every time) when GitHub file downloads arrive about 1000X more slowly (and more erratically) than on other days.

Likely the problem will go away tomorrow and/or when using other ISP's?

In any case the root cause is that IIAB's OSM role needs to download about ~40 different files, and so when downloads become painfully slow and somewhat erratic, a frustrating situation arises where [roles/osm-vector-maps](https://github.com/iiab/iiab/tree/master/roles/osm-vector-maps) gets close to installing every time &mdash; but then one of those ~40 file downloads (at random) causes the entire Ansible job to fail.

(So be it.  Something to monitor if it recurs regularly.)

**Comment by holta** [comment]
Just a reminder that IIAB sets `download_timeout` for good reason, so that such ISP & mirroring glitches are properly brought to the attention of the person installing IIAB:

https://github.com/iiab/iiab/blob/e378fae876ddfe4ca14d7a39cba87ef4e28157ed/vars/default_vars.yml#L49-L50

(At the same time everyone is free to raise this number in [/etc/iiab/local_vars yml](https://wiki.iiab.io/go/FAQ#What_is_local_vars.yml_and_how_do_I_customize_it%3F) from 100 seconds to a higher number — e.g. if they use an old/unreliable/rural Internet connection — or face download/mirroring/ISP/peering issues further upstream as in this case!)

**Comment by jvonau** [comment]
One could clone the repo with a depth of 1 and then use 'copy' in place of get_url but that results in reduced space available within the system due to duplicate files being present.

**Comment by holta** [comment]
ISP/peering issue has not recurred in 2 weeks thankfully; good enough.
