### ISSUE TITLE
Calibre-Web officially desupports 32-bit ARM due to lack of Rust (like JupyterHub?)

### ISSUE THREAD

**Issue by holta** [iiab/iiab#3479]
FYI:

- https://github.com/janeczku/calibre-web/issues/2697

JupyterHub might do the same possibly?

Related:

- PR #3421
- PR #3422
- PR #3459

**Comment by holta** [comment]
32-bit RasPiOS might/possibly have Rust restored in coming weeks:

- PR piwheels/piwheels#322
- PR piwheels/piwheels#328

**Comment by jvonau** [comment]
Is this still relevant now that cryptography's wheel is now available from piwheels? Ref: #3493

**Comment by holta** [comment]
Good question:

Testing will positively confirm on 32-bit (especially) RasPiOS in coming weeks.

While most everyone (except for legacy RPi Zero W users) should very strongly consider 64-bit RasPiOS going forward.

**Comment by holta** [comment]
All cleared up.  Calibre-Web once again now runs well on 32-bit RasPiOS:

- https://github.com/iiab/iiab/pull/3422#issuecomment-1474883535
- 7db4dc54 part of PR #3496 (to be merged shortly)
