### ISSUE TITLE
Debian: [WARNING]: Consider using get_url or uri module rather than running wget

### ISSUE THREAD

**Issue by arky** [iiab/iiab#349]
Harmless warning from Ansible. Report from nightly Jenkins CI run. Please kindly close the bug if it is low priority.

> TASK [2-common : Install yum packages] ****************************************************************************************************************
> skipping: [127.0.0.1] => (item=yum-utils) 
> skipping: [127.0.0.1] => (item=createrepo) 
> skipping: [127.0.0.1] => (item=wpa_supplicant) 
> skipping: [127.0.0.1] => (item=linux-firmware) 
> skipping: [127.0.0.1] => (item=syslog) 
> skipping: [127.0.0.1] => (item=xml-common) 
> 
> TASK [2-common : Download usbmount -- not in debian-9] ************************************************************************************************
>  [WARNING]: Consider using get_url or uri module rather than running wget
> 
> changed: [127.0.0.1]
> 
> TASK [2-common : Install usbmount for debian-9] *******************************************************************************************************
> changed: [127.0.0.1]
>

**Comment by jvonau** [comment]
s/b resolved problem code has been changed
