### ISSUE TITLE
Internet Archive server not running due to javascript error

### ISSUE THREAD

**Issue by landowark** [iiab/iiab#3492]
### Expected behavior and actual behavior:

Expected behaviour: able to access internetarchive through the web gui.
Actual behaviour: got a server not available error

### Steps to reproduce the problem:

Happened on a fresh install on Raspbian.

### IIAB version, OS version, hardware details:
install_date = 2023-03-14T22:15:03Z   Current TZ: CDT

iiab: 95a69316, 3 PR's / 9 commits since tag 8.1-preview-1
    "Merge pull request #3488 from holta/iiab-diagnostics_cypress"
    https://github.com/iiab/iiab   branch: master

iiab-admin-console: 600cfb6, 1 PR's / 4 commits since tag v0.6.2
    "Merge pull request #523 from tim-moody/0.6.1-misc"
    https://github.com/iiab/iiab-admin-console   branch: master

Raspberry Pi reference 2023-02-21
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, 25e2319effa91eb95edd9d9209eb9f8a584d67be, stage2
/etc/debian-version: 11.6
display-manager? inactive   Arch1: arm64   Arch2: armhf
5.15.84-v8+ #1613 SMP PREEMPT Thu Jan 5 12:03:08 GMT 2023 unknown
Cortex-A72   CPU(s): 4   Mem: 3553 Swap: 1023
Raspberry Pi 4 Model B Rev 1.1

### Please run the `iiab-diagnostics` command, to generate a URL summarizing your IIAB configuration, for volunteers seeking to help you: (Include that short URL here, Thanks!)

I was actually able to solve the problem myself by checking the journalctl -u internetarchive which gave me:

```dweb-mirror:internetarchive Failed: Function yaml.safeDump is removed in js-yaml 4. Use yaml.dump instead```

eventually I found /opt/iiab/internetarchive/node_modules/@internetarchive/dweb-mirror/ConfigController.js.

Changing the yaml.safeDump on line 186 to yaml.dump fixed the issue.

**Comment by holta** [comment]
@mitra42 is this indeed an easy and straightforward fix?  Do you need assistance here?

> I was actually able to solve the problem myself by checking the journalctl -u internetarchive which gave me:

> dweb-mirror:internetarchive Failed: Function yaml.safeDump is removed in js-yaml 4. Use yaml.dump instead

> eventually I found /opt/iiab/internetarchive/node_modules/@internetarchive/dweb-mirror/ConfigController.js.

> Changing the yaml.safeDump on line 186 to yaml.dump fixed the issue.

@landowark huge thanks for reporting your experience! 💯

**Comment by landowark** [comment]
Everything seems to be running okay. Thanks.

**Comment by mitra42** [comment]
Thanks for catching this landowark done and pushed v0.2.95.

**Comment by holta** [comment]
THANKS @mitra42 & @landowark 🙏
