### ISSUE TITLE
using the presence of library.xml means kiwix install can fail permanently

### ISSUE THREAD

**Issue by tim-moody** [iiab/iiab#35]
if the kiwix install fails after library.xml has been copied it will not be attempted again

**Comment by holta** [comment]
@tim-moody can we resolve this now?

(With an associated PR ideally?)

**Comment by holta** [comment]
Possibly related:

PR #153 (check for existence of index dir when creating library.xml) ...was merged during mid-August http://OFF.NETWORK hackathon.

**Comment by tim-moody** [comment]
not addressed and #153 is unrelated

**Comment by jvonau** [comment]
Should be addressed by #213 #241

**Comment by holta** [comment]
@jvonau confirms this is fixed.
