### ISSUE TITLE
kolibri global vars

### ISSUE THREAD

**Issue by tim-moody** [iiab/iiab#3506]
kolibri_home and kolibri_user should be in default_vars so they can be used outside of the kolibri role

**Comment by holta** [comment]
This is largely a matter of advertising usage to people who might want that right?

It's certainly possible that https://github.com/iiab/iiab/wiki/IIAB-Variables#order-of-execution-and-precedence might not be 100% correct in its ordering (if anybody sees flaws there!?)

But either way values set in [/etc/iiab/local_vars.yml](https://wiki.iiab.io/go/FAQ#What_is_local_vars.yml_and_how_do_I_customize_it%3F) should dominate over values set in either [/opt/iiab/iiab/vars/default_vars.yml](https://github.com/iiab/iiab/blob/master/vars/default_vars.yml) or [/opt/iiab/iiab/roles/kolibri/defaults/main.yml](https://github.com/iiab/iiab/blob/master/roles/kolibri/defaults/main.yml)

Refs:

- #3504 
- PR #3505

**Comment by holta** [comment]
> advertising usage to people who might want that

i.e. so far this hasn't been an issue, but quite possibly it's now time to promote awareness of these 2 vars more widely going forward...

**Comment by tim-moody** [comment]
has nothing to do with awareness. if they are local to the kolibri role they are not visible anywhere else. at the moment I have hard coded the values. if they are put in defaults then they can be read anywhere is ansible

**Comment by holta** [comment]
Ok ✅ 

I guess that's awareness of another kind (e.g. "machine awareness").

With most all implementers still not expected to be needing these 2 vars, if I'm understanding you correctly.

**Comment by holta** [comment]
Done:

- PR #3507
