### ISSUE TITLE
Linphone sip extensions cannot be reached when iphone or desktop is locked.It seems this is a known issue.Online solutions advise to enable push notifications but still doesn’t work.Apparently a battery saving trick from Apple. I am trying to source android phones to test in meantime. I have tried Zoiper but push notification is a paid for feature.All solutions welcome. https://github.com/balusreekanth/ios-asterisk-push [Asterisk, FreePBX]

### ISSUE THREAD

**Issue by EMG70** [iiab/iiab#3512]

**Comment by holta** [comment]
Thank you @EMG70 for reporting ✅

If possible let's link to the most pragmatic Android workaround (or more real solution) if you can suggest one for IIAB's Guide below, in the coming week or so?

https://github.com/iiab/iiab/tree/master/roles/pbx#readme

cc: @lemueldsouza

**Comment by EMG70** [comment]
> Thank you @EMG70 for reporting ✅
> 
> If possible let's link to the most pragmatic Android workaround (or more real solution) if you can suggest one for IIAB's Guide below, in the coming week or so?
> 
> https://github.com/iiab/iiab/tree/master/roles/pbx#readme
> 
> cc: @lemueldsouza

OK I will look into Android solutions in the coming week.

**Comment by holta** [comment]
ASIDE: @EMG70 worked hard today trying a few different things to get Asterisk 19 or 20 working on 64-bit Raspberry Pi OS:

- #3489

Sorry it appears not to have worked out 🕊️

**Comment by holta** [comment]
Workaround / solution posted to pbx/README.adoc thanks to @EMG70 !

- PR #3533
