### ISSUE TITLE
Can I assume devices are being connected via this VPN tunnel? [home router sometimes (helpfully) resolves box to 192.168.0.x]

### ISSUE THREAD

**Issue by jvonau** [iiab/iiab#3543]
@jvonau ,Not sure this issue is related to this PR.
I have accidentally found out that if I connect my server to an ethernet cable and VPN is enabled post install, I can access iiab home page from any device connected to my Sky home router without hooking up via IIAB hotspot.
This happens across OS systems ,just tried on Debian 11 desktop,23.04 server and desktop ,same happens.
Can I assume devices are being connected via this VPN tunnel?

_Originally posted by @EMG70 in https://github.com/iiab/iiab/issues/3537#issuecomment-1516922628_

**Comment by EMG70** [comment]
Apologies,this has nothing to do with VPN indeed. I have disabled VPN but devices can still connect to IIAB via home router without connecting to iiab hotspot.
![F804E673-AE31-4965-BC78-FB9A28C79741](https://user-images.githubusercontent.com/52469992/233493920-b41a93ee-9fa1-44ca-b407-05742a9bd9cd.jpeg)
![42D6F529-C80D-4F25-A35A-76D44F1D80D2](https://user-images.githubusercontent.com/52469992/233493974-62da5c92-8b38-4639-bfbb-e909999086b6.jpeg)

**Comment by jvonau** [comment]
openvpn_enabled = True
```
6: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN group default qlen 500
    link/none 
    inet 10.8.0.46 peer 10.8.0.45/32 scope global tun0
       valid_lft forever preferred_lft forever
```
How did you turn off the vpn?

**Comment by jvonau** [comment]
https://github.com/iiab/iiab/pull/3537#issuecomment-1516985248

**Comment by holta** [comment]
@EMG70 will re-test causality when he has time tomorrow:

- His home router sometimes (helpfully!) resolves `box` to an IIAB at 192.168.0.x — while unexpected this is convenient when it happens — as every other device in his house can then browse to http://box (suddenly without having to type in http://192.168.0.33 or http://192.168.0.38 !)

- Tomorrow he will try to verify under what exact conditions this happens (and under what exact conditions this does not happen!)

- _@EMG70 please also verify that all other devices in the house... that happen to be named "box" ...are turned off ?_

**Comment by EMG70** [comment]
It was DHCP enabled in my router . I disabled it and couldn’t access box/ via home router as before.
I think it’s a good feature though, people can still access their mobile data and have access to IIAB learning at same time.Apologies for the wild goose chase.

**Comment by EMG70** [comment]
![Uploading C5ECBCBB-1270-420C-85AD-2F62345E815C.jpeg…]()

IP 192.168.0.33 is the server

**Comment by EMG70** [comment]
![2F94CAE5-542C-4146-BE81-C32B1ECDB276](https://user-images.githubusercontent.com/52469992/233543334-15f88042-2238-4c7f-940d-67d9d2ddfbe0.jpeg)

**Comment by EMG70** [comment]
Not sure about security side if iiab (open network) is accessible from an online router.

**Comment by holta** [comment]
> It was DHCP enabled in my router . I disabled it and couldn’t access box/ via home router as before.

When DHCP is enabled in your router, does toggling VPN on/off on the IIAB have any effect... on **http://box** and **box/** URL's working-or-not-working on devices throughout the house?

(Or no effect at all?)

> I think it’s a good feature though, people can still access their mobile data and have access to IIAB learning at same time.

That depends on the phone?

As mentioned below, "Mobile Data" needs to be turned off in many Samsung and Huawei phones:

http://FAQ.IIAB.IO -> "12 My Android device says "Connected, no Internet" and won't browse http://box"

**Comment by EMG70** [comment]
I can still access IIAB via my home router with VPN set to True or False.All gadgets can still access IIAB via home router.
