### ISSUE TITLE
Multi-lingual Characters (e.g. accents) mangled, perhaps due to recent Kiwix catalog changes?

### ISSUE THREAD

**Issue by holta** [iiab/iiab#3545]
@tim-moody is on top of this.  Possibly arising from new Mac-like editing / character sets in the catalog itself?  So this ticket is just a place marker until workarounds and/or longer-term solutions emerge.

(Here's just one example of mangled characters in **Admin Console > Install Content > Get ZIM Files from Kiwix** :)

![image](https://user-images.githubusercontent.com/2458907/233717562-1f485d85-c761-4671-8d77-e9eaf5881055.png)

Related:

- iiab/iiab-admin-console#530

**Comment by tim-moody** [comment]
see my comment on https://github.com/kiwix/k8s/issues/30

**Comment by holta** [comment]
Looks like Emmanuel Engelhart found the root cause:

- https://github.com/kiwix/libkiwix/issues/941

Interestingly the new catalog _file itself_ is fully correct — any idea why IIAB is acting like a browser[*] i.e. requiring http header `content-type: charset=utf-8` ?

[*] Rightly or wrongly 😄

**Comment by holta** [comment]
Workaround installed:

- PR iiab/iiab-admin-console#537

**Comment by holta** [comment]
Also now being solved upstream:

- PR kiwix/libkiwix#942
