### ISSUE TITLE
jupyterhub error

### ISSUE THREAD

**Issue by jvonau** [iiab/iiab#3553]
Noted jupyterhub error open an issue or I will.

_Originally posted by @jvonau in https://github.com/iiab/iiab/issues/3549#issuecomment-1523219241_

**Comment by jvonau** [comment]
> psutil could not be installed from sources

Long story short is that this error is very similar to #3538 solved with #3503 with PR coming

**Comment by holta** [comment]
Not sure if this applies to OS's beyond Ubuntu 23.04 and/or Python 3.11+ ?

In any case here's an example, excerpted from http://sprunge.us/r0BpIy?en :

> 2296 /opt/iiab/iiab/iiab-install.log-2023-04-25 20:12:41,271 p=5540 u=root n=ansible | TASK [jupyterhub : Break up jupyterhub/jupyterlab pip installs into 2 parts (3 packages above + 4 packages here) due to mutual dependency deadlock on some OS's] ***
2297 /opt/iiab/iiab/iiab-install.log-2023-04-25 20:13:28,310 p=5540 u=root n=ansible | fatal: [127.0.0.1]: FAILED! => {"changed": false, "cmd": ["/opt/iiab/jupyterhub/bin/pip3", "install", "--no-cache-dir", "jupyterlab", "jupyterhub_firstuseauthenticator", "jupyterhub-systemdspawner", "ipywidgets"], "msg": "stdout: Collecting jupyterlab\n  Downloading jupyterlab-3.6.3-py3-none-any.whl (8.9 MB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.9/8.9 MB 4.5 MB/s eta 0:00:00\nCollecting jupyterhub_firstuseauthenticator\n  Downloading jupyterhub_firstuseauthenticator-1.0.0-py3-none-any.whl (9.6 kB)\nCollecting jupyterhub-systemdspawner\n  Downloading jupyterhub_systemdspawner-0.17.0-py3-none-any.whl (14 kB)\nCollecting ipywidgets\n  Downloading ipywidgets-8.0.6-py3-none-any.whl (138 kB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 138.3/138.3 kB 6.4 MB/s eta 0:00:00\nCollecting ipython\n  Downloading ipython-8.12.0-py3-none-any.whl (796 kB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 796.4/796.4 kB 5.6 MB/s eta 0:00:00\nRequirement already satisfied: packaging in /opt/iiab/jupyterhub/lib/python3.11/site-packages (from jupyterlab) (23.1)\nRequirement already satisfied: tornado>=6.1.0 in /opt/iiab/jupyterhub/lib/python3.11/site-packages (from jupyterlab) (6.3.1)\nCollecting jupyter-core\n  Downloading jupyter_core-5.3.0-py3-none-any.whl (93 kB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 93.2/93.2 kB 6.1 MB/s eta 0:00:00\nCollecting jupyterlab-server~=2.19\n  Downloading jupyterlab_server-2.22.1-py3-none-any.whl (57 kB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.0/57.0 kB 5.9 MB/s eta 0:00:00\nCollecting jupyter-server<3,>=1.16.0\n  Downloading jupyter_server-2.5.0-py3-none-any.whl (366 kB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 366.8/366.8 kB 5.7 MB/s eta 0:00:00\nCollecting jupyter-ydoc~=0.2.3\n  Downloading jupyter_ydoc-0.2.4-py3-none-any.whl (5.9 kB)\nCollecting jupyter-server-ydoc~=0.8.0\n  Downloading jupyter_server_ydoc-0.8.0-py3-none-any.whl (11 kB)\nCollecting nbclassic\n  Downloading nbclassic-0.5.5-py3-none-any.whl (10.0 MB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.0/10.0 MB 5.3 MB/s eta 0:00:00\nCollecting notebook<7\n  Downloading notebook-6.5.4-py3-none-any.whl (529 kB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 529.8/529.8 kB 5.8 MB/s eta 0:00:00\nRequirement already satisfied: jinja2>=2.1 in /opt/iiab/jupyterhub/lib/python3.11/site-packages (from jupyterlab) (3.1.2)\nCollecting bcrypt\n  Downloading bcrypt-4.0.1-cp36-abi3-manylinux_2_28_aarch64.whl (583 kB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 583.6/583.6 kB 5.6 MB/s eta 0:00:00\nRequirement already satisfied: jupyterhub>=1.3 in /opt/iiab/jupyterhub/lib/python3.11/site-packages (from jupyterhub_firstuseauthenticator) (4.0.0)\nCollecting ipykernel>=4.5.1\n  Downloading ipykernel-6.22.0-py3-none-any.whl (149 kB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 150.0/150.0 kB 6.9 MB/s eta 0:00:00\nRequirement already satisfied: traitlets>=4.3.1 in /opt/iiab/jupyterhub/lib/python3.11/site-packages (from ipywidgets) (5.9.0)\nCollecting widgetsnbextension~=4.0.7\n  Downloading widgetsnbextension-4.0.7-py3-none-any.whl (2.1 MB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 5.4 MB/s eta 0:00:00\nCollecting jupyterlab-widgets~=3.0.7\n  Downloading jupyterlab_widgets-3.0.7-py3-none-any.whl (198 kB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 198.2/198.2 kB 6.2 MB/s eta 0:00:00\nCollecting comm>=0.1.1\n  Downloading comm-0.1.3-py3-none-any.whl (6.6 kB)\nCollecting debugpy>=1.6.5\n  Downloading debugpy-1.6.7-py2.py3-none-any.whl (4.9 MB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 5.3 MB/s eta 0:00:00\nCollecting jupyter-client>=6.1.12\n  Downloading jupyter_client-8.2.0-py3-none-any.whl (103 kB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 103.2/103.2 kB 6.2 MB/s eta 0:00:00\nCollecting matplotlib-inline>=0.1\n  Downloading matplotlib_inline-0.1.6-py3-none-any.whl (9.4 kB)\nCollecting nest-asyncio\n  Downloading nest_asyncio-1.5.6-py3-none-any.whl (5.2 kB)\nCollecting psutil\n  Downloading psutil-5.9.5.tar.gz (493 kB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 493.5/493.5 kB 5.6 MB/s eta 0:00:00\n  Installing build dependencies: started\n  Installing build dependencies: finished with status 'done'\n  Getting requirements to build wheel: started\n  Getting requirements to build wheel: finished with status 'done'\n  Preparing metadata (pyproject.toml): started\n  Preparing metadata (pyproject.toml): finished with status 'done'\nCollecting pyzmq>=20\n  Downloading pyzmq-25.0.2-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (865 kB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 865.6/865.6 kB 5.6 MB/s eta 0:00:00\nCollecting backcall\n  Downloading backcall-0.2.0-py2.py3-none-any.whl (11 kB)\nCollecting decorator\n  Downloading decorator-5.1.1-py3-none-any.whl (9.1 kB)\nCollecting jedi>=0.16\n  Downloading jedi-0.18.2-py2.py3-none-any.whl (1.6 MB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 5.4 MB/s eta 0:00:00\nCollecting pickleshare\n  Downloading pickleshare-0.7.5-py2.py3-none-any.whl (6.9 kB)\nCollecting prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30\n  Downloading prompt_toolkit-3.0.38-py3-none-any.whl (385 kB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 385.8/385.8 kB 5.6 MB/s eta 0:00:00\nCollecting pygments>=2.4.0\n  Downloading Pygments-2.15.1-py3-none-any.whl (1.1 MB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 5.4 MB/s eta 0:00:00\nCollecting stack-data\n  Downloading stack_data-0.6.2-py3-none-any.whl (24 kB)\nCollecting pexpect>4.3\n  Downloading pexpect-4.8.0-py2.py3-none-any.whl (59 kB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.0/59.0 kB 7.2 MB/s eta 0:00:00\nRequirement already satisfied: MarkupSafe>=2.0 in /opt/iiab/jupyterhub/lib/python3.11/site-packages (from jinja2>=2.1->jupyterlab) (2.1.2)\nCollecting platformdirs>=2.5\n  Downloading platformdirs-3.3.0-py3-none-any.whl (15 kB)\nCollecting anyio>=3.1.0\n  Downloading anyio-3.6.2-py3-none-any.whl (80 kB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 80.6/80.6 kB 8.0 MB/s eta 0:00:00\nCollecting argon2-cffi\n  Downloading argon2_cffi-21.3.0-py3-none-any.whl (14 kB)\nCollecting jupyter-events>=0.4.0\n  Downloading jupyter_events-0.6.3-py3-none-any.whl (18 kB)\nCollecting jupyter-server-terminals\n  Downloading jupyter_server_terminals-0.4.4-py3-none-any.whl (13 kB)\nCollecting nbconvert>=6.4.4\n  Downloading nbconvert-7.3.1-py3-none-any.whl (284 kB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 284.1/284.1 kB 5.9 MB/s eta 0:00:00\nCollecting nbformat>=5.3.0\n  Downloading nbformat-5.8.0-py3-none-any.whl (77 kB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.4/77.4 kB 7.8 MB/s eta 0:00:00\nRequirement already satisfied: prometheus-client in /opt/iiab/jupyterhub/lib/python3.11/site-packages (from jupyter-server<3,>=1.16.0->jupyterlab) (0.16.0)\nCollecting send2trash\n  Downloading Send2Trash-1.8.0-py3-none-any.whl (18 kB)\nCollecting terminado>=0.8.3\n  Downloading terminado-0.17.1-py3-none-any.whl (17 kB)\nCollecting websocket-client\n  Downloading websocket_client-1.5.1-py3-none-any.whl (55 kB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.9/55.9 kB 5.5 MB/s eta 0:00:00\nCollecting jupyter-server-fileid<1,>=0.6.0\n  Downloading jupyter_server_fileid-0.9.0-py3-none-any.whl (15 kB)\nCollecting ypy-websocket<0.9.0,>=0.8.2\n  Downloading ypy_websocket-0.8.4-py3-none-any.whl (10 kB)\nCollecting y-py<0.6.0,>=0.5.3\n  Downloading y_py-0.5.9-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (1.6 MB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 5.5 MB/s eta 0:00:00\nRequirement already satisfied: alembic>=1.4 in /opt/iiab/jupyterhub/lib/python3.11/site-packages (from jupyterhub>=1.3->jupyterhub_firstuseauthenticator) (1.10.4)\nRequirement already satisfied: async-generator>=1.9 in /opt/iiab/jupyterhub/lib/python3.11/site-packages (from jupyterhub>=1.3->jupyterhub_firstuseauthenticator) (1.10)\nRequirement already satisfied: certipy>=0.1.2 in /opt/iiab/jupyterhub/lib/python3.11/site-packages (from jupyterhub>=1.3->jupyterhub_firstuseauthenticator) (0.1.3)\nRequirement already satisfied: jupyter-telemetry>=0.1.0 in /opt/iiab/jupyterhub/lib/python3.11/site-packages (from jupyterhub>=1.3->jupyterhub_firstuseauthenticator) (0.1.0)\nRequirement already satisfied: oauthlib>=3.0 in /opt/iiab/jupyterhub/lib/python3.11/site-packages (from jupyterhub>=1.3->jupyterhub_firstuseauthenticator) (3.2.2)\nRequirement already satisfied: python-dateutil in /opt/iiab/jupyterhub/lib/python3.11/site-packages (from jupyterhub>=1.3->jupyterhub_firstuseauthenticator) (2.8.2)\nRequirement already satisfied: requests in /opt/iiab/jupyterhub/lib/python3.11/site-packages (from jupyterhub>=1.3->jupyterhub_firstuseauthenticator) (2.28.2)\nRequirement already satisfied: SQLAlchemy>=1.4 in /opt/iiab/jupyterhub/lib/python3.11/site-packages (from jupyterhub>=1.3->jupyterhub_firstuseauthenticator) (2.0.10)\nRequirement already satisfied: pamela in /opt/iiab/jupyterhub/lib/python3.11/site-packages (from jupyterhub>=1.3->jupyterhub_firstuseauthenticator) (1.0.0)\nCollecting babel>=2.10\n  Downloading Babel-2.12.1-py3-none-any.whl (10.1 MB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.1/10.1 MB 5.3 MB/s eta 0:00:00\nCollecting json5>=0.9.0\n  Downloading json5-0.9.11-py2.py3-none-any.whl (19 kB)\nRequirement already satisfied: jsonschema>=4.17.3 in /opt/iiab/jupyterhub/lib/python3.11/site-packages (from jupyterlab-server~=2.19->jupyterlab) (4.17.3)\nCollecting ipython-genutils\n  Downloading ipython_genutils-0.2.0-py2.py3-none-any.whl (26 kB)\nCollecting notebook-shim>=0.1.0\n  Downloading notebook_shim-0.2.3-py3-none-any.whl (13 kB)\nRequirement already satisfied: Mako in /opt/iiab/jupyterhub/lib/python3.11/site-packages (from alembic>=1.4->jupyterhub>=1.3->jupyterhub_firstuseauthenticator) (1.2.4)\nRequirement already satisfied: typing-extensions>=4 in /opt/iiab/jupyterhub/lib/python3.11/site-packages (from alembic>=1.4->jupyterhub>=1.3->jupyterhub_firstuseauthenticator) (4.5.0)\nRequirement already satisfied: idna>=2.8 in /opt/iiab/jupyterhub/lib/python3.11/site-packages (from anyio>=3.1.0->jupyter-server<3,>=1.16.0->jupyterlab) (3.4)\nCollecting sniffio>=1.1\n  Downloading sniffio-1.3.0-py3-none-any.whl (10 kB)\nRequirement already satisfied: pyopenssl in /opt/iiab/jupyterhub/lib/python3.11/site-packages (from certipy>=0.1.2->jupyterhub>=1.3->jupyterhub_firstuseauthenticator) (23.1.1)\nCollecting parso<0.9.0,>=0.8.0\n  Downloading parso-0.8.3-py2.py3-none-any.whl (100 kB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.8/100.8 kB 6.3 MB/s eta 0:00:00\nRequirement already satisfied: attrs>=17.4.0 in /opt/iiab/jupyterhub/lib/python3.11/site-packages (from jsonschema>=4.17.3->jupyterlab-server~=2.19->jupyterlab) (23.1.0)\nRequirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /opt/iiab/jupyterhub/lib/python3.11/site-packages (from jsonschema>=4.17.3->jupyterlab-server~=2.19->jupyterlab) (0.19.3)\nRequirement already satisfied: python-json-logger>=2.0.4 in /opt/iiab/jupyterhub/lib/python3.11/site-packages (from jupyter-events>=0.4.0->jupyter-server<3,>=1.16.0->jupyterlab) (2.0.7)\nCollecting pyyaml>=5.3\n  Downloading PyYAML-6.0-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (732 kB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 732.4/732.4 kB 5.6 MB/s eta 0:00:00\nCollecting rfc3339-validator\n  Downloading rfc3339_validator-0.1.4-py2.py3-none-any.whl (3.5 kB)\nCollecting rfc3986-validator>=0.1.1\n  Downloading rfc3986_validator-0.1.1-py2.py3-none-any.whl (4.2 kB)\nRequirement already satisfied: ruamel.yaml in /opt/iiab/jupyterhub/lib/python3.11/site-packages (from jupyter-telemetry>=0.1.0->jupyterhub>=1.3->jupyterhub_firstuseauthenticator) (0.17.21)\nCollecting beautifulsoup4\n  Downloading beautifulsoup4-4.12.2-py3-none-any.whl (142 kB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.0/143.0 kB 6.2 MB/s eta 0:00:00\nCollecting bleach\n  Downloading bleach-6.0.0-py3-none-any.whl (162 kB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 162.5/162.5 kB 6.0 MB/s eta 0:00:00\nCollecting defusedxml\n  Downloading defusedxml-0.7.1-py2.py3-none-any.whl (25 kB)\nCollecting jupyterlab-pygments\n  Downloading jupyterlab_pygments-0.2.2-py2.py3-none-any.whl (21 kB)\nCollecting mistune<3,>=2.0.3\n  Downloading mistune-2.0.5-py2.py3-none-any.whl (24 kB)\nCollecting nbclient>=0.5.0\n  Downloading nbclient-0.7.4-py3-none-any.whl (73 kB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.1/73.1 kB 10.8 MB/s eta 0:00:00\nCollecting pandocfilters>=1.4.1\n  Downloading pandocfilters-1.5.0-py2.py3-none-any.whl (8.7 kB)\nCollecting tinycss2\n  Downloading tinycss2-1.2.1-py3-none-any.whl (21 kB)\nCollecting fastjsonschema\n  Downloading fastjsonschema-2.16.3-py3-none-any.whl (23 kB)\nCollecting ptyprocess>=0.5\n  Downloading ptyprocess-0.7.0-py2.py3-none-any.whl (13 kB)\nCollecting wcwidth\n  Downloading wcwidth-0.2.6-py2.py3-none-any.whl (29 kB)\nRequirement already satisfied: six>=1.5 in /opt/iiab/jupyterhub/lib/python3.11/site-packages (from python-dateutil->jupyterhub>=1.3->jupyterhub_firstuseauthenticator) (1.16.0)\nRequirement already satisfied: charset-normalizer<4,>=2 in /opt/iiab/jupyterhub/lib/python3.11/site-packages (from requests->jupyterhub>=1.3->jupyterhub_firstuseauthenticator) (3.1.0)\nRequirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/iiab/jupyterhub/lib/python3.11/site-packages (from requests->jupyterhub>=1.3->jupyterhub_firstuseauthenticator) (1.26.15)\nRequirement already satisfied: certifi>=2017.4.17 in /opt/iiab/jupyterhub/lib/python3.11/site-packages (from requests->jupyterhub>=1.3->jupyterhub_firstuseauthenticator) (2022.12.7)\nRequirement already satisfied: greenlet!=0.4.17 in /opt/iiab/jupyterhub/lib/python3.11/site-packages (from SQLAlchemy>=1.4->jupyterhub>=1.3->jupyterhub_firstuseauthenticator) (2.0.2)\nCollecting aiofiles<23,>=22.1.0\n  Downloading aiofiles-22.1.0-py3-none-any.whl (14 kB)\nCollecting aiosqlite<1,>=0.17.0\n  Downloading aiosqlite-0.19.0-py3-none-any.whl (15 kB)\nCollecting ypy-websocket<0.9.0,>=0.8.2\n  Downloading ypy_websocket-0.8.3-py3-none-any.whl (10 kB)\n  Downloading ypy_websocket-0.8.2-py3-none-any.whl (10 kB)\nCollecting argon2-cffi-bindings\n  Downloading argon2_cffi_bindings-21.2.0-cp36-abi3-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (80 kB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 80.6/80.6 kB 9.8 MB/s eta 0:00:00\nCollecting executing>=1.2.0\n  Downloading executing-1.2.0-py2.py3-none-any.whl (24 kB)\nCollecting asttokens>=2.1.0\n  Downloading asttokens-2.2.1-py2.py3-none-any.whl (26 kB)\nCollecting pure-eval\n  Downloading pure_eval-0.2.2-py3-none-any.whl (11 kB)\nCollecting fqdn\n  Downloading fqdn-1.5.1-py3-none-any.whl (9.1 kB)\nCollecting isoduration\n  Downloading isoduration-20.11.0-py3-none-any.whl (11 kB)\nCollecting jsonpointer>1.13\n  Downloading jsonpointer-2.3-py2.py3-none-any.whl (7.8 kB)\nCollecting uri-template\n  Downloading uri_template-1.2.0-py3-none-any.whl (10 kB)\nCollecting webcolors>=1.11\n  Downloading webcolors-1.13-py3-none-any.whl (14 kB)\nRequirement already satisfied: cffi>=1.0.1 in /opt/iiab/jupyterhub/lib/python3.11/site-packages (from argon2-cffi-bindings->argon2-cffi->jupyter-server<3,>=1.16.0->jupyterlab) (1.15.1)\nCollecting soupsieve>1.2\n  Downloading soupsieve-2.4.1-py3-none-any.whl (36 kB)\nCollecting webencodings\n  Downloading webencodings-0.5.1-py2.py3-none-any.whl (11 kB)\nRequirement already satisfied: cryptography<41,>=38.0.0 in /opt/iiab/jupyterhub/lib/python3.11/site-packages (from pyopenssl->certipy>=0.1.2->jupyterhub>=1.3->jupyterhub_firstuseauthenticator) (40.0.2)\nRequirement already satisfied: pycparser in /opt/iiab/jupyterhub/lib/python3.11/site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi->jupyter-server<3,>=1.16.0->jupyterlab) (2.21)\nCollecting arrow>=0.15.0\n  Downloading arrow-1.2.3-py3-none-any.whl (66 kB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.4/66.4 kB 6.9 MB/s eta 0:00:00\nBuilding wheels for collected packages: psutil\n  Building wheel for psutil (pyproject.toml): started\n  Building wheel for psutil (pyproject.toml): finished with status 'error'\nFailed to build psutil\n\n:stderr:   error: subprocess-exited-with-error\n  \n  × Building wheel for psutil (pyproject.toml) did not run successfully.\n  │ exit code: 1\n  ╰─> [47 lines of output]\n      running bdist_wheel\n      running build\n      running build_py\n      creating build\n      creating build/lib.linux-aarch64-cpython-311\n      creating build/lib.linux-aarch64-cpython-311/psutil\n      copying psutil/__init__.py -> build/lib.linux-aarch64-cpython-311/psutil\n      copying psutil/_pssunos.py -> build/lib.linux-aarch64-cpython-311/psutil\n      copying psutil/_common.py -> build/lib.linux-aarch64-cpython-311/psutil\n      copying psutil/_psaix.py -> build/lib.linux-aarch64-cpython-311/psutil\n      copying psutil/_psosx.py -> build/lib.linux-aarch64-cpython-311/psutil\n      copying psutil/_psbsd.py -> build/lib.linux-aarch64-cpython-311/psutil\n      copying psutil/_pswindows.py -> build/lib.linux-aarch64-cpython-311/psutil\n      copying psutil/_compat.py -> build/lib.linux-aarch64-cpython-311/psutil\n      copying psutil/_pslinux.py -> build/lib.linux-aarch64-cpython-311/psutil\n      copying psutil/_psposix.py -> build/lib.linux-aarch64-cpython-311/psutil\n      creating build/lib.linux-aarch64-cpython-311/psutil/tests\n      copying psutil/tests/runner.py -> build/lib.linux-aarch64-cpython-311/psutil/tests\n      copying psutil/tests/__init__.py -> build/lib.linux-aarch64-cpython-311/psutil/tests\n      copying psutil/tests/test_bsd.py -> build/lib.linux-aarch64-cpython-311/psutil/tests\n      copying psutil/tests/test_system.py -> build/lib.linux-aarch64-cpython-311/psutil/tests\n      copying psutil/tests/test_windows.py -> build/lib.linux-aarch64-cpython-311/psutil/tests\n      copying psutil/tests/test_connections.py -> build/lib.linux-aarch64-cpython-311/psutil/tests\n      copying psutil/tests/__main__.py -> build/lib.linux-aarch64-cpython-311/psutil/tests\n      copying psutil/tests/test_memleaks.py -> build/lib.linux-aarch64-cpython-311/psutil/tests\n      copying psutil/tests/test_sunos.py -> build/lib.linux-aarch64-cpython-311/psutil/tests\n      copying psutil/tests/test_contracts.py -> build/lib.linux-aarch64-cpython-311/psutil/tests\n      copying psutil/tests/test_osx.py -> build/lib.linux-aarch64-cpython-311/psutil/tests\n      copying psutil/tests/test_unicode.py -> build/lib.linux-aarch64-cpython-311/psutil/tests\n      copying psutil/tests/test_posix.py -> build/lib.linux-aarch64-cpython-311/psutil/tests\n      copying psutil/tests/test_process.py -> build/lib.linux-aarch64-cpython-311/psutil/tests\n      copying psutil/tests/test_linux.py -> build/lib.linux-aarch64-cpython-311/psutil/tests\n      copying psutil/tests/test_testutils.py -> build/lib.linux-aarch64-cpython-311/psutil/tests\n      copying psutil/tests/test_aix.py -> build/lib.linux-aarch64-cpython-311/psutil/tests\n      copying psutil/tests/test_misc.py -> build/lib.linux-aarch64-cpython-311/psutil/tests\n      running build_ext\n      building 'psutil._psutil_linux' extension\n      creating build/temp.linux-aarch64-cpython-311\n      creating build/temp.linux-aarch64-cpython-311/psutil\n      aarch64-linux-gnu-gcc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_SIZEOF_PID_T=4 -DPSUTIL_VERSION=595 -DPy_LIMITED_API=0x03060000 -DPSUTIL_LINUX=1 -I/opt/iiab/jupyterhub/include -I/usr/include/python3.11 -c psutil/_psutil_common.c -o build/temp.linux-aarch64-cpython-311/psutil/_psutil_common.o\n      psutil/_psutil_common.c:9:10: fatal error: Python.h: No such file or directory\n          9 | #include <Python.h>\n            |          ^~~~~~~~~~\n      compilation terminated.\n      psutil could not be installed from sources. Perhaps Python header files are not installed. Try running:\n        sudo apt-get install gcc python3-dev\n      error: command '/usr/bin/aarch64-linux-gnu-gcc' failed with exit code 1\n      [end of output]\n  \n  note: This error originates from a subprocess, and is likely not a problem with pip.\n  ERROR: Failed building wheel for psutil\nERROR: Could not build wheels for psutil, which is required to install pyproject.toml-based projects\n"}
2298 /opt/iiab/iiab/iiab-install.log:2023-04-25 20:13:28,373 p=5540 u=root n=ansible | TASK [jupyterhub : SEE ERROR ABOVE (skip_role_on_error: False)] ****************

**Comment by jvonau** [comment]
side note nodejs repo should be removed if the curl install fails to install.

**Comment by jvonau** [comment]
https://pypi.org/project/psutil/#files

**Comment by jvonau** [comment]
https://github.com/giampaolo/psutil/issues/2206
https://github.com/giampaolo/psutil/issues/2163

**Comment by holta** [comment]
Resolved by:

- PR #3554

**Comment by whomobile** [comment]
In case any comes here to fix "#include <Python.h>" not found issue with psutils
you will need to install correct python dev lib for your python. (error message is not wrong but not correct " sudo apt-get install gcc python3-dev" if you have more than one python verion.) 

e.g. use one of following
```
apt-get install -y python3.11-dev
apt-get install -y python3.10-dev
apt-get install -y python3.12-dev
apt-get install -y python3.13-dev
```
