### ISSUE TITLE
"Disabling Captive Portal in Admin Console causes Ansible to fail"

### ISSUE THREAD

**Issue by holta** [iiab/iiab#3563]
Thank you to @EMG70 for this report!

Apparently this can be reproduced every time:

- Tick the checkbox to enable Captive Portal under http://box.lan/admin **> Configure > Internal Wi-Fi AP > Check to Enable Captive Portal**
- **Save Configuration** then Install **Configured Options**

- Remove tick from checkbox **Check to Enable Captive Portal**
- **Save Configuration** then **Install Configured Options**

Preliminary evidence:

![IMG-20230501-WA0004](https://user-images.githubusercontent.com/2458907/235498859-b2236b9e-e712-4873-b369-c735bb7bb86a.jpg)

iiab-diagnostics: http://sprunge.us/tmT0FB?en#n-2650

**Comment by holta** [comment]
If confirmed (as appears very likely, he's tried it several times!) the reason would appear to be...

...that Admin Console is presumably changing `captiveportal_install: True` to `captiveportal_install: False` in [/etc/iiab/local_vars.yml](https://wiki.iiab.io/go/FAQ#What_is_local_vars.yml_and_how_do_I_customize_it?) ?

**Comment by tim-moody** [comment]
a user could manually make the same change, regardless of whether adm cons is doing that, so the bug is in iiab

**Comment by holta** [comment]
I'm not following.

Reverting any `_install` variable from True back to False is not allowed, after that service/app is installed (and appears in /etc/iiab/iiab-state.yml).

(If this report is confirmed, then Admin Console is doing something that's not been allowed for many years now.)

**Comment by holta** [comment]
CLARIF: Admin Console appears to be trying to _uninstall_ Captive Portal, when it says it's merely _enabling/disabling_ Captive Portal.

Background: IIAB [does not allow uninstalling](https://github.com/iiab/iiab/blob/7db038c72c44ac60d14c405c45480aa14eca7f6b/vars/local_vars_small.yml#L7-L8) of any app/service.

**Comment by tim-moody** [comment]
any software that crashes on bad data has a bug. What would happen if a user made this change by editing local vars?

**Comment by holta** [comment]
Admin Console is not doing what its checkbox describes (enabling then disabling Captive Portal).

Ansible is supposed to fail when anybody tries to _uninstall_ an app/service that's already been installed in /etc/iiab/iiab_state.yml.  Nothing has changed here in many years.  Validation and documentation explains this clearly.

**Comment by holta** [comment]
I don't think there's any ambiguity here, but just FYI this /etc/iiab/iiab_state.yml behavior (disallowing the uninstall of all IIAB apps/services) was enacted in 2019.

**Comment by holta** [comment]
We can make this documentation even louder if necessary:

https://github.com/iiab/iiab/blob/7db038c72c44ac60d14c405c45480aa14eca7f6b/iiab-install#L186

**Comment by holta** [comment]
Just FYI @EMG70's report is confirmed.  Starting with:

```
root@box:~# grep ^captiveportal_ /etc/iiab/local_vars.yml
captiveportal_install: True
captiveportal_enabled: True
```

- Browse to and log in to http://box.lan/admin **> Configure > Internal Wi-Fi AP**
- Remove the tick in the checkbox to the left of **Check to Enable Captive Portal**
- Click **Save Configuration > OK**

The result is:

```
root@box:~# grep ^captiveportal_ /etc/iiab/local_vars.yml
captiveportal_install: False
captiveportal_enabled: False
```

**Comment by tim-moody** [comment]
OK. I was hung up on the word crash, now changed to fails, and the fact that the report was speculative. This clarifies.
I also ran the same test with the same results.
The problem is figuring out if install should remain True if enabled is False. That is only supposed to be the case if installed is False.
That logic is not working.

**Comment by holta** [comment]
_Thanks to @EMG70 and @tim-moody for identifying and resolving this issue:_

- PR iiab/iiab-admin-console#541

CLARIF: Admin Console now keeps `captiveportal_install: True` from reverting to `False` ( in `/etc/iiab/local_vars.yml` ) if `captiveportal_installed: True` is in `/etc/iiab/iiab_state.yml`
