### ISSUE TITLE
Calibre-web on Rpi Bookworm -  502 Bad Gateway [and 32-bit question?]

### ISSUE THREAD

**Issue by miloshev** [iiab/iiab#3755]
### Expected behavior and actual behavior: When i try to start calibre-web from the main menu it goes to a page with nginx 502 Bad Gateway
Everything else is working

### Please run the `iiab-diagnostics` command, to generate a URL summarizing your IIAB configuration, for volunteers seeking to help you: (Include that short URL here, Thanks!) 
https://dpaste.com/AFPYPWSV4

**Comment by holta** [comment]
Hi @miloshev

Coincidentally this was fixed yesterday!

Please either [upgrade](https://github.com/iiab/calibre-web/wiki#upgrading) or reinstall, Thanks.

Related:

- iiab/calibre-web#187
- PR IIAB/calibre-web#201

**Comment by holta** [comment]
@miloshev

And please reconfirm that you get Calibre-Web working, if possible?

(This would be very useful 32-bit testing for others, as you are running "armhf" as your primary OS architecture according to your iiab-diagnostics, and kernel "armv7l" according to uname !)

**Comment by miloshev** [comment]
I have tried to upgrade, but "git pull https://github.com/iiab/calibre-web --no-rebase --no-edit"
throws an error: "fatal: not a git repository (or any of the parent directories): .git"

**Comment by holta** [comment]
> fatal: not a git repository (or any of the parent directories): .git

It sounds like... you're not in the right directory?

Are you able to run all 7 commands in order, one at a time?

```
sudo -i
pipx upgrade --include-injected xklb
cd /usr/local/calibre-web-py3
git pull https://github.com/iiab/calibre-web --no-rebase --no-edit
cd /opt/iiab/iiab
git pull https://github.com/iiab/iiab --no-rebase --no-edit
./runrole --reinstall calibre-web
```

Paste a larger screenshot / photo of the error on your screen maybe?

**Comment by miloshev** [comment]
Sorry, my mistake.
Now Calibre works :)

**Comment by holta** [comment]
Huge thanks @miloshev, for confirming!

**Comment by EMG70** [comment]
IIAB -DIAGNOSTICS -https://dpaste.com/78PF7Y8QA
Tested on Raspberry Pi 3B+, IIAB small size installed.
Calibre-web working despite the slow downloads, a Playlist of 16 short videos all downloaded well.
![Screenshot 2024-06-25 at 21-47-48 Internet in a Box Tasks](https://github.com/iiab/iiab/assets/52469992/5fa77900-108f-4520-9b70-cc7962680669)

**Comment by holta** [comment]
> Tested on Raspberry Pi 3B+, IIAB small size installed.
Calibre-web working despite the slow downloads, a Playlist of 16 short videos all downloaded well.

Tremendous news:

Thank you @EMG70 for reconfirming!
