### ISSUE TITLE
Admin Console fails to change launch page http://box to WordPress

### ISSUE THREAD

**Issue by kananigit** [iiab/iiab#377]
Right now if you try to change the homepage from the admin interface the server breaks and you lose access to the homepage. I tried to change to wordpress severally but it broke each time. @jvonau  adviced that I do the change in local_vars.yml then do a runtags <wordpress>i nstead.  This worked for me but it would be nice if its fixed because it gets kinda frustrating if you don't know what is happening.

**Comment by holta** [comment]
Thx Kanani!

Can you clarify if changing "iiab_home_url: /home" to "iiab_home_url: /wordpress" in [local_vars.yml](http://wiki.laptop.org/go/IIAB/local_vars.yml) is what works for you?  (Followed by running "cd /opt/iiab/iiab; .runansible" of course :)

**Comment by jvonau** [comment]
PR #378

**Comment by kananigit** [comment]
I changed "iiab_home_url: /home" to "iiab_home_url: /wordpress" in local_vars.yml  before i did                 cd /opt/iiab/iiab; .runansible" in the first install and it worked for me.

**Comment by holta** [comment]
@tim-moody do you have time to look into this week?

**Comment by holta** [comment]
@tim-moody if possible review or improve upon #378 if this is the fix?

**Comment by holta** [comment]
@kananigit can we resolve this now, preferably with your official testing of #378 merged into master yesterday morning?  Thanks!

**Comment by holta** [comment]
@kananigit plz re-open if your issue's not resolved, Thanks!
