### ISSUE TITLE
Edit Technical Contributors wiki page to remove Wikipedia/ZIM caution

### ISSUE THREAD

**Issue by avni** [iiab/iiab#3788]
In the "[Install IIAB on a Virtual Machine](https://github.com/iiab/iiab/wiki/Technical-Contributors-Guide#install-iiab-on-a-virtual-machine)" section of the Technical Contributors guide, the following caution can be removed now that we confirmed that #3039 is working:  _"CAUTION: Content such as Wikipedia (all ZIM files) does not yet work on M1/M2/M3/M4 Macs, no matter what virtualization product you use (Multipass, Parallels, VirtualBox, VMWare or UTM). See [#3039](https://github.com/iiab/iiab/issues/3039) for more details."_

**Comment by holta** [comment]
Done!

- https://github.com/iiab/iiab/wiki/Technical-Contributors-Guide/_compare/654ed61f8815bd39326db9028bab4c08eef3e5c9...0a89fe2bbedebb650236adc5e8745ee79d45d9ed

PS instructions are also cleaned up to explain adding a DHCP IP address (e.g. 192.168.0.x) to a Multipass VM, so as to help with testing of IIAB using mobile devices.
