### ISSUE TITLE
Test balenaEtcher to clone IIAB microSD card on M1 or M2 [i.e. on Mac, and try on Windows too?]

### ISSUE THREAD

**Issue by avni** [iiab/iiab#3792]
From @holta 

Can you try BalenaEtcher on M1 or M2 to see if it will clone an IIAB microSD card without too much hassle?

Or if not, suggest any amendment to `FAQ #47` here?

https://wiki.iiab.io/index.php?title=FAQ&diff=793&oldid=792

FAQ 47 is:

"How do I back up, shrink & copy IIAB microSD cards?"

Requested date: 8/31

**Comment by holta** [comment]
@EMG70 can you likewise take a look at balenaEtcher on Windows, if you have time, this month ideally?

To see if it now offers a decent IIAB cloning approach for newcomers + newbies! 🙏

Background on balenaEtcher:

https://en.wikipedia.org/wiki/Etcher_(software)

**Comment by holta** [comment]
`FAQ #47` slightly cleaned up:

https://wiki.iiab.io/index.php?title=FAQ&diff=795&oldid=792

(If it needs to be corrected or cleaned up in coming weeks with a screenshot-or-otherwise LMK, Thanks!)

**Comment by EMG70** [comment]
The steps shown below are for cloning an  SD card of same size and model (Sandisk 128GB) using   BalenaEtcher on Windows 11 and SD card adapter (Ugreen  model used). The same procedure can be used with different sizes as long as source SD card is smaller than target SD card.
IIAB size 1 was built on the SD card.The process for cloning took 10 minutes.Both cards tested and working OK.

![Screenshot from 2024-08-27 17-19-08](https://github.com/user-attachments/assets/94b0ec3d-14f2-4241-be7a-fcc0153ef318)
![Screenshot from 2024-08-27 17-19-24](https://github.com/user-attachments/assets/fcccd489-6256-4d9c-a426-b22ea4629825)
![Screenshot from 2024-08-27 17-19-36](https://github.com/user-attachments/assets/fb16144a-ba6a-4519-93a6-730a7a455335)
![Screenshot from 2024-08-27 17-19-45](https://github.com/user-attachments/assets/d8cc9c69-3d1e-40ad-b6b4-290240b984cd)
![Screenshot from 2024-08-27 17-20-01](https://github.com/user-attachments/assets/295eedeb-1001-4bdd-9356-c5873c3fef07)
![Screenshot from 2024-08-27 17-20-30](https://github.com/user-attachments/assets/e7d40c8a-9bb5-491f-ab55-097406d2e4ed)
![Screenshot from 2024-08-27 17-20-48](https://github.com/user-attachments/assets/d293dad8-4692-4124-97db-638d2f61dd30)

The two SD cards are shown below after successful cloning as /dev/mmcblk/0p2 and /dev/sdd2
![Screenshot from 2024-08-27 17-36-03](https://github.com/user-attachments/assets/a8b4c13d-9287-45f3-a1a6-4c818f8dd36d)

**Comment by holta** [comment]
@avni has confirmed likewise (successfully duplicating / cloning an IIAB microSD card) using the macOS version of balenaEtcher !

**Comment by holta** [comment]
Many thanks to @EMG70 and @avni for the hard work of verifying this!

**Comment by avni** [comment]
It only took 4 adaptors to do the test on the M1 MacOS! So glad we were able to figure it out and make it work! ✅
