### ISSUE TITLE
Ubuntu 24.10 removed legacy apt package `wireless-tools`

### ISSUE THREAD

**Issue by holta** [iiab/iiab#3805]
We should probably reconfirm in coming days, that Ubuntu Oracular Oriole has indeed stuck with its decision to permanently remove the `wireless-tools` apt package.

Meantime, folks should be able to install IIAB by commenting out Line 35 of...

```
sudo nano /opt/iiab/iiab/roles/network/tasks/install.yml
```

In other words...

https://github.com/iiab/iiab/blob/4dd927cfd00c3bed1a36b9c197f554d7ee680ceb/roles/network/tasks/install.yml#L35

...and then continue the IIAB install, e.g. by running:

```
sudo iiab
```

Thank you to @EMG70 !

**Comment by jvonau** [comment]
Looks like the library was renamed to [libiw30t64](https://launchpad.net/ubuntu/+source/wireless-tools/30~pre9-17ubuntu2 )

**Comment by holta** [comment]
Interesting.

A name like `libiw30t64` is (presumably) not going to be standardized/available on all distros in coming years however.

**Comment by jvonau** [comment]
This is not my problem to correct, but you could start with some conditional to exclude the package on U24.10 so people do not have to hand edit files.

**Comment by holta** [comment]
Good idea.

Anything along those lines probably makes sense prior to Ubuntu 24.10's release on October 10th.

**Comment by holta** [comment]
Resolved by:

- PR #3818
