### ISSUE TITLE
[RFC] Bug Report Template 

### ISSUE THREAD

**Issue by arky** [iiab/iiab#390]
To further improve the contribution pathways, we need to add a bug report template in _docs/issue_template.md_ or _github/issue_template.md_

It would be included when someone is reporting a bug. More information [here](https://help.github.com/articles/creating-an-issue-template-for-your-repository/)
![](https://help.github.com/assets/images/help/issues/issue-template-sample.png)

Please kindly add your comments to improve this template by adding comments in this bug report. 

## Specifications like the version of the IIAB, operating system version, or hardware details.

**Comment by holta** [comment]
Self-reminder...such "code health" guidelines can+should be set here: https://github.com/iiab/iiab/community

See also: https://help.github.com/articles/setting-guidelines-for-repository-contributors/
