### ISSUE TITLE
[RFC] Pull Request Template 

### ISSUE THREAD

**Issue by arky** [iiab/iiab#391]
To further improve the contribution pathways, we need to add a Pull Request template in _docs/PULL_REQUEST_TEMPLATE_ or _.github/PULL_REQUEST_TEMPLATE_. It would be included when someone is reporting a bug. More information[ here](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/)

![](https://help.github.com/assets/images/help/pull_requests/pr-template-sample.png)

Please kindly add your comments to improve this template by adding comments in this bug report.

**Comment by holta** [comment]
Self-reminder...such stuff can+should be set here: https://github.com/iiab/iiab/community

See also: https://help.github.com/articles/setting-guidelines-for-repository-contributors/

**Comment by jvonau** [comment]
merged
