### ISSUE TITLE
Remove Unused Roles 

### ISSUE THREAD

**Issue by arky** [iiab/iiab#410]
Please remove unused roles,tasks,variables  like 'Gateway' (any others?)  from the IIAB code base. 

These regular spring cleaning helps keep the code neat and tidy. Thanks!

**Comment by holta** [comment]
Some possible candidates for removal:
- dokuwiki
- owncloud
- pathagar
- rachel
- teamviewer

_Conversely: dokuwiki & teamviewer can be brought back into service by popular demand, should implementation communities demand it in significant numbers._

**Comment by holta** [comment]
@jvonau can this be closed now?

Or is there still some 'Gateway' task/variable that needs to be removed?  I don't see any such Role.

**Comment by jvonau** [comment]
#403 was pushed
