### ISSUE TITLE
no Internet (Ethernet or WiFi) after WiFi installs

### ISSUE THREAD

**Issue by holta** [iiab/iiab#438]
WiFi installations of IIAB 6.5 do complete!  But after rebooting, Internet access is lost (via Ethernet and WiFi both).

See details @ #432 where /etc/network/interfaces.d/iiab is pasted in.

Here's one interim workaround to restore Ethernet access to the Internet:
```
rm /etc/network/interfaces.d/iiab
reboot
```
FYI this does not restore WiFi access to the Internet.  But perhaps that part is intentional?  i.e. so that IIAB's Hotspot/AP works &mdash; until we later make progress with #430 (simultaneous hotspot + client-WiFi) during the [IIAB 6.6](https://github.com/iiab/iiab/milestone/3) release cycle.

**Comment by holta** [comment]
Related if indirectly:
#197 Permit installation of IIAB over Wi-Fi instead of Ethernet
#424 RFC on moving network last
#433 Enable simultaneous Hotspot/AP & client-WiFi on RPi's internal WiFi?
#438 No Internet (Ethernet or WiFi) after WiFi installs

**Comment by jvonau** [comment]
extend [current code](https://github.com/iiab/iiab/blob/master/roles/1-prep/templates/iiab-network-reset)

**Comment by holta** [comment]
@jvonau can we close this?  (Or better to test further?)

**Comment by jvonau** [comment]
You'll have at least wired internet seemlessly

**Comment by holta** [comment]
> You'll have at least wired internet seemlessly

Great.

(As you know my personal vote is for WiFi-to-Internet to hold on until all content & glitches are resolved to the satisfaction of the implementer, but we'll try to work to streamline workflows there in due course)
