### ISSUE TITLE
Update project description 

### ISSUE THREAD

**Issue by arky** [iiab/iiab#445]
Please kindly update the project description to something meaningful instead of current "Internet in a Box - NEW VERSION originally from http://github.com/xsce http://iiab.io" 

Also add relevant tags such as 'education', 'raspberrypi', 'ansible' etc.

**Comment by holta** [comment]
https://github.com/iiab/iiab title's been refined from:

> Internet in a Box - NEW VERSION originally from http://github.com/xsce http://iiab.io

To:

> Internet-in-a-Box - build your own LIBRARY OF ALEXANDRIA with a Raspberry Pi ! http://internet-in-a-box.org

Same for the main page http://github.com/iiab, which used to say:

> Build Your Own Digital Library!

Which was short+sweet, but didn't quite explain enough... _this will surely evolve as our diverse global communities define what Internet-in-a-Box becomes :-)_
