### ISSUE TITLE
Admin Console warnings: when statements should not include jinja2 delimiters

### ISSUE THREAD

**Issue by holta** [iiab/iiab#456]
These warnings sound more serious &mdash; are they?

> TASK [cmdsrv : Download zeromq and python binding] *****************************
[WARNING]: when statements should not include jinja2 templating delimiters such as {{ }} or {% %}. Found: not {{ use_cache }} and not {{ no_network }}

> TASK [cmdsrv : Download speedtest-cli] *****************************************
[WARNING]: when statements should not include jinja2 templating delimiters such as {{ }} or {% %}. Found: not {{ use_cache }} and not {{ no_network }}

**Comment by jvonau** [comment]
ref #66

**Comment by holta** [comment]
@tim-moody is preparing a PR

**Comment by holta** [comment]
Appears resolved by https://github.com/iiab/iiab-admin-console/pull/40
