### ISSUE TITLE
Admin Console's 3 Network Parameters radio buttons [nye checkboxes!] are empty on 1st boot

### ISSUE THREAD

**Issue by holta** [iiab/iiab#481]
All 3 checkboxes are empty at http://box/admin -> Configure tab -> Network Parameters when testing against [jvonau/iiab branch merge-order4](https://github.com/jvonau/iiab/tree/merge-order4) [*] based on PR #477:

( ) Gateway
( ) Appliance
( ) LAN Controller

In the past the Gateway checkbox was filled in, on all installs from [download.iiab.io/6.5/rpi](http://download.iiab.io/6.5/rpi/) anyway.  So this is a change in behavior (none of the 3 checkboxes being ticked, on new IIAB servers).

Is this a bug that presumably needs fixing for IIAB 6.5?  Or a lower priority issue that can be documented as a [Known Issue](https://github.com/iiab/iiab/wiki/IIAB-6.5-Release-Notes#known-issues)?

[*] e.g. when installing IIAB 6.5 pre-releases on Raspbian 2017-09-07 using e.g. using [load-merge-order4-big-vpn.txt](http://download.iiab.io/6.5/rpi/load-merge-order4-big-vpn.txt)

**Comment by holta** [comment]
Side Observation:

Admin Console install times dramatically improved (about 3X faster) in recent weeks, if you use Ansible 2.4.1 on RPi3 / Raspbian Lite fully updated from 2017-09-07, with @tim-moody's latest branch cloned as follows:
```
git clone https://github.com/tim-moody/iiab-admin-console -b fixes-oct-24
```
Currently this takes about ~6MIN.  A few weeks ago the equivalent/earlier installation of Admin Console took ~17MIN on Ansible 2.4.0.  I don't know why such a huge difference.

FWIW a *re-install* of Admin Console just took 3min37s, when doing "rm -rf /opt/iiab/iiab-admin-console" followed by "git clone https://github.com/tim-moody/iiab-admin-console -b fixes-oct-24" then the usual install routine ("cd /opt/iiab/iiab-admin-console" then "./install" with Ansible 2.4.1).

**Comment by tim-moody** [comment]
due to change of  iiab_network_mode to  iiab_network_mode_applied in iiab.ini[network]

**Comment by holta** [comment]
FYI Network Parameter’s choice among 3 radio buttons is set here in @jvonau's current #486: (branch iiab-order)

https://github.com/jvonau/iiab/blob/iiab-order/roles/network/defaults/main.yml#L35

e.g. by default Line 35 shows:
```
gui_desired_network_role: Gateway
```
(From @jvonau during today's community/team call, with ongoing discussion @ http://minutes.iiab.io)

**Comment by holta** [comment]
Apparently fixed by https://github.com/iiab/iiab-admin-console/pull/41
