### ISSUE TITLE
Should "Install packages (debuntu)" & "Update common packages (debuntu)" be combined in roles/2-common/tasks/packages.yml ?

### ISSUE THREAD

**Issue by holta** [iiab/iiab#518]
Or are these 2 sections really distinct for a good reason in [master/roles/2-common/tasks/packages.yml](https://github.com/iiab/iiab/blob/master/roles/2-common/tasks/packages.yml) ?

[Line 26-36](https://github.com/iiab/iiab/blob/master/roles/2-common/tasks/packages.yml#L26-L36) use:
```
state=present
```
[Lines 96-105](https://github.com/iiab/iiab/blob/master/roles/2-common/tasks/packages.yml#L96-L105) use:
```
state=latest
```
_Or should both sections be combined into 1 single section, installing all Debuntu-family packages?_

**Comment by jvonau** [comment]
Use 'present' only would be my vote as the docs say to start with a fully updated and rebooted machine.

**Comment by holta** [comment]
PR #542 merged after carefuly review with @georgejhunt, @tim-moody, @jvonau, @holta during community/team call @ http://minutes.iiab.io

In future both exFAT packages (exfat-fuse, exfat-utils) might be moved down in [/opt/iiab/iiab/roles/2-common/tasks/packages.yml](https://github.com/iiab/iiab/blob/master/roles/2-common/tasks/packages.yml) from "Install common packages" to cover most/all OS's including CentOS/Fedora etc possibly, instead of up top in "Install packages (debuntu)".

@jvonau clarifies:

> CentOS would needed the exFAT_enabled flag set in local_vars to enable the install routine in 2-common/tasks/centos.yml. warning the 3-rd party repo has not been tested in a very long time, on a side note the rpms might be included in centos now and the repo can go away but I have not checked recently.

> so no flag no install no problem ;)
