### ISSUE TITLE
apache_user defined twice

### ISSUE THREAD

**Issue by jvonau** [iiab/iiab#54]
apache_user is defined twice in some of the vars/OS.yml files.

**Comment by tim-moody** [comment]
even better, the definitions conflict for Raspian and Ubuntu

**Comment by jvonau** [comment]
Might want to have a look at PR #56 Those OS definitions would of been overwritten in 1-prep

**Comment by jvonau** [comment]
[WARNING]: While constructing a mapping from
/opt/iiab/iiab/vars/CentOS.yml, line 1, column 1, found a duplicate
dict key (apache_user). Using last defined value only.

Guess luck had it that the correct entries were second, would be nice to get this fixed though.

**Comment by jvonau** [comment]
#6

**Comment by jvonau** [comment]
#93
