### ISSUE TITLE
Remove networking pre-req "ifupdown"

### ISSUE THREAD

**Issue by holta** [iiab/iiab#552]
This seems to be in [roles/2-common/tasks/packages.yml#L35](https://github.com/iiab/iiab/blob/master/roles/2-common/tasks/packages.yml#L35) and possibly other places?

Suggested by @jvonau.

**Comment by jvonau** [comment]
Only place, #502 is where it was noted that should ifupdown not be installed networking failed to setup correctly as this package was absent. I suspect systemd-networkd or networkmanger is running the network configuration, lots of NM code is peppered about the code in the redhat side. Looked at what it might take to port over to systemd-networkd with a [quick layout](https://github.com/iiab/iiab/compare/master...jvonau:systemd-net?expand=1)

**Comment by jvonau** [comment]
#553 merged
https://wiki.ubuntu.com/ArtfulAardvark/ReleaseNotes#Network_configuration
https://wiki.ubuntu.com/Netplan
#554 to build upon

**Comment by holta** [comment]
Done, as part of #554 etc!
