### ISSUE TITLE
KA Lite aborts ./iiab-install on Raspbian 2017-11-29 (WiFi install especially?!)

### ISSUE THREAD

**Issue by holta** [iiab/iiab#589]
This error is repeatable every time I run "./iiab-install" or "./runtags kalite" &mdash; regardless whether I install via WiFi or via Ethernet &mdash; this occurs on different RPi3 systems:

> TASK [kalite : Install KA Lite static with pip - (debuntu)] ********************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "cmd": "/usr/bin/virtualenv --no-site-packages /usr/local/kalite/venv", "msg": "stdout: New python executable in /usr/local/kalite/venv/bin/python2\nAlso creating executable in /usr/local/kalite/venv/bin/python\nInstalling setuptools, pkg_resources, pip, wheel...\n  Complete output from command /usr/local/kalite/venv/bin/python2 - setuptools pkg_resources pip wheel:\n  Collecting setuptools\nException:\nTraceback (most recent call last):\n  File \"/usr/share/python-wheels/pip-9.0.1-py2.py3-none-any.whl/pip/basecommand.py\", line 215, in main\n    status = self.run(options, args)\n  File \"/usr/share/python-wheels/pip-9.0.1-py2.py3-none-any.whl/pip/commands/install.py\", line 353, in run\n    wb.build(autobuilding=True)\n  File \"/usr/share/python-wheels/pip-9.0.1-py2.py3-none-any.whl/pip/wheel.py\", line 749, in build\n    self.requirement_set.prepare_files(self.finder)\n  File \"/usr/share/python-wheels/pip-9.0.1-py2.py3-none-any.whl/pip/req/req_set.py\", line 380, in prepare_files\n    ignore_dependencies=self.ignore_dependencies))\n  File \"/usr/share/python-wheels/pip-9.0.1-py2.py3-none-any.whl/pip/req/req_set.py\", line 554, in _prepare_file\n    require_hashes\n  File \"/usr/share/python-wheels/pip-9.0.1-py2.py3-none-any.whl/pip/req/req_install.py\", line 278, in populate_link\n    self.link = finder.find_requirement(self, upgrade)\n  File \"/usr/share/python-wheels/pip-9.0.1-py2.py3-none-any.whl/pip/index.py\", line 465, in find_requirement\n    all_candidates = self.find_all_candidates(req.name)\n  File \"/usr/share/python-wheels/pip-9.0.1-py2.py3-none-any.whl/pip/index.py\", line 423, in find_all_candidates\n    for page in self._get_pages(url_locations, project_name):\n  File \"/usr/share/python-wheels/pip-9.0.1-py2.py3-none-any.whl/pip/index.py\", line 568, in _get_pages\n    page = self._get_page(location)\n  File \"/usr/share/python-wheels/pip-9.0.1-py2.py3-none-any.whl/pip/index.py\", line 683, in _get_page\n    return HTMLPage.get_page(link, session=self.session)\n  File \"/usr/share/python-wheels/pip-9.0.1-py2.py3-none-any.whl/pip/index.py\", line 792, in get_page\n    \"Cache-Control\": \"max-age=600\",\n  File \"/usr/local/kalite/venv/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py\", line 501, in get\n    return self.request('GET', url, **kwargs)\n  File \"/usr/share/python-wheels/pip-9.0.1-py2.py3-none-any.whl/pip/download.py\", line 386, in request\n    return super(PipSession, self).request(method, url, *args, **kwargs)\n  File \"/usr/local/kalite/venv/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py\", line 488, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/usr/local/kalite/venv/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py\", line 609, in send\n    r = adapter.send(request, **kwargs)\n  File \"/usr/local/kalite/venv/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/adapter.py\", line 47, in send\n    resp = super(CacheControlAdapter, self).send(request, **kw)\n  File \"/usr/local/kalite/venv/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/adapters.py\", line 423, in send\n    timeout=timeout\n  File \"/usr/local/kalite/venv/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py\", line 643, in urlopen\n    _stacktrace=sys.exc_info()[2])\n  File \"/usr/local/kalite/venv/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/util/retry.py\", line 315, in increment\n    total -= 1\nTypeError: unsupported operand type(s) for -=: 'Retry' and 'int'\n----------------------------------------\n...Installing setuptools, pkg_resources, pip, wheel...done.\nRunning virtualenv with interpreter /usr/bin/python2\n\n:stderr: Traceback (most recent call last):\n  File \"/usr/lib/python3/dist-packages/virtualenv.py\", line 2375, in <module>\n    main()\n  File \"/usr/lib/python3/dist-packages/virtualenv.py\", line 724, in main\n    symlink=options.symlink)\n  File \"/usr/lib/python3/dist-packages/virtualenv.py\", line 992, in create_environment\n    download=download,\n  File \"/usr/lib/python3/dist-packages/virtualenv.py\", line 922, in install_wheel\n    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)\n  File \"/usr/lib/python3/dist-packages/virtualenv.py\", line 817, in call_subprocess\n    % (cmd_desc, proc.returncode))\nOSError: Command /usr/local/kalite/venv/bin/python2 - setuptools pkg_resources pip wheel failed with error code 2\n"}

How To Reproduce This: run http://download.iiab.io/6.5/rpi/load.txt on Raspbian Lite 2017-11-29, which means kernel 4.9.59-v7+ and Ansible 2.4.2.0

**Comment by holta** [comment]
Does the final error above ("Command /usr/local/kalite/venv/bin/python2 - setuptools pkg_resources pip wheel failed with error code 2") have anything to do with very the familiar October issues https://github.com/iiab/iiab/issues/392 and https://github.com/learningequality/ka-lite/issues/5533 ?

**Comment by holta** [comment]
We have a new error at the exact same step this morning &mdash; this error occurred 3 out of 4 times on the RPi3 where ./iiab-install is run over WiFi:

> TASK [kalite : Install KA Lite static with pip - (debuntu)] ********************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "cmd": "/usr/local/kalite/venv/bin/pip2 install --no-cache-dir ka-lite-static==0.17.3", "msg": "stdout: New python executable in /usr/local/kalite/venv/bin/python2\nNot overwriting existing python script /usr/local/kalite/venv/bin/python (you must use /usr/local/kalite/venv/bin/python2)\nInstalling setuptools, pkg_resources, pip, wheel...done.\nRunning virtualenv with interpreter /usr/bin/python2\nCollecting ka-lite-static==0.17.3\n  Downloading ka_lite_static-0.17.3-py2-none-any.whl (40.7MB)\n\n:stderr: Exception:\nTraceback (most recent call last):\n  File \"/usr/local/kalite/venv/local/lib/python2.7/site-packages/pip/basecommand.py\", line 215, in main\n    status = self.run(options, args)\n  File \"/usr/local/kalite/venv/local/lib/python2.7/site-packages/pip/commands/install.py\", line 342, in run\n    requirement_set.prepare_files(finder)\n  File \"/usr/local/kalite/venv/local/lib/python2.7/site-packages/pip/req/req_set.py\", line 380, in prepare_files\n    ignore_dependencies=self.ignore_dependencies))\n  File \"/usr/local/kalite/venv/local/lib/python2.7/site-packages/pip/req/req_set.py\", line 620, in _prepare_file\n    session=self.session, hashes=hashes)\n  File \"/usr/local/kalite/venv/local/lib/python2.7/site-packages/pip/download.py\", line 821, in unpack_url\n    hashes=hashes\n  File \"/usr/local/kalite/venv/local/lib/python2.7/site-packages/pip/download.py\", line 659, in unpack_http_url\n    hashes)\n  File \"/usr/local/kalite/venv/local/lib/python2.7/site-packages/pip/download.py\", line 882, in _download_http_url\n    _download_url(resp, link, content_file, hashes)\n  File \"/usr/local/kalite/venv/local/lib/python2.7/site-packages/pip/download.py\", line 603, in _download_url\n    hashes.check_against_chunks(downloaded_chunks)\n  File \"/usr/local/kalite/venv/local/lib/python2.7/site-packages/pip/utils/hashes.py\", line 46, in check_against_chunks\n    for chunk in chunks:\n  File \"/usr/local/kalite/venv/local/lib/python2.7/site-packages/pip/download.py\", line 571, in written_chunks\n    for chunk in chunks:\n  File \"/usr/local/kalite/venv/local/lib/python2.7/site-packages/pip/utils/ui.py\", line 139, in iter\n    for x in it:\n  File \"/usr/local/kalite/venv/local/lib/python2.7/site-packages/pip/download.py\", line 560, in resp_read\n    decode_content=False):\n  File \"/usr/local/kalite/venv/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/response.py\", line 432, in stream\n    data = self.read(amt=amt, decode_content=decode_content)\n  File \"/usr/local/kalite/venv/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/response.py\", line 397, in read\n    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)\n  File \"/usr/lib/python2.7/contextlib.py\", line 35, in __exit__\n    self.gen.throw(type, value, traceback)\n  File \"/usr/local/kalite/venv/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/response.py\", line 312, in _error_catcher\n    raise ReadTimeoutError(self._pool, None, 'Read timed out.')\nReadTimeoutError: HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out.\n"}

Whereas this error occurred 1 out of 4 times on the RPi3 where ./iiab-install is run over WiFi:

> TASK [kalite : Install KA Lite static with pip - (debuntu)] ********************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "cmd": "/usr/local/kalite/venv/bin/pip2 install --no-cache-dir ka-lite-static==0.17.3", "msg": "stdout: Collecting ka-lite-static==0.17.3\n  Downloading ka_lite_static-0.17.3-py2-none-any.whl (40.7MB)\n\n:stderr: Exception:\nTraceback (most recent call last):\n  File \"/usr/local/kalite/venv/local/lib/python2.7/site-packages/pip/basecommand.py\", line 215, in main\n    status = self.run(options, args)\n  File \"/usr/local/kalite/venv/local/lib/python2.7/site-packages/pip/commands/install.py\", line 342, in run\n    requirement_set.prepare_files(finder)\n  File \"/usr/local/kalite/venv/local/lib/python2.7/site-packages/pip/req/req_set.py\", line 380, in prepare_files\n    ignore_dependencies=self.ignore_dependencies))\n  File \"/usr/local/kalite/venv/local/lib/python2.7/site-packages/pip/req/req_set.py\", line 620, in _prepare_file\n    session=self.session, hashes=hashes)\n  File \"/usr/local/kalite/venv/local/lib/python2.7/site-packages/pip/download.py\", line 821, in unpack_url\n    hashes=hashes\n  File \"/usr/local/kalite/venv/local/lib/python2.7/site-packages/pip/download.py\", line 659, in unpack_http_url\n    hashes)\n  File \"/usr/local/kalite/venv/local/lib/python2.7/site-packages/pip/download.py\", line 882, in _download_http_url\n    _download_url(resp, link, content_file, hashes)\n  File \"/usr/local/kalite/venv/local/lib/python2.7/site-packages/pip/download.py\", line 603, in _download_url\n    hashes.check_against_chunks(downloaded_chunks)\n  File \"/usr/local/kalite/venv/local/lib/python2.7/site-packages/pip/utils/hashes.py\", line 46, in check_against_chunks\n    for chunk in chunks:\n  File \"/usr/local/kalite/venv/local/lib/python2.7/site-packages/pip/download.py\", line 571, in written_chunks\n    for chunk in chunks:\n  File \"/usr/local/kalite/venv/local/lib/python2.7/site-packages/pip/utils/ui.py\", line 139, in iter\n    for x in it:\n  File \"/usr/local/kalite/venv/local/lib/python2.7/site-packages/pip/download.py\", line 560, in resp_read\n    decode_content=False):\n  File \"/usr/local/kalite/venv/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/response.py\", line 432, in stream\n    data = self.read(amt=amt, decode_content=decode_content)\n  File \"/usr/local/kalite/venv/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/response.py\", line 397, in read\n    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)\n  File \"/usr/lib/python2.7/contextlib.py\", line 35, in __exit__\n    self.gen.throw(type, value, traceback)\n  File \"/usr/local/kalite/venv/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/response.py\", line 312, in _error_catcher\n    raise ReadTimeoutError(self._pool, None, 'Read timed out.')\nReadTimeoutError: HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out.\n"}

**Comment by jvonau** [comment]
> ReadTimeoutError(self._pool, None, 'Read timed out.')\nReadTimeoutError: HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out.\n"}

I'll go with issue connecting with pypi.python.org

**Comment by holta** [comment]
> I'll go with issue connecting with pypi.python.org

This problem no longer occurs over Ethernet-connected RPi3.

The latest theory is that it's caused by a poor handshake (and hence poor bandwidth, around 1mbit/s typically) between the RPi3's internal WiFi and this particular home's WiFi router.  Also other laptops/phones sustain 30-100mbit/s downloads (and sometimes higher) in this very same home.  I have no idea if the RPi3's firmware or some other general incompatibility with the WiFi router is at play here, as we have no physical access to the WiFi router, and cannot determine its make/model/etc.

But the bandwidth to the RPi3 is painfully slow, as demonstrated by many other wget downloads that stop/start repeatedly until they complete finally complete, e.g. wget took more than 10min and 3 restarts to finally download 97MB.

@jvonau has found this link below that might help us increase Ansible's timeouts for downloads across the board?

http://docs.ansible.com/ansible/latest/network_debug_troubleshooting.html#sts=Timeout%20issues%C2%B6

**Comment by holta** [comment]
Great this issue seems to have resolved itself!

Plz re-open as nec if it recurs...
