### ISSUE TITLE
Tim may refine IIAB Menuing instructions

### ISSUE THREAD

**Issue by holta** [iiab/iiab#606]
Specifically @tim-moody might refine the Menu Definition Template (https://github.com/iiab/iiab/wiki/IIAB-Menuing#menu-definition-template) where @kananigit asked for quick clarification of all/new JSON options during our MiniApp-A-Thon in Minneapolis?

**Comment by tim-moody** [comment]
There are no new menu definition properties, but I added config.json documentation.
