### ISSUE TITLE
IIAB 6.5 microSD's cannot be moved from RPi3 to RPi Zero W?

### ISSUE THREAD

**Issue by holta** [iiab/iiab#661]
Mexico's various 128GB SanDisk IIAB 6.5 microSD's cannot be moved from RPi3 to RPi Zero W: the symptom is that the SSID ("Internet in a Box") is visible on the air, but client machines cannot connect, never quite receiving an IP address.

Whereas this worked in June of 2017, with Haiti's 64GB GB microSD's.

Please help investigate, those who can!

**Comment by holta** [comment]
Clarif: it's entirely possible that Raspbian Desktop (as used in Mexico, underlying IIAB) never ran properly on RPi Zero W, whereas Raspbian Lite does?

But whatever the underlying reason: RPi Zero W's inability to deliver WiFi AP Mode (i.e. a functional hotspot) needs investigation...since it works in certain conditions but not others :/

**Comment by holta** [comment]
Confirmed: Raspbian Desktop from earlier in 2017 (IIAB 6.2 or 6.3) works to create a fully functional hotspot in a RPi Zero W.

Hypothetically it's possible that WiFi-installed IIAB 6.5 (all I've tested so far, inside a RPi Zero W) continues to behave differently from Ethernet-installed IIAB 6.5 ?

In any case: thanks all who can evaluate what works in RPi Zero W and what doesn't!

**Comment by tim-moody** [comment]
installed 6.5 on rpi3 using medium over wire
moved to W
no ssid
accessed over usb wire OK
hostapd not running; started it
able to ssh in over wifi
over wifi connection reset on http
same over wired connection

**Comment by holta** [comment]
Is it possible that all-or-some-of-the-more-recent 3 Raspbian Stretch releases (2017-08-16, 2017-09-07, 2017-11-29) are themselves causing underlying incompatibility with RPi Zero W?

**Comment by tim-moody** [comment]
medbox is based on 2017-09-07 and I just reverified that it works on W

**Comment by tim-moody** [comment]
2017-11-29 is a suspect. seems there were extensive changes and nothing new in 2 1/2 months could represent struggles

**Comment by holta** [comment]
> medbox is based on 2017-09-07 and I just reverified that it works on W

Good news.

> 2017-11-29 is a suspect

Can you apply all "apt update; apt dist-upgrade" patches to a copy of medbox and see if it still works in a RPi Zero W?

Installing IIAB 6.4 onto Raspbian 2017-11-29 might not work 100%, but could also be a valuable test?

**Comment by tim-moody** [comment]
N.B. firmware-libertas firmware-misc-nonfree firmware-realtek in list of upgrades
also the bootloader and of course the kernel

**Comment by tim-moody** [comment]
took content-ready 6.4 and ran apt update and dist-upgrade on rpi3 then moved to W
it booted and I accessed it via ssh and http OK

6.5 on 9-7 seems more promising

**Comment by tim-moody** [comment]
root@raspberrypi:/opt/iiab/iiab# ./iiab-install
Placed /etc/ansible/facts.d/local_facts.fact into position.
Found Kernel 4.9.41-v7+

EXITING: Kernel 4.9.59-v7+ or higher required with Raspbian.
PLEASE RUN 'apt update' then 'apt install raspberrypi-kernel' then reboot.
IIAB INSTALL INSTRUCTIONS: https://github.com/iiab/iiab/wiki/IIAB-Installation

**Comment by tim-moody** [comment]
raspberrypi-kernel is already the newest version (1.20171029-1).

so waste of time

**Comment by holta** [comment]
> EXITING: Kernel 4.9.59-v7+ or higher required with Raspbian.

If nec this check can be commented out from ./iiab-install (it's in place for KA Lite).

**Comment by holta** [comment]
>> EXITING: Kernel 4.9.59-v7+ or higher required with Raspbian.
>
> If nec [during testing] this check can be commented out from /iiab-install (it's in place for KA Lite).

Correction: @jvonau asked for this minimum kernel check for bridging @ https://github.com/iiab/iiab/issues/482 ("Raspbian kernel update breaks bridging").

Whereas the KA Lite issue (https://github.com/iiab/iiab/issues/392, resolved by Ben Nuttall) appears only tangentially related.

**Comment by holta** [comment]
FYI IIAB MicroSD cards can be moved back and forth between RPi 3 and RPi Zero W using PR #697 (anticipated to become the foundation of IIAB 6.6, starting sometime next week!)

**Comment by holta** [comment]
@deldesir confirms this is no longer an issue &mdash; _profound thanks to @jvonau and @georgejhunt whose very hard work made this possible in recent weeks._
