### ISSUE TITLE
is Ansible 2.4.3 running out of memory when installing IIAB 6.5/master on RPi3?

### ISSUE THREAD

**Issue by holta** [iiab/iiab#669]
If #666 is the devil's number, we can revert it :)

Quick summary (of "cannot allocate memory" when running the ["network" role](https://github.com/iiab/iiab/tree/master/roles/network)) @ https://github.com/iiab/iiab/pull/666#issuecomment-364667294

The workaround is to reboot and re-run Ansible:
- cd /opt/iiab/iiab
- ./iiab-install

The suspicion (needs confirmation) is that this problem results from Ansible 2.4.3 released on 2018-01-31.

If confirmed/serious, reverting to Ansible 2.4.2 may be the pragmatic answer until the upstream issue can be addressed.

**Comment by holta** [comment]
@tim-moody @georgejhunt can you paste in the error message onto this ticket if poss?

**Comment by tim-moody** [comment]
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: OSError: [Errno 12] Cannot allocate memory

**Comment by holta** [comment]
> OSError: [Errno 12] Cannot allocate memory

Unrelated to IIAB, others experienced this with Ansible 2.4.1:
https://github.com/ansible/ansible/issues/32854

And yet this is (alleged) to be improved in Ansible 2.4.3:
https://github.com/ansible/ansible/issues/31673

Thanks all for more reports helping us isolate the issue & how to reproduce it.

**Comment by holta** [comment]
@jvonau : Ansible 2.5 was released in beta form yesterday @ https://releases.ansible.com/ansible/ so let's look into how we might pin [/opt/iiab/iiab/scripts/ansible](https://github.com/iiab/iiab/blob/master/scripts/ansible) to 2.4.x possibly?

**Comment by holta** [comment]
A workaround for RPi &mdash; and Ubuntu 16.04 LTS too if nec &mdash; until Ansible 2.4.3 is fixed:

> wget http://download.iiab.io/packages/ansible_2.4.2.0-1ppa~xenial_all.deb
> apt install ./ansible_2.4.2.0-1ppa~xenial_all.deb

I've cached Ansible 2.4.2's PPA above, as it's expected to disappear from https://launchpad.net/~ansible/+archive/ubuntu/ansible/+files/ansible_2.4.2.0-1ppa~xenial_all.deb shortly.

**Comment by holta** [comment]
Excellent News: Ansible's @sivel replied to me @ https://github.com/ansible/ansible/issues/31673#issuecomment-365011700

He explains this memory allocation problem is likely https://github.com/ansible/ansible/issues/35796 which was fixed late last week and has been backported to stable-2.4 for an upcoming 2.4.4 release.  It is also in stable-2.5 for the 2.5.0.b1 release (and in their devel branch).

**Comment by holta** [comment]
FYI Ansible 2.5.0's target release is March 2018, according to the official roadmap+checklist:
http://docs.ansible.com/ansible/devel/roadmap/ROADMAP_2_5.html

[January 23rd's Feature Freeze annc](https://groups.google.com/forum/#!topic/ansible-devel/vGCQQY5472s) from the release manager reaffirms this general schedule:
- 2.5.0 b1 was released last Friday (Feb 9, scheduled for Feb 8)
- 2.5.0 b2 is scheduled for Thur (Feb 15)
- 2.5.0 rc1 is scheduled for next Thur (Feb 22)

(in consideration of the [1-week delay announced Jan 9th](https://groups.google.com/forum/#!topic/ansible-devel/cuuZlKo_0Bs))

**Comment by holta** [comment]
This tkt can be re-opened later if absolutely nec:

IIAB 6.5 should be released sometime in March—but it remains an open question if with Ansible 2.4.4 or 2.5.0 (or whatever) will be ready at that time.

**Comment by holta** [comment]
Am re-opening this tkt as [Ansible 2.4.4 and 2.5.0](https://releases.ansible.com/ansible/) releases appear imminent in coming weeks, regardless how this affects IIAB 6.5 and 6.6

**Comment by holta** [comment]
Ansible 2.5.0 RC3 released:

https://releases.ansible.com/ansible/ansible-2.5.0rc3.tar.gz

**Comment by holta** [comment]
Error has returned on Ansible 2.5.0 on Raspbian 2018-03-13 on RPi3 &mdash; 38min into a run of "./iiab-install --reinstall" :

> TASK [network : Copy /etc/sysconfig/dhcpd file] ********************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: OSError: [Errno 12] Cannot allocate memory
fatal: [127.0.0.1]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}

**Comment by holta** [comment]
> why is 2.5 50% larger than 2.4.4 and does that affect memory usage?

No idea: Thx everybody for keeping an eye on this+other consequences of our transition from Ansible 2.4.x (IIAB 6.5) to Ansible 2.5.x+ (IIAB 6.6).

**Comment by jvonau** [comment]
Anish reported the same crash under 2.4.4 on unbutu 16.04 also

> OK 16. ./ansible-2.4.x 
OK 17. cd /opt/iiab/iiab/
XX 18. ./iiab-install
TASK [network : Copy /etc/sysconfig/dhcpd file] *****************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: OSError: [Errno 12] Cannot allocate memory
fatal: [127.0.0.1]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}
    to retry, use: --limit @/opt/iiab/iiab/iiab-stages.retry

**Comment by holta** [comment]
> Anish reported the same crash under 2.4.4 on ubuntu 16.04 also

@m-anish can you retest with [Ansible 2.5.1](https://github.com/iiab/iiab/pull/740#issuecomment-382581867) released yesterday?  Which can be installed in either of 2 ways:
1. Run `/opt/iiab/iiab/scripts/ansible` (recommended!)
2. `pip install ansible==2.5.1`

**Comment by holta** [comment]
@m-anish Ansible has had many memory leaks recently :) so I'm not sure which you ran into, but FYI the most recent fix (https://github.com/ansible/ansible/issues/38532#issuecomment-383040559) JUST missed inclusion in Ansible 2.5.1 released 2 days ago.  And so will be part of Ansible 2.5.2 expected "3 weeks later" by/around mid-May.

**Comment by holta** [comment]
> @m-anish Ansible has had many memory leaks recently :) so I'm not sure which you ran into, but FYI the most recent fix (ansible/ansible#38532 (comment)) JUST missed inclusion in Ansible 2.5.1 released 2 days ago. And so will be part of Ansible 2.5.2 expected "3 weeks later" by/around mid-May.

@m-anish: Ansible 2.5.2 is now released fixing memory leaks, try it if poss!  (I've confirmed `./iiab-install --reinstall` runs [IIAB 6.5] to completion on 2.5.2 on Ubuntu 16.04...of course stick with Ansible 2.4.4 if you require ./runtags to work with multiple roles...instead of IIAB 6.6's new ./runrole)

**Comment by holta** [comment]
Ansible 2.5.3 & Ansible 2.5.4 resolve even more memory issues for RPi, so these issues seem very much under control now.
