### ISSUE TITLE
"Failed to start usbmount@dev-sda.service." during every IIAB boot on RPi

### ISSUE THREAD

**Issue by holta** [iiab/iiab#710]
Error occurs on all boots, after installing IIAB 6.5/master on Raspbian Lite 2018-03-13 on a (regular!) RPi 3, using 1-line install script http://download.iiab.io/6.5/rpi/load.txt

FYI "systemctl start usbmount@dev-sda.service" also fails (after boot).  Inspired by /var/log/boot.log which recommended "systemctl status usbmount@dev-sda.service"

This seems to be a very new IIAB bug arising in recent days (or weeks?)

Somewhat Related:
#682 "automount USB exFAT sticks (& possibly portable NTFS disks too)"
#695 "Option to show entire USB stick/drive content (at http://box/usb)"

**Comment by holta** [comment]
Notes:
- error/warning appears during bootup when a USB stick/drive is inserted
- error/warning does NOT appear when rebooting without a stick inserted
- error/warning does not prevent actual usage of http://box/usb (i.e. USB stick's content is still visible, despite loud red message on boot)

**Comment by georgejhunt** [comment]
Note:
systemctl disable usbmount\@.service makes the error message dissappear

**Comment by holta** [comment]
> `systemctl disable usbmount@dev-sda.service` makes the error message disappear

Is [roles/usb-lib/tasks/main.yml](https://github.com/iiab/iiab/blob/master/roles/usb-lib/tasks/main.yml) the place to make this happen?

**Comment by holta** [comment]
@jvonau experiment shows another method to make red error go away...adding `After=rc-local.service` to the end of [Unit] section in /etc/systemd/system/usbmount@.service so that it appears as follows:
```
[Unit]
BindTo=%i.device
After=%i.device
After=rc-local.service

...
```
Where should this be implemented / in which playbook?

**Comment by holta** [comment]
(Resolved by @jvonau's PR #722 "delay usbmount's actions during boot to be as late as possible")

**Comment by tkantor81** [comment]
Error is still visible.

**Comment by holta** [comment]
TK Kang mentions this is an issue when installing IIAB 7.1 pre-releases on on Debian 10?
