### ISSUE TITLE
Pin IIAB 6.5 to Ansible 2.4.x in scripts/ansible ?

### ISSUE THREAD

**Issue by holta** [iiab/iiab#715]
@jvonau do you know how to do this in [scripts/ansible](https://github.com/iiab/iiab/blob/master/scripts/ansible) ?

PS pip within scripts/ansible-2.2.0 -> ansible-2.4.2 -> ansible-2.4.4 (soon) is one option.  But there's prob a better way, in preparation for 2.4.5 backported bug fixes etc.

**Comment by holta** [comment]
Related:
#669 "is Ansible 2.4.3 running out of memory when installing IIAB 6.5/master on RPi3?"
PR #711 "restore scripts/ansible now that Ansible 2.5.0 is released & smoke-tested"
PR #712 "support Ansible 2.5.x: include_role to import_role in Stages 3-9"
#714 "Enhancement - Generate Dynamic Playbook"
PR #716 "install.yml in every core IIAB role - also fixes ./runtags for Ansible 2.5"

**Comment by jvonau** [comment]
Looks like upstream ansible as reworked the repo urls again from
http://ppa.launchpad.net/ansible/ansible/ubuntu
to:
http://ppa.launchpad.net/ansible/ansible-2.5/ubuntu 
http://ppa.launchpad.net/ansible/ansible-2.4/ubuntu 

See and expand the 'Technical details about this PPA' link
https://launchpad.net/~ansible/+archive/ubuntu/ansible-2.5
https://launchpad.net/~ansible/+archive/ubuntu/ansible-2.4

Modifying the respective lines in scripts/ansible should pin you to 2.4 or 2.5 

Preventing ansible from updating from 2.4.2 that is being installed to 2.4.3 until 2.4.5 is released is the issue. I'd ensure that /etc/apt/sources.list does not contain ansible defination and /etc/apt/sources.list.d/ansible*.list does not exist to prevent apt from seeing the ansible repo and thus any available update available from upstream until 2.4.5 is released. 

Personally I feel the out of memory issue uncovered in #669 can be mitigated with a more adequate amount of swap space and 2.5 has shown the same behaviour now.

**Comment by holta** [comment]
Excellent summary above by @jvonau.

If Ansible 2.4.4 is released shortly, this might be best for IIAB 6.5 legacy systems, given the serious [maximum recursion depth](https://github.com/iiab/iiab/pull/716#issuecomment-376406165) issues recently uncovered in 2.4.2

Conversely rapid consolidation around 2.5.x (which already today solves essentially all our known issues) might serve us all strengthening community focus (certainly for IIAB 6.6) _...as soon as we transition from ./runtags to [./runrole or similar](https://github.com/iiab/iiab/issues/714)._

**Comment by holta** [comment]
FWIW Ansible 2.4.4 (v2.4.4.0-1, "the last regularly scheduled release in the 2.4.x series") is now released:
- https://releases.ansible.com/ansible/
- https://launchpad.net/~ansible/+archive/ubuntu/ansible-2.4

It can be installed using `pip install ansible==2.4.4.0` (on Raspbian & Ubuntu) until the above PPA's are built/publish in coming hours, whereupon "apt update" etc should work.

Its 70+ bug fixes are listed here:
- https://github.com/ansible/ansible/blob/stable-2.4/CHANGELOG.md

>"[2.4.4] is the last regularly scheduled release in the 2.4.x series.
We'll make further 2.4.x releases if we discover critical or security
bugs that must be fixed while 2.4.x is still supported but the
majority of new bugfixes will be made to the 2.5.x release series."

**Comment by holta** [comment]
FYI ./iiab-install and ./runtags and ./runrole all work well with the new Ansible 2.4.4

(Tests were completed on Ubuntu, similar tests are ongoing on Raspbian Lite...)

**Comment by holta** [comment]
Done.

See load scripts in http://download.iiab.io/6.5/rpi/ which now use scripts/ansible-2.4.x from PR #711
