### ISSUE TITLE
Ansible is having a problem enabling hostapd

### ISSUE THREAD

**Issue by deldesir** [iiab/iiab#744]
Each time iiab-network stucks at a point to Enable/Restart the Access Point 'hostapd' service, I have to start hostapd manually. 
Fresh Install on RPI 3 B with latest raspbian (stretch lite)

**Comment by jvonau** [comment]
Thought this was fixed on Raspbian with current master(It was when I tested last), 741 expanses on the fix to include Ubuntu as Anish reported the same issue on ubuntu-16 in skype as noted in 726

**Comment by holta** [comment]
@deldesir we're confused as PR #726 was merged 15 days ago:
1. Can you help us reproduce this on Raspbian Lite, and confirm this was the lastest master of iiab that you cloned/tested yesterday?
2. Can you please post the log file /opt/iiab/iiab/iiab-network.log to help @jvonau & all understand?

Thanks!

**Comment by jvonau** [comment]
noting that iiab-network has a runtime of ~90 seconds and hostapd is running
> bridge name bridge id STP enabled interfaces
br0 8000.b827eba995e3 no wlan0

While the aborted run is ~240 seconds without really doing anything, and the snippet at the top has a runtime of ~245 seconds... Was the SDcard being swapped around between machines?

**Comment by deldesir** [comment]
That was fixed with a fresh install. Thanks for your support.
