### ISSUE TITLE
Rapid networking & other IIAB config changes that can't wait ~20min for Ansible

### ISSUE THREAD

**Issue by holta** [iiab/iiab#796]
Am trying with @tim-moody to prioritize crucial features where implementers don't have time to wait ~20min for Ansible to finish.  Hopefully several of these improvements are possible for IIAB 6.6!?

Example things that (might!) be changeable in less than 1 minute, via Admin Console especially &mdash; or command-line interface if necessary &mdash; order VERY preliminary below!  Are these good ideas?  Are there other priorities needed from [local_vars.yml](http://wiki.laptop.org/go/IIAB/local_vars.yml) ?

0) Toggle student access to Internet (iiab_gateway_enabled: False/True)
1) Internal SSID Name Change (do implementers care about IIAB's internal Wi-Fi channel & password? Rarely...)
2) Connecting to / Disconnecting from upstream Wi-Fi with UX for SSID + password
3) VPN on/off + VPN handle
4) Fixed IP address to DHCP and back
5) Other network stuff...network sensing might be nec??
6) Turn services (server apps) on/off
7) iiab_home_url: /home or /wordpress or /mediawiki or /wiki (for DokuWiki)

**Comment by holta** [comment]
Quick thoughts from @jvonau:

>1 & 3 easy. 4 & 5 & 6 network services (squid dhcpd/dnsmasq) are in iiab-network. 2 is easy on raspbian but the others not so easy. 6 could just be calls to systemctl to enable/start and disable/stop

**Comment by m-anish** [comment]
5 would be good to have

**Comment by katneer91** [comment]
Like

**Comment by tim-moody** [comment]
I think that state and environment are two different things. I would like to see a state file (json/yml/ini) that holds name-value pairs for all the main features of iiab, but is not as chatty as iiab.ini, which was really intended for reporting. That file could be loaded as facts by ansible and also used (read/write) by non-ansible scripts/applications that change state. It would include networking (but not working variables), installed and (actually) enabled, and other things that define the current state of iiab at any point in time.

**Comment by holta** [comment]
Important...but not achievable for [IIAB 6.6](https://github.com/iiab/iiab/wiki/IIAB-6.6-Release-Notes) so moved to [IIAB 6.7](https://github.com/iiab/iiab/milestone/4)

**Comment by holta** [comment]
If any such redesign of /etc/iiab/iiab.env and related files moves forward, it should take into account that 3 different people got stuck as a result of iiab.env &mdash; i.e. not know that such a centrally-important file even exists:

#880 "Install script fails to create /opt/iiab/downloads folder"

**Comment by holta** [comment]
@darkenvy & @floydianslips ask how SSID might be rapidly changed from Admin Console.

Related:
#1520 Admin Console & instructions should offer iiab-hotspot-on | iiab-hotspot-off functionality more intuitively
#1536 IIAB installer should make hotspot & networking choices far more understandable

**Comment by jvonau** [comment]
0-7 above have been achieved.

**Comment by holta** [comment]
Great news indeed!

Public-spirited documentation should be added soon now, clarifying the most common public needs.

As part of #2096 "NGINX & ./runrole & ./iiab-network [Dual WiFi] & IIAB Maps need approachable docs for newbie/legacy implementers"

**Comment by holta** [comment]
> 0-7 above have been achieved.

Great news, and certainly good enough for the imminent [IIAB 7.1](https://github.com/iiab/iiab/wiki/IIAB-7.1-Release-Notes) !

@jerry where are the best places to monitor future networking possibilities, perhaps along the lines of Ubuntu's issue-tracking tickets you've linked to from #2270 ?
