### ISSUE TITLE
Fix http://box:3000 for those who want privacy & original/clean/short Kiwix URL

### ISSUE THREAD

**Issue by holta** [iiab/iiab#852]
http://box:3000 does not display ZIM's since kiwix-tools 0.6.0 (PR #845) were merged on 2018-06-20.  All nightly builds of kiwix-tools fail in the same way since Sunday June 10, 2018.

Thanks to Emmauel Engelhart, @tim-moody and TK Kang who helped isolate the issue, which is a side-effect of kiwix-serve flag --urlRootLocation=/URL_ROOT

This is likely an accidental regression in kiwix-serve and Matthieu Gautier will work on it when he can:
https://github.com/kiwix/kiwix-tools/issues/208

**Comment by holta** [comment]
Related:

PR #980 "Use Kiwix default URI box.lan/kiwix"

**Comment by holta** [comment]
FYI #1060 is an important fix for http://box/kiwix building off @arky's #980 and @tim-moody's #985

**Comment by holta** [comment]
Possibly this is not attainable and should be closed during the IIAB 7.2 release cycle, as the future of kiwix-tools becomes more clear via #1993 & #2063 etc?

**Comment by jvonau** [comment]
works with nginx

**Comment by holta** [comment]
> works with nginx

I don't think http://box:3000 works on NGINX (on the 2 IIAB machines where I tried it anyway).

But one can apparently use http://box:3000/kiwix/ to avoid the Apache/NGINX proxy e.g. for enhanced privacy, per #852 &mdash; and that's probably the best we can hope for.
