### ISSUE TITLE
Reboot + Auto-Continue? What should IIAB Installer & --reinstall scripts do about Critical OS updates etc?

### ISSUE THREAD

**Issue by holta** [iiab/iiab#872]
IIAB "1-liner" Install Scripts @ http://d.iiab.io/6.6 should:

0. [ Interactively populate local_vars.yml based on the preferences of the implementer/operator *WHILE below updates are being downloaded & installed?* ]
1. Install OS security updates e.g. "apt update; apt -y dist-upgrade" then...
2. Reboot then...
3. Auto-continue with IIAB installation

Potentially followed by:

4. Reboot upon IIAB install completion
5. MAYBE: Display confirmation message that IIAB install was successful??

As part of [IIAB 6.7](http://wiki.laptop.org/go/IIAB/6.7) or [7.0](https://github.com/iiab/iiab/milestone/5)?  (Unlikely this will be ready in time for IIAB 6.6 in coming weeks!)

**Comment by holta** [comment]
_EVEN BETTER:_

0. IIAB's 1-line installers should pre-populate local_vars.yml based on the preferences of the implementer/operator, before (or ideally WHILE!) running "apt update; apt -y  dist-upgrade" etc.

**Comment by holta** [comment]
Intimately (if indirectly) related to streamlining installs:
- #201 Automate re-homing of http://<HOSTNAME>/wordpress? (instead of RELOCATE flag)
- #317 Install OpenVPN/TeamViewer/support tool(s) BEFORE installs begin
- #658 Add a welcome message for KA Lite
- #799 Standardize upgrade/reinstall of IIAB services (server apps)
- #816 Much nicer "calibre-web" front-end for Calibre
- #822 IIAB 6.5 takes 45 sec to shut down (Rasp Lite on RPi3)
- #857 Auto-display of ZIM files when Teachers insert USB sticks/drives
- #884 Automate torrenting+installing of KA Lite videos in 7 languages

**Comment by holta** [comment]
Who knows clever tricks exist to make /etc/rc.local auto-continue [install scripts](http://download.iiab.io/6.6) ?

 It's time to make this happen.

(Am far from the only one with better things to do than watch "apt update; apt -y dist-upgrade; reboot" every time ;)

**Comment by holta** [comment]
During today's community/team call (http://minutes.iiab.io) @jvonau & @georgejhunt helped discuss revising [IIAB 6.6 install scripts](http://download.iiab.io/6.6/) so that a 4th hassle-free option emerges alongside MIN-sized, MEDIUM-sized and BIG-sized.

That 4th option would take as input a custom [local_vars.yml](http://wiki.iiab.io/local_vars.yml) file.

It will not matter if that custom local_vars.yml file is:
- generated by a Public Web GUI
- generated by a Local TTY GUI
- generated by a tiny bash script asking you 4-quick-n-easy-questions
- generated by an in-country colleague who hand edited local_vars.yml to be regionally-polished-n-perfect
- downloaded from an official site like https://github.com/iiab/iiab/tree/master/vars
- scraped from a informal community forum or site like http://wiki.iiab.io/local_vars.yml
- stolen from any random Facebook posting

CORE IDEA: de-couple the generation of the IIAB definition file (local_vars.yml) from the provisioning/manufacturing process, so that community/curation experts (those most atune to community fieldback/needs) can then circulate the very best local_vars.yml files &mdash; that best suit those grassroots AND global needs.

TOUGHER IDEA: this IIAB-definition file (local_vars.yml for now) might then later expand to pre-define what content auto-downloading should be attempted, along with a few very basic auto-configuration recommendations?

**Comment by holta** [comment]
Related:

PR #931 "/etc/iiab/local_vars.yml puts /opt/iiab/iiab/vars/local_vars.yml out of its misery"
PR #934 "softcode local_vars path" which puts `iiab_local_vars_file: /etc/iiab/local_vars.yml` in default_vars.yml

**Comment by holta** [comment]
FYI the Raspbian OS from 2018-06-27 currently requires you to do the following TWICE before its kernel stabilizes... from 4.14.50-v7+ to 4.14.52-v7+ ...and then again after reboot, on to kernel 4.14.62-v7+:
```
apt update
apt -y dist-upgrade
reboot
```
Which makes automating the install sequence that much harder (not knowing in advance how many reboots might be required ;)

**Comment by holta** [comment]
- Raspbian fixed its need for a double-reboot 2 weeks ago
- @jvonau has ideas for implementing this auto-reboot-and-continue-installing...using a long-running systemd unit file?!

**Comment by holta** [comment]
> @jvonau has ideas for implementing this auto-reboot-and-continue-installing...using a long-running systemd unit file?!

See this evolving prototype: https://github.com/iiab/iiab-factory/pull/33

**Comment by holta** [comment]
Related:
#799 "Standardize upgrade/reinstall of IIAB services (server apps)"
#1028 "Implementers R Us: quick wins allowing rapid-fire installation by almost anyone"
#1041 "IIAB Apps need: Upgrades, Reinstalls, Backups, Accounts, Content, Audits (provisioning norms needed!)"

Is @aidan-fitz's #1557 ("./runrole options") related?

Are @jvonau's PRs #1937 ("pi-gen") and #2008 ("installed") -> #2020 ("begin breaking apart playbooks into install.yml + setup.yml + enable.yml") related?

(Should this issue #872 be closed now/soon?)

**Comment by holta** [comment]
Good enough!

**Comment by jvonau** [comment]
hum... 1028, 1041 still open deferred to 8.0 
--reinstall question open...
