### ISSUE TITLE
Need clarification for basic instruction in the wiki

### ISSUE THREAD

**Issue by benjaoming** [iiab/iiab#876]
### Expected behavior and actual behavior.

In [this section](https://github.com/iiab/iiab/wiki/IIAB-Installation#install-the-software) of the installation guide, I have a problem understanding the **highlighted part**

> There are basically two ways to install IIAB software:
> 
> * Do **everything from scratch**. Strongly recommended (since IIAB 6.4 especially) as our new **1-line installer scripts** do essentially everything!
> (...)

This is because doing everything from scratch implies to me that I'll be doing everything from scratch, and then I don't understand from the sentence if that's discouraged to the alternative of using another _1-line installer script_ ? So I immediately started searching for this script that I'd need, but found out that essentially I still have to read through various platform bootstrapping guides, from which you arrive to a point whereby the dependencies of the script are satisfied?

### Steps to reproduce the problem.

1. Be a complete stranger to IIAB :D
1. Read the install guide

### Specifications like the version of the IIAB, operating system version, or hardware details.

Just wanna bootstrap a dev environment to reproduce issue in https://github.com/learningequality/ka-lite/issues/5575

**Comment by holta** [comment]
@benjaoming you're absolutely right.  In summary https://github.com/iiab/iiab/wiki/IIAB-Installation is getting very long in the tooth, and increasingly acts as reference documentation that does not need to be consulted (outside of exceptional cases!)

Most implementers prefer to jump in directly and run Internet-in-a-Box / IIAB's 1-line installers directly/immediately here:

   http://d.iiab.io/6.6

**Comment by benjaoming** [comment]
Thanks a lot for the explanation, and yes those READMEs in plain text are just infinitely easier to read :)

I take it that the Wiki is more like IIAB developers notes. That's okay.
