### ISSUE TITLE
FAQ/Docs need 6.3 groundtruth (e.g. KA Lite ports 8006, 8007, 8008)

### ISSUE THREAD

**Issue by holta** [iiab/iiab#88]
Example:

Haitians and others need 2 (or 3) KA Lite languages on IIAB 6.3, with videos/lessons direct-linked from http://box

They do this on ports 8006 for French and 8008 for English, as explained at the bottom of FAQ #22:
http://wiki.laptop.org/go/IIAB/FAQ#KA_Lite_Administration:_What_tips_.26_tricks_exist.3F

But they need precise instructions how to maintain this, so they can ./runansible on occasion, remaining full+active members of the IIAB community, so these ports are encoded into iiab-gen-iptables in an agreed-upon / recoverable way.

**Comment by tim-moody** [comment]
iptables allows a range, which I use on the demo machine. Maybe we should just allow 8001-8009 when services externally accessible flag (or whatever it is) is true.

**Comment by holta** [comment]
Very Interesting Idea.  The flag being:

services_externally_visible: True

...e.g. within:
http://download.iiab.io/6.3/rpi/local_vars.yml

...which triggers:
https://github.com/iiab/iiab/blob/master/roles/network/templates/gateway/iiab-gen-iptables

**Comment by jvonau** [comment]
I see that services_externally_visible is only needed in gateway mode now, LAN has always been wide open, and now appliance is also wide open under the current thinking with the use of $MODE. The whole point of services_externally_visible was so the box was **not** wide open. Prior [related issue](https://github.com/XSCE/xsce/issues/914)

**Comment by jvonau** [comment]
[ProxyPass](https://github.com/iiab/iiab/search?utf8=%E2%9C%93&q=proxy&type=) might work here. Setup /kalite pointing to localhost:8008, kalite-fr pointing to 8006. If proxypass works with http://box/kalite there is no need to open ports.

**Comment by tim-moody** [comment]
services_externally_visible was indeed invented for appliance mode, when it went from completely open to completely closed. when did it go back to open? I don't think that's true.

**Comment by jvonau** [comment]
Not sure when, hard to tell with the move, you can figure out that. Click on Adam's link above, the code is there in full colour.
edit: [found the commit](https://github.com/iiab/iiab/pull/20/commits/b108e8ce6d67c5c85fbd13b8e40af8bddb6ef5a6)

**Comment by jvonau** [comment]
/usr/bin/iiab-gen-iptables
+ IPTABLES=/usr/sbin/iptables
+ IPTABLES_DATA=/etc/sysconfig/iptables
++ cat /etc/sysconfig/xs_lan_device
+ LANIF=br0
++ cat /etc/sysconfig/xs_wan_device
+ WANIF=enp0s25
++ grep iiab_network_mode_applied /etc/iiab/iiab.ini
++ gawk '{print $3}'
+ MODE=Appliance
+ '[' xenp0s25 == x ']'
+ '[' Appliance == Appliance ']'
+ clear_fw
+ /usr/sbin/iptables -F
+ /usr/sbin/iptables -t nat -F
+ /usr/sbin/iptables -X
+ /usr/sbin/iptables -A INPUT -i lo -j ACCEPT
+ /usr/sbin/iptables -A INPUT -p tcp --dport 111 -j DROP
+ /usr/sbin/iptables -A INPUT -p udp --dport 111 -j DROP
+ /usr/sbin/iptables -A INPUT -p tcp --dport 3306 -j DROP
+ /usr/sbin/iptables -A INPUT -p udp --dport 3306 -j DROP
+ /usr/sbin/iptables -A INPUT -p tcp --dport 5432 -j DROP
+ /usr/sbin/iptables -A INPUT -p udp --dport 5432 -j DROP
+ /usr/sbin/iptables -A INPUT -p tcp --dport 5984 -j DROP
+ /usr/sbin/iptables -A INPUT -p udp --dport 5984 -j DROP
+ iptables-save
+ exit 0

**Comment by jvonau** [comment]
From https://github.com/iiab/iiab/wiki/IIAB-Installation
"Appliance - No firewall, no dhpcd, no DNS, just a contributor to an already existing network. "
Might want to fix up the references to /opt/schoolserver on that page.

**Comment by holta** [comment]
> "Appliance - No firewall, no dhpcd, no DNS, just a contributor to an already existing network."

@jvonau: does the above need to be changed?

> Might want to fix up the references to /opt/schoolserver on that page.

Agreed.  I'll do this in coming days.  While I'd intentionally left the references to /opt/schoolserver over the past month (in support of IIAB/XSCE 6.2 legacy users) the time has now come to move on, with IIAB 6.3's release imminent in coming weeks (if not in coming days possibly?)

**Comment by jvonau** [comment]
@holta: No, that is the behaviour I observed, but I would double check with Tim as he disagrees.

**Comment by holta** [comment]
Let's try to finalize what services_externally_visible should do during Monday's call.  I'm happy with @tim-moody's suggestion that this open up "campus" WAN-side access to ports 8001-8009.  Or 8006-8008 could also work, per https://github.com/iiab/iiab/wiki/IIAB-Networking#list-of-open-ports--services

For the imminent [IIAB 6.3](http://wiki.laptop.org/go/IIAB/6.3) release, I've begun documenting this @ http://FAQ.iiab.io

([FAQ#22 = "KA Lite Administration: What tips & tricks exist?"](http://wiki.laptop.org/go/IIAB/FAQ#KA_Lite_Administration:_What_tips_.26_tricks_exist.3F) now much improved, but not quite there yet, pending this wider decision!)
