### ISSUE TITLE
[Debian 10]  Ansible reports os_ver as "OS_not_supported"

### ISSUE THREAD

**Issue by arky** [iiab/iiab#902]
### Expected behavior and actual behavior.
Installation of IIAB to start 
### Steps to reproduce the problem.
On Debian 10 

curl download.iiab.io/6.6/load-big.txt | sudo bash 

### Specifications like the version of the IIAB, operating system version, or hardware details.
Debian 10 (buster/sid)

Full logs https://paste.ubuntu.com/p/HY7DmSJJ4C/
Full ansible local vars https://paste.ubuntu.com/p/nwn3pkSVVb/

**Comment by holta** [comment]
@arky it looks like we need a new file /opt/iiab/iiab/vars/debian-10.yml

Can you begin to help us formulate that?

ASIDE: Debian 9.5 and Ubuntu 18.04 are now tested & looking great with http://download.iiab.io/6.6/load-big.txt !

Related: #899 "Enable Debian 9 rsyslog service"

**Comment by arky** [comment]
@holta Now that I have finished the initial work on Kolibri playbook, I'll take a shot at this next week.
