### ISSUE TITLE
Yank power from MongoDB and see if Sugarizer 1.0 works on next boot(s)

### ISSUE THREAD

**Issue by holta** [iiab/iiab#915]
If Sugarizer 1.0.1 does not recover after electricity is suddenly removed without warning from IIAB 6.6, @llaske offers some possible strategies to beef up MongoDB here; https://github.com/iiab/iiab/issues/254#issuecomment-404577658

**Comment by holta** [comment]
@jvonau suggests closing this tkt after a month, if PR #919 is confirmed (as we're very hopeful) to provide a substantially more stable MongoDB / Sugarizer environment.

**Comment by holta** [comment]
Appears solid, after basic testing by TK Kang.

So am moving this to IIAB 6.7, towards final confirmation in coming weeks.

**Comment by jvonau** [comment]
close
