### ISSUE TITLE
Kolibri systemd service says “active (exited)” instead of “active (running)”

### ISSUE THREAD

**Issue by holta** [iiab/iiab#917]
This message appears on all mainline IIAB Linux OS's (Raspbian, Ubuntu 18.04, Debian 9.5) &mdash; upon running `systemctl status kolibri`, which responds with `active (exited)` in green &mdash; rather than `active (running)` in green, as expected of systemd services in general.

@arky, @jvonau & @georgejhunt would you know how to fix Kolibri's systemd unit file ([/etc/systemd/system/kolibri.service](https://github.com/iiab/iiab/blob/master/roles/kolibri/templates/kolibri.service.j2)) to make its status appear as `active (running)` ?  This should not only help it play well with others (other systemd services) but also help with logging/restarting correctly etc, per systemd standards.

**Comment by arky** [comment]
@holta  Thanks for fixing this! Much appreciated.
