### ISSUE TITLE
pip cache memory issues installing Kolibri, similar to KA Lite & OSM?

### ISSUE THREAD

**Issue by holta** [iiab/iiab#920]
@arky requests we monitor this ongoing situation based on:
- https://github.com/iiab/iiab/issues/908#issuecomment-405345180 "Kolibri playbook fails to pip install on Raspbian"
- #910 "Adding 'no-cache-dir' extra arguments"
- https://github.com/learningequality/kolibri/issues/4040 "On Raspberry Pi, use ''--no-cache-dir" pip option to install Kolibri"

@jvonau likely has expertise here to help us understand?!

**Comment by holta** [comment]
Moving to [IIAB 6.7](http://wiki.laptop.org/go/IIAB/6.7) as we finalize IIAB 6.6 for release.

**Comment by arky** [comment]
@holta After some of work it is clear to me that swap size is not the problem here.  So you could change the title of this bug. (I don't have the permissions to do that. Also can your please assign this bug to me.) 

At this point it seems that Debian devs are making some substantial changes to python environment, it might be possible source of the problem. I need to talk to upstream Debian python maintainers next.  
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=880472

**Comment by holta** [comment]
> swap size is not the problem.

Great that there is so much progress, establishing a cleaner foundation for Debian 10!  @jvonau & all of us can definitely learn from you, whatever you uncover here~

> So you could change the title of the bug.

What should the title be?

**Comment by arky** [comment]
@holta  Well my sleep deprived brain says like 'Install Pip tools from Pypa.io for Raspbian'. It seems that pip from OS maintainers tend to be problematic with numerous bugs. 

Perhaps one possible solution would be to install pip using 'get-pip.py' in the IIAB setup? 

>get-pip.py is a bootstrapping script that enables users to install pip, setuptools, and wheel in Python environments that don't already have them. You should not directly reference the files located in this repository and instead use the versions located at https://bootstrap.pypa.io/.

**Comment by holta** [comment]
Idea from @arky:

> 'Install Pip tools from Pypa.io for Raspbian'. It seems that pip from OS maintainers tend to be problematic with numerous bugs.
>
> Perhaps one possible solution would be to install pip using 'get-pip.py' in the IIAB setup?
>
> > get-pip.py is a bootstrapping script that enables users to install pip, setuptools, and wheel in Python environments that don't already have them. You should not directly reference the files located in this repository and instead use the versions located at https://bootstrap.pypa.io/.

**Comment by arky** [comment]
@holta  I checked the code and we already have some code for this. Anyone test if using this over system provided pip solves this issue?

https://github.com/iiab/iiab/blob/50b792869d65114daccfc77ab290b16295e207a2/roles/2-common/tasks/packages.yml#L75-L79

**Comment by arky** [comment]
(Continuing the conversation about @jvonau question here. 
https://github.com/iiab/iiab/issues/816#issuecomment-417381511 )
> (After looking into it last year, he believes Pypa.io can dangerously muddy the waters as to who is installing which Python package versions: #920 (comment))

@jvonau It seems no-one can give me a exact reason why this particular pip cache memory error occurs. Python developers put the blame on debian maintainers and vice versa. 

Lets continue digging deep into this problem and hopefully find a workable solution.

The search (for a solution) continue ....

**Comment by holta** [comment]
Aside: Kolibri memory / RAM issues (@jvonau concerns) mentioned in passing at https://github.com/iiab/iiab/issues/913#issuecomment-424708939

**Comment by holta** [comment]
I agree with @jvonau that we haven't seen almost any `pip` issues recently, so let's close this.
