### ISSUE TITLE
Optimize Sugarizer disk footprint/speed by "50%" using grunt

### ISSUE THREAD

**Issue by holta** [iiab/iiab#921]
Proposal detailed by @llaske at https://github.com/iiab/iiab/pull/888#issuecomment-405627950

Should be easy to implement if someone can step forward to test on RPi 3 or 3 B+ (and also RPi Zero W if possible!)

**Comment by jvonau** [comment]
close

**Comment by holta** [comment]
This (might) remain a possibility for IIAB 7.2+ if communities need such Sugarizer improvements perhaps ?

**Comment by jvonau** [comment]
close

**Comment by holta** [comment]
Agreed.

Sugarizer should really implement grunt by default, if it's an efficient win-win for all.
