### ISSUE TITLE
Verify Kolibri 0.10.0 -> 0.10.1 -> 0.10.2 or 0.11.0 ?

### ISSUE THREAD

**Issue by holta** [iiab/iiab#922]
If Kolibri [0.10.1](https://github.com/learningequality/kolibri/milestone/27) -> [0.10.2](https://github.com/learningequality/kolibri/milestone/28) released in time for [IIAB 6.6](http://wiki.iiab.io/6.6) ?

See also future release [0.11.0](https://github.com/learningequality/kolibri/milestone/22)

**Comment by holta** [comment]
Kolibri 0.10.1 was released 3 days ago, so give a shout anybody who's tried IIAB 6.6/master's BIG-sized install since then (which should pip install 0.10.1).

https://github.com/learningequality/kolibri/releases

**Comment by holta** [comment]
FYI @ivanistheone our priority Kolibri ticket at this time is @arky's #913 &mdash; where many are hopeful he will succeed in reimplementing Kolibri with wsgi &mdash; so that http://box/kolibri works (not just http://box:8009 !)

**Comment by tim-moody** [comment]
fwiw @ivanistheone prefers a proxy to wsgi

**Comment by holta** [comment]
It's likely [IIAB 6.6](https://github.com/iiab/iiab/wiki/IIAB-6.6-Release-Notes) will be released with basic support for Kolibri 0.10.1

i.e. release of [0.10.2](https://github.com/learningequality/kolibri/milestone/28) currently appears to be many days/weeks away.

**Comment by holta** [comment]
Kolibri 0.10.2 released: https://github.com/learningequality/kolibri/releases

Basic testing should confirm this is sufficient for IIAB 6.6

**Comment by holta** [comment]
Basic testing of Kolibri 0.10.2 successful after "./runrole kolibri" and login to http://box:8009 &mdash; completed on Ubuntu 18.04/Server, 18.04/Desktop, 16.04, Raspbian Lite and Raspbian Desktop.
