### ISSUE TITLE
TK: RPi WiFi hotspot can fail within an hour if Ethernet IS plugged in during boot?

### ISSUE THREAD

**Issue by holta** [iiab/iiab#926]
Reposting from https://github.com/iiab/iiab/issues/823#issuecomment-405988436 :

> TK Kang is observing total WiFi failure about an hour after boot (of IIAB 6.6 on Raspbian 2018-06-27) with symptoms similar to: raspberrypi/linux#2453
> 
> Hopefully he and @jvonau can write up a more proper bug report ticket, so others can verify whether this is-or-is-not related to upstream firmware issues with Raspberry Pi's Wi-Fi?

@jvonau responded:
> Perhaps disabling the promiscuous mode hack from #638 might help or hurt but lets take that out of the picture as the firmware/kernel have been updated since the introduction of that 'fix'

@tim-moody responded:
> Think Jerry is right about promisc. Also implicated in firmware issue [@holta] discovered.

@holta responded:
> As TK has reconfirmed the pattern in comprehensive tests on both Raspbian Lite and Raspbian Desktop...
>
> > With Internet access from Ethernet cable and connection to the the RPi3 Wi-Fi, will fail after an hour. Sometimes can't connect to the Wi-Fi AP and if it is connected it is not able to access http://box, etc.
> >
> > If I boot with Ethernet cable unplugged (i.e. no Internet), the wifi access and http://box, etc will remain stable for hours.
>
> ...I've published this as a "Known Issue" at the bottom of the Release Notes:
>
> https://github.com/iiab/iiab/wiki/IIAB-6.6-Release-Notes#known-issues

**Comment by holta** [comment]
TK reports that he was unable to reproduce this symptom overnight.

**Comment by holta** [comment]
Hypothetically related?
http://community.rachelfriends.org/t/loosing-wifi-connectivity-on-rachel-plus-3-0/838

**Comment by holta** [comment]
Moving to IIAB 6.7 — close this tkt if incidents do not recur.

**Comment by holta** [comment]
Is upstream firmware bug https://github.com/raspberrypi/linux/issues/1342 ("wlan freezes in raspberry pi 3/PiZeroW (Not 3B+)") possibly related?

And/or https://github.com/raspberrypi/linux/issues/2453 ("wlan freezes in raspberry pi 3B+") possibly?

**Comment by randyoo** [comment]
@holta There are so many comments on the referenced issue, it's hard to know for certain if you found or tried [my workaround](https://github.com/raspberrypi/linux/issues/1342#issuecomment-351501303). See the bold text at the bottom.

**Comment by holta** [comment]
@randyoo it turns out we already have your workaround implemented as part of IIAB (Internet in a Box) since about 2 years ago, in both these files:
https://github.com/iiab/iiab/blob/master/roles/network/templates/hostapd/hostapd.conf.j2
https://github.com/iiab/iiab/blob/master/roles/network/templates/hostapd/iiab-hostapd.conf.j2

Aside: @jvonau mentions:
> Not sure of the implications of changing semaphores but give it a shot as the underlying ssl libraries changed over time... Might be needed but should test with passwords enabled also.

**Comment by jvonau** [comment]
probable wifi firmware, given the age of this close it?
