### ISSUE TITLE
Move logic from web curl script to iiab-install or factory

### ISSUE THREAD

**Issue by jvonau** [iiab/iiab#963]
Move the bulk of [web curl script](http://download.iiab.io/6.6/install.txt) to iiab-install to avoid duplication and provide easier maintenance or move install.txt to factory and point the url to github.

**Comment by holta** [comment]
Related:
PRs #931 #964 #965

**Comment by tim-moody** [comment]
I'd like to see a separate script for setup: clone repos, create initial dir, etc. before the actual install starts.

**Comment by jvonau** [comment]
[Move to github](https://github.com/iiab/iiab-factory/pull/33/files)

**Comment by holta** [comment]
Refs:
- https://github.com/iiab/iiab-factory/pull/33
- #1160 "Proactively discourage pi/raspberry password compromises"
- http://download.iiab.io/6.7/install.txt (major UX improvements over the past 2 months, so newbie implementers don't forget to reboot into new kernel, ETC)
