### ISSUE TITLE
How To Access Open Street Maps In New Image of School Server

### ISSUE THREAD

**Issue by vinaybissa** [iiab/iiab#969]
### Expected behavior and actual behavior.
As per the earlier image open street maps is accessible on http://box.lan/iiab/static.map.html, but in this new image (6.4) its not working on this Url. [I have map tiles files but don't know where to upload them]
### Specifications like the version of the IIAB, operating system version, or hardware details.
I have updated the school server image from 6.1 to 6.4

**Comment by holta** [comment]
@vinaybissa this was known issue #448 in 2017's IIAB 6.4 from almost a year ago.

I would strongly recommend you try our [IIAB 6.6](http://download.iiab.io/6.6/) pre-release instead.
