### ISSUE TITLE
install.txt on Raspberry PI  Stretch 9.4 booting from USB failing 

### ISSUE THREAD

**Issue by shantibhardwa** [iiab/iiab#991]

**Comment by shantibhardwa** [comment]
I am trying to do iiab build on Stretch 9.4 on PI3B Plus which is booting from USB  Flash drive using the OTP bit set ( i.e. no SD card in the PI). tune2fs gives an error saying No such file or directory while trying to open /dev/mmcblk0p2.  Couldn't find valid filesystem superblock. As there is no SD card the root partition with the file system  is on the USB  and  /dev/mmcblk0p2 does not exist..

**Comment by holta** [comment]
@shantibhardwa what was the fix if possible, for the benefit of others?
